### ISSUE TITLE
Dependency on fxa-auth-db-mysql is still not right

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1000]
`npm-shrinkwrap.json` for this repo still has an explicit dependency on the old `fxa-auth-db-server` repo. This means that anyone wanting to depend on a new endpoint they've added to the db server (for instance, me right now :worried:) gets 404s when they run their tests.

What is the correct way to fix the dependency?

I tried to re-use the `file:` magic from `fxa-auth-db-mysql/npm-shrinkwrap.json`, but couldn't find a way to make it work nested under an extra layer of dependency. I can't rely on the module from npm, because my in-progress changes aren't publilshed to npm yet.

I can manually hack in the correct git commit hash and that makes things work for now, but it's a bit of an arse-ache and seems like it should be unnecessary seeing as the real dependency is on `fxa-auth-db-mysql`.

@dannycoates, you got any insight on this?

**Comment by philbooth** [comment]
> I can manually hack in the correct git commit hash and that makes things work for now

No it doesn't. My plan was to have a dependency called `fxa-db-server` which actually loaded my version `fxa-auth-db-mysql`. But obviously the module exports are wrong for that to work.

I *can* make it work by updating `fxa-auth-db-mysql` to depend on a relative path to its `fxa-auth-db-server` subdirectory. But I don't know if that is something we want to do or not...

**Comment by dannycoates** [comment]
I usually use `npm link` locally. From your db-mysql root run `npm link` and from auth-server root run `npm link fxa-auth-db-mysql`.

**Comment by philbooth** [comment]
Ohhh, nice, I had no idea. Awesome npm-fu, thanks! :facepunch:
