### ISSUE TITLE
Protocol design and work breakdown for device id registration

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1009]
We need to be able to differentiate between long-lived device connections and transient web-based login sessions, to feed into various metrics and dashboard functionality in the Firefox 43 timeframe.

I'd hoped we could get a quick win with a first step in #988 but based on feedback there and elsewhere, we need to take a step back on come up with something a little more nuanced.  I'm filing this bug so we can explicitly include such planning work in iteration 43.1, feeding into concrete implementation in the 43.2 cycle.

**Comment by ncalexan** [comment]
I realize I didn't comment on #988, but I'd like to.

> @rnewman @ncalexan what do you think about putting the various sync clients in charge of  generating a device ID for themselves, storing it locally using whatever mechanism makes sense, and submitting it to the server to identify themselves when they request a sessionToken?

We're going to run into troubles uniquely identifying devices pretty soon.  Right now we just say "OK, new client GUID" but that leads to all sorts of issues on the client (see, for example, https://bugzilla.mozilla.org/show_bug.cgi?id=1180287) and yields a poor user experience.  Of course, clients could be more diligent about trying to identify themselves client-side.  For example, clients could use an advertising ID, the product name and channel, and some profile identifier to locally hash out a stable GUID.

We haven't done this in the past for privacy and unique identification reasons but I think that day has gone.  Looking ahead, it'd be a shame to take a "server-centric" device identification opportunity and dash it on the rocks of 3-5 different client identification implementations :(  So I'd rather keep the server in control, even if it costs additional round trips to our endpoints.

**Comment by rfk** [comment]
@ncalexan thanks for the comments.  I'm happy to yield to collective wisdom here and flip back over to generating on the server side.  However, I don't really understand what the server is supposed to do to help with the "all sorts of issues on the client".  What sort of cleverness are you expecting from the server that will help you work around them?

**Comment by rfk** [comment]
OK, here's a concrete proposal for managing a minimal device model as part of the core account data.  It's based on loads of previous discussions and the prototype device-manager that @kitcambridge @bbangert et al worked on.


Core premises
=============

1. Some subset of things that connect to your Firefox Account are full-blown "devices", and we want to provide extra affordances for dealing with them.
2. Devices are core enough to your connected experience that it makes sense to manage them as part of your account data, rather than via a separate service.
3. Devices are responsible for registering themselves as such with the server, to obtain an identity that's longer-lived than a single session token.
4. Devices belong to a user; if you sign out of Firefox and sign in as a different user, it will appear to be a different device.
5. We want to make available most of the device metadata currently present in the sync "clients" records [1], and it's OK for that to be lifted into FxA as unencrypted data.


Data model
==========

Each device has the following data associated with it to start:

* **device id**:  opaque id, assigned by the server when a device registers itself, persisted by the client to identify itself in future.
* **name**:  user-supplied identifying name for the device; we'll fill in a sensible default here if none is supplied.
* **session token**:  the single active session token currently maintained by this device.  May be null if the device is temporarily disconnected.
* **push endpoint**:  a device-supplied push endpoint that we can ping to let it know about events in its connected ecosystem.
* **type, application, etc**: as much of the fields from [1] as we think provide value at this level

The details of how this push endpoint will operate are not entirely clear to me, and we might leave it out entirely in the initial version.

There’s also the opportunity to add to this model later, for example with some sort of capabilities-registration mechanism.  But let’s start small.


Flows
=====

The core idea here is that the “device” is an optional layer above a “session”.  We keep the existing login-session mechanism in place and add a second step where you can upgrade from “vanilla web-based session” to “device session” with additional metadata attached.


Signing into a device for the first time:
* The device does the existing signin/signup flow and gets a sessionToken as normal.
* It checks its local state and finds no record of device id for this user.
* It calls a new session-token-authenticated auth-server API to register itself as a device, providing its metadata and receiving a freshly allocated device-id.
* It stores the device-id locally for future reference, keyed by user-id, somewhere that won't be reset when the user disconnects from sync.
* It listens on its push endpoint for events.

Signing into a device that has previously been signed in:
* The device does the existing signin/signup flow and gets a sessionToken as normal.
* It checks its local state and finds an existing device id for this user.
* It calls a new session-token-authenticated auth-server API to update its metadata.
* The auth server updates the metadata, including noting the new session-token for the device and destroying the old one if present.
* The device listens on the provided push endpoint for events.

Once registered, the device can pass `device=BLAH` to content-server endpoints or backend APIs in much the same way that it currently passes the `service` parameter, and we can provide additional contextual UI based on that info.

The auth-server will also provide APIs for listing devices, reading metadata for a device, revoking access to a device, etc.  They will be authenticated using FxA OAuth tokens with a specific scope.

The content-server will use these APIs to provide a dashboard of what’s connected to your account.

But we have to get the registration part implemented first.


User Experiences
================

We plan to use this device meta-data in a variety of ways, so we need to be clear about what experiences we want to enable and in what order.  Here’s a shortlist of things we’ve identified so far:

* Send better “account activity” emails that e.g. include device name, and whether this was a new or existing device.
* Have existing devices show a pop-up notification when a new device joins their sync cluster. 
* Provide a device-management dashboard (which needs to be specced out a good deal more)
  * allow editing of device name on the web
  * show metadata like last-sync-time in a convenient overview for all devices
  * revoke/burn devices through web view

I’m sure there are others.

There’s also an open question about how FirefoxOS fits into this picture, along with the existing FindMyDevice service.


Concrete implementation tasks
=============================

* design:
  * finalize the actual protocol details based on discussion of the above, and the initial work done by the Push team
  * design UX for management dashboard and any other initial experiences we want to build on top of this
* auth-server:
  * add device registration and update APIs
  * add supporting infrastructure to be an auth service provider
  * add auth-authenticated APIs for managing sessions and devices
  * send push notifications to devices when their data changes, and when a new device is added
* content-server:
  * accept “device” parameter alongside “service” and pass it along to the backend APIs
  * add device management dashboard
* desktop/fennec/iOS:
  * add ability to register as a device after signin
  * add ability to listen on push endpoint and update in response to server-side changes
  * propagate local edits of device name to the server, and vice versa
  * use device id as the client GUID in sync


So...before I get any futher into the weeds here, thoughts?
/cc @ncalexan @rnewman @dannycoates @kitcambridge @ryanfeeley 

[1] https://docs.services.mozilla.com/sync/objectformats.html#clients

**Comment by rfk** [comment]
@ckarlof raised two good points about this in in-person conversation:

* It's not obvious that we should keep any server-side state around for a device that you've explicitly signed out of, and in fact there's good arguments that we shouldn't.  In which case we don't really need to consider "signing into a device that has previously been signed in" as a separate flow.
* Having the "deviceness" of a session only come into being after a second request is a potential source of unreliability.

So trying to simplify a little, here's a modified "device connecting to sync" flow:

* The device checks local state for an existing device id.
    * If it has one, it includes `device=XXX` in its request to signup/signin along with `service=sync`
    * If not, it can either include `device=1` to explicitly indicate a new device, or we can just assume it's a device from the fact that it's connecting to sync
* When processing the login, the auth-server sees that it's a device, allocates a new device-id if one was not specified, and creates an empty device record to associate with the session token.
* The device id is returned to the client as an extra field in the response, alongside the existing "sessionToken" and "keyFetchToken" values.
    * At this point, we know that a device connected and that's reflected in the db, even for old clients or clients that fail to explicitly "register" as a second step.
* The device persists the allocated id into its local state.
* The device calls a new session-token-authenticated auth-server API to update its metadata, provide a push endpoint, etc.
* The device listens on its push endpoint for events.

When a connected device does something requiring a re-login, like respond to a password reset, it also provids its stored device id as above.  The auth-server can use that to maintain appropriate state, send more nuanced notice emails, etc.

However, this flow means that the device can't store a user-specific device id, since it needs to provide the ID up-front before the user sees any signin UI.  I think this is probably OK, and it should either throw away the device-id when a user explicitly disconnects the device, or accept that device-id might be re-used between users.

@ncalexan, if you have the bandwidth, I'd love to get a sanity-check of the above from you before pushing ahead with a concrete API proposal.

**Comment by ncalexan** [comment]
@rfk: I spent a long time thinking about this.  It's a hard problem.  Here's a Fennec-centric opinion; I think it's similar to the iOS situation.

I'm concerned that we're not hitting the core value here: avoiding duplicate
devices.  So I propose that rather than trying to store a device ID, which is
hard -- more below -- we try to catch 80% of the cases and generate a device
hint client-side.

Rationale: the place where folks feel their device list (now, and likely in the
future) is in the Synced Tabs panel and the Send Tab destination list.  This
device registration flow won't address the major issues we have, which is that
duplicate devices appear in the list and lead to stale devices persisting in the
list.

Our users want Sync to act like a backup.  Having your phone meltdown,
re-installing Firefox, and signing in to your Firefox Account should give you
the same configuration you had.  This flow (and what we have right now) won't
give that, since other devices will see your re-created phone as a different
device.

I'm concerned about meaningful device ID persistence.  On Desktop, the Profile
is the source of truth.  Storing a device ID is reasonable.

On Android, Fennec Profiles can have a shorter life than a Firefox Account --
surprising, I know -- and I believe that users start with a fresh profile
relatively frequently.  (Although I don't have data.  But, Android-level "Clear
package data" is surfaced in the Android UI and gives immediate "space saved"
feedback, and it's a commonly referred to "fix" for issues.)  We could try to
maintain a device ID using what storage is available (profile, Android
SharedPreferences, Android Account storage) but it's not going to be robust.

So can we generate a client-side hint?  Generating a truly stable client ID is
hard (for the depths of the tragicomedy on Android, read
http://stackoverflow.com/q/2785485) so it's best not to make it authoritative --
but perhaps we can use it as a hint?  So a device that wants to register
includes `devicehints=H(advertising IDs),H(hardware)` and the auth server can
potentially grow device disambiguation or unification capabilities over time?
That keeps the device IDs firmly owned by the auth server, while allowing some
persistence in the easiest situations.  (Most users don't change advertising IDs
or hardware.)

**Comment by ncalexan** [comment]
@rfk This is a blend of your original question from #988 and the proposal that you and @ckarlof suggest in this ticket.

As an aside, I would like to not tie `service=sync` and `device` directly.  Clients such as https://github.com/edmoz/fxa-sync-client sit somewhere in between.

**Comment by bbangert** [comment]
@ncalexan Ah, so, in that case the previous profile has not been explicitly signed out of, but the user clearly wants to indicate in some way that this is *now* the previous device in the device list. I think its reasonable that we'll need to give the user an option in that case to 'take-over' a previously registered device in that case (or perhaps just permanently delete the prior device). Or, if the desire is strong enough to avoid the "takeover prior device" flow, perhaps its replaced by, "This device appears to be the same as 'Old Device X', replace 'Old Device X'?", at which point the old one is wiped, and the new one is setup.

@rfk I think this hits all the same spots as our prototype work.

**Comment by rfk** [comment]
> On Android, Fennec Profiles can have a shorter life than a Firefox Account --
> surprising, I know -- and I believe that users start with a fresh profile relatively frequently.

@ncalexan what happens to e.g. the FxA sessionToken in cases like this?  Does that also sometimes get cleared?  In my mind, the device-id would be persisted as a sibling of the session-token id and we'd expect its lifetime to be greater-or-equal to the sessio token.

**Comment by rfk** [comment]
IIUC there's also the possibility of running two different Firefox installs on the same "device" under Android, e.g. separate "release" and "beta" installs.  Similarly to desktop, should I be able to sign in to both and sync data between them as two separate "devices"?

Chrome does an interesting thing where you can have multiple "browsers" connected on a single "device":
![screen shot 2015-09-09 at 11 18 53](https://cloud.githubusercontent.com/assets/34695/9751166/a81f8950-56e4-11e5-85da-545b81d10900.png)

But that's probably going too fine-grained for our current needs.

**Comment by bbangert** [comment]
Absolutely, this is the same case as on a PC when running different profiles. Some basic heuristics to detect whether this is the same profile as another existing one on the same 'device' (MAC id? hardware fingerprint? etc) could make it easy to present a user with an appropriate dialog. I would generally assume someone running multiple profiles on a single device to be advanced enough to choose an appropriate course of action.

**Comment by jrconlin** [comment]
A couple of notes:
1) I'd prefer if the endpoint descriptor was not tied to "push". I can easily see other, similar services where there may be a similar endpoint and calling it "push-endpoint" makes it either confusing or invites extra fields.
2) DeviceIDs are how devices self identify. Where they originate isn't really as important as they're unique per user. I believe we were just using a GUID4 with a "user friendly name". From what I've seen, other services either allow users to recreate from a default (in the case of a new or recovering device). If we're storing a backup per user per device and/or per profile things might get complicated for users unless we require or provide meaningful names. Seems like we're inviting Murphy to the party. 

As for the last one, I could easily make an argument that I might want a "desktop" vs. "mobile" or "work" vs. "personal" profile and have my new device recreate from one of those. It's not reducing the complexity, sadly, but might help users better understand (as I writes this using KDE, which has "[activities](http://www.datamation.com/open-source/the-mystery-of-kde-activities-1.html)" which I never use or really understand.)

**Comment by rfk** [comment]
> I'm concerned that we're not hitting the core value here: avoiding duplicate devices.

FWIW, I'm not sure "core value" is the right lens to view this through.  We have to do a good job of it, for sure, but the "core value" from a user POV is going to be about surfacing your connected devices in more places and doing more interesting and timely things with them.  The more we can avoid duplicate devices, the better and more seamless that experience will appear, but we don't have to get it 100% right.

So I like your "catch the 80% of cases" view :-)

> This device registration flow won't address the major issues we have, which is that
> duplicate devices appear in the list and lead to stale devices persisting in the list.

It's also interesting to consider exacty why this is a problem.  I suspect that many users who find themselves in this state are less *confused* than *frustrated*.  They can form a mental model of why they're seeing such a state, but we don't let them do anything about it.  Just given them the ability to clean up by manually zapping old devices from the tabs-from-other-devices view might go a long way.

ISTM that the right approach is a combination of:

1. Give the device some hooks to detect when a device is reconnecting without a clean disconnect, for the cases where we can do so reliably.  Err on the side of allowing duplicates in cases where we can't.
2. Give the user an easy way to clean up the list and recover from cases where we did not detect it.

The more likely a user is to find a way around the duplicate detection in (1), the more likely they are to understand and be happy to do (2).

>  So a device that wants to register includes `devicehints=....` and the auth server can potentially 
> row device disambiguation or unification capabilities over time? That keeps the device IDs firmly 
> owned by the auth server, while allowing some persistence in the easiest situations

Sounds good.

Slightly more concretely, we could let the device optionally specify a "hardware fingerprint" and an "agent fingerprint"  if it can determine such things reliably.  On Fennec, this might be something like the android-device-id and the release channel respectively.  On desktop, maybe it's a hash of mac address and the path to the profile directory.  Whatever, I deliberately don't want to have to care about how each client calculates them :-)

If you show up with a matching (hardware fingerprint, agent fingerprint) pair to an existing device record, we assume you're that device recovering from some local state destruction and re-issue you the previous server-generated device id.

If it *can't* generate such things reliably, it doesn't send them and we don't do any matching or deduplication.

This provides a nice separation between the "detecting duplicate devices" thing and the actual work of dealing with devices once they're registered, which is nice.

I also think it makes sense to get at this information via the mooted "device handshake" flow rather than cramming it into query parameters for the setup page.

**Comment by rfk** [comment]
> I'd prefer if the endpoint descriptor was not tied to "push". I can easily see other, similar 
> services where there may be a similar endpoint and calling it "push-endpoint" makes
> it either confusing or invites extra fields.

I'm not sure I understand the concern w.r.t "other similar services" but that's almost certainly because I don't know enough about the details of push.  @jrconlin what would you suggest as an alternate name?

> If we're storing a backup per user per device and/or per profile things might get complicated 

Let's not do this then :-)

**Comment by jrconlin** [comment]
@rfk I'd prefer simply "endpoint" rather than "push endpoint" as listed in https://github.com/mozilla/fxa-auth-server/issues/1009#issuecomment-136239523 

There may be other services we wish to tie to a profile & device (e.g. Pocket, Hello, etc.).

**Comment by rfk** [comment]
@jrconlin and I talked this over a little in IRC.  Broadly, the concern is that "push endpoint" sounds like a service name, so clients of this API might also expect to see things like "sync endpoint" and "hello endpoint" alongside it.  If we give it a more generic name then it will better set expectations.  A plain "endpoint" doesn't seem to convey enough information IMHO, but something like "notification endpoint" may be a good option.

**Comment by rfk** [comment]
@dannycoates is going to propose a more concrete data-model and API based on discussions here and IRL

**Comment by ckarlof** [comment]
There's a lot of discussion here about how a list of devices is surfaced to the user, but it's not at all clear to me that's even in scope for the initial use cases.

**Comment by ckarlof** [comment]
Towards getting a real, persistent device identifier, you're potentially getting into some real voodoo.  This is the kind of stuff that fraud and abuse teams and advertisers think hard about. I found this interesting page: https://www.chromium.org/Home/chromium-security/client-identification-mechanisms

It has an interesting section on device and browser fingerprinting. I imagine that's the kind of stuff we'd need to do if we want to associate, e.g., a deleted profile with the a new profile on the same machine.

**Comment by dannycoates** [comment]
> Towards getting a real, persistent device identifier, you're potentially getting into some real voodoo.

Fortunately, I don't think this is the type of identifier we need. I think our use cases are fairly tame. Simply adding one optional field to session tokens would get us *surprisingly* close to what we need. We only need a little bit more.

> There's a lot of discussion here about how a list of devices is surfaced to the user, but it's not at all clear to me that's even in scope for the initial use cases.

I think its partially in scope because having the list be user curated will greatly improve its accuracy, so considering the UX around that helps inform the data model. On the other hand I don't think we need to figure out all the edge cases up front.

**Comment by rfk** [comment]
We already surface a list of devices to the user in views like "tabs from other devices", it's just a pretty crappy list right now.  Fixing that may not be part of the initial use-cases here, but it will be nice to have a plausible story for how we can work towards fixing it in the future.

> It has an interesting section on device and browser fingerprinting. I imagine that's the kind 
> of stuff we'd need to do if we want to associate, e.g., a deleted profile with the a new 
> profile on the same machine.

This is what I want to explicitly *avoid* doing, having the server try to guess at the identity of a device.  My comments in https://github.com/mozilla/fxa-auth-server/issues/1009#issuecomment-138757974 are basically "if the device can explicitly tell us a reliable fingerprint for itself then use it; otherwise don't even try to guess".

We also don't have to implement that up-front.  If we're at a point where we can say "when devices are ready to disambiguate themselves, that could plug into the API like so" then I think we can all happily move forward.

**Comment by ckarlof** [comment]
@rfk, I feel it would be helpful if we had a prioritized list of stories/use cases for the device manager. I see some [here](https://github.com/mozilla/fxa-auth-server/issues/1009#issuecomment-136239523), and I don't see any in [Aha](https://mozilla.aha.io/features/FXA-45).

Does figuring out a devices dashboard MVP block the other stories?

**Comment by rfk** [comment]
I just realized that this issue doesn't link to @dannycoates' proposed API, so here we go:

  https://gist.github.com/dannycoates/44b1965a6be42060e15f

**Comment by rfk** [comment]
> I feel it would be helpful if we had a prioritized list of stories/use cases for the device manager

Bill and I spent some time going through these, and we've the following cards in aha, in this order:

1. Basic "connected devices" dashboard: https://mozilla.aha.io/features/FXA-16
2. More timely disconnection of devices after a password reset: https://mozilla.aha.io/features/FXA-53
3. In-browser notification when another device starts syncing: https://mozilla.aha.io/features/FXA-36
4. Send better "account activity" emails: https://mozilla.aha.io/features/FXA-35

Number (2) could be done independently of any "devices dashboard" work, but all of the others are telling you about devices, so they seem to warrant a place to link you to where you can see said devices.

The long-mooted "don't poll so damn much checking for verification status" is not repreented in Aha, but would fit into the same category as (2).  In fact, why don't I add a card for it right now...

**Comment by rfk** [comment]
> In fact, why don't I add a card for it right now

https://mozilla.aha.io/features/FXA-54

**Comment by rfk** [comment]
To me, the details of doing FxA-53, FxA-54 and FxA-36 are the biggest under-specified part of this API.  We know we will get a push notification endpoint from the device, but we haven't settled any details of how that endpoint will be used or what the device should do when it receives a ping on that endpoint.

A simple option: pings on that endpoint carry no information besides "something changed", and the device must refresh all the info it has cached about the state of the account.  This includes the verificaton status, its own device metadata and the metadata of any other devices on the account.

Not terribly efficient, but simple.

**Comment by kitcambridge** [comment]
@rfk, your proposal in https://github.com/mozilla/fxa-auth-server/issues/1009#issuecomment-136239523 looks fantastic. :balloon:

> It's not obvious that we should keep any server-side state around for a device that you've explicitly signed out of, and in fact there's good arguments that we shouldn't.

This is a nice simplification. I think @bbangert and I came to the same conclusion for the prototype—it's a lot easier if signing out of the device and deleting it from the dashboard are equivalent.

> A simple option: pings on that endpoint carry no information besides "something changed", and the device must refresh all the info it has cached about the state of the account.

I think the simplest option is the best. :smile_cat: You can send data in the push message, but it needs to be encrypted, which adds lots of complexity. If you'd like more granular notifications, you could also create multiple endpoints, one for each event.

**Comment by rfk** [comment]
> You can send data in the push message, but it needs to be encrypted, which adds lots of complexity

@kitcambridge if you've got a link handy to the spec for this, can you please drop it here?  I agree it smells like a lot of extra complexity, but will be good to have for reference.

**Comment by vladikoff** [comment]
@rfk to close this...

**Comment by kitcambridge** [comment]
@rfk Certainly: https://martinthomson.github.io/http-encryption/

**Comment by rfk** [comment]
I filed the above two follow-up bugs to drill down further into some of the details here, and I think the breakdown work represented in this bug is now complete.  All bugs in this milestone can be viewed at:

  https://waffle.io/mozilla/fxa?milestone=FxA-45:%20device%20registration

Thanks so much for your input everyone! Closing this out.
