### ISSUE TITLE
Switch to mozilla/micro-email-validator for email validation

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-server#1015]
Per [/lib/routes/validators.js:40-93](https://github.com/mozilla/fxa-auth-server/blob/55f7120dd360b0080df2277f15b4fc1ed51b1dcd/lib/routes/validators.js#L40-L93),

It looks like we extracted that code out to [**mozilla/micro-email-validator**](https://github.com/mozilla/micro-email-validator) for better reuse between projects. It'd probably be neat if we switched to using that module to reduce duplicated code and pool our efforts into the other project for Great Benefit.

**Comment by vladikoff** [comment]
Seems like our logic needs to be more flexible for email validation in https://github.com/mozilla/fxa-content-server/pull/3546 

If we still want to use the external module please reopen this.
