### ISSUE TITLE
 Emit events for account activity on key days

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1027]
(Migrating from https://github.com/mozilla/fxa-auth-db-mysql/issues/85 on behalf of @philbooth)

We need to emit events corresponding to activity on a given day for each account, to be processed by Heka as food for the retention graph.

**Comment by rfk** [comment]
This bug has some prior art from sync:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1194031

In that case, we started emitting a "the first time I saw this user" timestamp in our key metrics events.  A downstream processor can use this to calculate how many days old the user account is, for retention purposes.

We could do something similar here, since we already have a reliable `createdAt` timestamp for each user.  Would it suffice to just include `createdAt` as part of the metadata in our existing `activityEvent` logs?  Those are already designed to be the key points at which we want to measure user activity.

**Comment by vladikoff** [comment]
> philbooth self-assigned this 2 days ago

Let's chat again tomorrow (Wednesday) or Thursday if you can. Any time after 2:30pm BST

**Comment by vladikoff** [comment]
stuff from mtg:
 - we already have an account.created event but adding 'createdAt' should also be very useful
-  need to make sure other services are reported properly (not just sync)

**Comment by vladikoff** [comment]
> we already have an account.created event but adding 'createdAt' should also be very useful
need to make sure other services are reported properly (not just sync)

We already have that event as `account.login`, more context here: https://github.com/mozilla/fxa-auth-server/issues/1058

**Comment by philbooth** [comment]
I've pulled this out of the review column while it waits on https://github.com/mozilla/fxa-auth-db-mysql/pull/105.
