### ISSUE TITLE
Tag account activity events with user segmentation info

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1036]
To perform comparisons of our key metrics across different segments of users, we'll need to include segmentation info as part of our activity events.

The one we're most interested in to start with is comparing single-device/multi-device users.  Perhaps this can be as simple as including a "multiDevice: true/false" field in logged activity events, where it can be found and used by downstream log-processing stuff.  For example, it might show up as a tag in datadog.

**Comment by philbooth** [comment]
@vladikoff, as per our conversation yesterday, I tested https://github.com/mozilla/fxa-auth-server/pull/1056 with an OAuth relier to check the value of the `service` parameter on the `account.signed` activity event. As you expected/suggested, it is the hex id of the service, not the name.

So we need some other place to emit the service information; presumably from inside the OAuth server, unless there is some other place that knows the name of the service?

**Comment by vladikoff** [comment]
> As you expected/suggested, it is the hex id of the service, not the name.

> So we need some other place to emit the service information; presumably from inside the OAuth server, unless there is some other place that knows the name of the service?

Right, so we have to deal with "service" being "sync", and others being hex ids. Also Pocket has 2 hex ids. I feel like we'll have to just deal with it and expect the "service" event to be either "sync" or the oauth hex id.

@rfk thoughts?

**Comment by philbooth** [comment]
> I feel like we'll have to just deal with it and expect the "service" event to be either "sync" or the oauth hex id.

Oh cool, I didn't realise that was an option actually.

I *was* going to propose doing something like this in the OAuth server (not sure if it would actually work):

https://github.com/mozilla/fxa-oauth-server/compare/phil/retention-activity-event?expand=1

But now I don't have to! :grin:

**Comment by rfk** [comment]
Agree, we'll have to just cope with the hex ids and map them to names when we display the metrics; fwiw we already do this with e.g. the "account creates by service" graph at [1].

[1] https://metrics.services.mozilla.com/accounts-dashboard/

**Comment by rfk** [comment]
> https://github.com/mozilla/fxa-oauth-server/compare/phil/retention-activity-event?expand=1

Also FWIW I think you'll get more reliable service information by doing that in the oauth server, since the client *has* to specify the oauth relier when interacting with that API.  But if we're getting service information in the `signed` event here, we should definitely use it.

**Comment by philbooth** [comment]
@rfk, can this issue be closed now?

My understanding is that all the properties we need are now set on the activity events: user id, user-agent string, service id, account-creation timestamp.

**Comment by rfk** [comment]
yes; I had originally intended to include more device information here, but we have a different plan for how to do that now, so closing
