### ISSUE TITLE
Move basket event processing into basket-specific repo

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1037]
We have a new repo that's supposed to contain "all the server-side behaviours that we eventually want basket to handle naitvely":

  https://github.com/mozilla/fxa-basket-proxy

Let's move the existing basket event-sending stuff out of this repo and over to that one.

**Comment by vladikoff** [comment]
To be merged...

**Comment by rfk** [comment]
I think we should hold off this until after the train is cut; give @jrgm a change to move over to using the logic in fxa-basket-proxy before removing it from this repo.

**Comment by rfk** [comment]
Re-assigning to "quality" milestone since the only thing that remains here is removing dead code.

**Comment by rfk** [comment]
@jrgm gave the ok for this on train-48, merging
