### ISSUE TITLE
Publish device-connected events for basket journeybuilder integration

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1038]
The engagement team are launching an initiative to try to increase multi-device users, with a targetted email "journey" pitching the benefits of the connected experience.  To help drive it their "journeybuilder" software needs to receive notification when users connect new devices - both when they connect their first device to know when a user should start the journey, and when they connect their second device to know when they have completed the journey successfully.

At the same point where we send out an email saying "new device syncing with your account", let's also pop an event in the queue to be sent to basket, which will work the necessary magic to get it into journeybuilder.  This event will need to include whether or not the user has multiple devices connected to their account.

Basket-side bug, for context:  https://bugzilla.mozilla.org/show_bug.cgi?id=1179878

**Comment by rfk** [comment]
> This event will need to include whether or not the user has multiple devices connected to their account.

Actually it would be nice is basket or its proxy could query this using a service token, rather than us having to include it in the event.   Maybe in a future iteration...

**Comment by rfk** [comment]
(And of course by "multiple devices" I mean "multiple session tokens", at least until we start doing more explicit device registration)

**Comment by philbooth** [comment]
@rfk, if I understand correctly, setting `first_device` on this event requires knowing the count of session tokens for the current user. The obvious way to get that seems like adding a new database API endpoint to return `COUNT(*) FROM sessionTokens` for the current user, so I'm working under that assumption for now.

Just wanted to note that explicitly so you can holler if I'm barking up the wrong tree. :deciduous_tree: :poodle:

**Comment by philbooth** [comment]
One more question, @rfk.

I notice the `verified` event handler in `bin/basket.js` ignores events that have obvious test email addresses. Although there's no email address in the new payload, should I include it in the `login` (or whatever) event data so that I can perform a similar check in the new handler?

It feels like I probably should, because we're assuming that basket can look-up the email address using `fxa_id` from the `/fxa-register` request. So if I don't re-use the same logic in the new handler, they will end up with a bunch of ids that they can't look up. Does that sound right?

**Comment by rfk** [comment]
I'd like to avoid adding a super-special-purpose API for this, but I think a slightly more general "list the sessiontokens on the account" API like in [1] would suit our needs well and be more forward-looking for other purposes.  I don't think @dannycoates would be too sad if you wanted to take that one off his plate :-)

> Although there's no email address in the new payload, should I include it in the login
> (or whatever) event data so that I can perform a similar check in the new handler

Hmmm, good point.  It seems safe to add even if we don't end up needing to use it.

Also you just made me realize, I hadn't really shared an overview of the scope of work for this integration with you.  The waffleboad view for this milestone [2] should give you a bit of an idea, if you haven't already seen it.

[1] https://github.com/mozilla/fxa-auth-db-mysql/issues/98
[2] https://waffle.io/mozilla/fxa?milestone=FxA-44:%20journeybuilder%20events

**Comment by philbooth** [comment]
Just to flag it up for visibility, I have this implemented on [a branch](https://github.com/mozilla/fxa-auth-server/compare/phil/issue-1038?expand=1) but haven't opened a PR yet because it depends on https://github.com/mozilla/fxa-auth-db-mysql/issues/98.
