### ISSUE TITLE
Link in email should be /v1/reset_password, not /reset_password per Shane

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1054]
```
jrgm	stomlins_ or vladikoff or zaach - Hey, so /v1/reset_password vs /reset_password - the 
  former redirects to the latter, but which is the correct path for the 'Your Firefox Account 
  password has been reset' to call?
stomlins_	jrgm: in emails, we have used the first.
jrgm	stomlins_: ok, thanks. 
```

**Comment by dannycoates** [comment]
"we have used" !== "we should use"

I changed it intentionally to remove the redirect

**Comment by shane-tomlinson** [comment]
> "we have used" !== "we should use"
>
> I changed it intentionally to remove the redirect

Ahha, I was not aware of this change. Are all the URLs updated? Will we be able to [remove this redirect code](https://github.com/mozilla/fxa-content-server/blob/8323982b7007827d65d4fde81766e0475fc5602e/server/lib/routes.js#L33-L60) in the future?

**Comment by rfk** [comment]
> Will we be able to remove this redirect code in the future?

Let's file a bug to work purposely towards this.

**Comment by rfk** [comment]
Filed https://github.com/mozilla/fxa-auth-server/issues/1059; closing this one out
