### ISSUE TITLE
new "signed.session_new" activityEvent

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1058]
~~This event will be emitted when the /signed request session token UA does not match the stored one. 
(needs logic to determine the change and emit the event)~~

Possible names: `device.connected`, `signed.session_new`, `new_session_engaged`

https://github.com/mozilla/fxa-auth-server/blob/454f1a377dda3d634e810389c66a9e7624981794/lib/routes/sign.js#L34

@philbooth let me know if I'm forgetting anything

**Comment by rfk** [comment]
>  when the /signed request session token UA does not match the stored one

Unless I'm missing something, I don't think this accurately reflects a `device.connected` style event.  Each device has its own session token.  The UA info changing for a given session token indicates that the device owning that token has e.g. updated to a newer version of firefox, not that a new device has joined the constellation.

AFAICT the best place we currently have to emit a `device.connected` style event is when the session token is created, as @philbooth did in [1].  And if there *is* a better way, we should use that way for the journeybuilder events as well :-)

[1] https://github.com/mozilla/fxa-auth-server/pull/1051

**Comment by vladikoff** [comment]
@rfk helped me clear this up, (thanks @rfk!)

It seems like we can just use the `account.login` event defined here: https://github.com/mozilla/fxa-auth-server/blob/2dbbd5b1aea8f596e82aaddc7c36575ad544ade0/lib/routes/account.js#L273 to figure out multi-device

Notes from irc:

 "to confirm: users who have multiple account.login events with service "sync" or blank are the "multi device" users."

" so one thing to watch for is that their first device won't generate such an event, that's why in e.g. the journbuilder events pr, we had to emit the event in two places, one for account/create, one for account/login", "there's an account.created event though", "if we're lucky, looking for (account.login or account.created) will hit both cases", "	yep, seems to, except for again Fennec"
