### ISSUE TITLE
Remove `/v1` prefix from all email links targetting content-server

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1059]
Per https://github.com/mozilla/fxa-auth-server/issues/1054 we have removed the `/v1` prefix from some of our email links, because it really doesn't serve much of a purpose and causes a redirect on the content-server side.  Let's remove the rest of them and then we can remove the redirect logic [1] entirely.

[1] https://github.com/mozilla/fxa-content-server/blob/8323982b7007827d65d4fde81766e0475fc5602e/server/lib/routes.js#L33-L60

**Comment by vladikoff** [comment]
from mtg:
    - we first need to stop sending emails, later we should remove the path from the content server

**Comment by rfk** [comment]
This bug is specifically about the "stop sending emails with /v1 prefix" part, which we can safely do at any time.  Once that's deployed, we should make a separate content-server bug to remove the route redirections.

**Comment by yash14123** [comment]
Please share the link to the file where these changes need to be made.

**Comment by rfk** [comment]
I believe the remaining instances are at https://github.com/mozilla/fxa-auth-server/blob/master/config/index.js#L366
