### ISSUE TITLE
Error Messages -> Account Enumeration

### ISSUE THREAD

**Issue by priyalviroja** [mozilla/fxa-auth-server#1060]
mozilla/fxa-auth-server/blob/master/lib/error.js 

Error Messages:

Unknown account.
Incorrect email case.
Incorrect password.

Any XYZ guy can miss use these friendly error messages to enumerate real users. And can use this info for further Firefox Services specific attacks.

It's a best practice to alert users with generic error messages. 

ex. 
Username or Password Incorrect.
Incorrect Login Credentials.

**Comment by rfk** [comment]
Thanks @priyalviroja.  This was a deliberate trade-off we made in order to provide a better user experience; protection against large-scale user enumeration attempts depends on operational mitigations like rate-limiting.

**Comment by shane-tomlinson** [comment]
@priyalviroja - For more information about the rate limiting FxA uses to help mitigate these attacks, see https://github.com/mozilla/fxa-customs-server/ and https://wiki.mozilla.org/Identity/Firefox_Accounts/Fraud_and_abuse.

**Comment by priyalviroja** [comment]
@rfk , @shane-tomlinson  Thanks for the clarification :)
