### ISSUE TITLE
Device support

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#1061]
Implement the device API proposed here: https://gist.github.com/dannycoates/44b1965a6be42060e15f

**Comment by vladikoff** [comment]
for next train

**Comment by rfk** [comment]
This is "in review" but it doesn't seem to have a linked PR..?

**Comment by rfk** [comment]
@dannycoates a friendly reminder that you were going to post a WIP PR for this so that @philbooth can dive into some of the details :-)

**Comment by vladikoff** [comment]
ping @dannycoates

**Comment by rfk** [comment]
Closing this in favour of @philbooth's issue breakdown; thanks for kicking it off @dannycoates!
