### ISSUE TITLE
A lot of timeouts for /certificate/sign in prod

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1068]
https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/temp/AVAU7lB8ayLd6KaG9T8I

**Comment by jrgm** [comment]
I spent some time digging into what the logs were actually saying. The clients are strongly skewed to being Android clients. Actual response time from key_server is very low, but nginx records total request lifetime in the dozens of seconds. My feeling, without doing a thorough correlation with ELB logs is that this is reflecting poor wireless networking behaviour.

**Comment by rfk** [comment]
We need to figure out a better way to montior for this, but not uch we can do about it short term

**Comment by jrgm** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1210523. It's some kind of Firefox-Android behaviour.

**Comment by jrgm** [comment]
> My feeling, without doing a thorough correlation with ELB logs is that this is reflecting poor wireless networking behaviour.

I changed my mind. Why only and always /v1/certificate/sign and not other paths if this were due to overall networking? Seems more likely something particular about the client handling (given the actual auth-server indicates no slowness in responding).

**Comment by rfk** [comment]
Looks like this is a client-side bug, closing on our side
