### ISSUE TITLE
Update to scrypt 1.1.13

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1072]
Need to update to this https://github.com/dannycoates/scrypt-hash/commit/f5636635065c20552af798c4059b16554467a301 to support Node v4.

I tried but got tangled in the shrinkwrap :(

**Comment by rfk** [comment]
Shrinkwrap seems to be freaking out about the dev dependencies in fxa-auth-db-mysql, saying they're "extraneous".  I haven't the patience to figure out what that's about, and they're only dev dependencies, so I did the following to just zap them:

```
rm -rf node_modules npm-shrinkwrap.json
npm install
npm ls 2>&1 | grep extraneous: | cut -d ' ' -f 5 | xargs rm -rf
npm shrinkwrap --dev
```

Result: https://github.com/mozilla/fxa-auth-server/pull/1074

**Comment by vladikoff** [comment]
@dannycoates if you have a sec could you check if that's the right way to go? I had the same issue with shrinkwrap as @rfk

**Comment by dannycoates** [comment]
Yeah thats *probably* fine, although we ought to try to unfolk it enough so a vanilla shrinkwap will work. I gave myself #1075

**Comment by rfk** [comment]
Closing in favour of #1075
