### ISSUE TITLE
dependency maintenance

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#1075]
Update deps and simplify shrinkwrap

**Comment by rfk** [comment]
Consolidating the required updates into this single bug:

* scrypt => 1.1.13
* mozlog => 2.0.2

**Comment by vladikoff** [comment]
fixed in https://github.com/mozilla/fxa-auth-server/commit/193d16ffec128ee78be310c8737a2eeaeb938dff 

woohoo!
