### ISSUE TITLE
Design push notification protocol for connected devices

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1076]
(ref high-level design discussion in #1009)

We're adding a device registration API, and devices will be able to register a push notification endpoint on which we can notify them of account activity.  We need to lock down what the semantics of these notifications will be.

IIUC these will be "webpush" endpoints as documented in [1] - @kitcambridge please forcefully adjust my expectations if this is not in fact the case.

We can send data in these notifications, but there's crypto involved, using the scheme in [2].  We might be able to take this on, since we've already solved the problem of coordinating a key between client and server.  Or it might be simpler to just treat these as "ping" notifications that let the client know something about the account state has changed, without necessarily saying what that something was.

[1] https://webpush-wg.github.io/webpush-protocol/
[2] https://martinthomson.github.io/http-encryption/

**Comment by vladikoff** [comment]
@shane-tomlinson @philbooth @dannycoates @vladikoff and everyone meet to talk about this...

**Comment by rfk** [comment]
From discussion with @shane-tomlinson, one possible outcome is that push is not necessary for the very first version of device registration, and we take this out of the milestone and put it back in the backlog.  @shane-tomlinson and @philbooth to figure out during breakdown session.

**Comment by rfk** [comment]
Digging into the spec a little, it seems that the client-side will also generate a key that we would need to store alongside its endpoint URL, if we want to send messages with a payload:

  https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription

**Comment by vladikoff** [comment]
@vladikoff to follow up

**Comment by vladikoff** [comment]
> From discussion with @shane-tomlinson, one possible outcome is that push is not necessary for the very first version of device registration, and we take this out of the milestone and put it back in the backlog. @shane-tomlinson and @philbooth to figure out during breakdown session.

Yeap, it seems like we can skip this for now. @rfk I'm taking this out of FxA-45 because we can deal without it and we already have plenty of bugs in FxA-45.

**Comment by vladikoff** [comment]
I think we figured most of this out. 

Follow up issues: https://github.com/mozilla/fxa-auth-server/issues/1139
https://github.com/mozilla/fxa-auth-server/issues/1140
https://github.com/mozilla/fxa-auth-server/issues/1141
https://github.com/mozilla/fxa-auth-server/issues/1132

Reopen if still needed
