### ISSUE TITLE
Add tags to statsd messages

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1115]
The events that wind up in datadog from fxa-content server have an elaborate series of tags to allow filtering by e.g. user-agent platform, entrypoint, etc: https://github.com/mozilla/fxa-content-server/blob/master/server/lib/statsd-collector.js#L30

By contrast, the events that come from the auth-server barely have any tags, so we can't do a datadog dash for e.g. "all account.created events from Android".

We should either duplicate the tagging logic from content-server, or pull it out into a shared lib for both codebases to use.

**Comment by vladikoff** [comment]
I can mentor someone to make a PR for this!

**Comment by rfk** [comment]
@vladikoff suggestes this might be a good-next-bug for your second week, assigning you to it to put it on your radar

**Comment by vladikoff** [comment]
@vbudhram Hey! When you have time on Tuesday and Wednesday, could you please watch the DataDog screencast linked here: https://mana.mozilla.org/wiki/display/CLOUDSERVICES/Useful+Resources#UsefulResources-Screencasts 

Let me know after you watched it and we can schedule a quick Vidyo meeting to talk more about this issue. I also invited you to our dev and prod DataDog accounts.

**Comment by vbudhram** [comment]
@vladikoff Thanks for link, will check it out and let you know.
