### ISSUE TITLE
class-A data, class-B data

### ISSUE THREAD

**Issue by Yannik** [mozilla/fxa-auth-server#1129]
On https://github.com/mozilla/fxa-auth-server/wiki/onepw-protocol, the difference between class-A data and class-B data is explained:

>class-A: data assigned to this class can be recovered, even if the user forgets their password, by proving control over an email address and resetting the account. It can also be read by Mozilla (since it runs the keyserver and knows kA), or by the user's IdP (by resetting the account without the user's permission).

>class-B: data in this class cannot be recovered if the password is forgotten. It cannot be read by the IdP. Mozilla (via the keyserver) cannot read this data, but can attempt a brute-force dictionary attack against the password.

the following is also stated:
>data classes: each type of browser data (bookmarks, passwords, history, etc) can be assigned, by the user, to either class-A or class-B

However, I was unable to find the setting for this in FF44 and FF46. It's also very important for me to know to which data class different browser data defaults.

**Comment by vladikoff** [comment]
@Yannik Sorry, could you please rephrase your question. What exactly do you want answered?

**Comment by Yannik** [comment]
@vladikoff My question is how the user can configure whether select browser data(bookmarks, passwords, history etc.) is class-A data or class-B data. I could not find such a option in the FF44/FF46 implementation. Following that, my question is whether bookmarks, passwords, history are class-A data or class-B data by default.

**Comment by rfk** [comment]
Currently everything is class-B, and class-A is not used.  There's also no UI for the user to configure this choice, it's all class-B all the time.  We're considering revisiting this in 2016 to provide more choices and UI around it, but I don't have concrete plans yet to share in that regard.

**Comment by Yannik** [comment]
Thanks, @rfk, this is reassuring. Maybe the docs should be updated in that regard?

**Comment by rfk** [comment]
Thanks @Yannik, I've added a couple of notes to the linked wiki page to try to clarify the situation.

**Comment by Yannik** [comment]
Thanks!
