### ISSUE TITLE
investigate pushEncryption / auth support for the devices api

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1132]
To send push notifications with payload we need to add another field to our api and store authentication. We probably do not need this for initial features.

**Comment by vladikoff** [comment]
@kitcambridge when you have a sec, could you please provide a link to the latest push Auth spec or example where the public key is split from the auth key?

**Comment by kitcambridge** [comment]
Sure! Our server doesn't forward the new `Crypto-Key` header yet (waiting on mozilla-services/autopush#277), but the Firefox implementation is backward-compatible. For now, I'd recommend just storing the key and secret in your DB. The secret is 16 bytes, on top of the 65 bytes for the key.

* The latest [encrypted content coding](https://martinthomson.github.io/http-encryption/) draft describes [authentication secrets](https://martinthomson.github.io/http-encryption/#rfc.section.4.3).
* Martin's reference implementation has a [branch](https://github.com/martinthomson/encrypted-content-encoding/tree/auth) that adds the secret.
* The push crypto spec has a [section](https://webpush-wg.github.io/webpush-encryption/#rfc.section.2.3) on it, too.
* `PushCrypto.jsm` [describes](https://dxr.mozilla.org/mozilla-central/rev/cb66ffeb6725e8344818e8e2f707ae2eaeb953b4/dom/push/PushCrypto.jsm#237-248) how the secret is used to decrypt the message.

**Comment by rfk** [comment]
@kitcambridge is it still correct that we don't need either key or secret if we're not sending message payloads with the push?

**Comment by kitcambridge** [comment]
Yup, that's correct!

**Comment by vladikoff** [comment]
@eoger landed support for this
