### ISSUE TITLE
Investigate large number of "user@xyz.localdomain" errors in our bounce logs

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1134]
The auth-bouncer logs [1] show a large number (hundreds per day) of "databaseError" logs that have error info of the following form (edited to remove PII):

```
"err": "{\"message\":\"Unknown account\",\"isBoom\":true,\"errno\":102,\"output\":{\"statusCode\":400,\"payload\":{\"code\":400,\"errno\":102,\"error\":\"Bad Request\",\"message\":\"Unknown account\",\"info\":\"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format\",\"email\":\"USERNAME@SOMETHING.localdomain\"},\"headers\":{}}}",
```

Note the unusual email address "USERNAME@SOMETHING.localdomain".  More concrete examples for "SOMETHING" include "USERNAME@firefox.localdomain", "USERNAME@gmail.localdomain",  "USERNAME@hotmail.localdomain", etc.

I find it hard to believe that users are so regularly typing in "localdomain" when trying to sign up.  I wonder if it's being added by some part of our mail delivery infra, so that the sequence goes like this:

* User enters e.g. "ryan@gmail"
* Account gets created with "ryan@gmail", confirmation email sent
* Cloud emaily stuff happens, the email bounces but shows up in our bounce queue as "ryan@gmail.localdomain"
* The bounce processor tries to delete the account "ryan@gmail.localdomain", but that account doesn't exist, so it produces a databaseError log that shows up in the above dashboard
* Meanwhile, the user doesn't get told that their email bounced because we *didn't* delete the "ryan@gmail" account

@jrgm does this seem plausible?

[1] https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/Auth%20Bouncer%20Logs

**Comment by rfk** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1232587 to dig into the db and check for emails that should have been cleaned up after a bounce, but weren't.

**Comment by vladikoff** [comment]
Ah yes `localdomain` returns!

**Comment by shane-tomlinson** [comment]
> Ah yes localdomain returns! 

Is `localdomain` something attached by `sendmail` or whatever the Amazon equivalent is?

**Comment by rfk** [comment]
> Meanwhile, the user doesn't get told that their email bounced because
> we didn't delete the "ryan@gmail" account

The prod db does indeed show instances where we got a bounce for "user@gmail.localdomain" and left a corresponding "user@gmail" account live in the database.

**Comment by jrgm** [comment]
I confirmed in production logs and tests in stage that user@foomail is used as the To address when delivering the outbound email to postfix locally on each auth_server. Postfix logs indicate that it then "fixes" the email address to be user@foomail.localdomain before delivery to SES. This, subsequently, is what the bounce message reports in SQS.

**Comment by rfk** [comment]
A simple fix would be for us to strip the trailing `.localdomain` in the bounce processing code...@jrgm does this seem sensible, and can you think of any other scenarios that might break if we started doing that sort of cleanup?

**Comment by jrgm** [comment]
That would work. Can't think of anything that really expects the addition of this localdomain. 

I addition/alternative, there's probably a way to configure postfix to not append localdomain (i.e., there is, but don't have it at my fingertips right now). 

Perhaps, if not dev testing, auth-server should return error if the email does not match `/@.+\..+/`

**Comment by rfk** [comment]
> auth-server should return error if the email does not match /@.+\..+/

Aye.  Our email validation rules seem to be a regular source of surprise/contention, following the trail of bugs linked from https://github.com/mozilla/fxa-auth-server/issues/1135

**Comment by jrgm** [comment]
On Dec 21, I deployed a config change to Postfix to not append `.localdomain` to a non-FQDN email address, so (module extra quoting on some unusually punctuated localpart of email address), the bounce handling can now find and delete the row in the db.

**Comment by vladikoff** [comment]
FixeD!
