### ISSUE TITLE
Disallow email addresses without a fully-qualified domain component?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1135]
As noted in #1134, users can currently sign up with email addresses like "somebody@gmail" and "user@hotmail".  Wikipedia assures me these are perfectly well-formed email addresses [1] but it just seems extraordinarily unlikely that they're what the user actually wanted.  Should we re-consider allowing addresses without a fully-qualified domain component?

[1] https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/issues/1871 related?

**Comment by shane-tomlinson** [comment]
@vladikoff - I thought your email checker originally checked for this scenario? If it doesn't, could it be made to do so? Perhaps that'd drive up it's usage numbers and reduce this class of error.

**Comment by rfk** [comment]
Heh, I remembered having this discussion before, but I didn't remember just how *often* we'd had it!  In all the links out of all the issues linked form the one above though, I don't see a single instance of an actual user who wanted to register with an "a@b" email address.

Still, perhaps the best way to move forward with this is to improve our handling of bounced addresses, since "send it an email and see what happens" remins the Only True Way to properly validate an email address...

**Comment by rfk** [comment]
> improve our handling of bounced addresses

After much deliberation, I think this is probably the best way to move forward on the issue, otherwise we just end up playing whack-a-mole with things are do/dont fall into our current definition of "valid email address".
