### ISSUE TITLE
Investigate escaping-related lookup errors in our bounce handling code

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1136]
The auth-bouncer logs [1] show a small but steady stream of "databaseError" logs that have error info of the following form (edited to remove PII):

```
    "err": "{\"message\":\"Unknown account\",\"isBoom\":true,\"errno\":102,\"output\":{\"statusCode\":400,\"payload\":{\"code\":400,\"errno\":102,\"error\":\"Bad Request\",\"message\":\"Unknown account\",\"info\":\"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format\",\"email\":\"\\\"USERNAME\\\"@DOMAIN.com\"},\"headers\":{}}}",
```

That is, the "email" in the bounce message has backslashes and double-quotes and dots like `\"USERNAME.\"`@DOMAIN.com`.  That's unusual, but valid, and even if it bounces I don't see what it should cause the bounce handler to error out.

I wonder if something like the following is happening:

* User signs up with something like `"ryan."@hotmail.com` as their email address
* The account gets created, email gets sent, but it bounces
* Thanks to some normalization somewhere, the email in the bounce message gets backslashes on its quotes, becoming `\"ryan.\"@hotmail.com`
* The bounce handler tries to delete the account, but fails because it looks it up via a different address, producing the error log entry

[1] https://kibana.fxa.us-west-2.prod.mozaws.net/index.html#/dashboard/elasticsearch/Auth%20Bouncer%20Logs

**Comment by rfk** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1232587 to dig into the db and check for emails that should have been cleaned up after a bounce, but weren't.

**Comment by rfk** [comment]
> User signs up with something like "ryan."@hotmail.com as their email address

Peeking in the prod db reveals an account of the for `ryan.@hotmail.com` matching the bounced email address `\"ryan.\"@hotmail.com`, so I wonder if both the quotes and slashes are being added somewhere in the email sending pipeline.

**Comment by rfk** [comment]
@jrgm to take a look at postfix logs to make sure we understand what's going on here

**Comment by jrgm** [comment]
So, postfix is not adding quote marks (only adds .localdomain to a non-dotted domain part). 

The raw log on disk shows this format:
```
{"Timestamp":1450000000000000000,"Logger":"fxa-email-bouncer","Type":"databaseError",
 "Severity":2,"Pid":2247,"EnvVersion":"2.0","Fields":{"op":"databaseError","email":"USERNAME@DOMAIN.localdomain",
 "err":"{\"message\":\"Unknown account\",\"isBoom\":true,\"errno\":102,\"output\":{\"statusCode\":400,
   \"payload\":{\"code\":400,\"errno\":102,\"error\":\"Bad Request\",\"message\":\"Unknown account\",
   \"info\":\"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format\",
   \"email\":\"USERNAME@DOMAIN.localdomain\"},\"headers\":{}}}"}}
```
Note that the email is in there twice, normal format in the first case, escaped quotes inside JSON.stringify section.

**Comment by rfk** [comment]
The quoted ones I think are different, in that they have a dot somewhere in the username portion, like `ryan.@hotmail.com`.

**Comment by jrgm** [comment]
Yeah, sorry. Thought I had looked at that. Anyways, given input of `myuser.@mydomain.com`, the bounce message via SES will contain content that results[1] in `recipients[i].emailAddress` having the value `"myuser."@mydomain.com`.

[1] https://github.com/mozilla/fxa-auth-server/blob/master/lib/bounces.js#L43

Bleh. Other patterns on input that produce this extra escaping are a leading dot `.myuser@mydomain.com` and interior double-dots `my..user@mydomain.com`. Standards, ftw?

**Comment by jrgm** [comment]
p.s., the verbatim original email address is in the actual bounce message returned by MX host, but in unstructured text that will probably vary by SMTP implementation at the MX. So, not really usable in a predictable way. 

Example: `diagnosticCode: 'smtp; 550 5.1.1 <myuser.@mydomain.com>: Recipient address rejected: User unknown in local recipient table'`

**Comment by rfk** [comment]
Maybe relevant: http://www.postfix.org/postconf.5.html#smtp_quote_rfc821_envelope

**Comment by rfk** [comment]
@rfk to review and decide next step

**Comment by jrgm** [comment]
Yeah. So this needs to find a good library to un-escape the values back to the original submitted format.

**Comment by rfk** [comment]
The email-addresses module [1] claims to parse strictly according to the RFC, and seems to do a good job of the troublesome address encountered here:

```
> ea = require('email-addresses')
> ea.parseOneAddress('"ryan."@hotmail.com')
{ parts: 
   { name: null,
     address: 
      { name: 'addr-spec',
        tokens: '"ryan."@hotmail.com',
        semantic: 'ryan.@hotmail.com',
        children: [Object] },
     local: 
      { name: 'local-part',
        tokens: '"ryan."',
        semantic: 'ryan.',
        children: [Object] },
     domain: 
      { name: 'domain',
        tokens: 'hotmail.com',
        semantic: 'hotmail.com',
        children: [Object] } },
  name: null,
  address: 'ryan.@hotmail.com',
  local: 'ryan.',
  domain: 'hotmail.com' }
> 
```

So, I propose we try this out to normalize addresses in the bounce handler.  We could be conservative any only apply the normalization if we fail to look up the account with the unparsed form, e.g. something like:

```
  db.emailRecord(email)
    .catch(function(err) {
      if (err.errno === 102) {
          var normalizedEmail = ea.parseOneAddress(email).address
          if (email !== normalizedEmail) {
            return db.emailRecord(normalizedEmail)
          }
      }
      throw err;
    })
    .then(/* whatever logic is there already */)
```


[1] https://www.npmjs.com/package/email-addresses

**Comment by vbudhram** [comment]
@rfk Your solution seems reasonable. I will add checks and supporting test cases for this.

**Comment by vbudhram** [comment]
Woops! Ignore my previous comment...thought you were assigning me to work on issue not to review :)
