### ISSUE TITLE
Add push support for remote disconnect of devices

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1139]
When the user clicks "Disconnect" in the device view from the content server sends a device api request to the auth server 

TODO:
- [x] Desktop Patch
- [x] Payload support : https://github.com/mozilla/fxa-auth-server/issues/1132
- [x] XPCOM Component

This feature requires a Firefox desktop component to listen for push notifications and disconnect itself

![image](https://cloud.githubusercontent.com/assets/128755/11876175/426e761e-a4b6-11e5-9e89-528d578518e8.png)

https://www.lucidchart.com/documents/edit/93d1059c-f2d5-4669-94fa-536a08d5f30c

**Comment by vladikoff** [comment]
@kitcambridge is there a link to the bugzilla patch for the new XPCOM Push notifications so we can follow it? Thanks!

**Comment by rfk** [comment]
The proposal here seems to require message payloads in the push notification.  The push folks are welcome to disagree, but I get the strong sense that the payload-handling stuff in webpush is still too in-flux for us to commit to building something on top of it...

**Comment by kitcambridge** [comment]
@vladikoff https://bugzilla.mozilla.org/show_bug.cgi?id=1189998 landed in today's Nightly. The title refers to e10s, but the bug morphed into "clean up all the XPCOM stuff."

I started writing up some docs, but didn't get very far. :disappointed: For now, the only instructions are the comments in [`nsIPushService`](https://dxr.mozilla.org/mozilla-central/source/dom/interfaces/push/nsIPushService.idl#66-116) and [`nsIPushObserverNotification`](https://dxr.mozilla.org/mozilla-central/source/dom/interfaces/push/nsIPushObserverNotification.idl). Happy to help however I can.

**Comment by eoger** [comment]
Do we have a Bugzilla bug open for the desktop work?

**Comment by eoger** [comment]
@ryanfeeley Do we want to display a notification on Firefox Desktop when the device has been remotely disconnected or do we just sign-out silently?

**Comment by ryanfeeley** [comment]
@eoger This is a good idea. Should I file a bug on Bugzilla?

**Comment by eoger** [comment]
Yes please
