### ISSUE TITLE
Add push support for delete account, change password, reset password

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1140]
Secondary to https://github.com/mozilla/fxa-auth-server/issues/1139

https://www.lucidchart.com/documents/edit/93d1059c-f2d5-4669-94fa-536a08d5f30c/1

![image](https://cloud.githubusercontent.com/assets/128755/11876371/6daedc8c-a4b7-11e5-8ccd-af09ae35e9e6.png)

**Comment by vladikoff** [comment]
@eoger Are we only missing `delete account` from closing this?

**Comment by rfk** [comment]
Assigning to @eoger for comment

**Comment by eoger** [comment]
Yes and no, it is true that we only miss `delete account`, but the push messages we send are empty for now.
In my opinion we could do better an include a payload to these push messages saying explicitly what's happening here.

**Comment by vladikoff** [comment]
Okay, thanks for the comment. Let's reopen a specific bug when Desktop needs push messages to do more and contain data to act on .
