### ISSUE TITLE
Reduce polling in Fx Desktop using push notifications during verification

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1141]
Proposal to:

* Remove polling in FF Desktop
* Use Push to wait for a notification when the user verifies the account

![image](https://cloud.githubusercontent.com/assets/128755/11939589/13c356de-a7f1-11e5-8424-7d29d2c5599f.png)

https://www.lucidchart.com/documents/edit/93d1059c-f2d5-4669-94fa-536a08d5f30c/2

**Comment by vladikoff** [comment]
*Update from meeting:* the "3. ....." notifications parts in the diagram are notifications without payload, so the client has to check what happen, it has to check the account status.

**Comment by philbooth** [comment]
Related browser bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1235607
