### ISSUE TITLE
auth-server appears to be slow at re-resolving DNS

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1155]
currently requests to the oauth server come from clients, profile-servers and auth-servers.

When I put a new oauth-server in, traffic dropped to one-half in the old oauth stack and one-half in the new oauth stack, where the old stack appears to be getting requests from the auth-server, and the new stack taking other request sources.

**Comment by dannycoates** [comment]
Probably because `hapi-fxa-oauth` uses HTTP keep-alive

**Comment by jrgm** [comment]
Yeah, it's definitely using persistent connections from auth to oauth (but not from profile to oauth). 

Anyways, I'll have to use autoscale to refresh all lhe auth-servers to get this over to the new oauth stack. Just gonna give the tank a stir now.

**Comment by jrgm** [comment]
This is done now. All auth-server are using new oauth-server stack.

**Comment by vladikoff** [comment]
from mtg: not sure what to do here! needs investigation. What is the solution? You tell us!

**Comment by rfk** [comment]
It sounds like the ideal solution here would be for oauth-server to tear down any keep-alive connections after they've been held open a reasonable time, rather than allowing them to stay open indefinitely.  Not sure if that's possible form within node/hapi though.

**Comment by rfk** [comment]
Hmm, actually is the keep-alive handled by nginx on the oauth-server side?  If so then maybe we can fiddle with the nginx keep-alive settings to tear things down after a certain number of requests:

  http://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_requests

**Comment by jrgm** [comment]
Hmm, not sure nginx acting as a reverse proxy behind an ELB would enforce that, and would defer to the upstream. But we can test this out in stage.

**Comment by rfk** [comment]
Oh yeah, I always forget about the ELBs, so many layers...

**Comment by rfk** [comment]
I did a quick experiment in dev and the ELB seems to treat keep-alives with the client independently of keep-alives with server, which is the right spec-compliant thing to do, and also means there's no may to configure a cap on the number of requests made per connection.

Looks like if we want a short-term fix, we'll have to do it by tweaking the keep-alive behaviour of the auth-server.

**Comment by rfk** [comment]
Let's disable keep-alive on the auth-server for now, as there doesn't seem to be a good way to limit the lifetime of a keep-alive connection in node.

**Comment by shane-tomlinson** [comment]
> Let's disable keep-alive on the auth-server for now, as there doesn't seem to be a good way to limit the lifetime of a keep-alive connection in node.

Are you suggesting disable keep-alives from users, or between servers? If for users, that's going to have a negative signin performance impact since 6 requests are made in rapid succession:

<img width="494" alt="screen shot 2016-02-03 at 13 50 46" src="https://cloud.githubusercontent.com/assets/848085/12784118/2bd3971c-ca7d-11e5-8460-c81a9b78fb48.png">

Signup has 4 requests in immediate succession, then repeated calls to `/recovery_email/status`:

<img width="995" alt="screen shot 2016-02-03 at 14 00 28" src="https://cloud.githubusercontent.com/assets/848085/12784385/e09bad0a-ca7e-11e5-81aa-bc54ab7a0b19.png">

**Comment by shane-tomlinson** [comment]
I didn't finish my thought. w/o keep-alive, each of those requests will require a fresh TCP connection, with all the work necessary to establish the connection, including TLS negotiation.

**Comment by rfk** [comment]
>  Are you suggesting disable keep-alives from users, or between servers?

Only on the connection pool between fxa-auth-server and fxa-oauth-server
