### ISSUE TITLE
Increase token isFresh threshold to greater than one hour (perf issue)

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1159]
Background: 
  https://github.com/mozilla/fxa-auth-server/pull/1039#issuecomment-138110095
  https://github.com/mozilla/fxa-auth-server/pull/1039#issuecomment-138117419
  https://github.com/mozilla/fxa-auth-server/pull/1039#issuecomment-138138124
  https://github.com/mozilla/fxa-auth-server/pull/1042

When we put in code to update metadata on the session token table, we significantly increased write IO and CPU on the database. To reduce some of that load, we put in a "freshness" measure to skip some updates in the recent hour (chosen arbitrarily at that time of the PR).

This past Friday, there were some issues with database load (details in a bugzilla bug). With weekend traffic lower, it's less of a problem now, but we may see a return of wobbling on Monday. 

I am looking into upgrading the database instance size, which I expect will alleviate these problems. However, in the short term, to have the option if we need it, we could look at bumping the one hour threshold up to perhaps four (or more) hours.

Thoughts? 

Current code sets this threshold here: https://github.com/mozilla/fxa-auth-server/blob/master/lib/tokens/session_token.js#L69

**Comment by jrgm** [comment]
Put in a strawman PR in #1160. Please take a look and comment.

**Comment by philbooth** [comment]
As per https://github.com/mozilla/fxa-auth-server/pull/1160#issuecomment-174273379, I think 4 hours will have no effect. The only thing depending on this right now is the devices view, which is hidden anyway. We could try 24 or 48 hours if you like?
