### ISSUE TITLE
Backoff/retry handling for push subscriptions?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1163]
The webpush spec includes a simple 429/Retry-After mechanism for signalling that we've sent too many push notifications in too short a time [1].  It's almost identical to the one we use ourselves in FxA.  What, if anything, should we do to handle this response code when the auth-server sends a push notification?

(And if we decide the answer is "nothing", let's document that decision in the feature card for future reference)

[1] https://tools.ietf.org/html/draft-ietf-webpush-protocol-02#section-6

**Comment by vladikoff** [comment]
@kitcambridge you mentioned before that you don't send 429 at this time, should we close this?

**Comment by kitcambridge** [comment]
Let's close this out for now. I'll make sure to copy you on the ticket if we eventually decide to support 429.
