### ISSUE TITLE
TTLs for push notifications?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1164]
The webpush spec has some interesting nuance around message TTLs at [1]:

"""
   Absence of the TTL header field is interpreted as equivalent to a
   zero value.  A Push message with a zero TTL is immediately delivered
   if the user agent is available to receive the message.
   [...]
   If the user agent is unavailable, a push message with a zero TTL
   expires and is never delivered.
"""

Should we set a TTL value on our push notifications, and if so, what should it be?  At the  least, we need to be aware of this "never delivered if the client is offline" behaviour when building out features on top of it.

[1] https://tools.ietf.org/html/draft-ietf-webpush-protocol-02#section-6.2

**Comment by rfk** [comment]
(as usual, /cc @kitcambridge to please sanity-check whether I've misinterpreted anything in the spec)

**Comment by kitcambridge** [comment]
I think you can omit the TTL. It sounds like your use cases depend on Firefox running, and you already check on startup to see if the user has verified, deleted, or reset their account. Is that accurate, or am I totally off?

Also, any messages with a TTL will be delivered all at once when Firefox starts up. Unless you include data or create multiple push endpoints, you can't really distinguish between them. The server doesn't support message collapsing yet (via the `Topic` header; webpush-wg/webpush-protocol#62 has the deets), so you can't merge multiple messages sent while Firefox is offline into one.

**Comment by rfk** [comment]
> you already check on startup to see if the user has verified, deleted, or reset their account.

I suspect you're right, and we certainly do the verification check on startup, which is the most important driving case for this initial work.  In which case we should document this decision explicitly in the feature card, since it has important implications for client behaviour.

TTLs could become important when we move to messages with payload, where we might want more reliable delivery.

**Comment by vladikoff** [comment]
TODO: close this and update the feature card with "ignoring TTL"

**Comment by vladikoff** [comment]
Done in https://github.com/mozilla/fxa/commit/3a045e67823d97b82d6459519b45b9eab883ed13
