### ISSUE TITLE
How to run fxa-auth-server as a daemon ?

### ISSUE THREAD

**Issue by cwittmer** [mozilla/fxa-auth-server#1170]
There is nowhere any information on how to run 'fxa-auth-server' as a daemon. 
No start-script that is useable for SysVinit or systemd.
Please don't tell me to do ...
```
npm run start-mysql
```
... this is not convenient for a 'productive' system ...

**Comment by vladikoff** [comment]
@cwittmer we don't have a default daemon because it is out of scope of this project. we use `pm2` daemon and http://supervisord.org/ daemon in different environments.

**Comment by vladikoff** [comment]
Examples here https://github.com/mozilla/fxa-local-dev and https://github.com/mozilla/fxa-dev

**Comment by cwittmer** [comment]
@vladikoff and the scope is to have **fxa-auth-server** just for **development** purposes ?
really ?

**Comment by vladikoff** [comment]
@cwittmer I gave you 2 development examples that are open source. Both of those process / daemon managers are valid to use in production as well.
