### ISSUE TITLE
Add API to query whether an email already exists in the db

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1176]
In support of a better user experience during the AMO user migration, we want the ability to show either the sign-in or sign-up screen depending on whether the user already has a Firefox Account.  That means we need an unauthenticated API that can be used to query such information.

I propose we extend the existing `/v1/account/status` endpoint [1] for this purpose.  The simplest option could be:

```
curl -v "https://api-accounts.dev.lcip.org/v1/account/status?email=test@example.com"

{
  "exists": false
}
```

This runs a small risk of the plaintext email showing up in e.g. webserver logs; we could instead accept it in a POST request body if we want to avoid that.  Other sites that offer such an API seem to mostly do it via a POST request.

The tricky part of this will be appropriately limiting access to this API.  We don't want to allow simple automated scripts to enumerate all email addresses in our db.  There are a lot of hoops we could force consumers to jump through here, e.g. demanding some sort of CSRF token or a proof-of-work or even a signed JWT from AMO saying that it's OK to make this query.  But since we ultimately want to result of this API to be visible to the end-user, I'm not sure they'd be worth the complexity.

As a strawman, I suggest we just protect it by:

1. adding a new customs check (like [2]) that aggressively rate-limits the requests to this endpoint.
2. ensuring strict CORS headers so it can only be called from the content-server (not as a background API request from some shady website)

@vbudhram thoughts?

[1] https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L593
[2] https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L328

**Comment by vbudhram** [comment]
@rfk I think the best long term solution would be to use POST on getting account status. However, since there is already an endpoint that gets account status using GET, I am of the feeling that extending its functionality might be better. We could create a new issue on migrating the `/account/status` endpoint to using POST, to be solved later. I am not sure of the impact that refactoring would have.

Do you have an idea of the rate limiting policy that we could possibly use? Is there a standard for API requests?

**Comment by rfk** [comment]
I wouldn't be opposed to adding a `POST` behaviour to this route, if it's concretely better for handling the email case, and leaving existing consumers of it to continue using `GET`.

W.r.t rate-limiting, let's follow a similar pattern to what we use for rate-limiting bad login attempts [1].  (IIRC the numbers are tweaked in our production config, but that repo contains the basic idea).  We can block at two levels:

* Allow a small number of calls within a given timeframe from any individual IP address
* Allow a larger-but-finite number of total calls from any IP address (with the actual limit configurable, so we can adjust it based on our expected traffic pattern)

[1] https://github.com/mozilla/fxa-customs-server/blob/master/config/config.js#L58

**Comment by rfk** [comment]
@shane-tomlinson comments in [1] that we may need to know the verification status of the email.  Do we have any other requirements to capture at this stage?  (And given those requirements, does it still make sense to pile onto the `/v1/account/status` endpoint, or should we do something new over in e.g. the `/v1/recovery_email/` namespace?)

[1] https://github.com/mozilla/fxa-content-server/issues/3501#issuecomment-183053459

**Comment by vbudhram** [comment]
The only additional requirement I can think of is that we might need to add an additional response field "verified". Currently `/v1/account/status` returns [exists and locked](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#get-v1accountstatus). Or does an account not exist until the email has been verified?

**Comment by rfk** [comment]
>  Or does an account not exist until the email has been verified?

Nope, the account exists even if it's in an unverified state.  We could consider future compatibility with e.g. [1] and add an "account state" field to the response.  The current possible values would be "verified" and "unverified" but we might add "invalid" in the future.

[1] https://github.com/mozilla/fxa-auth-server/issues/721
