### ISSUE TITLE
fxa-auth-mailer #118 breaks tests in fxa-auth-server

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1177]
On a branch https://github.com/mozilla/fxa-auth-server/tree/train-56-with-updated-auth-mailer where I was updating to pick up latest fxa-auth-mailer, tests now fail after https://github.com/mozilla/fxa-auth-mailer/pull/118

See: https://travis-ci.org/mozilla/fxa-auth-server/jobs/108444351#L682 for test failure.

**Comment by rfk** [comment]
looks like a simple test tweak, I'll put up a fix in a min or two
