### ISSUE TITLE
`npm run` scripts should respect any NODE_ENV set in the environment

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1179]
Many of our `npm run` scripts explicitly set `NODE_ENV=dev` before launching the server, which can be confusing for people who want to run the server via e.g. `npm start`.  It would be helpful if the scripts could default to dev but respect any explicitly-set `NODE_ENV` environment variable.

**Comment by jrgm** [comment]
This could be `NODE_ENV=${NODE_ENV:-dev} scripts/foo.sh`, but perhaps scripts should include that default value handling (with the same bashism or other way).

**Comment by vladikoff** [comment]
Let's reopen this if confusion comes back
