### ISSUE TITLE
emit events for device create and delete

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#1186]
Similar to accounts, Sync (and maybe others) would like to know when devices are added/removed.

We'd like these fields:
* uid
* device id
* device type
* create date
* delete date

**Comment by vladikoff** [comment]
:+1:

**Comment by vladikoff** [comment]
from meeting: @dannycoates any updates on this issue?

**Comment by vladikoff** [comment]
@dannycoates should we move this from `active` to `next`?

**Comment by vladikoff** [comment]
does this have to be part of FXA-70?

**Comment by seanmonstar** [comment]
This isn't related to KPIs, as it's not that kind of event. This refers to pushing some sort of `device:delete` event to SNS, similar to the events pushed when an account is deleted.
