### ISSUE TITLE
Measure average time it took the user to verify 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1189]
Will help us understand how long it takes user to verify and use that time to maximize the effectiveness of Push.

**Comment by vladikoff** [comment]
ah we already have that here https://github.com/mozilla/fxa-auth-server/blob/9d864ce1ba45f8cd35ca26cba650d07c6932ab6e/lib/routes/account.js#L925 

AWesome

**Comment by rfk** [comment]
> use that time to maximize the effectiveness of Push.

IIUC, the push is only sent after the user verifies, so I'm not sure if it'll be a useful metric in that context.  Perhaps we need something like "time until device is ready to sync" which I'm working on figuring out as part of https://github.com/mozilla/fxa/pull/113
