### ISSUE TITLE
Flaky push tests?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1192]
Unexpected travis failure: https://travis-ci.org/mozilla/fxa-auth-server/jobs/110857863

**Comment by rfk** [comment]
Uh, I think I busted the link somehow as it's passing now, but I definitely saw a flaky test failure related to the push tests...

**Comment by vladikoff** [comment]
We'll check if this happens locally by looping these

**Comment by vladikoff** [comment]
I ran the test ~100 times and it seemed okay. 
We can reopen if we see this again. 

It could be that this block: 

```
var dbServer
var dbConn = TestServer.start(config)
    .then(
      function (server) {
        dbServer = server
        return DB.connect(config[config.db.backend])
      }
    )

test(
  'push db tests',
  function (t) {
```

works slowly on Travis and connection is not available when tests run. This should affect the other DB tests as well though.

**Comment by rfk** [comment]
>  We can reopen if we see this again. 
:+1:
