### ISSUE TITLE
Send account.reset event in /password/change/finish?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1195]
We recently started sending an SQS event from the /account/reset endpoint, to tell relying services that the password was reset and they should invalidate old device connections.  Should we do the same in /password/change/finish, which also calls `db.resetAccount` to finalize a passoword _change_ rather than _reset_?  If yes, should we reset the same event or make a different one?

@dannycoates thoughts?

**Comment by dannycoates** [comment]
A separate 'passwordChange' event might be nice

**Comment by vbudhram** [comment]
@rfk, for consistency, I think it makes sense to add this into the `/password/change/finish` route. Also, having it as a second event type, 'passwordChange' makes sense as well. This endpoint is being refactored for sign-in confirmation so I could add the notification in after `db.resetAccount` in change password.

Thoughts?

**Comment by rfk** [comment]
This sounds OK to me!

**Comment by rfk** [comment]
We now emit an `account.changedPassword` event.
