### ISSUE TITLE
Create placeholder device records for legacy clients?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1196]
When we shipped the initial version of device registration, we decided not to attempt to synthesize any device records for older devices, reasoning that having a device record on the server that's not actively maintained by the client could only lead to trouble.

I'd like to revisit that choice in light of two things going on right now:
* We're planning a lot of device-related metrics for the year, and having concrete device ids would make these simpler and more reliable. (e.g. #1168)
* We can't enable the "devices list" view until there's a reasonable change of mobile devices showing up in there

Could we do a good enough job of synthesizing placeholder records for devices that don't know how to register themselves?  The following might do the trick:

* A placeholder device record would have only the deviceId set - no name, no push url, nothing that conceptually belongs to the client itself.  When displaying them, we'd show some generic name synthesized from the user-agent data.
* Create a placeholder device record immediately upon signup or signin when service=sync.  This allows us to include the device id in metrics events etc straight away.
* If the device does explicitly register itself after connection, keep its deviceid stable and fill in the additional metadata that it provides.
* In the /cert/sign endpoint, we already try to look up the deviceId so we can log an event.  If there is not deviceId associated with the sessionToken, then:
    * If the service param is present and not equal to "sync", then don't register anything, as this is a web login session rather than  a device
    * Otherwise, create a placeholder device record for that sessionToken and use its deviceId in the logged events

This all seems a bit hacky but I think it could work out OK.  In particular, we would wind up with deviceIds registered for all actively syncing devices (because they have to call /cert/sign) but we would avoid creating bogus device records for web login sessions (because content-server always specifies the "service" parameter).  We might accidentally create device records for e.g. some hand-rolled API client that uses PyFxA to talk to the server, but I could live with that.

@dannycoates would this help with the metrics stuff you're working on?  @philbooth thoughts?

**Comment by philbooth** [comment]
I think it's a good idea, hackishness notwithstanding. I like how the count of synthesized device records decreases naturally as other clients implement device registration, it means there is a definite path towards removing the hacky code in the future.

**Comment by dannycoates** [comment]
This would improve Sync metrics a lot. It'd be great if devices created in this fashion also had a distinct type, like "android-auto" or something.

**Comment by dannycoates** [comment]
I'm :+1: on the approach as well as the concept

**Comment by ckarlof** [comment]
:+1:
