### ISSUE TITLE
GET /account/devices will fail if lastAccessTime is zero

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1197]
Response validation of `lastAccessTime` in the `/account/devices` endpoint requires that it is a positive number. Over in [the database migration](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/schema/patch-014-015.sql#L9), the column was created non-nullable but with a default value of `0`.

Pretty sloppy on my part, as I implemented both of those. :disappointed:

Anyway, I guess this should account for [jrgm's recent observation](https://github.com/mozilla/fxa-auth-server/pull/1131#issuecomment-188446941).

**Comment by philbooth** [comment]
Unless I'm missing something, writing a regression test for this fix isn't easy.

The regression test needs to be a remote test, since the fix is to the Joi validation object. Remote tests don't have a way to penetrate the API boundary and mock any behaviours or values. But `lastAccessTime` is set to `createdAt` by the db server and `createdAt` is automatically assigned to `Date.now()` deep within the auth server's `Token` object. So any remote test has to figure out a way to assign `0` to `createdAt` at that point instead, perhaps by adding some dirty query param handling or something.

I feel like we might benefit from some local tests that directly assert against the validation structure passed to Joi, but that seems a bit like cheating and doesn't really give us the same end-to-end confidence that a remote test does. Hmmm...

**Comment by rfk** [comment]
> Remote tests don't have a way to penetrate the API boundary and mock any behaviours or values.

Yeah, this has been an ongoing tension in this and previous projects.  I'd like to find a way around it where necessary while keeping the nice properties of running against an actual HTTP API.
