### ISSUE TITLE
Include more contextual information in activity events

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1200]
In support of [1] we'll need to include more contextual information in activity event records.  Ideally we'd reach parity with the front-end metrics events where we record things like:

* service
* context
* entrypoint
* campaign
* migration

We could even consider utm_* params if it seems worthwhile.  We'll need to have the content-server pass it through to all backend API calls, perhaps as query parameters or in a special-purpose "metrics_context" field in the POST body.

As a special case, I'd also like to consider persisting it alongside keyFetchTokens so that when the browser fetches down its keys, we can emit an `account.keyfetch` event that includes the context of the flow that let up to that point.

[1] https://github.com/mozilla/fxa/tree/master/features/FxA-70-kpi-dashboards

**Comment by rfk** [comment]
@ckarlof does the idea of having the content-server pass additional metrics-related params through to backend calls seem OK to you from a data-collection perspective?  It seems to blur the "operation essential to providing the service" line a little, but is consistent with what we do for e.g. utm_* parameters in other kinds of interaction.

**Comment by ckarlof** [comment]
> @ckarlof does the idea of having the content-server pass additional metrics-related params through to backend calls seem OK to you from a data-collection perspective? 

Given that all this information is needed or provided to our backend at some point, it doesn't feel like we're leaking any additional information.

That said, artifacts/how-we're-going-to-use-it first, collection second still applies here. I feel that many of those answers are straightforward, but it's still worth planning/documenting it before we do the work to collect it. 

And to conclude: :+1:

**Comment by rfk** [comment]
> artifacts/how-we're-going-to-use-it first, collection second

It's broadly in support of the event-data model described at [1], but that doc could probably say more specific things about the artifacts (e.g. success-rate and time-to-completion of device connection through various entrypoints).

[1] https://github.com/mozilla/fxa/tree/master/features/FxA-70-kpi-dashboards#data-capture-and-storage

**Comment by ckarlof** [comment]
Wow, FxA-70 is really coming along. Nice work.

**Comment by shane-tomlinson** [comment]
@rfk, @philbooth  - can you triage this as you see appropriate?

**Comment by philbooth** [comment]
> perhaps as query parameters or in a special-purpose "metrics_context" field in the POST body

As per https://github.com/mozilla/fxa-content-server/issues/3551#issuecomment-192328960, my preference is for the latter.

**Comment by philbooth** [comment]
Just realised the auth server part should come first, because of the Joi validation. Marking this as `in progress`.
