### ISSUE TITLE
Activity event documentation

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1202]
We need to provide clear documentation on what activity events we emit, when, and what info they contain.  It should be in a place that's easy to maintain in parallel with the code that emits them, and of sufficient clarify/detail that we could point interested end-users at it to help them understand our data collection practices.

Details like [1] are probably a good starting point, but that's not a good place for living documentation for a feature.

[1] https://github.com/mozilla/fxa/tree/master/features/FxA-70-kpi-dashboards#data-capture-and-storage

**Comment by vladikoff** [comment]
We have a starting point here: https://github.com/mozilla/fxa-auth-server/blob/master/docs/overview.md#logging

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this as you see fit?

**Comment by rfk** [comment]
backlogging until the other bugs in this milestone are a little further along
