### ISSUE TITLE
Address @rnewman comments on devices API

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1210]
@rnewman gave us some good feedback on the devices API while looking into implementing it for iOS.  He's got a good eye for these things so we should certainly take heed.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1250783#c3 for full context, but copying below:

"""
- The device descriptor should be at least as descriptive as http://docs.services.mozilla.com/sync/objectformats.html#id2.

That is, my iPhone should report formfactor="phone", device="iPhone 6S", not just "mobile". We're going to have TVs, tablets, phones, watches, laptops, desktops, and refrigerators here, not just phone-or-desktop.
- Presumably we don't bump createdAt if the device ID has already been seen.
- POST /device doesn't give much clarity around what happens if this session is already registered. It implies that if the device ID differs, it'll 400, and if it's the same it'll update metadata, but it'd be nice to be explicit.
- Similarly when I POST /account/create, and I specify a device bundle that's already associated with an existing device, what happens?
- GET /devices should have some kind of 204/delta response to avoid fetching the entire list every time.
  """

**Comment by rfk** [comment]
> GET /devices should have some kind of 204/delta response to avoid fetching the entire list every time.

I'm not convinced a delta response is necessary, but a `304 Not Modified` seems reasonable, and we support this for e.g. profile-server endpoints already.

> Similarly when I POST /account/create, and I specify a device bundle

Personally I'd like to remove that from the API in favour of a separate, explicit device-registration call.  But regardless, this may interact with #1196 and should get clarifying documentation.

**Comment by vbudhram** [comment]
from mtg: @rfk triage?
