### ISSUE TITLE
Add customs checks for password reset and account creation

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1211]
Ideally, calls to these endpoints should count towards the same "checking whether an account exists in our db" total that we added for #1184.  It might get complicated though, because unlike the `/account/status` endpoint, bad things will happen to the user flow if `/account/create` or `/password/forgot` stop working.

**Comment by vladikoff** [comment]
" It might get complicated though", is having a different "weight" for the attempt enough or did you have something else in mind?

**Comment by rfk** [comment]
I meant only that the front-end code will have to somehow gracefully cope with rate-limiting errors when calling these endpoints.  I think we can safely set the limit here high enough that having separate weights will not be much value.

BTW the full list of actions that would need to checked is here: https://github.com/mozilla/fxa-customs-server/blob/master/lib/actions.js#L13

**Comment by rfk** [comment]
AFAICT we have this in place now, closing this out
