### ISSUE TITLE
Check if hawk histogram is used with email status endpoint

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1215]
This might be sending too many events

**Comment by rfk** [comment]
Yeap, it's logged for any endpoint authenticated with a sessionToken, which includes `/recovery_email/status`.    It may be better to log it only for the `/certificate/sign` endpoint, and/or log at lower than 100% sample rate.  @jrgm thoughts?

**Comment by jrgm** [comment]
Yeah, I suppose throttling it could be done. But as noted in IRC, http request metrics are about 9 times the volume of the hawk metric, and that is mostly from the email status endpoint.
