### ISSUE TITLE
error when "npm install"

### ISSUE THREAD

**Issue by schleede** [mozilla/fxa-auth-server#1217]
i have a wheezyserver behind a firewall.
i set several proxyvariables for git and npm.
regardless i get errors because npn want connect to  the sshport from github.com.
But ssh is not open to the internet.
How can i install the fxa-auth-server?

Errors:
`npm ERR! Linux 3.2.0-4-686-pae
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.12.12
npm ERR! npm  v2.7.5
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates                                                                                --mirror ssh://git@github.com/mozilla/fxa-auth-db-mysql.git /root/.npm/_git-rem                                                                               otes/ssh-git-github-com-mozilla-fxa-auth-db-mysql-git-7c4498c4
npm ERR! ssh: connect to host github.com port 22: Connection timed out
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/fxa-auth-server/npm-debug.log
myserver:/opt/fxa-auth-server#
`

**Comment by vladikoff** [comment]
You probably need to tweak your npm or gitconfig, example: https://github.com/npm/npm/issues/5257

Also use node 0.10 or node 4.2. 0.12 is not supported
