### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cwittmer** [mozilla/fxa-auth-server#1236]
Hi,

is it possible to improve the doku in a way that a 'non-developer' is able to setup an own firefox-sync and firefox-auth service ?
I really miss a comunication matrix, which is telling  service a is communicating with service b and c.
Is it enough when all services (all on one host) are listening on 127.0.0.1 and are reached by an 'apache' or 'nginx' reverse proxy ?
Thank you very much :)

**Comment by vladikoff** [comment]
> 'non-developer' is able to setup an own firefox-sync and firefox-auth service ?

We cannot target `non-developers` to try to build FxA. This might be helpful though: https://fxa.readthedocs.org/en/latest/#code

**Comment by cwittmer** [comment]
Thanks for the link ... now the communication of the services seem to be more clear ...
May you add this link to the docu ? Thanks.
Sorry that you think everyone who wants to run his own 'sync' and 'auth' service needs to be a developper :(
My fingers are not all thumbs ... and am a linux sysadmin for long years now ... but never had so many problems to get a service running cause of really missing good documentation ...
... just a little bit more 'specific' info would be nice ...
... even for new devs it would be helpful how this stuff works together ...
