### ISSUE TITLE
signin via Hello in same browser generates 'New sign-in' email notification

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1239]
STR

- in a brand new profile, sign up for an account in the first run flow
- receive "Verify your Firefox Account" email and use it in same browser
- receive "Firefox Account Verified" email (expected)
- Click on Hello control in UI, click 'See how it works'
- Dismiss the X on the whatever intro Hello has.
- Now click on the Hello control in UI again
- click on the signin or signup link in the dropdown
- when prompted enter account password and submit
- Now you will receive a "New sign-in to Firefox" email. Not expected.

This is all in the same browser.

Originally reported by @jrgm

**Comment by shane-tomlinson** [comment]
https://github.com/mozilla/fxa-content-server/issues/3687

**Comment by rfk** [comment]
Unfortunately a Hello login is indistinguishable from a Sync login from a security perspective, I don't think we can justify the investment in fixing this corner case given current product plans for hello/fxa integration.
