### ISSUE TITLE
Request with unexpected param reports failure but that the param is "missing" instead of "unexpected"

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-auth-server#1246]
I've got a build with eoger's public-key patch applied (it was since backed out). The request has keys "id", "name", "pushAuthKey", "pushCallback" and "pushPublicKey". The response fails with a 400 with message set to "Missing parameter in request body: pushPublicKey". It seems the message should say "Unexpected parameter" rather than "Missing parameter".

**Comment by vladikoff** [comment]
@rfk should this be for Tuesday evening triage?

**Comment by vladikoff** [comment]
I think this happened when we had the old auth server deployed.

Here's the current validation for push params: https://github.com/mozilla/fxa-auth-server/blob/7a91f31966550abdab444e0857ff17f1eb1b0625/lib/routes/account.js#L808

Let's reopen if there is more confusion about Hapi error responses.
