### ISSUE TITLE
Do not send "Connect another device" solicitation when creating account from oauth reliers

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#1249]
I'm not sure it makes sense to ask the user to "Connect another device" when they created their account for a non-Sync relier. 

<img width="424" alt="screenshot 2016-05-03 11 46 32" src="https://cloud.githubusercontent.com/assets/2365255/14994428/cbefa856-1124-11e6-86d9-02febdb557b3.png">

/cc @ryanfeeley

**Comment by ryanfeeley** [comment]
We should only be sending this to Sync users. https://github.com/mozilla/fxa-auth-mailer/issues/129

**Comment by vladikoff** [comment]
@rfk any idea how to fix this besides adding the 'service' or whatever to the resume token and adding a new param to `verify_code`?

```js
  FxAccountClient.prototype.verifyCode = function(uid, code) {
    required(uid, 'uid');
    required(code, 'verify code');

    return this.request.send('/recovery_email/verify_code', 'POST', null, {
      uid: uid,
      code: code
    });
  };
```

****

![](http://v14d.com/i/5728f7a571e16.jpg)

**Comment by rfk** [comment]
> adding the 'service' or whatever to the resume token and adding a new param to verify_code

I think this is probably the best approach.  It looks like the verification link already has the service directly in it, so there may not be a need to add it to the resume token:

```
https://accounts.firefox.com/v1/verify_email?uid=6666[...]4f9b
  &code=72[...]]c7
  &service=a4907de5fa9d78fc
  &resume=eyJjYW1wYWlnb[...]3QiOiJubyJ9
```

**Comment by johngruen** [comment]
Hey @ckarlof @ryanfeeley et al...seeing this with Test Pilot is particularly jarring. Proposal:

I like the verification email, but maybe we could say something like

# Account verified

Congratulations on signing into **Test Pilot** with your new Firefox Account.

Did you know you can use the same account to sync your bookmarks, history, passwords and more for Firefox on Desktop, IOS and Android.

### Some kinda sync cta page button/link

**Comment by rfk** [comment]
Thanks @johngruen!  To keep things straight across our different repos, let's use this issue for a short-term "stop sending the sync-specific post-verification email" solution, and work on a more generic variant of the email over in https://github.com/mozilla/fxa-auth-mailer/issues/129

**Comment by rfk** [comment]
@rfk to follow up and see if there's outstanding work here
