### ISSUE TITLE
iCab mobile users receive incorrect user-agent into in "new login" email

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1258]
Spinning this off from https://bugzilla.mozilla.org/show_bug.cgi?id=1265958#c5 (which is moco-employee-only):

"""
It looks like you are now sending an email notification for all login attempts, so users can easily detect unauthorized logins. 

The email will tell the user the App name which is responsible for the login attempt, and here there’s still a potential source for confusion.  Currently it seems that you use the UserAgent to guess the App name, but this seems to be not yet working fully reliable. For the UserAgent of iCab Mobile (see my other post above) the email states that "AppleMail 601.1“ has done the login. It seems that the substring „AppleWebKit“ will result in „Apple Mail“ be reported as App if your UserAgent sniffer can not detect the UserAgent os one of some other popular browsers. Maybe it is more useful to use the very last components of the UserAgent as App name if the UserAgent can not be identified (at least it seems to be very common for browsers to put the real name as the last component into the UserAgent, though it is not always done this way). Or maybe just put the whole UserAgent in the email when in doubt, which is probably less confusing than using the wrong App name (like AppleMail) in the email.
"""

The iCab user-agent string looks like this:

```
Mozilla/5.0 (iOS; OS 9_3_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 iCab Mobile/9.4
```

**Comment by shane-tomlinson** [comment]
We may need to open an upstream patch against https://github.com/ua-parser/uap-ref-impl.

**Comment by shane-tomlinson** [comment]
The regexp list for uap-ref-impl is https://github.com/ua-parser/uap-core/

**Comment by rfk** [comment]
That package has an existing rule for "iCab" here:

  https://github.com/ua-parser/uap-core/blob/master/regexes.yaml#L326

So we may need to add a similar rule for "iCab Mobile".

We could also consider treating anything that produces "Apple Mail" as being unknown, since the regex for matching it is indeed "anything we don't know about that contains AppleWebKit", and it's highly unlikely that anyone is logging in to FxA from Apple Mail.

**Comment by vladikoff** [comment]
Related to this issue, see this: https://sentry.prod.mozaws.net/operations/fxa-content-product/issues/378789/

**Comment by vladikoff** [comment]
Let's reopen if still needed
