### ISSUE TITLE
Update TTL for certain push notifications

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1260]
cc @mhammond @eoger 

We need to adjust TTL for certain Push messages. 
Currently it is set to `'0'` here: https://github.com/mozilla/fxa-auth-server/blob/master/lib/push.js#L115

**Comment by seanmonstar** [comment]
What would be a good value to change this to?

**Comment by mhammond** [comment]
What flexibility do we have here? I can imagine different notifications wanting different requirements - eg, the existing "chrome://fxa-device-update" notification could always remain at zero, whereas a notification of something like "device just synced" could be relatively short, whereas a potential future "here's a tab you should open" would be longer.

cc @kitcambridge

**Comment by mhammond** [comment]
to be clear, I mean how sane would it be to change the code so the TTL is specific to the message type, and is there any scope for the client to dictate that when the push notification is sent directly in response to a specific request from a client? Asking for a friend...

**Comment by rfk** [comment]
Having the message type determine the TTL seems reasonable to me.  I'd hesitate to add a client-specific TTL unless we've got a clear case where it's needed, but that's purely from API-complexity concern.

**Comment by kitcambridge** [comment]
It seems like device updates and syncs could be zero or very short, since Sync will run on startup after a short delay, anyway. The push server can store messages for up to a month, so there's a fair bit of leeway on the TTL for more durable messages like sent tabs. 😉

> is there any scope for the client to dictate that when the push notification is sent directly in response to a specific request from a client?

I'm not quite sure what you mean. Is this a scenario where the client would make a request, and the server would eventually send a push in response?

**Comment by mhammond** [comment]
We are thinking of a http endpoint clients can connect to that will cause a push notification to certain other clients - I was wondering if there is scope for that request to dictate the ttl. But that really was more a thought experiment and I agree with @rfk that we don't need it now and I can't think of a realistic scenario where we would.

**Comment by seanmonstar** [comment]
I don't believe the push events in fxa-auth-server are for fine grained syncing. The 3 'reasons' a push notification is sent are `accountVerify`, `passwordReset`, and `passwordChange`.

**Comment by rfk** [comment]
We're in the process of figuring out how to add support for more types, see e.g. https://github.com/mozilla/fxa-auth-server/pull/1251

**Comment by kitcambridge** [comment]
> We are thinking of a http endpoint clients can connect to that will cause a push notification to certain other clients - I was wondering if there is scope for that request to dictate the ttl.

Oh, right, now I understand. Thanks!

**Comment by vladikoff** [comment]
TTL will be 5 hours for the device disconnect (and other notifications), and '0' by default, see https://github.com/mozilla/fxa-auth-server/pull/1269/files#diff-539df6289b63785f3c1f4660c1db4107R19

Closing this, let me know if anything is missing...
