### ISSUE TITLE
Not all endpoints perform schema response validation

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1262]
Noticed that some endpoints perform validation on the response of a request and some do not. Should this be made consistent or was their a reason not to perform validation?

Endpoints that don't perform response validation: 
1. /recovery_email/verify_code
2. /recovery_email/resend_code
3. /account/openid/login
4. /account/status
5. /account/profile
6. /account/unlock/resend_code
7. /account/unlock/verify_code
8. /account/reset
9. /account/destroy

**Comment by rfk** [comment]
consistency++, and I don't see any reason not to add validation to the endpoints listed above.

**Comment by vbudhram** [comment]
from mtg: closing for now
