### ISSUE TITLE
Send location information to auth-mailer.sendVerifyLoginEmail

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1274]
ref mozilla/fxa-auth-mailer#162.

The original signin confirmation spec calls for signin location information to be sent in the confirmation email. We descoped this work to move more quickly.

**Comment by rfk** [comment]
Ref https://github.com/mozilla/fxa-auth-mailer/issues/165

**Comment by rfk** [comment]
Moving this to the FxA-99 milestone

**Comment by shane-tomlinson** [comment]
This issue can now be closed since @TDA's patch has landed! Nice work @TDA, @vladikoff and @vbudhram on pushing this through.
