### ISSUE TITLE
Refactor metricsContext stuff to stop passing so many objects around

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1284]
From https://github.com/mozilla/fxa-auth-server/pull/1259/files#r65112250:

> We're doing a lot of passing objects around here, passing in a `metricsContext` to each route and them passing the `request` to a bunch of logging calls.  I wonder if we could clean this up by changing around our abstractions.  What if we have some Hapi plugin (or whatever it's called) that added a metrics object to the incoming request, so we could do something like:
>
> ```
> return request.app.metrics.event('delete', { ...data... });
> return request.app.metrics.activityEvent('account.signed', { ...data... });
> ```
>
> Do you think something like that might come out cleaner overall?

**Comment by rfk** [comment]
I'm going to bump this into "quality" milestone

**Comment by philbooth** [comment]
Related enough to tackle as part of the same refactor, from https://github.com/mozilla/fxa-auth-server/pull/1393#discussion_r73544667:

> Not in the scope of this PR, but seems like we could give [gather](https://github.com/mozilla/fxa-auth-server/blob/master/lib/metrics/context.js#L125) some smarts to pull out `code` if auth creds are not found. This could potentially help us not have to make fake request objects.

**Comment by philbooth** [comment]
More related discussion, from https://github.com/mozilla/fxa-auth-server/pull/1431#discussion_r77593478:

> Maybe that decision to stash per-event was wrong btw. I think we made it before we brought the lifetime of the stashed data in memcached down from infinity to 30 minutes. It seems entirely reasonable now to remove the event name from the key and just store data against the token (or faked token) instead.
>
> (the corollary to this is that we'd also need to change the behaviour of `gather` so that it doesn't clear the data after fetching it and remains available for subsequent events)

> ...

> One approach, which I'm not sure how well it would work out in practice, could be as follows.  We know that if the email bounched, there's no way that the `account.confirmed`, `account.signed` etc events can have taken place.  So we look for the data that was stashed for one of those events, clear it (because they're now never going to happen) and log it in the event here.
>
> Hmmm...having typed that out I'm not sure I like it, perhaps we should take a step back and think end-to-end about managing this metrics data, with the new requirements in mind.

**Comment by philbooth** [comment]
I just had a startling realisation, although maybe you were already aware of it @rfk? I don't think we need to most of the metricsContext data in the auth server at all, just `flowId` and `flowBeginTime`.

The tables in redshift are normalised as `flow_metadata` and `flow_events`. `flow_metadata` is mostly populated from the `flow.begin` event (there are also some derived columns calculated from later events). That includes all of the columns `context`, `entrypoint`, `migration`, `service`, `utmCampaign`, `utmContent`, `utmMedium`, `utmSource` and `utmTerm`.

So, unless I'm mistaken, this refactoring should also involve removing those fields from the `metricsContext`. Obviously we'll need to stop sending them to the server first, so that requests don't fail with 400 responses for an invalid payload.

**Comment by philbooth** [comment]
(to clarify, that last comment is discussing the tables in redshift as they are specced, not as they happen to be right now)

**Comment by rfk** [comment]
IIUC, what you're saying is, we won't need to include all the `utm*` and other junk on auth-server flow events, because we can get them off the corresponding `flow.begin` event after the fact?  SGTM!

**Comment by philbooth** [comment]
> we won't need to include all the `utm*` and other junk on auth-server flow events, because we can get them off the corresponding `flow.begin` event after the fact?

Yep, exactly.

**Comment by philbooth** [comment]
From https://github.com/mozilla/fxa-auth-server/issues/1457#issuecomment-247542611:

> > Hrm, so I think I see - on the server we use the `service` parameter to distinguish between cert-signs from content-server and from the device.  But if they're both part of the same flow, we only have a single value for the `service` parameter.
> >
> > ISTM that perhaps the cert-sign event from content-server should, somehow, just not be included in the flow metrics.  Perhaps we can detect on the server and not emit the flow event in this case?
>
> I like this plan, but we also need to consider what to do about non-Sync sessions.
>
> Currently we emit flow events for all sessions, not just Sync. Many of those non-Sync sessions are currently accidentally showing up as completed because of this bug (so right result for the wrong reason). If we fix it in this way, we'll need to change the re:dash queries to use different completion signals for non-Sync flows.

Based on the above, there is something else I'd like to include in this refactor. We should explicitly define the completion signal for each flow id. The assumption that it will be the first `account.signed` event has proven to be inaccurate for non-Sync sessions.

Doing this should ensure we get correct numbers in the sign-in funnel.

**Comment by rfk** [comment]
I think you mentioned it on IRC, but noting my support for it here: we should consider an explicit `flow.complete` event that we emit to signal the fact that we got you to where you wanted to go, whereever that was.

**Comment by philbooth** [comment]
> I think you mentioned it on IRC, but noting my support for it here: we should consider an explicit `flow.complete` event that we emit to signal the fact that we got you to where you wanted to go, whereever that was.

Opened separately as #1480.
