### ISSUE TITLE
Device names with non-BMP characters are rejected.

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-auth-server#1285]
If you add a non-BMP unicode char to the device name in Firefox Sync options (eg, I used 𝌆, but any should do), device registration fails with http status code 400, and a body of:

> {"code":400,"errno":107,"error":"Bad Request","message":"Invalid parameter in request body","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format","validation":{"source":"payload","keys":["name","name"]}}

I believe the request body is valid and correct utf-8 for the character, and devtools shows the request looking correct (ie, the name is rendered correctly by devtools in the request body)

All clients with names like this then retry registration each startup.

**Comment by rfk** [comment]
Sadly, fixing this will require a lot of infrastructure work for us to migrate our MySQL instance from the "utf8" charset to "utf8mb4".  Which we should definitely do, just noting it won't be a quick fix.

**Comment by vladikoff** [comment]
depends on https://github.com/mozilla/fxa-auth-db-mysql/issues/229

**Comment by vladikoff** [comment]
`show procedure status`

**Comment by rfk** [comment]
This is now unblocked, moving into train-96.  IIUC the only thing we have to do in this repo is to remove the filter on astral-plane characters when validating device name.
