### ISSUE TITLE
Fix nsp warning for moment.js

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-server#1295]
Ref: https://travis-ci.org/mozilla/fxa-auth-server/jobs/139036647#L830

We should probably add https://nodesecurity.io/advisories/55 to [.nsprc](https://github.com/mozilla/fxa-auth-server/blob/master/.nsprc) and then _maybe_ remove the `--force` flag from [.travis.yml:57](https://github.com/mozilla/fxa-auth-server/blob/52f9ee8255fe42bf401edd1e441c30abd8d81666/.travis.yml#L57).

```sh
$ grunt nsp --force

Running "nsp" task
Warning: (+) 1 vulnerabilities found
 Name     Installed   Patched    Path                                                              More Info                             
 moment   2.10.3      >=2.11.2   fxa-auth-server@1.63.0 > hapi@8.8.1 > joi@6.4.1 > moment@2.10.3   https://nodesecurity.io/advisories/55 
 Used --force, continuing.
Done, but with warnings.
The command "grunt nsp --force" exited with 0.
```

/cc @TDA

**Comment by TDA** [comment]
@pdehaan Doing sensei.

**Comment by pdehaan** [comment]
@pdehaan: Proudly delegating all his work since '13.

**Comment by TDA** [comment]
@pdehaan You are talking about yourself in the third person. https://en.wikipedia.org/wiki/Illeism

**Comment by pdehaan** [comment]
> "Illeism is also a device used to show idiocy"

Yep, checks out.
