### ISSUE TITLE
/password/change/finish should destroy the previous session token

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1303]
When the client submits a sessionToken to the /password/change/finish endpoint, we generate a fresh one in response.  The intention here is that the client replaces its old session token with the new one.  However, I don't see any logic to enforce that the old session token is destroyed.  Should it be?

/cc @shane-tomlinson @vbudhram

**Comment by shane-tomlinson** [comment]
Does the DB take care of destroying the original session token? If not, then yes, we should delete it. I can't think of any reasons why the old session token needs to live on.

**Comment by rfk** [comment]
Ah yes, the call the `db.resetAccount` should destroy it.  Thanks @shane-tomlinson, I'll close this out
