### ISSUE TITLE
verification_reminder_tests sometimes timeout on Travis

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1311]
I have seen this a few times on Travis. For an unknown reason when running the `verification_reminder_tests`, it would randomly timeout. Restarting the tests usually fixes it.

```
not ok test/local/verification_reminder_tests.js ........ 0/1

    Command: "/home/travis/.nvm/v0.10.46/bin/node verification_reminder_tests.js"

    TAP version 13

    not ok 1 test/local/verification_reminder_tests.js

      ---

        exit:     143

        timedOut: true

        command:  "/home/travis/.nvm/v0.10.46/bin/node verification_reminder_tests.js"

      ...

    

    1..1

    # tests 1

    # fail  1
 ```

Ref : https://travis-ci.org/mozilla/fxa-auth-server/jobs/140490182

**Comment by vladikoff** [comment]
from mtg: "maybe: process is not terminating correctly"

**Comment by vladikoff** [comment]
updating to latest `tap` seemed to resolved this a bit, will keep an eye on this if it fails again!

**Comment by vladikoff** [comment]
seems like still happens here: https://github.com/mozilla/fxa-auth-server/pull/1350#issuecomment-233642400

**Comment by vladikoff** [comment]
I think this stopped happening since https://github.com/mozilla/fxa-auth-db-mysql/commit/4de7f530450fd76bdab27341443ff82ec53dd909
