### ISSUE TITLE
Firefox pref "security.OCSP.require" prevents authentication with FxA

### ISSUE THREAD

**Issue by thomcc** [mozilla/fxa-auth-server#1312]
If the preference "security.OCSP.require" is set, then we fail to login via FxA. This was causing a number of problems for TPS. An error log is availiable [here](https://gist.github.com/thomcc/9121233455f034091200bb4e67a39218). The relevant part is probably lines 51 through 56.

There's some telemetry for this pref available as the [CERT_OCSP_REQUIRED histogram](https://telemetry.mozilla.org/new-pipeline/dist.html#!measure=CERT_OCSP_REQUIRED), which shows that it's rare for this to be set, but certainly not impossible.

Anyway, the error code on line 51 of that log is apparently [this](http://james-ross.co.uk/mozilla/misc/nserror?0x805A3FF8), which, after some tracking down, appears to be `MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING`, which is described in the as "The OCSP response does not include a status for the certificate being verified." by the nsserrors.properties file.

Hopefully this should be enough information to help track this down. Let me know if there's anything else that would help.

**Comment by jbuck** [comment]
@thomcc does setting that pref imply that the SSL server must implement OCSP stapling?

Right now we terminate SSL using an AWS Elastic Load Balancer (ELB). According to docs, ELB does not implement OCSP stapling. If we wanted to implement OCSP stapling we'd need to terminate SSL using AWS Cloudfront or individually on each EC2 instance.

**Comment by thomcc** [comment]
Not sure, I'd be lying if I told you this wasn't a bit outside my realm of expertise.

The description for the pref is "Is OCSP required when the cert has an OCSP URI?", and there is also a preference that is is called "security.ssl.enable_ocsp_must_staple", which sounds closer to what you're asking.

This makes me think the answer is no (or at least "not quite"), but at the same time, I'm not nearly comfortable enough with the subject matter to say for sure... and it sounds like something along those lines is likely to be the issue.

**Comment by thomcc** [comment]
FWIW it's very possible this is a bug in the client, either in TPS, or in the client-side sync or FxA code. I've done some testing, and if we do a full logout/login every phase, it will work, well, most of the time. See https://bugzilla.mozilla.org/show_bug.cgi?id=1275125#c11 for a more thorough description.

Also note that if we do this, the error becomes "SEC_ERROR_OCSP_INVALID_SIGNING_CERT".

**Comment by rfk** [comment]
Our certificate does point to digicert's OSCP server, could easily be some problem with that infrastructure as well.

**Comment by mhammond** [comment]
FTR, although it is implied above, Thom can't reproduce a failure when flipping that pref locally. I'm not sure this is actionable, so feel free to close it - we can pick it up again if we get more details or more reports later. In the meantime we are just going to disable setting that pref in TPS.

**Comment by vladikoff** [comment]
cc @rfk

**Comment by rfk** [comment]
> I'm not sure this is actionable, so feel free to close it

sold!
