### ISSUE TITLE
verification reminder emails lack resume token

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1327]
Here is an image of the auth mailer logs showing the original signup link and the two verification reminder emails:

<img width="841" alt="screen shot 2016-07-05 at 11 05 48" src="https://cloud.githubusercontent.com/assets/848085/16581359/fd2c0a24-42a0-11e6-87bf-eb510a5f7993.png">

**Comment by vladikoff** [comment]
There was no plan to support these because these emails arrive a week later. I guess we can add it by storing the token in the db (?) or something. @rfk thoughts?

**Comment by shane-tomlinson** [comment]
The resume token information is what makes it possible to show the user the "Sync preferences" button when the user verifies in the same browser. Storing the original UTM params doesn't seem like that much of a problem since it is the campaign that nudged the user to sign up in the first place.

Storing the resume token could help make https://github.com/mozilla/fxa-content-server/issues/3026 possible - instead of placing the entire resume token into the emails, we could place the resume token ID and then fetch the resume token on verification - this is an idea @rfk mentioned to me several months back.

**Comment by shane-tomlinson** [comment]
From @rfk's original [content-server bug write up](https://github.com/mozilla/fxa-content-server/issues/3026):

> store the resume-token contents server-side and generate shorter opaque ids through which they can be looked up (this would cost two round-trips to the server though)

**Comment by vladikoff** [comment]
I'm -1 on adding resume tokens to reminders, I don't want to complicate the flows. Trying to figure out why some user got into a weird state a week later (due to a reminder email). However if we have to add it I'll add it.

I'm +1 on storing the resume-token stuff server-side though, seems like a thing to do.

Not sure if these two bugs align with our OKRs for Q3 though (maybe the login success rate OKR?)

**Comment by rfk** [comment]
I think it's obvious how we could implement this, but I'm dubious of the value/complexity tradeoff here.  

Conceptually the resume token is to help you complete the original login flow even if it has to traverse an email loop.  Responding to a verification reminder doesn't feel like "completing the original login flow" to me.  I'd be worried that we'd generate weird edgecases by using stale state.

> show the user the "Sync preferences" button when the user verifies in the same browser.

It's not obvious to me that showing this button is any better than taking the user to their account settings page, given that this is potentially weeks after they did the initial sign-up.  @shane-tomlinson is this the only reason you want the resume-token, or do you have other uses for it in mind as well?

**Comment by rfk** [comment]
>  Responding to a verification reminder doesn't feel like "completing the original login flow" to me.

Now, you could argue, that maybe we should make the emails more like that - that the reminder email should be more about "Recently you tried to connect (some specific device) to sync, but didn't complete it.  Do you want to finish connecting it now?"  If we had that framing, I think it would make a lot more sense to preserve the resume-token so we can complete the initial login flow in all its glory.

But that's a bigger refactor that's unlikely make the cut for Q3.

So overall I agree with @vladikoff - if there's some terrible UX that we need to use the resume-token to avoid, we can add it, but the value of it isn't obvious to me at this stage.

**Comment by vladikoff** [comment]
>  if there's some terrible UX that we need to use the resume-token to avoid, we can add it, 

👍 , let me know if we need to reopen this.
