### ISSUE TITLE
Builds with failing tests are passing in CI

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1349]
Noticed this after pushing changes to a branch I'm working on. `npm test` fails but is followed by `npm run test-e2e`, which doesn't fail. The build status appears to be dictated by the result of that second job.

Example: https://travis-ci.org/mozilla/fxa-auth-server/jobs/145796037

**Comment by vladikoff** [comment]
Ah it is a regression from https://github.com/mozilla/fxa-auth-server/commit/8451a5621db22a7c7582be7ac42b9be37677bb34#diff-848030f6d2807bf034c74fb360316d44L21

Seems like we must listen on `spawn` `close` and exit with that status. 
Thanks for finding the issue!
