### ISSUE TITLE
Remove support for accepting raw session token in /password/change/finish

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1351]
This is a follow up to https://github.com/mozilla/fxa-content-server/issues/3875

Once this has been able to ride the trains, remove support for accepting session data from [/password/change/finish](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/password.js#L171)

**Comment by rfk** [comment]
This is blocked on the above content-server PR

**Comment by vladikoff** [comment]
content server 3875

**Comment by shane-tomlinson** [comment]
@vbudhram - the [content server portion of this](https://github.com/mozilla/fxa-content-server/issues/3875) has merged. Can this be pulled out of blocked?

**Comment by vbudhram** [comment]
@shane-tomlinson Yup, should be good to work on this train.

**Comment by vladikoff** [comment]
unblocked with train -67
