### ISSUE TITLE
Discuss adding deploy rate for geodb

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1365]

**Comment by vladikoff** [comment]
Rate limit the geoip emails by a certain rate / %.

**Comment by shane-tomlinson** [comment]
When I spoke with @rfk today, his thoughts were a simple kill switch should be sufficient.

**Comment by vladikoff** [comment]
> When I spoke with @rfk today, his thoughts were a simple kill switch should be sufficient.

-1 on that because there could be issues that we didn't even think of yet, but if you both agreed on that approach go ahead.

**Comment by vladikoff** [comment]
Kill switch is in the PR now 👍
