### ISSUE TITLE
Define Activity Events + Fields

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1366]
These events are used in Re:Dash. It would be helpful to better define them as well as their fields (mandatory + optional) in order to make data exploration easier for everyone on the team and for people outside of the team.

https://github.com/mozilla/fxa-auth-server/blob/master/docs/overview.md#activity-events

**Comment by vladikoff** [comment]
@davismtl do you mean you want description of the actual fields listed in https://github.com/mozilla/fxa-auth-server/blob/master/docs/overview.md#activity-event-structure ?

**Comment by davismtl** [comment]
Correct.

**Comment by vladikoff** [comment]
from mtg: expand the current activity metrics doc, add more detail to it

**Comment by davismtl** [comment]
@philbooth did a great job of doing a first round of definitions here: https://docs.google.com/document/d/1et1zy1f4qimYqpm6a3YGNinvLbFoRjOX8OqooPGg3O8/edit#heading=h.qrbb2drvq5dg

From there, we would just need to see if anything is missing or if we need to elaborate on definitions. Also, it would probably be valuable to put the definitions somewhere everyone can read them. We know  for example that Nick Nguyen is fascinated by FxA data.

**Comment by philbooth** [comment]
Moved this back in to active, proposed document needs more work.
