### ISSUE TITLE
*@o2.pl email users do not get emails

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1371]
Ref: https://www.reddit.com/r/firefox/comments/4upfgd/cant_get_my_confirmation_email_for_mozilla_sync/

I created an account on that service and the email doesn't work. One note: the login / email service does not use HTTPs.

**Comment by vladikoff** [comment]
cc @jbuck @jrgm

**Comment by jrgm** [comment]
So, messages for your test address and other o2.pl are successfully forwarded to SES, and we don't have bounce responses on those messages.

**Comment by rfk** [comment]
A similar report for another *.pl domain:

  https://input.mozilla.org/en-US/dashboard/response/5976726

"""
Hello
verification emails from sync do not come to your tlen.pl.
By that I can not configure the sync on the PC and on your phone
The administrator asks you to share logs SMTP transmission on
the sent message on your [elided]
"""

**Comment by vladikoff** [comment]
TODO:  @vladikoff to investigate

**Comment by vladikoff** [comment]
![](http://v14d.com/i/57bcbb30d4069.jpg)

Fixed! 

How?

Not sure, it started working
