### ISSUE TITLE
/account/reset sometimes fails with 'invalid token'

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1373]
Sometimes `/account/reset` starts failing for no apparent reason. It seems to fail more often on @shane-tomlinson's machine than on mine. Once it starts to fail, it continues doing so until the db server is restarted. Re-starting the auth server at that point has no effect.

This has been happening for a long time, but may have become more frequent recently. We've only seen it happen when running against the memory backend, although that doesn't necessarily mean the problem is there.

In the auth server logs, the `uid` in the failing request payload is always a null byte / `00`. In the db server logs, there is a `SyntaxError: Unexpected token ILLEGAL`.

auth server log:

![auth-server-logs](https://cloud.githubusercontent.com/assets/64367/17208868/4a968ef6-54b2-11e6-8920-8d17590bf6cb.png)

db server log:

![auth-db-logs](https://cloud.githubusercontent.com/assets/64367/17208891/70351650-54b2-11e6-8c38-18fc6ecf0552.png)

db syntax error:

![auth-db-with-compile-error](https://cloud.githubusercontent.com/assets/64367/17208907/80f9f848-54b2-11e6-8224-2825ae7f3fef.png)

**Comment by philbooth** [comment]
Sorry, raised this in the wrong repo, closing.

**Comment by philbooth** [comment]
It [turns out](https://github.com/mozilla/fxa-auth-db-mysql/issues/149#issuecomment-235857305), this was the right repo after all:

> I believe the problem is...drum roll...  the passwordForgotToken is [created with the same createdAt as the EmailRecord](https://github.com/mozilla/fxa-auth-server/blob/80aa280e1eec14ce28763fcb92fa49fa4f8da248/lib/db.js#L172). The emailRecord's createdAt is [propagated to the accountResetToken](https://github.com/mozilla/fxa-auth-server/blob/80aa280e1eec14ce28763fcb92fa49fa4f8da248/lib/db.js#L146). For local dev, [ttl for a passwordForgotToken is 60 mins and for an accountResetToken 15 mins](https://github.com/mozilla/fxa-auth-server/blob/80aa280e1eec14ce28763fcb92fa49fa4f8da248/config/index.js#L254:L268). If the account is more than 60 minutes old, password reset "start" fails. If the account is more than 15 minutes old but less than 60 minutes old, password reset "start" succeeds, but account reset fails. BAM!

**Comment by rfk** [comment]
The presence of this bug has been bugging me, so I was trying to do a bit of history spelunking to see how it was introduce.  @philbooth, I suspect that this issue explains the mystery line of code in our discussion from way back in February: https://github.com/mozilla/fxa-auth-server/pull/1198/files#r54102114

If that is what introduced the bug, then it was a modification in the base `Token` class, so I suspect we'll need to get the behaviour of all token types, not just the password-forgot-token fix in #1379.  At the very least, we should ensure we've got appropriate test coverage of the creation/expiry timestamp handling for all token types.  @philbooth does that seem prudent?  (Not necessarily asking you to do it, just to check my chain of reasoning here :grin:)

**Comment by philbooth** [comment]
> I suspect that this issue explains the mystery line of code in our discussion from way back in February: https://github.com/mozilla/fxa-auth-server/pull/1198/files#r54102114

...and so the epic sleuthing continues. That was very well hunted down!

> If that is what introduced the bug, then it was a modification in the base `Token` class, so I suspect we'll need to get the behaviour of all token types, not just the password-forgot-token fix in #1379.  At the very least, we should ensure we've got appropriate test coverage of the creation/expiry timestamp handling for all token types.  @philbooth does that seem prudent?

Yep, it does. Fwiw, I did trace through the other token creation paths last week and although `passwordForgotToken` was the severest case because it uses the account `createdAt`, there were two other less severe cases as well in `db.createPasswordChangeToken` and `db.forgotPasswordVerified`.

**Comment by philbooth** [comment]
@rfk, fyi I've created #1383 to cover this.
