### ISSUE TITLE
no post-verification email if service!=='sync'

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1385]
I understand the [reasons for not sending the current post-verification email to non-Sync users](https://github.com/mozilla/fxa-auth-server/issues/1249), but [the lack of an `else` on branch in the auth server seems a bit strange to me](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L1290). Users only receive a post-verification email if they are signing up for Sync. It seems like we should still send a "Welcome to Firefox Accounts!" email, that maybe says something along the lines of "Did you know you can use your Firefox Account to sign in to Sync and share data between all of your devices?"

cc @jrgm who brought this up with me.

**Comment by seanmonstar** [comment]
Definitely makes sense. Do we have a template that is a generic "Welcome" message, and doesn't assume the user is using Sync?

**Comment by rfk** [comment]
More context in https://github.com/mozilla/fxa-auth-mailer/issues/129 where we couldn't come up with anything that seemed to make sense from the user's perspective; FWIW I'd be happy to revisit this with input from @ryanfeeley and @davismtl, particularly if we can use it to raise more awareness of sync.

**Comment by vladikoff** [comment]
IMHO we should move this to fxa-features

**Comment by davismtl** [comment]
Just to be sure I understand, we are not currently sending verification emails to non-sync users. We would like to add a generic email notification for everything outside of sync.

If it wasn't in the initial scope then yeah, we should probably make it a new FXA-Feature and prioritize it.

Let me know if I've understood and if so, I'll move it over.

**Comment by rfk** [comment]
Agreed, let's move this into fxa-features for prioritization
