### ISSUE TITLE
Report: Number of FxA account made from Sync'd Tab Hanger

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1390]
Sync team is measuring the impact of the Sync'd Tabs button. We would like to know how many accounts were made via the hanger that opens. (June-24 to July-24)

Since Telemetry landed in Aurora numbers should be pretty low (979 users with no account clicked on the button) but we will likely need to keep tracking the number of FxA created here.

**Comment by rfk** [comment]
When I select the "synced tabs" button, it takes me to the following URL:

  about:preferences?entrypoint=uitour#sync

Not sure what "uitour" is doing there, perhaps it's the default value?  But anyway, if we want to call out specific metrics for this flow, we'll need to give it a specific `entrypoint` value.  It should then show up as part of the "registrations by entrypoint" breakdown here:

  https://app.datadoghq.com/dash/54206/fxa-content-server---registration?fullscreen=74943094

**Comment by davismtl** [comment]
@rfk What other entry point uses uitour?

**Comment by rfk** [comment]
I think it's supposed to be for the actual UI tour that runs (used to run?) the first time you start firefox.  It told you about sync and pointed you at the "sign in to sync" button.

**Comment by davismtl** [comment]
If it no longer exists, would it be fair to say that any tracked new accounts via "uitour" are likely created via the sync'd tabs hanger?

**Comment by rfk** [comment]
I can't find any other way to trigger "entrypoint=uitour" in latest release, so it may be OK to assume it corresponds to synced-tabs.  But we should give it its own entrypoint going forward, for sanity reasons if nothing else; I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1293128

@davismtl is the above-linked data-dog graph sufficient from our side, or should we leave this bug open for additional work?

**Comment by rfk** [comment]
> I can't find any other way to trigger "entrypoint=uitour" in latest release

Actually, not true - "tools -> sign in to sync" also produces it for me, and @mhammond says he can't repro the behaviour I'm seeing...so I don't think "uitour" will be a reliable indicator of use of the synced tabs panel.

**Comment by mhammond** [comment]
Sadly "uitour" seems too aggressive for reasons I don't understand (bug 1293181). When in that state, pretty-much all entry-points other than the hamburger's sync button will be uitour.

**Comment by davismtl** [comment]
This issue is blocked by this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1293181

I will close this until we resolve the "uitour" tracking.
