### ISSUE TITLE
Spurious account.confirmed activity event is emitted before account.verified

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1415]
I just noticed this while working on something else. During the sign-up flow, immediately before the `account.verified` activity event, I saw this rogue `account.confirmed`.

```
activityEvent {"event":"account.confirmed","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:50.0) Gecko/20100101 Firefox/50.0","service":"sync","uid":"85c9370f720c4d5996000d263c01f683"}
```

This event was only added recently in #1393, clearly I did it wrong.

**Comment by philbooth** [comment]
This problem is caused by setting `tokenVerificationId` in the call to `db.createSessionToken` inside the `/account/create` handler. It means that later on, when the account is verified, the initial attempt which is made for sign-in confirmation succeeds so we emit both an `account.confirmed` and an `account.verified`.

It seems to me that we should never set `tokenVerificationId` inside `/account/create`, but I'm wary that there are heaps of edge cases around this feature so I may be overlooking something.

@vbudhram, when you get online, can we have a chat about what the correct behaviour is here?

**Comment by rfk** [comment]
I'm pretty sure we *have* to set `tokenVerificationId` on the sessionToken from `/account/create` or it opens up some strange edge-case attacks.

**Comment by philbooth** [comment]
> I'm pretty sure we *have* to set `tokenVerificationId` on the sessionToken from `/account/create` or it opens up some strange edge-case attacks.

Yep, @vbudhram set me straight about this earlier, we've fixed it instead by special-casing the log statements in #1419.
