### ISSUE TITLE
Placeholder devices are not being destroyed

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1423]
1. Sign in on a legacy device.
2. View device list. Shows one item.
3. Disconnect account.
4. Sign in again.
5. View device list. Shows two identical items, one of which is marked as current device.

<img width="801" alt="screen shot 2016-08-17 at 09 30 46" src="https://cloud.githubusercontent.com/assets/64367/17729743/8d998dec-645d-11e6-9f50-db60a51c4da8.png" />

**Comment by rfk** [comment]
Is this as simple as just needing to delete the device record when the device destroys its sessionToken?

**Comment by philbooth** [comment]
> Is this as simple as just needing to delete the device record when the device destroys its sessionToken?

Quite possibly. Debugging now with a view to having an answer in time for our 1:1. 😄

**Comment by rfk** [comment]
Non-deletion of the device record may or may not be the Right Thing for devices that manage their own registration though.

**Comment by philbooth** [comment]
> Non-deletion of the device record may or may not be the Right Thing for devices that manage their own registration though.

Good point, it isn't. [That stuff definitely does go via `deleteDevice`](https://dxr.mozilla.org/mozilla-central/source/services/fxaccounts/FxAccountsClient.jsm#487-515).
