### ISSUE TITLE
Do we call lib/userAgent more than we need to?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1426]
I just realised there are a couple of places in the `/account/login` handler where we invoke `userAgent.call(...)` and I don't think we need to.

If we have a session token, the user agent data is already available in its parsed form, using the fields `uaBrowser`, `uaBrowserVersion`, `uaOS`, `uaOSVersion` and `uaDeviceType`. And in both of these places, we already have a session token:
- [The call to `mailer.sendNewDeviceLoginNotification`](https://github.com/mozilla/fxa-auth-server/blob/7a91f31966550abdab444e0857ff17f1eb1b0625/lib/routes/account.js#L557-L562).
- [The call to `mailer.sendVerifyLoginEmail`](https://github.com/mozilla/fxa-auth-server/blob/7a91f31966550abdab444e0857ff17f1eb1b0625/lib/routes/account.js#L583-L591).

It seems like we should just construct the data objects manually and assign the relevant `ua...` properties from the session token instead.

**Comment by vladikoff** [comment]
@philbooth should we backlog this?

**Comment by philbooth** [comment]
You can if you want to, although I'm still planning to get round to it soon fwiw (but I say that about a lot of stuff, I know).
