### ISSUE TITLE
Increased write traffic to PUT accountuiddevicedeviceid in train-67

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-auth-server#1427]
Upon deploying the auth server to production we noticed an increased in Auth DB write traffic:

![auth db write traffic](https://cloud.githubusercontent.com/assets/578466/17791904/efd07a0c-656b-11e6-8074-4535d2a25903.png)

@philbooth and I believe that this may be the [placeholder devices](https://github.com/mozilla/fxa-auth-server/commit/e12cd08faff8215fd41c9dff046e1e4f46366664) reintroduced in [train-67](https://github.com/mozilla/fxa-auth-server/compare/v1.66.1...v1.67.1). We expect this to trail off over time, so lets check Kibana during Monday triage and see if things have improved.

**Comment by jbuck** [comment]
Things are looking better today: ![screenshot 2016-08-22 11 42 00](https://cloud.githubusercontent.com/assets/578466/17861130/df2511aa-685d-11e6-8d62-6cc217b1d607.png)

**Comment by vladikoff** [comment]
status: graph needs to be checked again

**Comment by jbuck** [comment]
It's all good now!
