### ISSUE TITLE
Is the device record created too early?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1438]
This definitely isn't an auth server issue but it makes sense for us to discuss it here first I think.

I'm not sure about Fennec but certainly desktop Fx creates the device record as soon as it receives a session token. This was already weird in the case of new sign-ups, where it was occurring before the user verifies their email. But now we live in a post-signin-confirmation world, it is also weird for sign-ins too.

How big a deal is it? I'm aware that the following things annoy people:

* For the KPIs, we wanted to measure the time until the device is connected, but that activity event is emitted too early. We can work round it by using the time until the first `account.signed` event instead.

* For the sign-in funnel metrics, it is odd that the `device.created` stage of the funnel happens so early. Again, we can work round it by using first `account.signed` event instead.

* For the devices view, it means unconfirmed sessions will show up. That feels strange and unexpected to me, because we know those devices are not able to access Sync data. This seems like the most important reason to fix it.

The fix would need to be made in the clients, because they determine when to register a device themselves (I'll add this to my long list of things I got wrong when implementing device registration).

But even if we fix it there will always be old clients which can't be fixed. Would that inconsistency be even more annoying than the frustrations listed above? I'm not sure, hence this issue.

**Comment by rfk** [comment]
> For the devices view, it means unconfirmed sessions will show up.
> That feels strange and unexpected to me,
> because we know those devices are not able to access Sync data.

I'm not sure this is unexpected, although we should certainly talk through the details.  While unverified, these devices do still have an active login session on your account, so I feel like they should be visible somewhere in the "things connected to your account" list.

Perhaps we should visually distinguish verified vs unverified devices in the devices view?

**Comment by philbooth** [comment]
> Perhaps we should visually distinguish verified vs unverified devices in the devices view?

I am strongly 👍 to this idea.

/cc @ryanfeeley, @vladikoff for the devices/clients/apps-view feature.

**Comment by rfk** [comment]
I also recall that we originally planned to include device info in the /account/create and /account/login API calls, so we mustn't have been too worried about how early it was created at that time.  Overall I'm feeling like the simplest path forward, is to adjust our expectations for metrics in the manner you suggest above, and to separately figure out what to do about unconfirmed devices in the devices view.  @philbooth any further thoughts on your side?

**Comment by philbooth** [comment]
> @philbooth any further thoughts on your side?

Nope. That works for me, I just wanted to make sure we were conscious of it. Closing.
