### ISSUE TITLE
Report how many users are wiping their only Sync backup

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#1444]
It looks like approximately 150K users/month reset their passwords. How many are doing so without any device syncing in the previous two weeks? This will give us an idea of the scale of the "oops I deleted my only backup probem".

**Comment by rfk** [comment]
I started hacking on this a little over in https://sql.telemetry.mozilla.org/queries/1161/

A surprising number of resets occur with no device activity in the preceeding week.

**Comment by ryanfeeley** [comment]
@rfk Thanks! Looks like zero and one are converging. This is a good thing I imagine.

**Comment by rfk** [comment]
The report is done, let's file follow-up bugs for more detailed questions
