### ISSUE TITLE
Separate `/lib/routes/account.js` into different files

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1445]
This file contains several routes and has grown in size significantly. To help reduce its complexity we can break it up into more concrete routes. This is a follow on to #1400, where the test files were separated.

**Comment by philbooth** [comment]
...and, to be explicit, it should be broken up for 1:1 parity with how the route tests were broken up in #1445.

**Comment by imelismith** [comment]
hey @vbudhram , has this issue been handled/assigned? I'd like to take a crack at it..
