### ISSUE TITLE
Add tracking to distinguish password reset vs password change

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1452]
We can't currently tell the difference between password reset vs password change.
We would like to study retention rate of users that do a password reset with just one device connected.

**Comment by vladikoff** [comment]
from mtg: might not have a flow id  when password is changed.

**Comment by rfk** [comment]
I took a look back through the code here and it turns out, this bug is a lie, created by me mis-remembering how the change-password API works.  The `account.reset` activity event is *not* emitted when doing a password change, only during reset.  So I don't think there's anything to do here.

**Comment by davismtl** [comment]
@rfk do we track password changes?

**Comment by rfk** [comment]
> do we track password changes?

No; we could add a new activityEvent for this.
