### ISSUE TITLE
Asyncify all our calls to crypto.randomBytes

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1474]
Just in case it blocks on startup or whatever, let's make sure we're always calling `crypto.randomBytes` with a callback function rather than having it synchronously return a buffer.

**Comment by seanmonstar** [comment]
I figured I could write a custom eslint rule for this, and I was right! I'll figure out how to smush this together with our current eslint-config-fxa package, and then we can be sure to get them all!

https://github.com/seanmonstar/eslint-plugin-fxa

![async-random-bytes](https://cloud.githubusercontent.com/assets/51479/19010635/729ac864-8738-11e6-8a31-3b10d5707459.png)
