### ISSUE TITLE
Pre-compile features RegExps

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1476]
The `forceFeatureRegExp` or family are Strings in config, and then we run them through `new RegExp`. Currently, we do that `new RegExp` for every request. We should only compile them once.

Alternative I have heard from @philbooth is to add `RegExp` support to convict.

**Comment by philbooth** [comment]
Thanks for raising this @seanmonstar, for reference the convict PR is here: https://github.com/mozilla/node-convict/pull/165

**Comment by seanmonstar** [comment]
convict v1.5.0 is now in npm with support for `format: RegExp`
