### ISSUE TITLE
device.created is not a flow event

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1479]
This came up in my meeting with @davismtl just now.

The `device.created` event should not be a flow event because it doesn't represent a step of the user's flow. It is entirely controlled by the browser or, for legacy clients, the auth server.

Because of that, it might happen at a number of different junctures on any given flow, which makes plotting consistent graphs difficult. Either we'd need a different chart for each position of that event, or we'd have to accept that the event can appear in the wrong place and cause funnels to hockey-stick in the wrong direction.

Simpler to just leave it as an activity event.

**Comment by rfk** [comment]
Makes sense; IIRC we were expecting this to be more useful than it actually turned out to be, because we didn't realize how early in the flow the device would actually register itself.
