### ISSUE TITLE
Memory leak in email status polling endpoint?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1482]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1304287#c8

STR:
* In one shell, `npm run start-mysql | grep "heapUsed"`
* In another shell:
    * `cd ./tests/load/`
    * `make build`
    * edit Makefile and change first line to `SERVER_URL = http://localhost:9000/v1`
    * `make bench`

The running server should print lines about how much heap it's using, and the value steadily increases over the course of the loadtest run.  Interestingly, editing `loadtests.py` to remove calls to `session.get_email_status()` seems to make the problem go away.

**Comment by rfk** [comment]
>  Interestingly, editing loadtests.py to remove calls to session.get_email_status()
> seems to make the problem go away.

Looks like this may have been a read herring; replacing them with calls to `check_session_status` shows to same effect.

**Comment by rfk** [comment]
Also, I'm not able to repro with the v1.69.0 tag.

**Comment by rfk** [comment]
Doing a `git bisect` narrows it down to our update to the latest hapi in https://github.com/mozilla/fxa-auth-server/pull/1330:

```
b3adbcf66d67e8f29929564bc778fd0d22da7eb5 is the first bad commit
commit b3adbcf66d67e8f29929564bc778fd0d22da7eb5
Author: Vlad Filippov <vlad.filippov@gmail.com>
Date:   Tue Sep 13 20:52:06 2016 -0400

    chore(deps): update to latest version of hapi (#1330) r=rfk,seanmonstar,vbudhram
    
    * fix(validation): adjust validation, bump version of joi
    
    * fix(tests): restore tests
    
    * chore(deps): rewrap

:100644 100644 84eea09196d362c946b510953af85a3d90b0c165 a92e26e64d17215338b491aafd0a32b044e53aa4 M	.travis.yml
:100644 100644 40872d41d1693c053240315208f70f10ae92b708 221bfc5d0b4984d0f29d86e8f4c87153295f8c5e M	README.md
:040000 040000 b005fcc90f695847c206f53e4c0d8852cef4e00e c4a54f2a014f73096082d35304715d0c4ff1d723 M	lib
:100644 100644 4fa176872943f4425aa8728b52aab4811ba82ad7 f1a6eb0e2a73b931d9928651f97d0508fdfa4b2e M	npm-shrinkwrap.json
:100644 100644 ac10527bf3d9ffd9f8ef964a8241d01124660726 4117067af063ba30d3132105c156bf166b1b8e5a M	package.json
:040000 040000 c2d0b3bfa446d165754c0979580249e05bf702e6 967866194d7c049635b0420485ba05ff508dc617 M	test
```

**Comment by rfk** [comment]
Possibly related issue https://github.com/hapijs/hapi/issues/3347

**Comment by rfk** [comment]
This does indeed seem related to https://github.com/hapijs/hapi/issues/3347#issuecomment-248123795, I see a steady buildup of unprocessed events in the internal `_notificationsQueue`.  We may have to try downgrading to hapi 14.x in order to unblock train-70.

**Comment by jrgm** [comment]
I think this is all settled now, by reverting to hapi 14, no? Or keeping this open for upstream?

**Comment by rfk** [comment]
Let's close this and keep an eye on the upstream bug
