### ISSUE TITLE
Create dashboards for email bounce templates and types

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1488]
Once https://github.com/mozilla/fxa-auth-server/pull/1466, has been deployed we should create the server-side dashboards to help better track these values per https://github.com/mozilla/fxa-content-server/issues/4040.

**Comment by shane-tomlinson** [comment]
Blocked on train-71 deploy, then we can re-triage.

**Comment by vladikoff** [comment]
Blocked by AWS issues not showing data

**Comment by vladikoff** [comment]
Data is working now in AWS. @vbudhram what do we need to do now?

**Comment by vbudhram** [comment]
Updated bounder dashboards to reflect new data, https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/Auth%20Bouncer%20Logs
