### ISSUE TITLE
Internal Server Error 500 with error code 999 when performs requests

### ISSUE THREAD

**Issue by vityafx** [mozilla/fxa-auth-server#1501]
We used `fxa-auth-server` of `9fb1f71cc3a8629cab27eceacfb3c3ba8e9f5d32` commit before. But recently we have updated it to latest version which was `bbb1aa9f66b2ef3774a01a58c394f5adabef0542` commit. And after that when we perform requests (not all, but many of them) we receive a 500/999 error from the fxa.

This is a log of new version which gives 500 error:

```
> fxa-auth-server@1.71.2 start /home/OMP/v.polevoy/work/cloud/fxa-auth-server
> NODE_ENV=dev scripts/start-local.sh 2>&1

keys file already exists
mail_helper started...
fxa-auth-server.INFO: geodb.start {"op":"geodb.start","enabled":true,"dbPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/fxa-geodb/db/cities-db.mmdb"}
{"Timestamp":1476366184440000000,"Logger":"fxa-auth-db-server","Type":"bin.server.start","Severity":2,"Pid":15588,"EnvVersion":"2.0","Fields":{"message":"listen EADDRINUSE 127.0.0.1:8000"}}
fxa-auth-server.INFO: undefined {"env":"dev","geodb":{"dbPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/fxa-geodb/db/cities-db.mmdb","enabled":true},"log":{"level":"info","fmt":"pretty"},"memcached":{"address":"127.0.0.1:11211","idle":30000,"lifetime":1800},"publicUrl":"http://127.0.0.1:9000","domain":"127.0.0.1:9000","secretKeyFile":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/config/secret-key.json","publicKeyFile":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/config/public-key.json","trustedJKUs":["http://127.0.0.1:8080/.well-known/public-keys","http://127.0.0.1:10139/.well-known/public-keys"],"vapidKeysFile":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/config/vapid-keys.json","db":{"backend":"httpdb"},"httpdb":{"url":"http://127.0.0.1:8000"},"listen":{"host":"127.0.0.1","port":9000},"customsUrl":"none","contentServer":{"url":"http://127.0.0.1:3030"},"smtp":{"api":{"host":"127.0.0.1","port":9001},"host":"127.0.0.1","port":9999,"secure":false,"sender":"Firefox Accounts <no-reply@lcip.org>","verificationUrl":"http://127.0.0.1:3030/v1/verify_email","verifyLoginUrl":"http://127.0.0.1:3030/complete_signin","passwordResetUrl":"http://127.0.0.1:3030/v1/complete_reset_password","initiatePasswordResetUrl":"http://127.0.0.1:3030/reset_password","syncUrl":"https://www.mozilla.org/firefox/sync/","androidUrl":"https://www.mozilla.org/firefox/android/","iosUrl":"https://www.mozilla.org/firefox/ios/","supportUrl":"https://support.mozilla.org/kb/im-having-problems-with-my-firefox-account","redirectDomain":"firefox.com","privacyUrl":"https://www.mozilla.org/privacy","passwordManagerInfoUrl":"https://support.mozilla.org/kb/password-manager-remember-delete-change-and-import#w_viewing-and-deleting-passwords","initiatePasswordChangeUrl":"http://127.0.0.1:3030/settings/change_password","reportSignInUrl":"http://127.0.0.1:3030/report_signin"},"maxEventLoopDelay":0,"scrypt":{"maxPending":0},"i18n":{"defaultLanguage":"en","supportedLanguages":["ar","az","bg","cs","cy","da","de","dsb","en","en-GB","es","es-AR","es-CL","et","fa","ff","fi","fr","fy","he","hi-IN","hsb","hu","it","ja","kk","ko","lt","nl","pa","pl","pt","pt-BR","pt-PT","ro","rm","ru","sk","sl","sq","sr","sr-LATN","sv","sv-SE","tr","uk","zh-CN","zh-TW"]},"tokenLifetimes":{"accountResetToken":900000,"passwordForgotToken":3600000,"passwordChangeToken":900000},"verifierVersion":0,"snsTopicArn":"disabled","bounces":{"region":"","bounceQueueUrl":"","complaintQueueUrl":""},"verificationReminders":{"rate":1},"useHttps":false,"keyPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/key.pem","certPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/cert.pem","lockoutEnabled":true,"newLoginNotificationEnabled":true,"deviceUpdatesEnabled":true,"deviceNotificationsEnabled":true,"oauth":{"url":"http://localhost:9010","keepAlive":false,"extra":{"email":false}},"statsd":{"enabled":true,"host":"localhost","port":8125,"sample_rate":1},"metrics":{"flow_id_key":"YOU MUST CHANGE ME","flow_id_expiry":7200000},"corsOrigin":["*"],"clientAddressDepth":3,"signinConfirmation":{"enabled":true,"sample_rate":1,"supportedClients":["iframe","fx_firstrun_v1","fx_firstrun_v2","fx_desktop_v1","fx_desktop_v2","fx_desktop_v3","fx_ios_v1","fx_ios_v2","fx_fennec_v1"],"enabledEmailAddresses":{}},"securityHistory":{"enabled":true},"lastAccessTimeUpdates":{"enabled":false,"sampleRate":1,"enabledEmailAddresses":{}},"signinUnblock":{"codeLength":8,"codeLifetime":3600000,"enabled":true,"allowedEmailAddresses":".+@mozilla\\.com$","forcedEmailAddresses":"^$","sampleRate":1,"supportedClients":["web","oauth","iframe","fx_firstrun_v1","fx_firstrun_v2","fx_desktop_v1","fx_desktop_v2","fx_desktop_v3","fx_ios_v1","fx_ios_v2","fx_fennec_v1"]},"isProduction":false}
fxa-auth-server.ERROR: geodb.1 {"op":"geodb.1","err":"Unable to open file"}
fxa-auth-server.INFO: geodb.check {"op":"geodb.check","result":{}}
fxa-auth-server.INFO: geodb.start {"op":"geodb.start","enabled":true,"dbPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/fxa-geodb/db/cities-db.mmdb"}
fxa-auth-server.INFO: server.start.1 {"op":"server.start.1","msg":"running on http://127.0.0.1:9000"}
fxa-auth-server.WARN: metrics.context.validate {"op":"metrics.context.validate","valid":false,"reason":"missing context","agent":"curl/7.47.0"}
fxa-auth-server.INFO: account.create.emptyLocale {"op":"account.create.emptyLocale","email":"me@example.com","agent":"curl/7.47.0"}
fxa-auth-server.INFO: activityEvent {"event":"account.created","userAgent":"curl/7.47.0","uid":"51b01aeb46034a9ead99e7d2e57b3ed5"}
fxa-auth-server.ERROR: log.flowEvent {"op":"log.flowEvent","event":"account.created","missingFlowId":true}
fxa-auth-server.ERROR: request.summary {"op":"request.summary","code":500,"errno":999,"rid":"1476366190432:msk1wst010:15589:iu8eb314:10000","path":"/v1/account/create","agent":"curl/7.47.0","remoteAddressChain":["127.0.0.1"],"accountRecreated":true,"t":73,"uid":"00","keys":"true","email":"me@example.com","stack":"TypeError: signinConfirmation.enabledEmailAddresses.test is not a function\n    at Object.isSigninConfirmationEnabledForUser (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/lib/features.js:48:52)\n    at createSessionToken (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/lib/routes/account.js:221:22)\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)\n    at Async._drainQueue (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)\n    at tryOnImmediate (timers.js:534:15)\n    at processImmediate [as _immediateCallback] (timers.js:514:5)"}
^Cfxa-auth-server.INFO: shutdown {"op":"shutdown"}
```

This is old, working version log:

```
fxa-auth-server.ERROR: geodb.1 {"op":"geodb.1","err":"Unable to open file"}
fxa-auth-server.INFO: geodb.check {"op":"geodb.check","result":{}}
fxa-auth-server.INFO: geodb.start {"op":"geodb.start","enabled":true,"dbPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server-bak/fxa-auth-server/node_modules/fxa-geodb/db/cities-db.mmdb"}
fxa-auth-server.INFO: server.start.1 {"op":"server.start.1","msg":"running on http://127.0.0.1:9000"}
fxa-auth-server.DEBUG: server.onRequest
fxa-auth-server.DEBUG: Account.create
fxa-auth-server.WARN: metrics.context.validate {"op":"metrics.context.validate","valid":false,"reason":"missing context","agent":"curl/7.47.0"}
fxa-auth-server.DEBUG: customs.check {"op":"customs.check","email":"me@example.com","action":"accountCreate"}
fxa-auth-server.DEBUG: DB.emailRecord {"op":"DB.emailRecord","email":"me@example.com"}
fxa-auth-server.DEBUG: DB.deleteAccount {"op":"DB.deleteAccount","uid":{"type":"Buffer","data":[45,244,127,148,184,248,68,212,143,153,170,244,247,69,3,246]}}
fxa-auth-server.INFO: account.create.emptyLocale {"op":"account.create.emptyLocale","email":"me@example.com","agent":"curl/7.47.0"}
fxa-auth-server.DEBUG: DB.createAccount {"op":"DB.createAccount","uid":{"type":"Buffer","data":[23,55,189,253,41,72,71,134,187,169,120,201,137,84,131,191]},"email":"me@example.com"}
fxa-auth-server.INFO: activityEvent {"event":"account.created","userAgent":"curl/7.47.0","uid":"1737bdfd29484786bba978c9895483bf"}
fxa-auth-server.ERROR: log.flowEvent {"op":"log.flowEvent","event":"account.created","missingFlowId":true}
fxa-auth-server.DEBUG: DB.createSessionToken {"op":"DB.createSessionToken","uid":{"type":"Buffer","data":[23,55,189,253,41,72,71,134,187,169,120,201,137,84,131,191]}}
fxa-auth-server.INFO: userAgent:truncate {"op":"userAgent:truncate","userAgent":"curl/7.47.0"}
fxa-auth-server.DEBUG: SessionToken.create {"op":"SessionToken.create","uid":{"type":"Buffer","data":[23,55,189,253,41,72,71,134,187,169,120,201,137,84,131,191]}}
fxa-auth-server.DEBUG: mailer.verifyEmail {"op":"mailer.verifyEmail","email":"me@example.com","uid":"1737bdfd29484786bba978c9895483bf"}
fxa-auth-server.DEBUG: mailer.verifyEmail {"op":"mailer.verifyEmail","email":"me@example.com","uid":"1737bdfd29484786bba978c9895483bf"}
fxa-auth-server.INFO: mailer.send {"email":"me@example.com","op":"mailer.send","template":"verifyEmail"}
fxa-auth-server.DEBUG: DB.createKeyFetchToken {"op":"DB.createKeyFetchToken","uid":{"type":"Buffer","data":[23,55,189,253,41,72,71,134,187,169,120,201,137,84,131,191]}}
fxa-auth-server.DEBUG: KeyFetchToken.create {"op":"KeyFetchToken.create","uid":{"type":"Buffer","data":[23,55,189,253,41,72,71,134,187,169,120,201,137,84,131,191]}}
fxa-auth-server.DEBUG: keyFetchToken.bundleKeys {"op":"keyFetchToken.bundleKeys","id":"684ff87a14ae63de95b94a0cef327fa51b75f2743a8178a784a1889ce47129ca"}
fxa-auth-server.DEBUG: Token.bundle {"op":"Token.bundle"}
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
fxa-auth-server.INFO: request.summary {"op":"request.summary","code":200,"errno":0,"rid":"1476365950861:msk1wst010:14710:iu8e60vj:10000","path":"/v1/account/create","agent":"curl/7.47.0","remoteAddressChain":["127.0.0.1"],"accountRecreated":true,"t":133,"uid":"1737bdfd29484786bba978c9895483bf","keys":"true","email":"me@example.com"}
fxa-auth-server.INFO: mailer.send.1 {"op":"mailer.send.1","status":"250 2.0.0 Ok: queued as e77b1f455d2a24d0b00c","id":"3b4e117de564d0c9d089771997d23b@msk1wst010"}
fxa-auth-server.DEBUG: DB.createVerificationReminder {"op":"DB.createVerificationReminder","reminderData":{"uid":"1737bdfd29484786bba978c9895483bf","type":"first"}}
fxa-auth-server.DEBUG: DB.createVerificationReminder {"op":"DB.createVerificationReminder","reminderData":{"uid":"1737bdfd29484786bba978c9895483bf","type":"second"}}
 http://127.0.0.1:3030/v1/verify_email?uid=1737bdfd29484786bba978c9895483bf&code=e918d7d26d8de4c69c32f62b2cb3a43a&utm_source=email&utm_medium=email&utm_campaign=fx-welcome&utm_content=fx-activate 
^Cfxa-auth-server.INFO: shutdown {"op":"shutdown"}
```

At  first we found this as response to our client. When we tried to test it with your example:

`curl -v \
-X POST \
-H "Content-Type: application/json" \
"http://127.0.0.1:9000/v1/account/create?keys=true" \
-d '{
  "email": "me@example.com",
  "authPW": "996bc6b1aa63cd69856a2ec81cbf19d5c8a604713362df9ee15c2bf07128efab"
}'`

What is the problem?
I assume in this:

`"stack":"TypeError: signinConfirmation.enabledEmailAddresses.test is not a function\n    at Object.isSigninConfirmationEnabledForUser (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/lib/features.js:48:52)\n    at createSessionToken (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/lib/routes/account.js:221:22)\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)\n    at Async._drainQueue (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)\n    at tryOnImmediate (timers.js:534:15)\n    at processImmediate [as _immediateCallback] (timers.js:514:5)"}
`

P.S. I use 5.12.0 nodejs interpreter for both, new and old servers. Also, then I comment `lib/features.js:48-50` it returns 200.

**Comment by shane-tomlinson** [comment]
It looks like two problems:

> {"Timestamp":1476366184440000000,"Logger":"fxa-auth-db-server","Type":"bin.server.start","Severity":2,"Pid":15588,"EnvVersion":"2.0","Fields":{"message":"listen EADDRINUSE 127.0.0.1:8000"}}

From this, it looks like you have an auth-db-server already running when you the process was started. If you start this from fxa-local-dev, do a `pm2 kill` to stop all the fxa related processes and then restart.

> "stack":"TypeError: signinConfirmation.enabledEmailAddresses.test 

You are right, this is definitely a problem. In 020235fe40f315095b1b834c6d0d748dc303283d, we changed the format of [signinConfirmation.enabledEmailAddreses](https://github.com/mozilla/fxa-auth-server/blob/bbb1aa9f66b2ef3774a01a58c394f5adabef0542/config/index.js#L468:L473) from an array of regular expression strings to a regular expression. If you have an external json config file or use the environment to configure FxA, you'll have to update accordingly. Note that in external config from a JSON file or the environment, `.` in `.com` needs to be double escaped: `\\.com` or else the regular expression ends up being created with a single `.` which matches any single character.

**Comment by vityafx** [comment]
From what you have just said:

1. Is it a problem having `fxa-auth-db-server` running at the same time as `fxa-auth-server`? For the first, I use it to have data saved between `fxa-auth-server` start and stops (this would be impossible with in-memory database) and for the second, I have the same error without the db server.
2. Are not you saying that the problem is in my config file? I use the official config file (`/config/index.js`) and it contains exactly the same fields and type (RegExp)` as you say.

**Comment by philbooth** [comment]
@vityafx, when the auth server starts it dumps the config object to the console. Can you pastebin that so we can see what the value is for `enabledEmailAddresses` when it fails?

**Comment by vityafx** [comment]
Sure, here it is:

`fxa-auth-server.INFO: undefined {"env":"dev","geodb":{"dbPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/node_modules/fxa-geodb/db/cities-db.mmdb","enabled":true},"log":{"level":"info","fmt":"pretty"},"memcached":{"address":"127.0.0.1:11211","idle":30000,"lifetime":1800},"publicUrl":"http://127.0.0.1:9000","domain":"127.0.0.1:9000","secretKeyFile":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/config/secret-key.json","publicKeyFile":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/config/public-key.json","trustedJKUs":["http://127.0.0.1:8080/.well-known/public-keys","http://127.0.0.1:10139/.well-known/public-keys"],"vapidKeysFile":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/config/vapid-keys.json","db":{"backend":"httpdb"},"httpdb":{"url":"http://127.0.0.1:8000"},"listen":{"host":"127.0.0.1","port":9000},"customsUrl":"none","contentServer":{"url":"http://127.0.0.1:3030"},"smtp":{"api":{"host":"127.0.0.1","port":9001},"host":"127.0.0.1","port":9999,"secure":false,"sender":"Firefox Accounts <no-reply@lcip.org>","verificationUrl":"http://127.0.0.1:3030/v1/verify_email","verifyLoginUrl":"http://127.0.0.1:3030/complete_signin","passwordResetUrl":"http://127.0.0.1:3030/v1/complete_reset_password","initiatePasswordResetUrl":"http://127.0.0.1:3030/reset_password","syncUrl":"https://www.mozilla.org/firefox/sync/","androidUrl":"https://www.mozilla.org/firefox/android/","iosUrl":"https://www.mozilla.org/firefox/ios/","supportUrl":"https://support.mozilla.org/kb/im-having-problems-with-my-firefox-account","redirectDomain":"firefox.com","privacyUrl":"https://www.mozilla.org/privacy","passwordManagerInfoUrl":"https://support.mozilla.org/kb/password-manager-remember-delete-change-and-import#w_viewing-and-deleting-passwords","initiatePasswordChangeUrl":"http://127.0.0.1:3030/settings/change_password","reportSignInUrl":"http://127.0.0.1:3030/report_signin"},"maxEventLoopDelay":0,"scrypt":{"maxPending":0},"i18n":{"defaultLanguage":"en","supportedLanguages":["ar","az","bg","cs","cy","da","de","dsb","en","en-GB","es","es-AR","es-CL","et","fa","ff","fi","fr","fy","he","hi-IN","hsb","hu","it","ja","kk","ko","lt","nl","pa","pl","pt","pt-BR","pt-PT","ro","rm","ru","sk","sl","sq","sr","sr-LATN","sv","sv-SE","tr","uk","zh-CN","zh-TW"]},"tokenLifetimes":{"accountResetToken":900000,"passwordForgotToken":3600000,"passwordChangeToken":900000},"verifierVersion":0,"snsTopicArn":"disabled","bounces":{"region":"","bounceQueueUrl":"","complaintQueueUrl":""},"verificationReminders":{"rate":1},"useHttps":false,"keyPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/key.pem","certPath":"/home/OMP/v.polevoy/work/cloud/fxa-auth-server/cert.pem","lockoutEnabled":true,"newLoginNotificationEnabled":true,"deviceUpdatesEnabled":true,"deviceNotificationsEnabled":true,"oauth":{"url":"http://localhost:9010","keepAlive":false,"extra":{"email":false}},"statsd":{"enabled":true,"host":"localhost","port":8125,"sample_rate":1},"metrics":{"flow_id_key":"YOU MUST CHANGE ME","flow_id_expiry":7200000},"corsOrigin":["*"],"clientAddressDepth":3,"signinConfirmation":{"enabled":true,"sample_rate":1,"supportedClients":["iframe","fx_firstrun_v1","fx_firstrun_v2","fx_desktop_v1","fx_desktop_v2","fx_desktop_v3","fx_ios_v1","fx_ios_v2","fx_fennec_v1"],"enabledEmailAddresses":{}},"securityHistory":{"enabled":true},"lastAccessTimeUpdates":{"enabled":false,"sampleRate":1,"enabledEmailAddresses":{}},"signinUnblock":{"codeLength":8,"codeLifetime":3600000,"enabled":true,"allowedEmailAddresses":".+@mozilla\\.com$","forcedEmailAddresses":"^$","sampleRate":1,"supportedClients":["web","oauth","iframe","fx_firstrun_v1","fx_firstrun_v2","fx_desktop_v1","fx_desktop_v2","fx_desktop_v3","fx_ios_v1","fx_ios_v2","fx_fennec_v1"]},"isProduction":false}
`

**Comment by philbooth** [comment]
Hmm, that is different to what I see with the same tag checked out:

`"signinConfirmation":{"enabled":true,"sample_rate":1,"supportedClients":["iframe","fx_firstrun_v1","fx_firstrun_v2","fx_desktop_v1","fx_desktop_v2","fx_desktop_v3","fx_ios_v1","fx_ios_v2","fx_fennec_v1"],"enabledEmailAddresses":"/.+@mozilla\\.com$/"},"securityHistory":{"enabled":true},"lastAccessTimeUpdates":{"enabled":false,"sampleRate":1,"enabledEmailAddresses":"/.+@mozilla\\.com$/"}`

Is it possible that you're over-riding some of the default config settings, either with a separate JSON file or with environment variables?

**Comment by philbooth** [comment]
Oh wait! Have you done an `npm install`? It needs the latest version of `convict` in order to work.

**Comment by vityafx** [comment]
Nope! And I have done that just now and everything works now it seems. Thank you very much. Let us check other 2 pcs please and I'll close this issue by myself.

**Comment by vityafx** [comment]
It works. Thanks.
