### ISSUE TITLE
Eliminate bluebird promises?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1509]
I wrote a new source module earlier today and absent-mindedly used native promises rather than bluebird. Everything worked fine of course but then I suddenly realised it could potentially cause problems in the future if the usage changed and somebody expected the bluebird API to be available where it wasn't.

So, given that it seems sensible not to mix our promise implementations and I'm not aware of us leaning on the broader bluebird API, I thought I'd ask the question: do we, at some point, want to swap out bluebird for native promises?

**Comment by seanmonstar** [comment]
Maybe bluebird is better than native Promises. It may have improved in
newer V8 (or might not), but node 4 is not new V8. See
http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird

**Comment by rfk** [comment]
On a personal level, I feel like I'd probably miss helpers like `.finally()`, `.each()`, `.spread()` and others.  Do these have native equivalents?  Mucking around in the node shell did not reveal them to me.

**Comment by philbooth** [comment]
Good points both, seems like the answer to the question is pretty firmly "no".

**Comment by shane-tomlinson** [comment]
> .spread()

For a counter-point, native promises have `.all`, and with array destructuring, `spread` is no longer needed... 

```js
return Promise.all([ promise1, promise2, promise3 ])
  .then(([ result1, result2, result3 ]) => {
     // do something clever with the results.
  });
```
