### ISSUE TITLE
Emit flow events for confirmation/verification emails

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1511]
I propose:

* `email.confirmation.sent`, emitted when the sign-in confirmation email is sent.
* `email.confirmation.clicked`, emitted when `/recovery_email/verify_code` is hit for sign-in confirmation.
* `email.verification.sent`, emitted when the sign-up verification email is sent.
* `email.verification.clicked`, emitted when `/recovery_email/verify_code` is hit for sign-up verification.

But also feel free to come up with better names and use them instead.

**Comment by seanmonstar** [comment]
As I was adding these, I found that `account.confirm` was emitted for **signup verification**. Should I just leave that state out since we already record an event, or was there desire for another event besides `account.confirm`.

**Comment by philbooth** [comment]
> As I was adding these, I found that `account.confirm` was emitted for **signup verification**. Should I just leave that state out since we already record an event, or was there desire for another event besides `account.confirm`.

Not 100% certain I understand the question accurately without knowing I'm looking at the bit of code you mean. Let's chat on IRC later.

**Comment by seanmonstar** [comment]
I'm also adding `email.verification.resent` and `email.confirmation.resent` to the `resend_code` route.

For the `clicked` events, I was wondering if this is supposed to be at the very top of the route (`/recovery_email/verify_code`), or when there was success. There already appears to be metrics events on success: both [`account.confirmed`](https://github.com/mozilla/fxa-auth-server/blob/2f03ce5f37dab0cdf3ecad407ab2462ef16da16e/lib/routes/account.js#L1514) and [`account.verified`](https://github.com/mozilla/fxa-auth-server/blob/2f03ce5f37dab0cdf3ecad407ab2462ef16da16e/lib/routes/account.js#L1557).

**Comment by philbooth** [comment]
Yep, the clicked events were supposed to be fore immediate entry to the route, before anything back-endy has a chance to fail. So it would have to be just a single event I guess, since we don't know which type of token it is yet.

**Comment by seanmonstar** [comment]
Oh ok, so before `db.account` and `customs.check`. Indeed, then we don't know what kind of email it actually was. `email.verify_code.clicked`?

 Alternatively, it could be just after the `db.account` (and/or after `customs.check`), and then we would know what kind it is, before checking if the code was valid.

**Comment by philbooth** [comment]
I think the earlier the better. Essentially it is the user action of clicking the link that we want to capture here, before anything on the back-end can fail and thus distort the numbers.
