### ISSUE TITLE
Can we bump up the metricsContext data expiry time in memcached?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1513]
Currently the `metricsContext` data survives in memcached for 30 minutes. This means that we can only use the sign-in funnel to analyse flows that complete within half an hour of the user submitting the form. Other flows will show up as incomplete.

Instinctively this feels a little bit on the tight side to me. Would it be okay to increase it up to an hour or two instead?

/cc @jrgm @jbuck @rfk

**Comment by jbuck** [comment]
This seems entirely reasonable to me

**Comment by rfk** [comment]
👍
