### ISSUE TITLE
Order by error number in lib/error.js

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1518]
Today, for some reason, I have a low tolerance for stuff that annoys me. And the ordering of the `ERRNO` constant in `lib/error.js` really grinds my gears.

Currently it's alphabetical, which makes the following two operations more painful than they should be:

1. I see an error number in the logs and I want to look it up. If these were ordered numerically, my eye would fall naturally to the position of interest. But now I have to scan wildly or, even worse, *do extra typing on my keyboard* to search for the error number I'm interested in.

2. I want to add a new error and don't know what the current greatest error number is. If these were ordered numerically, et cetera and so on.

The alternative operation, of looking up an error by its name, seems less common to me.

Feel free to close this if you think I'm wrong / need to get a grip.

**Comment by shane-tomlinson** [comment]
> I want to add a new error and don't know what the current greatest error number is. If these were ordered numerically, et cetera and so on.

This reason is why we sort by number in the content server.

**Comment by vladikoff** [comment]
> I want to add a new error and don't know what the current greatest error number is. 

Yeah happens to me too. It's like a fun mini-game! 🎮

**Comment by rfk** [comment]
Let's do it, esp. if we already have prior art for this ordering in the content-server.
