### ISSUE TITLE
request.emitMetricsEvent is a leaky abstraction

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1523]
It takes an optional second argument, which is only used in the activity event path of execution. Efficiently setting (or not) that argument requires the caller to know implementation details of the callee.

**Comment by seanmonstar** [comment]
In `log.summary` we already have some code to search the request in many places for the `uid`, perhaps we could use the same code and do so automatically if it's an activityEvent.

**Comment by philbooth** [comment]
Changed my mind, I do want this in `next` actually.

**Comment by philbooth** [comment]
I started to have a crack at this but it unravelled quickly. Too many different properties being set and too many different data sources for those properties.

I'm going to close the issue, back away and pretend it never happened. Anyone else is welcome to re-open it if they have an approach in mind.

**Comment by philbooth** [comment]
Fwiw, this leakiness is not a problem any more, because both event types include `uid` and so both of the event methods receive the optional data.
