### ISSUE TITLE
Error 137 during installation

### ISSUE THREAD

**Issue by nagromc** [mozilla/fxa-auth-server#1538]
`npm install` exits with a code 137.

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie
$ node --version
v4.6.1
$ npm --version
3.10.8
$ # from here, just following the instructions in the README.md file
$ git clone git://github.com/mozilla/fxa-auth-server.git
$ git checkout v1.73.1
$ cd fxa-auth-server
$ npm install
'npm install' terminated by signal SIGKILL (Forcé à quitter)
$ echo $?
137
```

Same results with the latest NodeJS 6.9.1 LTS.

**Comment by vladikoff** [comment]
@nagromc try with npm 2, not 3.

**Comment by nagromc** [comment]
Thanks @vladikoff. The tiny `/tmp` partition seemed to be too small to run `npm install` (with `npm --version` 2.15.11), but I could finally run the server.

Wouldn't it be a good idea to make the [required `npm` version](https://github.com/mozilla/fxa-auth-server/blob/165df8e9d1f34981260fb0f167c9f52f076e342a/README.md#prerequisites) clear?
