### ISSUE TITLE
Run auth server PRs against a subset of content server functional tests

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1544]
Sometimes changes in this repo break the content server, which is very frustrating and annoying for whoever ends up debugging them to find out what is wrong (usually @shane-tomlinson).

It would be better if the burden of sorting out these problems was shifted on to the person making the breaking change in this repo. We could make a move towards that by running auth server PRs against a subset of the functional tests in the content server. Then any bustage would be immediately visible and fixes could be planned in advance, rather than rush-fixed after the event as they are currently.

**Comment by vladikoff** [comment]
we need to decide if we want to use another cloud box or install some of the servers...

**Comment by philbooth** [comment]
We should also include the js-client tests in this.

**Comment by vladikoff** [comment]
closing, make sure to check the circle notifications....
