### ISSUE TITLE
Confusing synthesized device name for Firefox on iOS

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1556]
From https://github.com/mozilla/fxa-content-server/issues/4412#issuecomment-261009838, the device name for Firefox for iOS v6 device record appears as:

  "Firefox iOS 6, iOS 10.1"

This is confusing because it has two different version numbers in it.  We should simplify it to something like "Firefox on iOS 10.1".

IIUC this device name is being synthesized by the auth-server, so it's within our power to fix.  I also recall a similar bug in fxa-auth-mailer, from which we may be able to steal some code.

**Comment by philbooth** [comment]
> ...fxa-auth-mailer, from which we may be able to steal some code.

I was poking around in there just now. For the record, [here is the code in `mailer.js`](https://github.com/mozilla/fxa-auth-mailer/blob/013f136add20c01dea9b137b7a4fe0773f567ebe/mailer.js#L137-L148):

```js
var translator = this.translator(message.acceptLanguage)
var uaBrowser = message.uaBrowser
var uaOS = message.uaOS
var uaOSVersion = message.uaOSVersion

if (uaBrowser && uaOS && uaOSVersion) {
  return translator.format(translator.gettext('%(uaBrowser)s on %(uaOS)s %(uaOSVersion)s'),
                           { uaBrowser: uaBrowser, uaOS: uaOS, uaOSVersion: uaOSVersion })
} else if (uaBrowser && uaOS) {
  return translator.format(translator.gettext('%(uaBrowser)s on %(uaOS)s'),
                           { uaBrowser: uaBrowser, uaOS: uaOS })
}
```

...where `this.translator` points `translator.js` in the same directory.

**Comment by vladikoff** [comment]
One of the blockers of this is the fact that we would need to add L10N translation support in fxa-auth-server (for the `translator.gettext('%(uaBrowser)s on %(uaOS)s'`) string. Not sure if it is worth doing that for just one string. 

Also, latest version of Firefox iOS has device registration so it will have the proper name. Please reopen if still needed...
