### ISSUE TITLE
Android phone showing up as a tablet in devices view

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1557]
Only just got round to checking my devices list in prod, after reading through the comments in mozilla/fxa-content-server#4412 and #1555. For some reason my Android 6 phone, running Firefox 49.0.2, shows up as a tablet device.

<img width="486" alt="Screenshot showing @philbooth's list of connected devices" src="https://cloud.githubusercontent.com/assets/64367/20381940/a61b392e-aca1-11e6-80e7-0fec6de94189.png" />

(I'm also not sure whether that `Android` device name is one I've set or is the result of our user-agent parsing)

Maybe we can we refine the logic in [`lib/userAgent::isTablet`](https://github.com/mozilla/fxa-auth-server/commit/e09406a45247829ff6aec73a2d461306a160bc00#diff-989657afb0a0dbbc2b7eb07a75f6eb39R79) to get this right?

```js
function isTablet(data) {
  // 'tablets' are iPads and Android devices with no word 'Mobile' in them.
  // Ref: https://webmasters.googleblog.com/2011/03/mo-better-to-also-detect-mobile-user.html
  if (getFamily(data.device)) {
    if (data.device.family === 'iPad' ||
       (data.os && data.os.family === 'Android' && data.userAgent.indexOf('Mobile') === -1)
    ) {
      return true
    }
  }

  return false
}
```

I can look into this at the same time as #1555, if nobody else is already on the case with that.

**Comment by philbooth** [comment]
Weirdly, when I connect to a local instance using the same user agent string as the browser on my phone, it parses correctly and gives me the right device type:

<img width="490" alt="Screenshot showing a correctly identified Android mobile device" src="https://cloud.githubusercontent.com/assets/64367/20391923/7ea0d31e-accd-11e6-9924-29b6578d3cc0.png" />

I also notice it has a different device name in prod than the browser on my phone thinks it has. Device name on the phone is `Firefox on LG-H525n`, device name on the server is just that plain old `Android`.

To make sure this wasn't some intermittent weirdness, I disconnected my device and refreshed the view. Yep, that device was deleted as expected. Then I reconnected my device and refreshed the view again. And once more, it shows up with the device name `Android` and as a tablet rather than a phone.

Might there be some weirdness in the client going on here?

**Comment by vladikoff** [comment]
>  And once more, it shows up with the device name Android and as a tablet rather than a phone.
Might there be some weirdness in the client going on here?

It takes a bit of time for device registration to kick in I find, so the initial device you see is "Android" and then it becomes the proper Firefox Mobile after like 1 minute (in my experience)

**Comment by philbooth** [comment]
> It takes a bit of time for device registration to kick in I find, so the initial device you see is "Android" and then it becomes the proper Firefox Mobile...

Interesting. So I refreshed the view again just now, an hour later, but it still showed `Android` as the device name with the tablet icon.

But then I clicked `Synchronise now` in mobile Firefox again (I'd done this before too btw, and it was showing `Last synchronised: 1 hour ago`), refreshed the view again and Hey Presto! The device name and icon are fixed.

So not an ideal user experience, but maybe there's nothing we can do about it? Closing this.

**Comment by philbooth** [comment]
As pointed out by @vladikoff [here](https://github.com/mozilla/fxa-auth-server/pull/1558#discussion_r88477764), this is caused by the default user agent string [here](https://dxr.mozilla.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko/fxa/FxAccountConstants.java?q=Firefox-Android-FxA&redirect_type=single#40).

I'm working on a PR that will handle the device name part of this, but I don't think the tablet icon part is resolvable.
