### ISSUE TITLE
Log more diagnostic info about email complaint notifications

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1561]
In `lib/bounces.js` we log a lot of diagnostic info about email *bounces*, but that's not the only thing that code can be called for.  IIUC it can also be called if there is a complaint about one of our emails, per:

  https://aws.amazon.com/blogs/ses/handling-bounces-and-complaints/

We should log diagnostic info about the complaint in the same way we do for bounces.

**Comment by shane-tomlinson** [comment]
@rfk - I put this in the backlog, feel free to re-triage as you see appropriate.
