### ISSUE TITLE
Blacklist bounced emails

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1565]
Approximately 6.25% of emails sent bounce.

If we send emails multiple times to the same bounced email address, our sender score will be penalized.

Let's make sure we don't send messages more than once to a bounced email.

**Comment by rfk** [comment]
I think this is a great opportunity to do part of the mooted data model refactor from https://github.com/mozilla/fxa-auth-server/issues/973, and create a separate table just for emails and what we know about them.

Strawman schema, expanding on one of the tables from that bug:

```
+-----------------+---------------------+------+-----+---------+-------+
| Field           | Type                | Null | Key | Default | Extra |
+-----------------+---------------------+------+-----+---------+-------+
| normalizedEmail | varchar(255)        | NO   | PRI | NULL    |       |
| email           | varchar(255)        | NO   |     | NULL    |       |
| uid             | binary(16)          | NO   |     | NULL    |       |
| addedAt         | bigint unsigned     | NO   |     | NULL    |       |
| emailCode       | binary(16)          | NO   |     | NULL    |       |
| emailState      | tinyint unsigned    | NO   |     | 0       |       |
| bounceCount     | tinyint unsigned    | NO   |     | 0       |       |
| complaintCount  | tinyint unsigned    | NO   |     | 0       |       |
| blockedAt       | bigint unsigned     | NO   |     | 0       |       |
+-----------------+---------------------+------+-----+---------+-------+
```

The first five columns are straight for the `accounts` table, but storing them here will help prepare us for a world with multiple email addresses on a single account.  We would also have an index on this table mapping uids to email addresses, for reverse lookup.

The `emailState` field can be an enum with states like "unverified", "verified", "soft bounced", "hard bounced", and maybe one for "You marked us a spam? How could you?? Well I didn't want to send you any more emails anyway so there!! 😢".

There's columns for tracking the number of bounces and complaints received at a certain address, and if these exceed a threshold, then we can set a timestamp in the `blockedAt` column to prevent us from sending any more email to that address.

@davismtl does this seem like it would give us what we need to control bounces etc here?

**Comment by davismtl** [comment]
This seems to make sense to me.

It gives us the opportunity to block someone after 2-3 soft bounces, after 1 hard bounce or after 1 spam complaint.

**Comment by rfk** [comment]
Should we maintain 3 separate counters for soft-bounce, hard-bounce, and complaint?

**Comment by davismtl** [comment]
I think so if it allows us to do the following better:

- Soft bounces should have like a 7 day period where we don't resend.
- Hard bounces or "reported as spam" should never be emailed again.

As per the last point, if we no longer send emails to an address, it begs the question, can the user even log into his account now?

**Comment by seanmonstar** [comment]
- Soft bounces mean things like a) mail box was full, b) mail server error, etc. Email delivery sites suggest a back off strategy, but not necessarily waiting 7 days. I'd imagine something 1 day, 3 days, 7 days.
- Hard bounces mean the address does not exist. This is where all the fun is. We shouldn't keep trying to send a message to a hard bounced email, we'll look like spam.
    - Just because an email address doesn't exist when we email it, doesn't mean it cannot exist in the future. This would be especially true for bigger public email providers, like Gmail, Yahoo, Outlook. So we shouldn't keep it in a blocklist forever.
    - If the email never existed, then the account was never verified, so it has never been syncing. We could probably just delete it.
    - If the email did exist at signup, but now it doesn't, then the user most likely does not have a way to sign back in (with us). In fact, their account is in a position to be taken over by someone who does create that email address again. They cannot take their synced data unless they can also guess their password, but they can reset the account.

**Comment by rfk** [comment]
> If the email never existed, then the account was never verified,
> so it has never been syncing. We could probably just delete it.

This part, we do already, and the account suddenly disappearing is the only way that client code can currently detect that an account creation attempt got bounced.  We could keep the account around in a "that email hard bounced" state in order to provide better error messages and recovery options to the user.

**Comment by davismtl** [comment]
> Just because an email address doesn't exist when we email it, doesn't mean it cannot exist in the future. This would be especially true for bigger public email providers, like Gmail, Yahoo, Outlook. So we shouldn't keep it in a blocklist forever.

Good point. How should we approach that? How long should we block it? Any thoughts?

**Comment by rfk** [comment]
Sounds like we need a State Diagram showing what happens in each state, and how you transition between them.

**Comment by vladikoff** [comment]
@rfk backlogging, please update priority if needed....

**Comment by davismtl** [comment]
This can remain in backlog for now however we should look into prioritizing soon since improper management of bounced emails is likely impacting our sender score and may be part of the cause of why FxA is being flagged as spam in Outlook/hotmail.

As a result, it hurts our sign-up and sign-in rates.

**Comment by rfk** [comment]
@davismtl yes, let's have a conversation in Hawaii about turning "improve email deliverability" into a concrete milestone.

**Comment by rfk** [comment]
I'm moving this up to "next" and will chat with some folks about prioritizing this work.

**Comment by rfk** [comment]
For context, the types of bounces reported by SES: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#bounce-types

**Comment by davismtl** [comment]
@rfk So awesome! Glad we will be able to capture the types of bounces from SES.

Will we instrument some metrics around this? For example, it would be great to see:
1) how many bounces do we get at sign-in vs sign-up. (there is a big difference between the two)
2) What are the most common types of bounces that we see? 
3) How often does an email hard bounces that previously didn't do so before?

**Comment by rfk** [comment]
@vbudhram's graph here is a great start to answer these sorts of questions:

  https://sql.telemetry.mozilla.org/queries/2323/source#4293

@vbudhram if you get a chance, if may be worth editing the graph to add more readable labels on the data series; for example it's not obvious to me what the difference between "count_recovery_email_bounced" and "count_password_reset_email_bounced" is without digging into the auth-mailer code.

**Comment by vbudhram** [comment]
@rfk Updated graph labels and published queries 👍

**Comment by vladikoff** [comment]
some PRs in the works...

**Comment by seanmonstar** [comment]
I think technically #1684 fixes this, or at least the title of the issue, "blacklist bounced emails". There's some other work related to the feature, but those issues are filed and assigned the appropriate milestone.

**Comment by vladikoff** [comment]
^ See above, closing, shipping train-83
