### ISSUE TITLE
Should we include experiment data in the activity events?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1567]
Related to mozilla/fxa-content-server#4290.

For the proposed "connect a second device" feature, there is a requirement to analyse how the active experiment affects the percentage of users that connect a second device.

One way of approaching this would be to propagate flow ids from the original sign-in through that second device flow, then lean on the planned inclusion of experiment data in the flow events from the linked issue.

That approach troubles me a little bit because it makes the flow events more complex. Each flow has a very limited scope at the moment, which provides easy answers to questions like what to do when the user refreshes (we generate a fresh flow id). Expanding the scope of a flow beyond that introduces exciting new ways for us to break the flow data, such as session storage and increased view data propagation.

Instead, if we were to add experiment information to the activity events, it could give us the insight we need because those events contain user and device ids. It wouldn't enable detailed funnel analysis to pinpoint exactly where users drop off during the process, but it would allow us to view the overall success rates for each branch of an experiment. Would that be enough for our purposes?

The main downside to doing this might be the hassle of updating the tables in redshift. We have a lot of activity event data stored, going back to the start of 2016, and the tables aren't small.

@shane-tomlinson @rfk @davismtl, what do you think? Am I inventing imaginary problems?

**Comment by rfk** [comment]
I don't think I have my head around exactly what this proposal would look like in practice - do you have a strawman data model in mind?

Is the specific question we want to answer: "what % of users who got the new multi-device flow succeeded in connecting a second device, relative to the users in the control group?"?

One option may be to associate successful flows with a uid, so we can do things like "find all the users who logged in on day X through a flow with Y experiment" or "find all the users who signed up through experiment Z".

(We'd have to gut-check the level of tracking-creepiness enabled by making such additional correlations possible, but I don't think it would be too bad).

**Comment by philbooth** [comment]
> ...do you have a strawman data model in mind?

Nope, I didn't think it through any further than what I wrote, sorry. But no matter, because...

> One option may be to associate successful flows with a uid...

In the conversation with @shane-tomlinson that preceeded this issue, I told him we definitely weren't allowed to do this. I may have misremembered some early conversations about flow events to that end. But if it's an option, I agree that adding the uid (or a hash thereof) to `flow_metadata` would be an easy fix.

Closing this.

**Comment by rfk** [comment]
> I told him we definitely weren't allowed to do this. I may have
> misremembered some early conversations about flow events to that end

No, I think you're right, this was explicitly part of the original design of these flow events.  If we want to change that, we should put together a proposal and run it past the data stewards for completeness.

**Comment by rfk** [comment]
Which is to say: we designed it that way because it didn't seem like we needed that flowid<->uid correlation, and we don't collect data we don't need.  If we do in fact need it, we should seek permission to collect it.

**Comment by rfk** [comment]
Actually it occurs to me that this correlation is probably already possible.  If I have a flow containing an `account.login` event at time T, and there's an `account.login` activity-event that also has time T, then I can make a pretty good guess about what user that flow belongs to...

**Comment by philbooth** [comment]
> Actually it occurs to me that this correlation is probably already possible.  If I have a flow containing an `account.login` event at time T, and there's an `account.login` activity-event that also has time T, then I can make a pretty good guess about what user that flow belongs to...

That is a very good point!

**Comment by davismtl** [comment]
If I am to summarize here, we do not have uid in our flow events so we can't match a login on a second device to a signup flow?

If it means anything, the Sync team is implementing a type of flow ID to event telemetry where the uid will also be passed. The goal is to understand a user starting and completing an experience across devices. Seems very similar that what we are doing here. This went through validation with stewards.

**Comment by rfk** [comment]
@davismtl do you have a link to the bug for the sync on handy?  It does indeed sound very similar.

**Comment by davismtl** [comment]
Here it is:
https://bugzilla.mozilla.org/show_bug.cgi?id=1289536
