### ISSUE TITLE
Rate limiting is really aggressive if you use the wrong email case

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1570]
If you login with different capitalization of your email address than the one you used when signing up, every login attempt actually counts as two - one for a failing login attempt that returns the correct email capitalization, and another when we transparently retry using your canonical email address.  This can cause our rate-limiting to kick in *really* quickly.

I'm not sure what to do about this yet, but wanted to get it on file.  See also https://github.com/mozilla/fxa-auth-server/issues/1562#issuecomment-263178068

**Comment by rfk** [comment]
This is even worse if you're trying to change your password.  STR:

* Login with a weird capitalization of your email address, such "eXamPle@gMAIL.com"
* Try to change your password

Result:

![screen shot 2016-11-28 at 20 01 35](https://cloud.githubusercontent.com/assets/34695/20662106/1bf84e0e-b5a6-11e6-837c-9dec54ee4a8c.png)

Despite entering the correct password first try, this process involves *three* failed login attempts - one for the initial login with incorrect capitalization, one when the change-password form checks your old password with incorrect capitalization, and one when we call `/password/change/start` with incorrect capitalization.  You hit the rate limit before you even get to trying password `/password/change/start` with the right credentials.

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-auth-server/issues/1573

**Comment by vladikoff** [comment]
from mtg: even if we change config we still want to fix this in auth / customs server...

**Comment by rfk** [comment]
One simple approach might be, to not count "incorrect email case" errors as a failed login attempt.  They don't let you learn any information about the user's password.  We'd have to give it some thought, but it seems OK to me at first glance from a security POV.
