### ISSUE TITLE
Cannot send unblock code if using the wrong email case

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1573]
/account/login/send_unblock_code responds with http response 503, error number 202, "feature not enabled"

STR

1. Using local dev, sign up for Sync using `block123@restmail.net`
2. Verify email address from 1. 
3. Sign out of Sync.
4. Sign in to Sync using `BLOCK123@restmail.net`
5. Go back a screen and try `block123@restmail.net`, everything works as expected.

#### Response to /account/login using `BLOCK123@restmail.net`
![screen shot 2016-11-28 at 13 49 05](https://cloud.githubusercontent.com/assets/848085/20670643/b1683cd6-b571-11e6-9c09-8e3e73e9cae6.png)

#### Response to /account/login/send_unblock_code using `BLOCK123@restmail.net`
![screen shot 2016-11-28 at 13 47 09](https://cloud.githubusercontent.com/assets/848085/20670579/61d289f6-b571-11e6-9341-0a01fdf72fe6.png)

Ref #1570

**Comment by shane-tomlinson** [comment]
Here's the error to the `/account/login/send_unblock_code` reported to the auth-server console:

> auth-server key server PORT 9000-2 fxa-auth-server.ERROR: request.summary {"op":"request.summary","code":503,"errno":202,"rid":"1480340720900:Shanes-Retina-MBP.local:12634:iw1xsvny:13695","path":"/v1/account/login/send_unblock_code","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0","remoteAddressChain":["127.0.0.1"],"t":2,"uid":"00","email":"BLOCK123@restmail.net","stack":"Error: Service unavailable\n    at Function.AppError.featureNotEnabled (/Users/stomlinson/development/fxa-auth-server/lib/error.js:407:10)\n    at createUnblockCode (/Users/stomlinson/development/fxa-auth-server/lib/routes/account.js:1752:25)\n    at bound (domain.js:287:14)\n    at runBound (domain.js:300:12)\n    at tryCatcher (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise._settlePromiseFromHandler (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/promise.js:507:31)\n    at Promise._settlePromiseAt (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/promise.js:581:18)\n    at Async._drainQueue (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:128:12)\n    at Async._drainQueues (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/Users/stomlinson/development/fxa-auth-server/node_modules/bluebird/js/main/async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"}

**Comment by shane-tomlinson** [comment]
Similar to what @rfk suggests in another bug, this could be worked around in the short term by having the content server use the normalized email returned in the call to `/account/login` to send the unblock code. Opening an issue on the content server to do that.

**Comment by rfk** [comment]
The send_unblock_code route calls `features.isSigninUnblockEnabledForUser(uid, email, request)` using the `email` submitted in the request, rather than the normalized version of the email looked up from the database.  Possible this is causing the regex-based unblock forcing to miss it?

**Comment by shane-tomlinson** [comment]
https://github.com/mozilla/fxa-content-server/pull/4472 ensures the content server uses the normalized email when requesting an unblock code, so we've worked around this. Not sure what the best approach is for the auth-server.
