### ISSUE TITLE
/account/create does not return normalized email if account already exists

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1583]
STR:

1. Sign up for an account, verify.
2. Open the browser's network console.
3. Go to the content server's /signup page, signup again with the email from step 1, using different casing.
4. The response to /account/create returns an `email` field, but it's the email that was entered instead of the normalized email.

Returning the normalized email would allow the first call to `/account/login` to use the correct email instead of the unnormalized version.

![screen shot 2016-12-01 at 19 12 53](https://cloud.githubusercontent.com/assets/848085/20808487/b20b5386-b7fa-11e6-8093-e06dc39b7fa6.png)

**Comment by rfk** [comment]
This should be trivial, taking a look now...
