### ISSUE TITLE
Will signin-unblock get accidentally disabled in train 75?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1586]
While giving a final once-over to my changes in #1585, I suddenly realised something alarming: [`isSigninUnblockEnabledForUser` includes a check against the value of `metricsContext.context`](https://github.com/mozilla/fxa-auth-server/blob/ed9ec795657b1d6d66e1f5d58e659113d3ec6134/lib/features.js#L50-L59), but the content server stops sending that data in train 75 (see mozilla/fxa-content-server#4456 and mozilla/fxa-js-client#224).

The check short-circuits subsequent checks of the sample rate so, IIUC, as thing stand **the train-75 content server will disable sign-in unblock even if `sampleRate === 1` in the auth server**.

Not sure whether this means we should drop that check, thus enabling sign-in unblock for all clients, or reinste all the `metricsContext` crap that we just got rid of. Obviously, that second option is the messier one and I'd prefer the first option if possible. Either way, somewhere we're going to need another point release for train 75 (unless I've misunderstood something).

/cc @mozilla/fxa-devs, what do you guys think we should do?

**Comment by rfk** [comment]
I don't see a problem with removing the context check from auth-server; I can prep a quick PR and ask @seanmonstar for r?
