### ISSUE TITLE
Unable to receive confirmation email

### ISSUE THREAD

**Issue by nE0sIghT** [mozilla/fxa-auth-server#1601]
My account is ykonotopov at gnome dot org and I'm unable to receive confirmation email from https://accounts.firefox.com/
There is no proper component for a.f.c. at bugzilla.mozilla.org so I'm creating issue here.

**Comment by vladikoff** [comment]
@nE0sIghT Hey! did it work out?

**Comment by nE0sIghT** [comment]
@vladikoff 

I finally get 2 emails (about a half of hour ago) after requested ~10 resends.
I'm unsure what was a cause for this

**Comment by vladikoff** [comment]
@nE0sIghT Okay, thanks for letting us know. I guess the email got stuck somewhere, but not clear where. We will try to investigate...

cc @jbuck @jrgm
