### ISSUE TITLE
Customize email / signin confirmation screen for Outlook users

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1607]
When users register or sign in with an Outlook account, we should probably tell them to check their Spam box as a temporary work around to increase registration and login success rates.

**Comment by shane-tomlinson** [comment]
@davismtl - can you triage this as you see fit?

**Comment by davismtl** [comment]
@shane-tomlinson  I've put it in Next since it should be a pretty quick temporary fix with high impact until we improve Outlook deliverability.

**Comment by davismtl** [comment]
@ryanfeeley can you do a quick mockup around this?
I will see if I can make a quick feature doc but I think this doesn't need to be A/b tested since it's a pretty simple no brainer.

**Comment by ryanfeeley** [comment]
On this page? https://mozilla.invisionapp.com/share/MH8OJXZAR#/190520154_07_Confirm

**Comment by davismtl** [comment]
On 
- that page (sign-in confirmation)
- email confirmation screen (after registration)
- the sign-in unblock page (when we send the code)

Essentially, every time we send an email, we should tell Outlook/Hotmail/Live/MSN users to check spam if they didn't get their email.

**Comment by ryanfeeley** [comment]
@davismtl Password reset too?

**Comment by ryanfeeley** [comment]
@davismtl Did our marketing email efforts get us marked as spam too much?

**Comment by davismtl** [comment]
Password reset too. Good catch!

@ryanfeeley Marketing has their own mail servers. For various reasons described here, Outlook is giving us a hard time. We also are not properly respecting every best practice which they seem more sensitive too: mozilla/fxa/issues/209

**Comment by ryanfeeley** [comment]
Something like this? It feels dirty even mentioning spam.
![outlook-spam](https://cloud.githubusercontent.com/assets/68213/21726910/c4855aa6-d40c-11e6-8fed-b40577765d7a.png)

**Comment by davismtl** [comment]
How about we keep it more similar to the current but indicate:

Didn't arrive? Check your **spam folder** or **[resend](url)**

**Comment by ryanfeeley** [comment]
@davismtl I like that better.

Is this an improvement?

* Didn't arrive? Not in spam folder? Resend

**Comment by ryanfeeley** [comment]
or shortened (maybe too short)

* Not arriving, nor in spam folder? Resend

**Comment by davismtl** [comment]
I like the screenshot. If we want to avoid putting 2 questions, it could be but I'm indifferent for now:

Didn't arrive and not in spam folder? Resend

**Comment by ryanfeeley** [comment]
@davismtl Ship it!
<img width="550" alt="screenshot 2017-01-06 15 43 57" src="https://cloud.githubusercontent.com/assets/68213/21732317/f405ead8-d426-11e6-92d5-af2c95941fb0.png">

**Comment by ryanfeeley** [comment]
@davismtl (we could just replace the old string in all instances)

**Comment by rfk** [comment]
@ryanfeeley do you like the old version better enough that we should only display this for outlook users, or should we just show it for everyone?  "Remember to check your spam folder" is pretty good advice all-round, but I agree it feels weird to have to mention it in practice.

**Comment by vladikoff** [comment]
From mtg: yes let's do it for all providers

**Comment by shane-tomlinson** [comment]
@ryanfeeley and @davismtl agree - let's present the updated text to all users, not just Outlook.
