### ISSUE TITLE
Refresh Charts from Dashboard Daily

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1608]
These are the charts that I use the most often:
https://sql.telemetry.mozilla.org/dashboard/fxa-overview?p_days=30

It would like to have the latest data in the charts when I open the dashboard daily (at worst,  perhaps every 48 for some of them).

Some charts can take hours to refresh so I can't quickly get an update on performances.

In order to get a refresh every 24h, we may need to improve the performance of some of the queries.

- A possible suggestion for some quick wins in many cases could be to default most of the charts to last 30 days but add field to specify more or less days. {{p_days}}

- Some other charts might need a more optimized query if the date range isn't enough. 

- And in the most extreme cases, we might need to think about the data format but I am hoping we don't need to go there.

**Comment by philbooth** [comment]
Hey @davismtl, I have some work in progress that may fix these issues but we also need to chat about whether it is a good approach first. I was trying to finish some other stuff off before talking about it but seeing as you've opened this issue, now seems like a good time.

Essentially the mooted approach is to have three different sets of activity event data.

The first set would use the existing table names, but would only contain data for the last three months. That would allow existing queries to continue working and see an automatic improvement in performance. But of course, the charts would only go back three months.

The second set of tables would go back six months and be sampled to 50% of the data. The table names would be the same but with a `_sampled_50` suffix (or something).

The third set would go back two years and be sampled to 10% of the data. The table names would have a `_sampled_10` suffix.

The import scripts would take care of automatically expiring old data and so on, so all query authors need to do is reference the appropriate set of tables in their query. It could also be that we want the 10 percent / 2 year sample to be the default view, if that's the case we just change the names round but the principle is the same.

Does that make sense? What do you think about the approach?

**Comment by rfk** [comment]
> In my experience, it can be nice to compare YoY some periods to verify things like seasonality.

FWIW in my experience, seasonal effects show up really well in even a 10% sample at the event volume we're talking about here.

> https://sql.telemetry.mozilla.org/queries/1597#2842

I own this one, I'll try adding the `{{days}}` picker and see what difference it makes.  Also reminds me how nice it would be to have shared editing permission on these graphs :-)

**Comment by rfk** [comment]
I also think that for our most important metrics, it's probably worth maintaining an ongoing rollup table where we can query that metric directly, e.g. https://github.com/mozilla/fxa-activity-metrics/issues/41

But that's a fair amount of work, so we'll look for lower-hanging performance fruit first.

**Comment by rfk** [comment]
Limited to 30 days, this still took an hour to run:

  https://sql.telemetry.mozilla.org/queries/1597/source?p_days=30

**Comment by davismtl** [comment]
> Limited to 30 days, this still took an hour to run:
> https://sql.telemetry.mozilla.org/queries/1597/source?p_days=30

That's still long but it was previously >3h so that's a big win to me. 66% faster!

**Comment by philbooth** [comment]
I've updated query 1312, copying @rfk's approach on 1597. Execution time 1 hour.

Looking down your list, I think that is the only query I'm the author of, so I'm removing my face from this issue. @davismtl, I'll leave it to you to close this out if and when it's appropriate to do so.

> > Limited to 30 days, this still took an hour to run:
> > https://sql.telemetry.mozilla.org/queries/1597/source?p_days=30
>
> That's still long but it was previously >3h so that's a big win to me. 66% faster!

Fwiw, I'd be wary of reading too much into a single timing. I've seen 1-hour queries take 4 hours depending on what else is running concurrently. Avoiding collisions is really the key until we have smaller datasets, imho.

**Comment by davismtl** [comment]
Thanks @philbooth 

It def makes a diff if there are collisions but so far, things seems to run smoothly.

Do we know if the scheduling has gotten any better? We were experiencing scheduling problems last I heard (something about always firing or not firing).

**Comment by philbooth** [comment]
> Do we know if the scheduling has gotten any better?

Not sure. I turned off the auto-refresh on all my queries, because of those annoying issues with duplicate queries running and not being able to cancel them. I plan to enable them again when we have a solution to the wider performance problem.

**Comment by rfk** [comment]
IIUC the scheduling is a bit better now that we're using specific times of day to refresh each query, rather than selecting "every day" and letting redash figure it out?

**Comment by philbooth** [comment]
> IIUC the scheduling is a bit better now that we're using specific times of day to refresh each query, rather than selecting "every day" and letting redash figure it out?

It depends in what sense you mean "better". The issues with respawning duplicate queries aren't fixed in any meaningful sense, but they're less likely to happen as long as we stay on top of what time everything is scheduled for. I figured that the most helpful thing I could do in that sense would be to disable my queries entirely.

**Comment by vladikoff** [comment]
from mtg: some queries need to run over night. 

@philbooth to add more details...

**Comment by philbooth** [comment]
My take is that we need to agree on a synchronisation medium, so that we can avoid collisions. I was thinking a spreadsheet would do, something like:

https://docs.google.com/a/mozilla.com/spreadsheets/d/1gk_2-GhOifp85Win4X2PMfbmtnZ2i527R92I3noei5w/edit?usp=sharing

**Comment by davismtl** [comment]
I put the numbers of the queries I care the most about. I put the owners and I put how frequently we should schedule them. (weekly vs daily)

I did not however propose an hour to run them at. I'll let you guys pick

**Comment by rfk** [comment]
I've updated the spreadsheet with guesstimates of the running time for each query.  From there, I suppose we just fill in some times and hope for the best :-)

Unfortunately it doesn't look like re:dash will let us specific "weekly at X specific time", it's either "at X specific time each day" or one of the "hourly/daily/weekly" options.

**Comment by rfk** [comment]
I've updated my queries based on the times proposed in the above spreadsheet; @philbooth and @davismtl some of them belong to you, so please do the same when you get a chance, and we'll see how well this system works in practice...

**Comment by vladikoff** [comment]
from mtg: need to switch on the dashboards.

**Comment by philbooth** [comment]
Finally got round to updating my query, sorry for the hold-up. Removing my face from this.

**Comment by rfk** [comment]
IIUC this is done, so closing it out.  Please file a fresh bug if there are still freshness issues.
