### ISSUE TITLE
Write local tests for lib/server.js

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1610]
See background discussion at https://github.com/mozilla/fxa-auth-server/pull/1606#issuecomment-270205779.

The initial motivation for this was to be able to test that the route summary flow events are being emitted correctly, in addition to the unit tests that exist for `lib/metrics/events.js` and `lib/log.js`. But if we're doing that, we should also test a bunch of other stuff in there while we're at it.

We really want these tests to be as end-to-endy as possible I think, so we should be looking to plug in an actual route handler and then make sure that any pre/post handler events all behave correctly and so on.

**Comment by vladikoff** [comment]
We now have a file for those local tests here: https://github.com/mozilla/fxa-auth-server/blob/master/test/local/lib/server.js 

I guess to resolve this issue we need to add more tests @philbooth ?

**Comment by philbooth** [comment]
> ...to resolve this issue we need to add more tests...

Yep, I think we do.
