### ISSUE TITLE
Sign in on iOS not loading iFrame

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1638]
This bug needs to be verified but I'm logging it before I forget.

I recently disconnect a bunch of duplicate devices from my device list. Apparently I didn't always disconnect the right duplicate so Firefox Beta on iOS required me to login again to Sync.

When I click to login to Sync, the page looks like it's loading but it never displays the login form. It end with a red error message saying: "could not load page".

**Comment by davismtl** [comment]
![img_2213](https://cloud.githubusercontent.com/assets/19537086/22624805/5e662d7c-eb3b-11e6-8f94-b59ed7c4651b.PNG)
![img_2214](https://cloud.githubusercontent.com/assets/19537086/22624804/5e635264-eb3b-11e6-8cee-8648d0c1f7ae.PNG)

**Comment by shane-tomlinson** [comment]
@davismtl - have you seen this again?

**Comment by davismtl** [comment]
I'm testing it again but it will take some time because disconnect flow takes time.

Using beta, I have signed in. Then disconnected. I'm waiting for the disconnect to happen.

**Comment by davismtl** [comment]
Here is a related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1342376

**Comment by davismtl** [comment]
I have tried to replicate it but I am unable to. Although, as you can see from the bugzilla link, other people are also experiencing it.

**Comment by vladikoff** [comment]
>other people are also experiencing it. 

I think on Bugzilla they said that that they turned off internet / data on the phone. (so the page will not load)

**Comment by shane-tomlinson** [comment]
Has anybody else experienced this? If not, I'm tempted to close it down as non-actionable. The referenced bugzilla bug mentions turning data/network off completely, and suggests a retry button be shown.

**Comment by davismtl** [comment]
I have not re-experienced this. I do login tests every other week in Sync fest but have not encountered it.
