### ISSUE TITLE
Handle SMS delivery receipts

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1649]
I left this out of the initial implementation but its something we can add later to provide finer-grained flow events to track SMS delivery.

Currently we emit success if the message was successfully sent to the network provider. In future we can defer that to when the message is actually delivered to the user's phone (or keep `sms.sent` where it is and send an `sms.delivered` later), by registering a delivery receipt webhook.

More info on how to do this in the Nexmo docs:

https://docs.nexmo.com/messaging/sms-api/api-reference#delivery_receipt

**Comment by vladikoff** [comment]
Closing for now!
