### ISSUE TITLE
large request latencies on /account/devices/notify

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1657]
Here's a snapshot of recent requests to `/account/devices/notify`, from kibana [1]:

![screen shot 2017-02-15 at 13 14 50](https://cloud.githubusercontent.com/assets/34695/22958105/f6459216-f380-11e6-906d-897c363faabf.png)

There's something really odd about the request times (fourth column) here:

* most complete within a few hundred milliseconds
* a significant minority take just over 5 seconds to complete
* a few of them take just over 10 seconds to complete

Multi-second request latencies are pretty bad, we should try to figure out what's going on here.  In particular, we need to figure out if it's happening inside fxa-auth-server, or upstream in the push service.  The fact that they seem to be clustered around multiples of five may or may not be a clue.

/cc @bbangert @eoger

[1] https://kibana-fxa-us-west-2.prod.mozaws.net/index.html#dashboard/temp/AVo_j-ifTlXM2FwOP6vG

**Comment by rfk** [comment]
(For context, this endpoint receives a message from a connected device in the request body, and relays it to other connected devices via webpush).

**Comment by vladikoff** [comment]
@rfk I think we can tweak this logic to just reply() success early, we catch the errors anyway 

```js

        return customs.checkAuthenticated(endpointAction, ip, stringUid)
          .then(function () {
            if (body.to === 'all') {
              return push.pushToAllDevices(uid, endpointAction, pushOptions)
                .catch(catchPushError)
            } else {
              return push.pushToDevices(uid, body.to, endpointAction, pushOptions)
                .catch(catchPushError)
            }
          })
          .done(
            function () {
              reply({})
            },
            reply
          )
      }
    },
```

**Comment by vladikoff** [comment]
bonus points ⚡️  if someone can do the math before / after and confirm that the change there actually helps

**Comment by eoger** [comment]
Returning early and let the server do its thing in the background sounds like a good idea 👍

**Comment by rfk** [comment]
The one thing with returning early, is it makes it harder on the tests.  But in general it does seem like a good idea :-)
