### ISSUE TITLE
Missing flow.complete event for this flow?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1659]
@vbudhram shared this with me, from re:dash

![screen shot 2017-02-16 at 07 34 17](https://cloud.githubusercontent.com/assets/34695/22994249/5da28d26-f41a-11e6-8ace-6c2def134b19.png)

ISTM that this flow has all the prerequisites for having completed - the device registerd, it fetched keys, it signed a certificate.  But it doesn't have a flow.complete event.

@philbooth any idea what might have gone on here?

**Comment by philbooth** [comment]
> any idea what might have gone on here?

Not from eyeballing the code. I'll dig into it some more tomorrow though.

**Comment by rfk** [comment]
I suppose it could be as simple as the data getting evicted from memcache

**Comment by philbooth** [comment]
> I suppose it could be as simple as the data getting evicted from memcache

I'm pretty sure that's not it. The `flow.complete` event doesn't require going back to memcached, it just re-uses the same metrics context it already had from the preceding event.

If you check the timestamps, those events all occur within two minutes of each other. And looking at the code,

**Comment by rfk** [comment]
I think the moment has passed, let's just close this out
