### ISSUE TITLE
Let's auto-generate the API docs

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1662]
Maintaining `docs/api.md` is laborious and annoying. Worse, most of the time we forget, so it's perpetually out of date. Throw a dart at that document and, wherever it hits, something will be wrong.

It seems like at least 90% of the information contained therein could be auto-generated if we parse the code. Specifically, the Joi schemata and calls to `reply` and the `AppError` instantiation methods account for most of the details regarding what endpoints accept and what they return.

What becomes trickier with this approach is documenting the meaning of individual parameter names or the broader intention of each endpoint. We could possibly tackle those by having interpolated sections of the document for human description. Initially empty but once filled, they retain their content through successive regenerations.

The regeneration script could be run automatically as part of the release process and it would be like living in the future, with self-documenting code and hover-boards and flying cars! 🚀

Is this an unrealistic pipe-dream or something we should pursue?

**Comment by vbudhram** [comment]
> Is this an unrealistic pipe-dream

I don't think so? Would be nice to not worry about it, or at least have the documentation part be closer to the code. Is there anything out there that kind of does what you are talking about? 

At first glance Hapi uses [lout](https://github.com/hapijs/lout) plugin for documentation and it allows full customization of output. Maybe we could test that out?

**Comment by vladikoff** [comment]
and the other option is yuidoc or similar https://mozilla.github.io/fxa-js-client/classes/FxAccountClient.html

**Comment by philbooth** [comment]
> At first glance Hapi uses lout plugin for documentation and it allows full customization of output.

Looks like that runs as a server or can you also tell it to write markdown (or whatever) to disk?

What I had in mind was just a little script that runs acorn or esprima against the contents of `lib/routes`, then traverses the ASTs dumping stuff in markdown format as it goes. Maybe I've oversimplified it in my head, but I plan to try something along those lines out for Experiment Day tomorrow.

**Comment by philbooth** [comment]
> and the other option is yuidoc or similar

Docs generated from comments are an improvement over standalone docs, I agree, but people still forget to update comments. In my imaginary nirvana, nobody has to remember to update anything, ever!

**Comment by seanmonstar** [comment]
I wanted to do this using lout in the oauth server (ref https://github.com/mozilla/fxa-oauth-server/issues/153), but back then it couldn't generate to files, and we didn't want to run the extra routes in production.

If it's improved to be able to output as static files, that seems like the simplest thing. It will serialize all the accepted parameters for a route, and I believe we can add some sort of `description` field or similar that will show in the docs.

**Comment by rfk** [comment]
> nobody has to remember to update anything, ever

This is an excellent ideal to strive for :-)

I don't think I've ever seen auto-generated documentation that I'd give higher praise than "barely acceptable", so colour me a little dubious about this in practice...but I'd be very happy to be proven wrong!  And it would certainly beat docs that are outright *wrong* as you mention above.

So yeah, a cautious +1
