### ISSUE TITLE
skipForNewAccounts not active in production?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1671]
We noticed this in the syncfest the other day.  STR:

* Create a new account
* Sign in to sync from a different IP address (to avoid ip-based skipping of sign-in confirmation)

Expected results:

* I can sign in to sync without doing an email confirmation loop, because it's a newly-created account

Actual results:

* I am prompted to confirm my signin before I can start syncing.

I looks like `skipForNewAccounts.enabled` is set to true in puppet-config, so I'm not entirely sure why this doesn't trigger.  /cc @jrgm @vbudhram

**Comment by vbudhram** [comment]
I tested this locally with security history and ip profiling disabled to avoid the ip based skipping of sign-in confirmation.

Local auth-server log shows that `account.signin.confirm.bypass.age` was triggered.
```
{"Timestamp":1487812204438000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":36607,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"errno":0,"rid":"1487812204434:vbudhram-23693:36607:izhoyzow:10004","path":"/v1/recovery_email/status","remoteAddressChain":"[\"127.0.0.1\"]","t":4,"uid":"0d80c83b57a747a19babe0ac92481ec6"}}
{"Timestamp":1487812204442000000,"Logger":"fxa-auth-server","Type":"metrics.context.validate","Severity":4,"Pid":36607,"EnvVersion":"2.0","Fields":{"op":"metrics.context.validate","valid":false,"reason":"missing context"}}
{"Timestamp":1487812204444000000,"Logger":"fxa-auth-server","Type":"account.signin.confirm.bypass.age","Severity":6,"Pid"
```

However, Kibana [dashboard](https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/FxA%20Sign-in%20Confirmation) we don't have any records of that event. Plot thickens..

**Comment by vbudhram** [comment]
Mystery solved!

The code that perform the `skipForNewAccounts` gets passed an [email record](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L658) and then proceeds to check for the `createdAt` value on that object. However, `createdAt` is only passed back in the [mem](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/mem.js#L526) db but not the [mysql](https://github.com/mozilla/fxa-auth-db-mysql/blob/22e27d16d635927d2facfe8382030ec10447e600/lib/db/schema/patch-013-014.sql#L5) db. When date check occurs we have `if(NaN <= skipForNewAccounts.maxAge)` which fails.

Couple solutions could be to set `verifierSetAt` or update the db procedure to return `createdAt`.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-auth-server/commit/dc2562c697b81d830c838da6e6f33a6aeb580811  Release v1.81.1
