### ISSUE TITLE
Add API support for adding a recovery email

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1672]
This bug outlines some of the authentication server engineering tasks needed for a user to be able to add an additional email to their account.

* /recovery_emails
  * GET
    * Params: none
    * Response: ```[{isPrimary: true, verified: true, email: `primary@email.com`}, {isPrimary: false, verified: false, email: `anotherone@email.com`}]```
* /recovery_email
  * POST
    * Params: `{email: `anotherone@email.com`}`
    * Response: `{}`
    * Errrors: `Email already verified on another account`, `Email bounced.`, `Email already added to account.`
* /recovery_email/destroy
  * POST
    * Response: `{}`
    * Params: ```{email: `anotherone@email.com`}```
    * Error: `Email not found.`, `Can not delete primary email.`

Ref: https://docs.google.com/document/d/1DOUWRbxU8ah6AL3gUTrlYKFY42jt_czOHbu4wL4E-sc/edit#

- [x] Add support for endpoint
- [x] Add test cases
- [x] Add documentation
- [x] Update shrinkwrap for new db

**Comment by rfk** [comment]
Thanks @vbudhram, can you please also tie these bugs together with the appropriate milestone for easy tracking?

**Comment by vladikoff** [comment]
> the appropriate milestone

@rfk meant to talk you about this, with the new script, do we still add the milestone in /fxa first or how does that work?

**Comment by rfk** [comment]
Steps now are:

* Ensure the feature card is in "defined" or later
* Run the sync_milestones script

If the card's not ready to be in "defined" because we're still figuring out the details, maybe we can change the script to create milestones for things in "defining" as well.

**Comment by vbudhram** [comment]
@rfk Moved to defining and synced milestones 👍

**Comment by vladikoff** [comment]
API added
