### ISSUE TITLE
auth-server->auth-mailer depends on l10n module that is extraneous and would be remove by prune

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1678]
Happened to notice this. Not sure what exactly to do about it. But thought I should document.

If you do a clean install of auth-server, and do `npm ls`, it reports:
`npm ERR! extraneous: fxa-content-server-l10n@0.0.0`.

If you then do `npm prune`, tests fail, since `node_modules/fxa-auth-mailer/translator.js` wants to load `node_modules/fxa-auth-mailer/node_modules/fxa-content-server-l10n` files. I'm not really sure why npm thinks this is extraneous, since there is not other fxa-content-server-l10n under node_modules that I can see.

**Comment by jrgm** [comment]
Ah right. `postinstall` does an npm install of l10n under auth-mailer. So it is extraneous per top-level npm view. 

Okay, so don't prune this install **ever**. Or maybe a git clone to a data subdirectory might be better since this l10n module is never `require`d.

**Comment by philbooth** [comment]
What if we just promoted it to a first class dep instead of `postinstall`?

**Comment by vladikoff** [comment]
It was like that before, but we want it to be a 'live' dep, so it always updates from latest SHA anot tje shrinkwrap file

**Comment by rfk** [comment]
Is there a way we can list it in package.json while still allowing postinstall to pull in the latest version?

**Comment by vladikoff** [comment]
after it pulls latest `npm ls` will throw

**Comment by philbooth** [comment]
:+1: to using `git clone`.

**Comment by vladikoff** [comment]
cc @seanmonstar , related to shrinkwrap updates
