### ISSUE TITLE
Unify the `log` implementations

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1680]
The auth mailer code was pulled into this repo with a newer implementation of the `log` object and a legacy adapater that allows auth server code to pass in its own log implementation. Instead, we should use the same log object everywhere, presumably updating all the auth server code to use the newer log object.

**Comment by vladikoff** [comment]
Closing for now until we need this

**Comment by philbooth** [comment]
Actually I'm minded to re-open this now as I believe it to be the reason we need [this ugly logic](https://github.com/mozilla/fxa-amplitude-send/blob/460b977f8bfe582e7c26620b49d03b4be8f482ea/amplitude.py#L71-L82) in `fxa-amplitude-send`:

```python
if "Fields" in event:
    # Auth server events are wrapped inside a `Fields` property.
    event = event["Fields"]
    if "op" in event and "data" in event:
        # Mailer events have an extra layer of indirection.
        event = json.loads(event["data"])
    else:
        # Non-mailer events have stringified `event_properties` and `user_properties`.
        if "event_properties" in event:
            event["event_properties"] = json.loads(event["event_properties"])
        if "user_properties" in event:
            event["user_properties"] = json.loads(event["user_properties"])
```

We could at least get rid of the inner condition if all auth server logs were in proper mozlog format. And depending on how much faff it involves in our log-processing infrastructure, we might even be able to eliminate this block entirely and have the logs passed to us cleanly without all this wrapping gunf, as is the case for the content server.

Still not sure if we'll get round to it, but opening again for a little while at least.

**Comment by philbooth** [comment]
I don't think we're getting to this, closing.
