### ISSUE TITLE
Investigate if we can use postfix to detect bad MX records

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1686]
Check the error and see if it is a domain error...

**Comment by vladikoff** [comment]
MX or A record, postfix will know 🆗

**Comment by philbooth** [comment]
postfix will do it, @jrgm needs to investigate how errors are handled

**Comment by jrgm** [comment]
So, quick notes: 
- set `smtpd_recipient_restrictions = reject_unknown_recipient_domain, reject_non_fqdn_recipient, permit_mynetworks, reject_unauth_destination`
- using a non-registered domain name to sign up:
  - postfix will respond with `450 4.1.2 <email@nonexistent.org> : Recipient address rejected: Domain not found., and auth-server logs this.
  - however, /create will return 200 despite the postfix reject.

**Comment by jrgm** [comment]
Note: don't use nonexistent.org. It, of course, exists.

**Comment by vladikoff** [comment]
from mtg: we are not using postfix anymore.
