### ISSUE TITLE
Emit locale and domain for bounce/delivery events

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1689]
In support of https://github.com/mozilla/fxa/tree/master/features/FxA-56-email-deliverability, we need to log email domain associated with the email event and the email locale.

Per irc with phil
```
vbudhram: 1. include it in the extra data explicitly here: https://github.com/mozilla/fxa-auth-server/blob/master/lib/metrics/events.js#L144-L147
8:26 AM vbudhram: 2. over in puppet-config, open a pr to read the new field, like this one: https://github.com/mozilla-services/puppet-config/pull/2488/files
8:26 AM vbudhram: 3. last step, over in fxa-activity-metrics, open a pr to update the import scripts, like this one: https://github.com/mozilla/fxa-activity-metrics/pull/55/files
```

From follow up IRC conversation,  decided to emit `email.${templateName}.${type}.${domain}` email events and do the filtering SQL side.

**Comment by philbooth** [comment]
@vbudhram, I didn't understand the full context of this when you asked in IRC, sorry. Seeing this though, a better option might be to emit some kind of dedicated `email.domain.${domain}` event.

Changing the even structure should be reserved for more generic properties that apply to all (or most) event types, I reckon.

**Comment by vbudhram** [comment]
From follow up IRC conversation,  decided to emit `email.${templateName}.${type}.${domain}` email events and do the filtering SQL side.
