### ISSUE TITLE
Push notifications are innacurate after sign-in

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1691]
I signed into my iOS browser and was displayed the screen to confirm my email.

On desktop, I was notified that a new device was syncing.

This is not actually accurate since I have yet to confirm my email.

Recommendation:
- Send a notification across devices to confirm the login on the new device.
- Once login confirmed, then send a push to say that new device has been added to Sync.

**Comment by rfk** [comment]
I think @eoger landed a fix for this recently, but it may not be deployed yet.  It delays the push message about a new device until after the device is confirmed.

**Comment by davismtl** [comment]
Oh great, that fixes half this bug.
Is it realistic to add a "Go confirm your login" notification?

**Comment by rfk** [comment]
>  Is it realistic to add a "Go confirm your login" notification?

I think it's realistic but we should run it past @ryanfeeley; how similar would it be to the experience in https://github.com/mozilla/fxa-features/issues/65?

**Comment by vladikoff** [comment]
from mtg: close enough to the other feature we are developing where we send the url to verify
