### ISSUE TITLE
Dashboard breakdown for Email Deliverability

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1694]
Not sure best place to put this, but will put it here for tracking. This issue will help us track all the dashboards that will be built out for https://github.com/mozilla/fxa-auth-server/milestone/49

Dashboard breakdown:

#### Completion Rate for Email Flows
- [x] Email Sent = Email Delivered + Email Bounced
- [x] Email Delivered = (email.{template}.delivered)
- [x] Email Bounced = (email.{template}.bounced)
- [x] Link Clicked / Flow completed
- [ ] Sign-in Flow Complete = Sign-in confirm/VerifySyncLogin
- [x] Sign-up Flow Complete = Sign-up confirm/VerifyAccount

#### Lost Mail Rate for Email Flows
- [ ] Sign-in Flow

#### Bounce and complaint rate by template
- [x] Add support for complaint flow
- [x] Add support for logging domain

#### Bounce and complaint rate by template
- [x] Have pieces of this already

#### Bounce, complaint, and click rate by domain
- [x] Will have pieces of this

#### Bounce, complaint, and click rate by language
- [x] Will have pices of this

#### User blocked send rate
- [ ] Hard Bounce
- [ ] Complained
- [ ] Soft Bounce

**Comment by seanmonstar** [comment]
I started working on these today, I've got 3 so far: https://sql.telemetry.mozilla.org/dashboard/fxa-email-deliverability

**Comment by vladikoff** [comment]
from mtg: cc @seanmonstar , setting P1, last issue to close out the milestone

**Comment by seanmonstar** [comment]
https://sql.telemetry.mozilla.org/dashboard/fxa-email-deliverability
