### ISSUE TITLE
Cross-repo testing is broken

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1704]
The cross-repo testing was broken by #1692.

The js client tests work correctly but the setup for the content server tests fails to start the content server itself. This is only visible when running in the `fxa-test` org (or anywhere that `$CIRCLE_PROJECT_USERNAME` is set to `fxa-test`).

For some reason, the same `nohup` command that works for the other servers, doesn't work for the content server. When you SSH into the box there is no content server running and the logfile for that process is empty. Probably I'm doing something stupid.

Anyway, would be good to fix this if we can.

**Comment by vladikoff** [comment]
this is still usefull, let's keep it open for now, but backlog it

**Comment by philbooth** [comment]
Nominating this for triage later.

**Comment by vladikoff** [comment]
from mtg: 🗡  killing for now
