### ISSUE TITLE
Optimize the docker image

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1705]
Current image seems to be ~700MB. It'd be grand if we could shrink that.

Compared to the other micro services we have, the auth server required a few extra dependencies, specifically to build `scrypt-hash`.

- Python is only need to run the `gyp` building of the module, afterwards we could uninstall it.
- Are any of the other extra packages able to be uninstalled after building also?

**Comment by jbuck** [comment]
Perhaps we can look at building/installing pre-built binaries of scrypt-hash like some other projects with binary modules

**Comment by seanmonstar** [comment]
It was a while ago when we added the scrypt-hash dependency (a few years). It's possible there is a better package now? Though, to remove the native module build step, the package would probably need to be pure JS, and I don't imagine that'd be fast enough...

**Comment by vladikoff** [comment]
This is better now 👍
