### ISSUE TITLE
Add config to specify Nexmo sender id

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-auth-server#1720]
Right now we have a [config file](https://github.com/mozilla/fxa-auth-server/blob/master/config/sms-sender-ids.json) committed to the source tree that specifies what phone number to send as for a given country. 

Right now for stage & prod which use a different account, we'll need to overwrite this file. Could we add some sort of configuration option to specify the sender id directly?

Maybe something like: `SMS_SENDERS={"CA":"16475551212","US":"15035553434"}` ?

**Comment by philbooth** [comment]
Yep, definitely! I should have done it that way originally in hindsight.
