### ISSUE TITLE
[docker] skip postinstall of fxa-geodb 50M database

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1724]
RUN FXA_GEOIP_SKIP_MAXMIND_DOWNLOAD=1 npm install ...

But it will need to be downloaded before running tests, I believe. Maybe in a npm `pretest` script.

**Comment by jrgm** [comment]
> Maybe in a `npm pretest` script.

So the downloader script in geodb will download everytime, which will make for slow local testing if on a home connection. (Or, bleh, `[ -s filepath ] && ./node_modules/fxa-geodb/scripts/start-db-download.js ]`).

**Comment by vladikoff** [comment]
Do we need some precautions to make sure the file is there when we are in prod?

**Comment by vladikoff** [comment]
Please reopen if still an obstacle
