### ISSUE TITLE
senders/index.js could use a refactor

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1725]
It does some mangling of the email sender, which is just an instance of `Mailer`. This used to be needed sine we didn't have the `Mailer` class in-tree, but now that it is, perhaps those methods can just exist on the class directly.

Additionally, the bounce gating logic could move into a `bounces.js` module or similar.

**Comment by vbudhram** [comment]
> Additionally, the bounce gating logic could move into a bounces.js module or similar.

Looks like this was done in https://github.com/mozilla/fxa-auth-server/pull/1776

Some other refactoring

* Update to support ES5
* Alot of common code in sending function, reduce boiler plate, ref: https://github.com/mozilla/fxa-auth-server/pull/1888/files#r115416282

**Comment by vladikoff** [comment]
some work done in https://github.com/mozilla/fxa-auth-server/commit/a37589c1e8f8d3d4c5377ec6a02f3069a19cd5e5 and  https://github.com/mozilla/fxa-auth-server/commit/a37589c1e8f8d3d4c5377ec6a02f3069a19cd5e5
