### ISSUE TITLE
incorrect test in test/local/lib/senders/email.js

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1726]
Not really understanding this line:
https://github.com/mozilla/fxa-auth-server/blob/master/test/local/lib/senders/email.js#L142

```
assert.equal(templateName, 'verificationReminderFirstEmail' || 'verificationReminderSecondEmail')
```
which really means
```
 assert.equal(templateName, 'verificationReminderFirstEmail')
```
So what was it trying to do?

**Comment by philbooth** [comment]
I'm guessing it's just a brain fart that intended to be equivalent to:

```
assert.ok(templateName === 'verificationReminderFirstEmail' || templateName === 'verificationReminderSecondEmail')
```

But presumably that intention was wrong, if it's never failed?

**Comment by vladikoff** [comment]
added in https://github.com/mozilla/fxa-auth-server/commit/17ca63af7dd69f43b7832343eccd5bea7329a5ef 

We should switch to Phil's version
