### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by Happyfeet01** [mozilla/fxa-auth-server#1736]
Hello,

i have no chance to install the Auth-server. npm has problems with it.

my system:

ubuntu 16.04 LTS Rootserver

`fxa-auth-server.ERROR: geodb.1 {"op":"geodb.1","err":"Unable to open file"}
fxa-auth-server.INFO: geodb.check {"op":"geodb.check","result":{}}

root@domain.tld:/opt/fxa-auth-server# npm install
npm WARN lifecycle fxa-auth-server@1.81.0~postinstall: cannot run in wd %s %s (wd=%s) fxa-auth-server@1.81.0 scripts/download_l10n.sh /opt/fxa-auth-server

npm WARN optional Skipping failed optional dependency /grunt-nunjucks-2-html/nunjucks/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1`

thanks

Lars

**Comment by vladikoff** [comment]
` cannot run in wd %s ` probably means you are running as root. do not do that
