### ISSUE TITLE
Change sms.region config to be an Array

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-auth-server#1740]
Right now [sms.region](https://github.com/mozilla/fxa-auth-server/blob/master/config/index.js#L649) config is a a RegExp:

```
    regions: {
      doc: 'Valid ISO 3166-1 alpha-2 country codes for enabled regions',
      default: /^(?:US|CA)$/,
      format: RegExp,
      env: 'SMS_REGIONS'
    },
```

Could we change this to be a plain Array?

```
    regions: {
      doc: 'Valid ISO 3166-1 alpha-2 country codes for enabled regions',
      default: ['CA', US'],
      format: Array,
      env: 'SMS_REGIONS'
    },
```

@philbooth thoughts?

**Comment by philbooth** [comment]
Yep, we can do this no probs. Out of curiosity (and for future reference), why is an array preferable?

**Comment by jbuck** [comment]
I think the most important consideration (for me) when choosing between an Array or a RegExp comes down to how it's being compared. If the data and the comparison only require you to test for equality, then I'd try to use an Array. If whatever I'm testing can't use equality then I'd use a RegExp.

In this case, the RexExp is trying to match one of two exact strings, which we can represent in an Array and test using indexOf() without losing any specificity.

For something like the forced signin confirmation email addresses you couldn't use something like a list of strings & testing for equality because that wouldn't let you express your intent well enough.
