### ISSUE TITLE
Attempt to shrink docker image size by using yarn 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1741]
Let's try to introduce yarn just for the docker image for now, hopefully using a lockfile gives us features of shrinkwrap and we can use `--production` to only install prod deps. (something that npm cannot do)

**Comment by seanmonstar** [comment]
We can also stop shrinkwrapping dev-dependencies... but the reason we do still has some merit: if we accidentally depend on something in dev-dependencies, there isn't a really good way to detecting that, since running the test suite requires we download the dev-deps anyways...

**Comment by vladikoff** [comment]
the 1.7 gb are due to caching issues on Circle. Merging with https://github.com/mozilla/fxa-auth-server/issues/1746
