### ISSUE TITLE
docker: Circle CI builds are failing or have a huge cache size

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1746]
```
  675 passing (3m)
  1 failing

  1) remote account reset account reset w/o sessionToken:
     An internal server error occurred
```

It seems like there are permission or caching issues. If built with no cache then it is fine

**Comment by vladikoff** [comment]
>  If built with no cache then it is fine

Did this for `master` and got a passing  build

**Comment by shane-tomlinson** [comment]
@philbooth thinks we should remove the caching, it was only used for fxa-test, which is not being run at the moment.

**Comment by vladikoff** [comment]
should be fixed via https://github.com/mozilla/fxa-auth-server/pull/1723
