### ISSUE TITLE
NODE_ENV=dev node test/mail_helper.js doesn't start anymore

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1762]
@seanmonstar the mail_helper broke fxa-local-dev:

```
NODE_ENV=dev node test/mail_helper.js
```

this doesn't work anymore ^

Before it used to start the helper:

```
➜  fxa-auth-server git:(master) NODE_ENV=dev node test/mail_helper.js
mail_helper started...
```

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa-local-dev/blob/master/servers.json#L4-L12

**Comment by seanmonstar** [comment]
Bleck, this behavior should probably be part of the tests or something I guess...
