### ISSUE TITLE
Send the disconnected push notification to every device in the account

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-auth-server#1777]
This is a follow-up to [Bugzilla #1339861](https://bugzilla.mozilla.org/show_bug.cgi?id=1339861):
We would like to be able to get a push notification every time another device is disconnected in order to refresh our list of known stale devices. This list is built by fetching the FxA device list and comparing it with our own.

As for now, fxa only sends the `fxaccounts:device_disconnected` push notification to the device that has been disconnected.
The proposed change is to send that push notification to everyone, so they can fetch the new devices list.
This should be a relatively safe change, as the client receiving that notification checks if they are the one being disconnected by comparing their deviceId with the one in the push payload [0][1].(although we log an error if it was not directed at us :/)

[0] https://dxr.mozilla.org/mozilla-central/source/services/fxaccounts/FxAccounts.jsm#1571-1574
[1] https://dxr.mozilla.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko/fxa/FxAccountPushHandler.java#88

**Comment by rfk** [comment]
FWIW the proposed change sounds fine to me, 👍

**Comment by eoger** [comment]
About the error logs, we could wait until our clients changes (= at least ignoring the error, which we could do now) are deployed on the Release channel before merging the server-changes. @mhammond may want to chime in here.

**Comment by vladikoff** [comment]
@vladikoff to talk to @eoger

**Comment by vladikoff** [comment]
REF: https://github.com/mozilla/fxa-auth-server/blob/4604d5c2095767e889a871257fa7ee56ddcadbe9/lib/push.js#L207

Change from `pushToDevice` to `pushToAllDevices`. In Firefox Desktop and Firefox For Android remove the logs where the disconnect push logs error with the deviceId mismatch.

**Comment by eoger** [comment]
Device ID mismatch error logging to remove on clients:

- [Firefox Desktop](http://searchfox.org/mozilla-central/rev/abe68d5dad139e376d5521ca1d4b7892e1e7f1ba/services/fxaccounts/FxAccounts.jsm#1575-1578)

- [Firefox for Android](http://searchfox.org/mozilla-central/source/mobile/android/services/src/main/java/org/mozilla/gecko/fxa/FxAccountPushHandler.java#100-102)

- [Firefox for iOS](https://github.com/mozilla-mobile/firefox-ios/blob/master/Account/FxAPushMessageHandler.swift) (not implemented yet at the time of writing)

**Comment by vladikoff** [comment]
This was fixed! Thanks so much @udaraweerasinghege 👍
