### ISSUE TITLE
"Please enter the master password for the Software Security Device."

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1779]
Someone (at the hospital) asked me to help them with their Firefox because they had an annoying pop-up all the time so I was obviously interested in helping. Due to this problem, they had switched to Chrome but wanted to get back to Firefox. So I had to investigate.

 The bug seems somewhat Sync or FxA related and is a bit alarming if it is not caused by us but rather by a 3rd party.

**Behavior**
Regularly the user gets a pop-up that says "Please enter the master password for the Software Security Device."

We can trigger the pop-up on demand by hitting the sync button or going to Synced Tabs or pretty much anything FxA and Sync related.

When going to settings or to the login window, this pop-up came up before seeing the content. Once we would hit cancel, our content normally appeared after
![img_2614](https://cloud.githubusercontent.com/assets/19537086/24419680/cf595f2c-13a4-11e7-87cc-e738a752c442.JPG)
(if you click on the image it will rotate it, looked good on my computer before upload)
![img_2617](https://cloud.githubusercontent.com/assets/19537086/24419916/c7020ba2-13a5-11e7-95e0-0e412e5b64e2.JPG)
(if you click on the image it will rotate it, looked good on my computer before upload)

Note that even if they were logged in, they would get the pop-up.
![img_2613](https://cloud.githubusercontent.com/assets/19537086/24419731/040d1114-13a5-11e7-8c32-44b87ca09c5f.JPG)

Fearing some sort of malware, we re-installed the browser and reset the profile but it did not resolve anything. (so yes, Fx 52)
![img_2618](https://cloud.githubusercontent.com/assets/19537086/24419860/8c22fc58-13a5-11e7-839b-d78d79a1fce0.JPG)
(if you click on the image it will rotate it, looked good on my computer before upload)

As we can see they had no suspicious add-ons or extensions:
![img_2616](https://cloud.githubusercontent.com/assets/19537086/24419785/34c52062-13a5-11e7-8b6a-f26578038641.JPG)
![img_2615](https://cloud.githubusercontent.com/assets/19537086/24419790/3bec37fe-13a5-11e7-84c5-328a4ba49180.JPG)
(if you click on the image it will rotate it, looked good on my computer before upload)

Suspecting FxA, we logged out and back in. When logging back into FxA + Sync, they even got the pop-up on the login confirmation screen:
![img_2619](https://cloud.githubusercontent.com/assets/19537086/24419831/6717bb06-13a5-11e7-9363-6940946aff20.JPG)

My hypothesis is that this is either related to (1) legacy sync or (2) it is malware trying to do some phishing. In either case, the experience is unacceptable.

See: 
- https://support.mozilla.org/t5/Firefox/quot-Please-enter-the-master-password-for-the-Software-Security/m-p/716381
- https://social.technet.microsoft.com/Forums/windows/en-US/5f8fb309-1e76-4b1c-bad2-0356838b1723/please-enter-the-master-password-for-the-software-security-device-i-need-to-diable-this-part-of?forum=w7itproinstall

The good news is that this person was happy to help us fix this in hopes that they could eventually use Firefox again as their default browser. So if we have any further questions, we can email them.

**Comment by rfk** [comment]
That's the Firefox "master password" dialog.  If they go into Preferences -> Security does it have "Use a master password" checked?  Unchecking it should make the dialog go away, although you probably have to enter whatever the actual password is before it can be removed.

The reason this appears related to FxA/Sync is that the browser stores its FxA login credentials in the password manager.  If you have a master password set, the password manager store is encrypted with the master password.  Which means that any time the browser wants to do something FxA/Sync related, it has to unlock the password store, which means prompting for you master password.

(There's a rich history of bugs about whether and why we store the FxA credentials in the password manager store; TL;DR is that it's the safest place we have to store them locally.  But I'm not sure it's worth crappy hard-to-debug experiences like this one).

There are some things we could do to make this better:

* Just store the FxA credentials outside the password manager store.  That's the simplest option but we'd have to think about whether we lose anything security-wise.
* Store the FxA credentials in the system keychain, if available.  This would product a much better user experience, but I don't know the complexity of doing that in a cross-platform manner.
* Get rid of "master password" and just use the system key chain for the whole password store.  IIRC this option is favoured by @ryanfeeley; it might be something we can request the new password-manager team to work on with us.

**Comment by rfk** [comment]
>  If they go into Preferences -> Security does it have "Use a master password" checked?
> Unchecking it should make the dialog go away, although you probably have to enter
> whatever the actual password is before it can be removed.

You can apparently reset the master password if you've forgotten it, at the cost of discarding any saved passwords (and FxA login credentials) that it might be protecting:

  https://support.mozilla.org/t5/Firefox/I-forgot-my-master-password-How-do-i-find-or-change-it-again/m-p/886315

**Comment by vladikoff** [comment]
This is not actionable on the fxa-auth-server. might need to be moved to a card

**Comment by davismtl** [comment]
I've spoken to MattN about this and he has actually had a few meetings this week about Master Password UX and its dire state.

I'll create a card for this in my backlog and close it here.
