### ISSUE TITLE
Update regex for Sync user-agent strings

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1781]
[Bug 1350146](https://bugzilla.mozilla.org/show_bug.cgi?id=1350146) and [bug 1350768](https://bugzilla.mozilla.org/show_bug.cgi?id=1350768) exist to update the Sync user-agent strings for iOS and Android respectively. We have some special-case code for those user-agent strings in the auth server, based on [this regex](https://github.com/mozilla/fxa-auth-server/blob/a44523dc6cf12da4986a0b796b96cf1239bf8240/lib/userAgent.js#L30):

```js
const SYNC_MOBILE_USER_AGENT = /^Firefox-(Android|iOS)-FxA(?:ccounts)?\/(\S+)/
```

We should update the regex in accordance with however those changes pan out.

**Comment by philbooth** [comment]
Also, note to self, do the same for the lua scripts that export our data from the metrics pipeline:

* https://github.com/mozilla-services/puppet-config/blob/03e8ec140239ccf992645e927ec001a74c085c4e/shared/modules/fxa/files/hekad/lua_outputs/fxa_retention_csv.lua#L118-L145

* https://github.com/mozilla-services/puppet-config/blob/03e8ec140239ccf992645e927ec001a74c085c4e/shared/modules/fxa/files/hekad/lua_outputs/fxa_flow_csv.lua#L144-L171

**Comment by philbooth** [comment]
Fwiw, the lua scripts don't need updating for the iOS change. I've made a tweak to the auth server regex for iOS in #1787.

**Comment by philbooth** [comment]
Ref: mozilla-mobile/firefox-ios#2556

**Comment by vladikoff** [comment]
Fixed for now, need to keep an eye on Android ua strings
