### ISSUE TITLE
locale lookup throws 500s if it has `de-formal,` as part of it

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1791]
Example, change the Firefox lang setting to `en-US,en,de-formal,fr-FR,fr`

cc @philbooth

**Comment by philbooth** [comment]
Ah, sorry, stupid assumption on my part. Fixing now...

**Comment by jbuck** [comment]
Also failing: `fr,en-US,en,fr-FR,de-DE,de,de-AT,pt-br,pt,sr-RS,sr,en-gb,sv-SE,sv,ja-JP,ja,se-SE,se,en-ca,ru-RU,ru,nl-NL,nl,it-IT,it,es-ES,es,en-en,fa-IR,fa,ar-AE,ar,tr-TR,tr,th-TH,th,en-my,en-FR,zh-CN,zh,pl-PL,pl,ro-RO,ro,pt-PT,hu-HU,hu,fr_FR.UTF-8,fr_FR.UTF,en-AU,en-UK`

**Comment by shane-tomlinson** [comment]
@philbooth, @vbudhram - was this taken care of?

**Comment by jbuck** [comment]
Yeah, fixed in https://github.com/mozilla/fxa-auth-server/pull/1794/files

**Comment by shane-tomlinson** [comment]
Thanks @jbuck, closing.
