### ISSUE TITLE
Distinguish users who have fallen back to English as the default locale

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1802]
@vbudhram's fix in 748fcee9fb322cbd9293605161c0be2d7673511b removed the broken `isLocaleAcceptable` function that was used to differentiate between users that request English via `Accept-Language` and those who fall back to English because their preferred language is not translated. We should implement something that isn't broken to replace it.

**Comment by shane-tomlinson** [comment]
@philbooth - can you promote this if you feel it needs it?

**Comment by philbooth** [comment]
I don't think we're ever going to do this, closing.
