### ISSUE TITLE
don't replicate verification reminders

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1806]
Set (probably) `replicate-ignore-table` on the replica.

**Comment by vladikoff** [comment]
woo!

**Comment by jrgm** [comment]
The internets suggest that that option in not available with RDS, but that instead the replica can be made writeable, and switch the reminders table to use engine blackhole (mysql's /dev/null).

**Comment by vladikoff** [comment]
@jrgm to check if this is working

**Comment by vladikoff** [comment]
enabled here: https://github.com/mozilla-services/cloudops-deployment/commit/e615754a2fee00ec504de784e3171af6d6b40098
