### ISSUE TITLE
Replace SMS Link to Track Installs

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1808]
The current bit.ly redirects to an Adjust URL with no tracking parameters so we can't track installs.

Please replace it with:
https://mzl.la/firefoxapp

Which should redirect to:
https://app.adjust.com/2uo1qc?campaign=fxa-conf-page&adgroup=sms&creative=link

**Comment by rfk** [comment]
Let's do a point release of train-84 with this change, so we can start getting accurate metrics as soon as possible.
