### ISSUE TITLE
Intermittent Internal Server Error when running content server functional tests against latest

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1810]
See https://tc-test.dev.lcip.org/viewLog.html?buildId=9531&tab=buildResultsDiv&buildTypeId=FxaLatest_FunctionalTests and https://github.com/mozilla/fxa-content-server/issues/4922.

Here is the corresponding stack trace on the auth-server logs (scrubbed of IPs and rids):

> {"Timestamp":1491853685745000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":26692,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":500,"errno":999, "path":"/auth/v1/recovery_email/verify_code","agent":"node-XMLHttpRequest","remoteAddressChain":"[...]","t":5514,"uid":"...","stack":"Error: An internal server error occurred\n    at Function.AppError.translate (/data/fxa-auth-server/lib/error.js:143:13)\n    at /data/fxa-auth-server/lib/server.js:314:26\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:403:22\n    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n    at Object.exports.serial (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:39:9)\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:398:15\n    at internals.Protect.run.finish [as run] (/data/fxa-auth-server/node_modules/hapi/lib/protect.js:56:16)\n    at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/data/fxa-auth-server/node_modules/hapi/lib/request.js:396:19)\n    at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/data/fxa-auth-server/node_modules/hapi/lib/request.js:455:10)\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:389:21\n    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:31:25)\n    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:21:16)\n    at /data/fxa-auth-server/node_modules/hapi/lib/protect.js:52:16\n    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:82:20)\n    at Function.wrapped [as _next] (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at Function.internals.Reply.interface.internals.response (/data/fxa-auth-server/node_modules/hapi/lib/reply.js:138:14)\n    at reply (/data/fxa-auth-server/node_modules/hapi/lib/reply.js:70:22)\n    at tryCatcher (/data/fxa-auth-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:687:18)\n    at Async._drainQueue (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"}}

There is a similar error in /account/status:

> {"Timestamp":1491853685743000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":26692,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":500,"errno":999,,"path":"/auth/v1/account/status","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0 FxATester/1.0","remoteAddressChain":"[...]","t":5205,"uid":"00","email":"sync0.7955678710713983@restmail.net","stack":"Error: An internal server error occurred\n    at Function.AppError.translate (/data/fxa-auth-server/lib/error.js:143:13)\n    at /data/fxa-auth-server/lib/server.js:314:26\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:403:22\n    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n    at Object.exports.serial (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:39:9)\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:398:15\n    at internals.Protect.run.finish [as run] (/data/fxa-auth-server/node_modules/hapi/lib/protect.js:56:16)\n    at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/data/fxa-auth-server/node_modules/hapi/lib/request.js:396:19)\n    at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/data/fxa-auth-server/node_modules/hapi/lib/request.js:455:10)\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:389:21\n    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:31:25)\n    at internals.input.exports.response.postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:163:16)\n    at each (/data/fxa-auth-server/node_modules/hapi/lib/request.js:384:16)\n    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)\n    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:21:16)\n    at /data/fxa-auth-server/node_modules/hapi/lib/protect.js:52:16\n    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:82:20)\n    at Function.wrapped [as _next] (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at Function.internals.Reply.interface.internals.response (/data/fxa-auth-server/node_modules/hapi/lib/reply.js:138:14)\n    at reply (/data/fxa-auth-server/node_modules/hapi/lib/reply.js:70:22)\n    at /data/fxa-auth-server/lib/routes/account.js:1063:15\n    at tryCatcher (/data/fxa-auth-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:687:18)\n    at Async._drainQueue (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:17:14)"}}
js/release/promise.js:687:18)\n    at Async._drainQueue (/data/fxa-auth-server/node_modules/bluebir
d/js/release/async.js:133:16)\n    at Async._drainQueues (/data/fxa-auth-server/node_modules/bluebi
rd/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/data/fxa-aut
h-server/node_modules/bluebird/js/release/async.js:17:14)"}}

as well as for /account/login

> {"Timestamp":1491854225829000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":26692,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":500,"errno":999,"path":"/auth/v1/account/login","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0 FxATester/1.0","remoteAddressChain":"[...]","t":5125,"uid":"00","service":"sync","reason":"signin","keys":true,"email":"sync0.8702165777795017@restmail.net","stack":"Error: An internal server error occurred\n    at Function.AppError.translate (/data/fxa-auth-server/lib/error.js:143:13)\n    at /data/fxa-auth-server/lib/server.js:314:26\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:403:22\n    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n    at Object.exports.serial (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:39:9)\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:398:15\n    at internals.Protect.run.finish [as run] (/data/fxa-auth-server/node_modules/hapi/lib/protect.js:56:16)\n    at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.callback._protect.run [as _invoke] (/data/fxa-auth-server/node_modules/hapi/lib/request.js:396:19)\n    at internals.Request.internals.Request._execute.internals.Request._lifecycle.internals.Request._invoke.internals.Request._reply.exit [as _reply] (/data/fxa-auth-server/node_modules/hapi/lib/request.js:455:10)\n    at /data/fxa-auth-server/node_modules/hapi/lib/request.js:389:21\n    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:31:25)\n    at internals.input.exports.response.postValidate (/data/fxa-auth-server/node_modules/hapi/lib/validation.js:163:16)\n    at each (/data/fxa-auth-server/node_modules/hapi/lib/request.js:384:16)\n    at iterate (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:36:13)\n    at done (/data/fxa-auth-server/node_modules/hapi/node_modules/items/lib/index.js:28:25)\n    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:21:16)\n    at /data/fxa-auth-server/node_modules/hapi/lib/protect.js:52:16\n    at wrapped (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at finalize (/data/fxa-auth-server/node_modules/hapi/lib/handler.js:82:20)\n    at Function.wrapped [as _next] (/data/fxa-auth-server/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)\n    at Function.internals.Reply.interface.internals.response (/data/fxa-auth-server/node_modules/hapi/lib/reply.js:138:14)\n    at reply (/data/fxa-auth-server/node_modules/hapi/lib/reply.js:70:22)\n    at tryCatcher (/data/fxa-auth-server/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/data/fxa-auth-server/node_modules/bluebird/js/release/promise.js:687:18)\n    at Async._drainQueue (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/data/fxa-auth-server/node_modules/bluebird/js/release/async.js:17:14)"}}

**Comment by shane-tomlinson** [comment]
The line before each of these is something along the lines of:

> {"Timestamp":1491853685742000000,"Logger":"fxa-auth-server","Type":"server.EndpointError","Severity":2,"Pid":26692,"EnvVersion":"2.0","Fields":{"op":"server.EndpointError","message":"127.0.0.1:8000 error: request timed out","reason":"socket hang up","method":"HEAD"}}

**Comment by vbudhram** [comment]
@shane-tomlinson Hrm, that error is usually the auth-db timing out.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson Hrm, that error is usually the auth-db timing out.

I'll have a look in the auth-db logs to see if there's anything obvious.

**Comment by shane-tomlinson** [comment]
Caused by https://github.com/mozilla/fxa-auth-db-mysql/issues/221, closing here.
