### ISSUE TITLE
Soft bounces never expire

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1812]
I did a bit of debugging to try to figure out why so many users were having so many problems with the "soft bounced" error [1], and it turns out that soft bounce errors never expire in the default config.  We *try* to make them expire by setting `BOUNCES_SOFT_DURATION="5 mins"` in the default config:

  https://github.com/mozilla/fxa-auth-server/blob/64c96d652f2096674d24832534e560fd5e30d462/config/index.js#L301

But this "5 mins" syntax is not supported by moment.js, hence not supported by convict, and it winds up being interpreted as a zero:

```
> +moment.duration(5, 'mins')
0
```

Which our code, in turn, interprets as "these should never expire".  So if the user ever experiences a transient delivery failure, they get stuck in that state forever.  We need to spell out "5 minutes" in order for this to work correctly:

```
> +moment.duration(5, 'minutes')
300000
```

To fix this up we'll need to:

* [ ] Change the default config value to "5 minutes", and re-deploy train-84.
* [ ] Audit our test coverage to see why we didn't discover this problem before shipping it to prod.
* [ ] See if we can have convict reject unknown duration strings rather than silently returning a zero.

[1] see e.g. https://support.mozilla.org/t5/Firefox/Firefox-Sync-Email-account-soft-bounced/m-p/1389567

**Comment by rfk** [comment]
Oh, and:

* [ ] Put `BOUNCES_SOFT_MAX` back to `1` once we've fixed this issue.

**Comment by seanmonstar** [comment]
To clarify, the default of `BOUNCES_SOFT_MAX` was `0`, per the feature doc. This works via `if count > max`. (I'd be fine with making the default more generous, though.)
