### ISSUE TITLE
Intermittent test failures with push

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#1816]
Seen this a few times over the past couple of weeks.

<img width="797" alt="screen shot 2017-04-13 at 10 09 06 am" src="https://cloud.githubusercontent.com/assets/1295288/25008226/18d1c00c-2031-11e7-8b50-e5f684d562f0.png">

Restarting the test usually fixes it.

**Comment by vladikoff** [comment]
Vapid private key!

**Comment by vladikoff** [comment]
Closing it until we see it again
