### ISSUE TITLE
Not sending unblock codes? Or metrics problem?

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1822]
According to this chart, there are no more confirmed flows:
https://sql.telemetry.mozilla.org/queries/1958#3478

Then, it turns out the login success rate with unblock codes is near 0%.
https://sql.telemetry.mozilla.org/queries/1626#2878

I am hoping it is only metrics related. The fact that there has been no change to our login success rate provides optimism. (In fact, there was a slight jump in success rate)
https://sql.telemetry.mozilla.org/queries/1751#3117

**Comment by davismtl** [comment]
Also relevant:
Number of invalid code errors before successful confirmation has spiked:
https://sql.telemetry.mozilla.org/queries/1958#3631

**Comment by seanmonstar** [comment]
We just changed the number of failed attempts before a customs block from 3 to 10, does this correlate with the same time?

**Comment by davismtl** [comment]
I'm not sure what exact day the failed attempts were changed but the charts drop on April 11th.

**Comment by rfk** [comment]
The dates here do indeed correspond to what @seanmonstar mentions, where we increased the allowed number of failed login attempts in production.  I expect this is simply the result of us blocking much, much fewer people than we previously were, giving fewer people reason to go through the unblock flow in the first place.

**Comment by davismtl** [comment]
I suspect that this is correct. The volume just seems to have dropped tremendously.

My hypothesis was that if this is true, our signin success rate must be much higher.

It turns out that signin success rate **has** climbed by about 10% on firstrun.

**Comment by vladikoff** [comment]
@shane-tomlinson what to do with this issue?

**Comment by rfk** [comment]
I'm happy to call this "expected due to config change" and close the issue.
