### ISSUE TITLE
npm install errors with 'no such file' on 'node_modules/.staging/nyc-ccd1dd90/node_modules/lodash'

### ISSUE THREAD

**Issue by MrHappy** [mozilla/fxa-auth-server#1826]
Running on Ubuntu 14.04
This is the logging:

`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.1 (node_modules/grunt-nunjucks-2-html/node_modules/nunjucks/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! path /opt/fxa-auth-server/node_modules/.staging/nyc-ccd1dd90/node_modules/lodash
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/opt/fxa-auth-server/node_modules/.staging/nyc-ccd1dd90/node_modules/lodash' -> '/opt/fxa-auth-server/node_modules/.staging/lodash-b9bdd4ee'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
`

**Comment by jrgm** [comment]
What is the output of `node --version` and `npm --version`?

**Comment by MrHappy** [comment]
node --version: v4.8.2
npm --version: 4.5.0

**Comment by shane-tomlinson** [comment]
@MrHappy - I believe we are stuck on npm 2.x, whatever comes stock with node v4.8

**Comment by vladikoff** [comment]
Downgrade to npm 2
