### ISSUE TITLE
repair ./tests/load loadtest

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1828]
This was working until recently, but now I get unexplained `ClientError: Unverified account` running `make test` or `make build`. It happens sometimes but not always. This may be a problem with auth-server, but I haven't figured it out yet what's wrong there.

However, I was running with an old (0.0.9) version of FxAPy. So I updated to current 0.3.0, but now was getting `AttributeError: 'module' object has no attribute 'epoll'`, which is probably some `urllib3 v. gevent` monkey patch confusion, as noted in https://github.com/kennethreitz/requests/issues/3831.

I worked around it by hacking the virtualenv ./bin/loads-runner, to add
```
from gevent import monkey
monkey.patch_all()
```
as the first thing run there. And that let me get back to having the `ClientError: Unverified account` with 0.3.0 PyFxA. (Obviously, not a real fix).

Anyways, it would be good to get this all running properly (in PyFxA and fxa-auth-server) to be able to run the load test, to compare non-docker and docker runs in stage.

**Comment by rfk** [comment]
Also worth noting that loads is no longer supported, and QA team are focusing their efforts on this new thing: https://github.com/loads/molotov.  Perhaps we should take this opportunity to migrate over to that instead.

@jrgm do you make use of any of the distributed-load-runner capabilities of loads, or just run these locally on a single box?

**Comment by rfk** [comment]
> ClientError: Unverified account

My first guess upon encountering this error is always "oh, sign-in confirmation..."

**Comment by jrgm** [comment]
> @jrgm do you make use of any of the distributed-load-runner capabilities of loads, or just run these locally on a single box?

Never found the framework useful, mostly in its old form, where there were always problems with it. Actually, while distributed load test might be nice, it would be hard to work with since I have to exempt in allowedIPs the load runners, and if they were dynamically moving around...

**Comment by rfk** [comment]
> Perhaps we should take this opportunity to migrate over to that instead.

FWIW I've decided against doing the loads -> molotov migration right now, since getting the tests up and running is a P1.

> ClientError: Unverified account

This definitely does appear to be related to signin confirmation.  It's intermittent because it only happens on existing accounts, not the newly-created-in-preverified-state accounts we use for the loadtest.  I'm going to see if I can switch to using restmail and verifying accounts as needed, but we'll have to see whether that reduces the throughput of the loadtest.
