### ISSUE TITLE
Separate AuthDB stack

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1831]
To discuss....

**Comment by rfk** [comment]
From meeting: complications to watch out for:
* more $$ spent on machines
* need to stage deployments of db ahead of those of auth-server for API changes

Seems unlikely to get this done in Q2 due to prioritization and dependencies

**Comment by vladikoff** [comment]
🗡 Closing this until we have any plans to do this. Please reopen if you think we should....
