### ISSUE TITLE
Add SMS templates to Documentation

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1839]
SMS events are now documented here:
https://github.com/mozilla/fxa-auth-server/blob/master/docs/metrics-events.md

Events are called:
sms.${templateName}.sent

It is unclear what the template names are.

So I ran this to figure it out:
SELECT *
FROM flow_events
WHERE type LIKE 'sms%'
LIMIT 100

The answer is that templates are numbers. Example: ms.1.sent

Let's document what those templates numbers mean.

**Comment by rfk** [comment]
Not sure how complex it would be, but perhaps we can map these back to meaningful names for metrics purposes, and leave the integers as an internal implementation detail?
