### ISSUE TITLE
Sign our emails so we get snazzy authenticated "key" icons in gmail

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1855]
Importing from https://github.com/mozilla/fxa-auth-mailer/issues/64

-----

> As described in:

> https://support.google.com/mail/answer/3070163

> This is what they look like in Gmail
> ![](https://cloud.githubusercontent.com/assets/557895/8738679/b313030a-2be7-11e5-9356-0fdec532a895.png)

> This is what they look like in Outlook
> ![](https://cloud.githubusercontent.com/assets/51007/8739430/f1c7e568-2c8f-11e5-80a6-feabbb2cd613.PNG)

> We tried to do this before, related bug https://bugzilla.mozilla.org/show_bug.cgi?id=1003299

**Comment by rfk** [comment]
I'm bumping this back into the "quality" milestone, as we wrap up fxa-56 feature card.

**Comment by shane-tomlinson** [comment]
@jrgm to investigate what needs to be done here.

**Comment by vladikoff** [comment]
wontfix
