### ISSUE TITLE
Establish baseline click-through rate of post-verification email

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1857]
Importing from https://github.com/mozilla/fxa-auth-mailer/issues/127

-----

> We added utm_* params to the add-a-second-device links in our post-verification email. This is a follow-up issue to get some stats on the click-through rate of those links, so we can compare the effectiveness of these vs the new sms install link.

> it looks like we’re getting just under 5% click-through on the links in these emails.

**Comment by rfk** [comment]
We have great metrics on this in re:dash now, closing out the issue here.
