### ISSUE TITLE
Add App/Play Store badges to post-verification email

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1859]
Imported from https://github.com/mozilla/fxa-auth-mailer/issues/264

-----

> Lesson from Sync Fest – make it easier to download the app by putting a link directly in the email. We can use the same UTM params in the links used currently.

![](https://cloud.githubusercontent.com/assets/68213/23410827/782c03a6-fd9e-11e6-8a04-a88d4d50c101.png)

> I guess those need to be the translated, which is always fun ...

**Comment by rfk** [comment]
> mozilla/fxa-auth-mailer#264

FWIW these links no longer work because issues are disabled on that repo.

**Comment by rfk** [comment]
@ryanfeeley is this something we still want to do, or does our much-improved "connect another device" experience mean that we can close this issue and replace it with https://github.com/mozilla/fxa-auth-server/issues/1860 ?

**Comment by ryanfeeley** [comment]
I think we should still add the badges in this email.

**Comment by rfk** [comment]
Potentially we could have them send via adjust and deeplink with the user's email address prefilled, once that code lands.

**Comment by vladikoff** [comment]
@ryanfeeley How important is this comparing to the rest of the features? Set P3 priority

**Comment by vladikoff** [comment]
Closing until we need this
