### ISSUE TITLE
Change destination of Connect Another Device in email to FxA-controlled page

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1860]
Imported from https://github.com/mozilla/fxa-auth-mailer/issues/265

----

>We certainly need a page we can drive people to that can detect if you're on desktop and mobile and give you buttons or the SMS form accordingly.
>
>Once we have that page, we can drive people to it from email, device manager, etc.

> The Mozilla.org page does a decent job of this now, but I think a simpler page that we control would be better. We can also direct users from the "Not synced tabs… yet!" states in desktop.

> The mozilla page only does Android. We support both. Further more, we will be pre-populating forms and deeplinking in future phases. They will not support this (though we should look into helping them support it).

> +1, I'm strongly in favour of having a single landing page that we control that can be used for links of this sort. Using https://accounts.firefox.com/connect_another_device?service=sync right now is not too bad at it and ISTM we can easily iterate it into shape for this purpose.

**Comment by ryanfeeley** [comment]
One thing is improve is that this page should not have a fixed "Email verified" message. https://accounts.firefox.com/connect_another_device/?service=sync

**Comment by shane-tomlinson** [comment]
> One thing is improve is that this page should not have a fixed "Email verified" message. https://accounts.firefox.com/connect_another_device/?service=sync
cc/ @rfk

Ref https://github.com/mozilla/fxa-content-server/issues/5009

**Comment by vladikoff** [comment]
cc @ryanfeeley @vladikoff to take a look at this
