### ISSUE TITLE
Add parameter to links in text-only emails

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1861]
Imported from https://github.com/mozilla/fxa-auth-mailer/issues/197

----

> Is anyone clicking the links in our text only emails? Would be good to differentiate them.

> Is the bigger question here, how many people view text only emails?

> Yeah, handy to know, but not crucial. Good to know how many users have less capabilities.

**Comment by rkalyan3** [comment]
Can you elaborate on this issue? Also, when I click on the above link, the page is not available.

**Comment by vladikoff** [comment]
@riddle03 We have 2 version of emails HTML and Text, we want to add extra query parameters to the Text version of the links to see if anyone is actually seeing the Text emails. Google's UTM parameters might be useful here

**Comment by riddle03** [comment]
Thanks for explaining that. Can you tell me what I'd need to do to help with this?

**Comment by vladikoff** [comment]
Let's reopen this if we still need it...
