### ISSUE TITLE
Expire old sessionTokens that don't belong to a device?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1863]
As seen in e.g. the screenshot in https://github.com/mozilla/fxa-content-server/issues/4987#issuecomment-297115457, it's easy for users to accidentally leave behind a bunch of old orphaned session tokens.  We could try to clear that up by introducing a rule such as:

**_If a sessionToken is more than 4 weeks old, and does not have an associated device record, then it is expired and cannot be used to log in_**

We could delete such sessionTokens from the if possible to do so efficiently, but if nothing else, we could hide them from the device-manager and disallow any attempts to use them.

This would allow users who log in to sync to continue syncing indefinitely, but would force users who logged in through the web to re-login after 4 weeks.  That seems like an OK tradeoff to me.  @davismtl @vladikoff thoughts?

**Comment by vladikoff** [comment]
Yes, let's do it! 

from mtg: let's discuss in the product meeting
