### ISSUE TITLE
Add an explicit push-endpoint-status flag to device records

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1873]
Per discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1359279

Currently if we detect that a device's push endpoint is no longer working, we just delete the invalid endpoint from its device record.  To make it easier for the client to recover, we should instead set an explicit flag saying that the device record is state and needs to be updated.

ISTM the simplest possible thing is a "pushEndpointExpired" flag which can default to false, but be set to true when we discover that the push endpoint has expired.  It's probably useful to make this state visible to other connected devices as well.

@vladikoff does this sound reasonable?  Always good to get a second opinion on these things :-)

**Comment by vladikoff** [comment]
> ISTM the simplest possible thing is a "pushEndpointExpired" flag which can default to false, but be set to true when we discover that the push endpoint has expired. 

Sounds good! and do we return `pushEndpointExpired` in GET /device and GET /devices?

**Comment by rfk** [comment]
> and do we return pushEndpointExpired in GET /device and GET /devices?

👍

**Comment by rfk** [comment]
I re-read Bug 1359279 and I think the approach described here is good to move forward with, and will help mobile clients keep their push subscriptions up-to-date.  I don't anticipate any additional changes we want to make to the devices table in the short-term so we could do this as a stand-alone migration; @philbooth can you think of any?

If we're worried about the cost of adding a new column after the recent rollback of a change to the "sessionTokens" table, we could consider putting this data in a separate table and joining onto it, like we do for the token verification stuff.  But I'm hopeful we can get through that migration issue with @jrgm's help on the timeouts thing.

**Comment by rfk** [comment]
In fact, let's make that an explicit question for @jrgm and @philbooth: thoughts on the doability of adding a new column to the devices table?

**Comment by philbooth** [comment]
> I don't anticipate any additional changes we want to make to the devices table in the short-term so we could do this as a stand-alone migration; @philbooth can you think of any?

I can't.

**Comment by grigoryk** [comment]
@rfk can you comment on landability of this? I'm thinking we should actually push through with https://bugzilla.mozilla.org/show_bug.cgi?id=1359279

**Comment by rfk** [comment]
@grigoryk I think we're OK to move forward with this, we just haven't prioritized it because it doesn't directly feed into any Q3 OKRs at this stage.  I'll try to take a quick look sometime this week and see what the possibilities are.

**Comment by rfk** [comment]
> I don't anticipate any additional changes we want to make to the devices table in the short-term

Sounds like we might be adding a new column to better support unicode device names, so let's keep that in mind as maybe we can add the new column here as well.
