### ISSUE TITLE
Drop in Registration Success Rate

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1876]
Investigative issue:

Since April 16th, our sign-in success rate seems to have dropped. @rfk does this line up with train 84?

https://sql.telemetry.mozilla.org/queries/1975#3534
https://sql.telemetry.mozilla.org/queries/2412?p_start_date=2017-02-01#4457

This might also be related to "Free as a Fox" released on April 13th.

Figure out cause and impact.

**Comment by davismtl** [comment]
Meanwhile sign in success rate has increased:
https://sql.telemetry.mozilla.org/queries/2078?p_start_date=2017-02-01#3815

To-do: Look into absolute numbers.

**Comment by vladikoff** [comment]
from mtg: need to sanity check

**Comment by vladikoff** [comment]
from mtg: ping @davismtl

**Comment by vladikoff** [comment]
🔪
