### ISSUE TITLE
Add tiered blocking for hard bounces

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1893]
Sometimes, email servers fall over and SES tells us it was a hard bounce, and then the email server comes back up, but we throw up our arms "NO! you bounced! won't do it!". It sounds like we want to add some tiers for how blocked a hard bounced email address is.

A suggested tier system is:

> - We refuse to send more email if you've had 1 hard bounce in the last 24 hours
> - We refuse to send more email if you've had 2 hard bounces in the last 12 months

**Comment by philbooth** [comment]
@seanmonstar we've stuck this in the backlog but move it if that was wrong.
