### ISSUE TITLE
Automatically expire signinCodes that are older than 2 days

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1898]
There is a db endpoint for expiring signinCodes that are older than a specified timestamp:

https://github.com/mozilla/fxa-auth-db-mysql/blob/b74079397aab4bebdf031e95e138955e990afc53/fxa-auth-db-server/index.js#L203-L206

We need to ensure it gets called at regular intervals so that signinCodes are cleaned up.

Where is the sweet spot between over-stressing the db server and not expiring frequently enough to satisfy security concerns? Hourly? Daily? Somewhere in between?

**Comment by g-k** [comment]
We might be able to do this lazily by checking that the signin code createdAt column is not more than two days old when the code is used too.
