### ISSUE TITLE
Try to remove links on email addresses in email body

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#1902]
I'm not sure if this is possible, but is it possible to escape the email addresses so they are not links in secondary email body? Or can they be styled as regular text? When providers like Gmail automatically make them links, it makes the emails harder to read.

**Comment by rfk** [comment]
Can you please post a screenshot or similar for clarity?

**Comment by ryanfeeley** [comment]
@rfk absolutely! 
<img width="671" alt="screen shot 2017-05-18 at 4 04 31 pm" src="https://cloud.githubusercontent.com/assets/68213/26221211/b79532d2-3be3-11e7-8bca-f1f232c4c96a.png">

**Comment by vladikoff** [comment]
from mtg: need to see if we can do this!

**Comment by ryanfeeley** [comment]
@vladikoff Apparently the way to do it is like this:
<a href="mailto:[email]" style="color: [color]; text-decoration: none;">[email]</a>
Seem like a bad idea?

**Comment by vladikoff** [comment]
@ryanfeeley in the current template we don't have `<a>` anchors around them in the first place.

**Comment by vladikoff** [comment]
So this could make it even worse :(

**Comment by vladikoff** [comment]
🗡
