### ISSUE TITLE
Device manager not showing icons

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1913]
The device manager is not showing device icons. This was detected during Sync fest.

![screen shot 2017-05-24 at 1 52 37 pm](https://cloud.githubusercontent.com/assets/19537086/26425042/5780bd2c-4088-11e7-8038-6eaecc31280d.png)

**Comment by davismtl** [comment]
Might be a duplicate of:
https://github.com/mozilla/fxa-content-server/issues/5073

**Comment by davismtl** [comment]
Also worth noting, I have A LOT of duplicate devices and yet I keep clearing these. I'm not sure what is causing this.

Also, those Android devices were not there in recent months so I don't know why they are back.

**Comment by rfk** [comment]
> Also worth noting, I have A LOT of duplicate devices and yet I keep clearing these.
> I'm not sure what is causing this.

@davismtl do you fell like duplicate device records are appearing despite you not signing in to anything?  If you're getting dupes because you have to re-sign-in on an device then that's one thing, but if they're just appearing without you haven't had to type in your password then it may be a bug in the placeholder device creation logic.

**Comment by davismtl** [comment]
I'm pretty certain that in the last 2-3 months, I haven't signed in and out anywhere near that amount of times. 
I also feel pretty certain that this list was a lot shorter recently (since I regularly disconnect) and didn't have those Android devices.

**Comment by rfk** [comment]
"Firefox 43.0a1, Android" is a pretty old version of Firefox too.  Any chance you've got some old abandoned Android device left lying around that's logged in as you and still trying to sync?

**Comment by davismtl** [comment]
That old device hasn't been turned on for months since it's at the bottom of a drawer with a dead battery....

**Comment by rfk** [comment]
And if you have previously disconnected it through this view, it really shouldn't suddenly re-appear in the list...

**Comment by philbooth** [comment]
Closing this, the hive mind thinks it's fixed.
