### ISSUE TITLE
Replace devices image in verification email with new illustration

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#1914]
current (in context):
<img width="467" alt="screen shot 2017-05-25 at 3 10 52 pm" src="https://cloud.githubusercontent.com/assets/68213/26466464/d4f20f5c-415c-11e7-85cb-48274ef7aadc.png">

proposed (optimized 8-bit PNG):
![choose-what-to-sync](https://cloud.githubusercontent.com/assets/68213/26466454/cd7d7946-415c-11e7-80d6-04d4a7c9c32f.png)

**Comment by ryanfeeley** [comment]
(scale to half size in HTML for retina-friendliness)

**Comment by shane-tomlinson** [comment]
Same comment as in mozilla/fxa-content-server#5098 - it's a laptop with speakers!

**Comment by philbooth** [comment]
@ryanfeeley, they look like speakers.

**Comment by vladikoff** [comment]
@ryanfeeley could you provide a link to the **final final** version of this icon? Thanks

**Comment by vladikoff** [comment]
@ryanfeeley I sent the given image to the marketing team, but the provided image is wrong. Could you please attached the updated optimized 8-bit again with high contrast?

**Comment by ryanfeeley** [comment]
@vladikoff Oops, my fault! I forgot to update the bitmap when the SVG was updated for the other issue. Stay tuned.

**Comment by ryanfeeley** [comment]
@vladikoff Sized to a more half-able size of 540 × 280
![comp](https://user-images.githubusercontent.com/68213/28579648-36f086a4-712b-11e7-9316-cb57218e0bd1.png)
