### ISSUE TITLE
Photon menu doesn't detect that I am logged in

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#1917]
- Enable Photon in about-config. (browser.photon.structure.enabled)
- Open hamburger menu. I don't appear logged in.

![image](https://cloud.githubusercontent.com/assets/19537086/26504451/851a8fe8-41f9-11e7-81ab-3e024e20ed7e.png)

In preferences though, it does detect my session:
<img width="414" alt="image" src="https://cloud.githubusercontent.com/assets/19537086/26504504/adda4c02-41f9-11e7-9902-7a9ed6d1efc8.png">

**Comment by rfk** [comment]
I was able to repro this yesterday, but after the most recent nightly update it appears to be working again?  @davismtl can you still repro?

I also have to believe this is a client-side bug with the new menu, so we may be better off tracking in bugzilla so we can link it with the rest of the photon work.

**Comment by eoger** [comment]
@davismtl Can you reproduce if you restart Firefox after setting the pref? (By the way, if confirmed, this probably belongs in Bugzilla).

**Comment by davismtl** [comment]
After a reboot this morning, it looks good. I will close this for now since rebooting seems to have resolved it for everyone.
