### ISSUE TITLE
Push notifications can interfere with WebChannel messages during password change/reset

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1929]
@mhammond diagnosed this issue over IRC, capturing it here.  STR:

1. Sign in to sync.
2. Click through "manage account" and change your account password in the same browser.
3. Force a "sync now" in that browser.

Expected result:  this all works transparently, because when you changed your password, the content-server sent updated login credentials to the browser over a local webchannel.

Actual result:  the browser thinks it has been disconnected and asks you to sign back in.

AFAWCT this is caused by a chain of events such as:

* content-server calls `/password/change/finish`, causing fxa-auth-server to fire off a "password_changed" push notification as part of processing the request.
* The push notification is super fast and is received by the browser *before* content-sever has finished its change-password logic.
* In response to the push notification, the browser checks off a request to /account/status to check its login state.
* The content-server finishes its change password procedure, and messages out new credentials to the browser, which updates its local sessionToken.
* The browser's /account/status check returns with a 401 because it was using the previous, invalidated sessionToken.  The browser decides it needs to re-auth and sadness ensues.

I guess *technically* this is a browser bug, due to the handled race between the last two bullet points there.  But given this is shipping release clients I think we'll have to try to mitigate it on the server.

Short term, perhaps we can introduce a short delay before sending the push notifications, to reduce the race window?

Longer term, perhaps we can avoid sending the push message to the originating device at all, since we know it should receive new credentials via webchannel?

**Comment by rfk** [comment]
We hypothesize there may be a similar situation if you're doing a password-reset from a connected device, although I'm not sure why you'd be doing that in practice.

**Comment by mhammond** [comment]
Logs in the failure case look like:

`FirefoxAccounts	DEBUG	push command: fxaccounts:password_changed`
(which is obviously the push coming in)
`Services.Common.RESTRequest	DEBUG	GET request to https://api.accounts.firefox.com/v1/session/status`
(so we've fired off the check with the old creds)
`FirefoxAccounts	DEBUG	FxAccountsWebChannel message received: fxaccounts:change_password`
`FirefoxAccounts	DEBUG	updateUserAccountData called with fields: ["deviceId","email","keyFetchToken","sessionToken","uid","unwrapBKey","verified"]`
(the webchannel message has updated the creds)
`Services.Common.RESTRequest	DEBUG	GET https://api.accounts.firefox.com/v1/session/status 401`
(the response from session/status)
and we now wipe the creds.

I made a local change to wait 3 seconds between that change-password notification and acting on it, and we see the account/status call fired *after* the channel message has updated the creds, the response comes back as 200, and life is good.

Somewhat oddly, if I use my test profile to reproduce with 53, I see the logs indicate we failed to subscribe to push notifications for reasons I don't understand, but possibly has something to do with the profile having previously been used with 55. If I create a branch new profile in 53, the push subscription works and I can reproduce. The fact it can be reproduced in 53 is the main reason Ryan suggested the server perform the wait.

**Comment by rfk** [comment]
I'm wondering if we can avoid the wait and instead go straight to a "nicer" solution: if the password change is coming from a sessionToken that's associated with a device, do not send the push notification to that device, on the assumption that it'll find out via webchannel.

@mhammond thoughts?

**Comment by mhammond** [comment]
That sounds ideal

**Comment by rfk** [comment]
It may not be 100% reliable, e.g. I think you could still get into trouble if you're signed in to the browser, but also signed in to web content with a different sessionToken.  It should catch the majority of cases there though.

**Comment by mhammond** [comment]
> Somewhat oddly, if I use my test profile to reproduce with 53

FTR, we've confirmed that push is broken when you "downgrade" a profile, so this will only repro when the profile has never been used with a version of Firefox greater than the one attempting the reproduction.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-auth-server/pull/1931
