### ISSUE TITLE
Use text-string SMS sender ids in config for supported countries

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1939]
This issue is in the wrong repo (presumably it should be somewhere in mozilla-services but I'm not a member of that org).

But anyway, I notice that in prod, the SMS message we send to UK numbers is sent from a phone number rather than the text-string sender id `Firefox` that we use in the default config / dev. In supported countries, I reckon we should prefer text-string sender ids for reasons of user-friendliness as it may impact the completion rate for connecting another device. AFAIK that is just `GB` out of our current list.

Not sure whether SNS supports non-numeric sender ids but if it does then this applies post-migration too.

/cc @jbuck.

**Comment by jbuck** [comment]
I have updated my PR to use that senderid: https://github.com/mozilla/fxa-auth-server/pull/1940/files#diff-efee666b200420719c39f5501104be45R36

I'll need to update the configs for the auth server but we can ship that on this train

**Comment by philbooth** [comment]
Closing this, done as part of #1964.
