### ISSUE TITLE
Send to other devices only in /account/devices/notify

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-auth-server#1942]
In [Bugzilla #1363412](https://bugzilla.mozilla.org/show_bug.cgi?id=), we need to be able to send a push notification to all devices, except the one making the request.
This is not possible at the moment using `/account/devices/notify`.
We could either:
- add another special string value the `to` property sent in the body of the request. Right now we have `"all"`, we could have `"all-others"`.
- add another property to the body of the request, like `sendToCaller`, defaulting to true if not present.

What do you guys think? @rfk @vladikoff @philbooth

**Comment by rfk** [comment]
In what situations do we *want* a device to send a push notification to itself?  I wonder if we can make the semantics for `"all"` be "all the other devices".

**Comment by eoger** [comment]
Probably none, good point.

**Comment by eoger** [comment]
Oh I'm actually an idiot, this endpoint has a "excluded" parameter!

**Comment by vladikoff** [comment]
👍
