### ISSUE TITLE
If your primary email is bouncy, we don't send to your secondary email

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#1953]
I could have this wrong here, but my read of the code suggests that our sending logic goes like this:

* in `lib/routes/account.js`, we call e.g. `sendVerifyLoginEmail` using the primary address as the "To:" address, and the secondary addresses as "CC:" addresses.
* in `lib/senders/index.js`, we check whether the "To:" address has a history of bounces, and if so then we error out.

So if your primary email address is bouncy, we'll just refuse to send the signin confirmation email at all, and adding a secondary email won't help you.  @seanmonstar @vbudhram thoughts?

**Comment by vbudhram** [comment]
> adding a secondary email won't help you

Unfortunately, that looks like what is going on. I think the fix should be to check all the users emails and gate the ones that have been marked as bounced. If it is a primary email, then send to all valid secondary emails.
