### ISSUE TITLE
Block all push notification except "sync:collection_changed"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#1955]
from mtg with @davismtl and Stefan: 

The iOS client is past the L10n deadline and iOS forces us to show all notifications.
The client is not ready to receive push notifications except  `"sync:collection_changed"` so we have to check the type of device and if it is an iOS device then we should not send the extra Push notifications to those clients.

**Comment by vladikoff** [comment]
cc @st3fan

**Comment by jbuck** [comment]
Do we want to ship this during the all-hands? If so, just make sure we get a train-89 point release too

**Comment by vladikoff** [comment]
@jbuck we need this live before July 13th, so we have a bit of time :)

**Comment by st3fan** [comment]
@vladikoff I think it woud be pretty great if we could see the effects of this next week in a staging environment. Since we will be all in the same room.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-auth-server/commit/111bfbb2db79fd7ba593dc23f0358a6097bccc62

thanks @udaraweerasinghege !
