### ISSUE TITLE
Our usage of uuid has synchronous randomBytes calls

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1958]

**Comment by seanmonstar** [comment]
Severity is probably about the same as when we were calling `crypto.randomBytes(16)` ourselves. It is possible if the host machine doesn't have enough entropy to block the node process until it has some. I don't know if that happens frequently and is hurting us or not.

**Comment by philbooth** [comment]
Nominating this for triage later.

**Comment by vladikoff** [comment]
from mtg: closing for now. 

ref https://github.com/kelektiv/node-uuid/issues/150
