### ISSUE TITLE
Email: Use deeplinks for the install buttons

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1970]

**Comment by seanmonstar** [comment]
I believe this is already done. Looking in the auth-server, the `androidUrl` and `iosUrl` in our config is now `app.adjust.com` URLs. These are what we put into the post-verify templates for the install buttons.

**Comment by rfk** [comment]
IIRC the deeplinks have some random token in the domain, like `abcdef.adjust.com` rather than `app.adjust.com`; @vbudhram can you confirm whether that's what we should expect to see if deep links are in use here?

**Comment by vbudhram** [comment]
Verified that our install Firefox button in emails use adjust deeplink and open App Store...closing.
