### ISSUE TITLE
A way to force an account into "must reset password" mode is needed for functional tests.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1975]
We need to [add functional tests for the account reset](https://github.com/mozilla/fxa-content-server/issues/3653) feature we added last year. To do so, we need a way to force an account into the "must reset password" mode.

We had similar requirements when we had the "account lockout" feature. We added an endpoint that took the user's email/pw combination, if the email/pw matched, then we'd lock the account.

**Comment by vbudhram** [comment]
from mtg: kill content-server version, closing this too
