### ISSUE TITLE
Update /account/login route to send a push notification instead of an email for confirmation

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-server#1978]
When a user is signing in, the content-server will `POST /account/login`. In many cases, we will send a confirmation email, but we want to send a push notification instead.

- There is the [`sendVerifyLoginEmail`](https://github.com/mozilla/fxa-auth-server/blob/v1.90.0/lib/routes/account.js#L966) function, and we want to **add** a `sendVerifyLoginPush`.
- We should probably only do this if the user already has a device logged in. If the user logged in once on a desktop, and then logged out, they could be in a state where no devices are logged in. Then we would need to fall back to the email.
- A `notifyVerifyLogin` method will need to be added ti `lib/push.js` (see this [example](https://github.com/mozilla/fxa-auth-server/blob/v1.90.0/lib/push.js#L236))
- The push message itself will probably need these properties:
  - A `title` that we can have translated
  - A `text` body that is also translated
  - A `url` that the other device should open. The `url` needs to include a few things its query parameters:
    - `code`, which is what we normally send in the confirmation email
    - ... Well, really most of the properties we would send in an email, since we need to display all of that information on the content-server screen when it loads, like IP address, browser, etc. This probably requires working on the content-server + UX to determine exactly what we want to send.
- This should probably have a feature gate to start with. This allows us to slowly turn the feature on while we test it (like only mozilla users, or 5% of users, etc). This means adding to `lib/features.js` similar to [this example](https://github.com/mozilla/fxa-auth-server/blob/v1.90.0/lib/features.js#L24), and updating `config/index.js` accordingly.
- And of course, tests! 🎉

**Comment by vladikoff** [comment]
@seanmonstar is this related to https://github.com/mozilla/fxa-auth-server/issues/1976 ?

**Comment by seanmonstar** [comment]
@vladikoff I don't think so. This is the 2FA via Push project that @vershwal is working on.

**Comment by vladikoff** [comment]
@seanmonstar oh woops. I think I got confused because we already send something on login I think

**Comment by rfk** [comment]
> We should probably only do this if the user already has a device logged in

A quick note to call it out explicitly: we should only do it if the user has a device with a *verified* session; it's possible to login and register a device record without ever doing the email confirmation loop.

**Comment by vladikoff** [comment]
Some code for that here: https://github.com/mozilla/fxa-auth-server/pull/2068

**Comment by shane-tomlinson** [comment]
Closing this until we decide we are going to do 2FA via push.
