### ISSUE TITLE
Eliminate token.tokenId?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#1981]
Pre-#1950, token objects used to have an `id` property that was a hex string representation of their `tokenId` property, which was a `Buffer`. Post-#1950, `id` and `tokenId` are identical. Although it's essentially harmless, I predict this will cause a certain amount of head-scratching for future developers. Let's ditch `tokenId` and use `id` everywhere.

**Comment by seanmonstar** [comment]
I don't like stuttering in my code, like `token.tokenId`, so I'd prefer if we used `token.id` instead.

**Comment by philbooth** [comment]
> I don't like stuttering in my code, like `token.tokenId`, so I'd prefer if we used `token.id` instead.

Fwiw, that turns out to be a messier change because the property returned by the db is `tokenId`, so we have to map the array returned by `db.sessions` for example. How strong is your distaste for `token.tokenId`?

**Comment by seanmonstar** [comment]
I would strive very hard in any new project I made to not have stuttering. But I realize we have it all over here, and it's not really the hill I'd want to die on.
