### ISSUE TITLE
Receiving "Final Reminder: Complete Your Firefox Sync Setup" even though account is deleted

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#1997]
I created a test account last week that I thought I verified then deleted. I have received both verification reminder emails telling me to complete setup, but when I try to sign in, I am told the account is not found:

<img width="437" alt="screen shot 2017-07-18 at 10 31 41" src="https://user-images.githubusercontent.com/848085/28311244-ef17cce0-6ba6-11e7-9fe5-3a91212cad20.png">

<img width="403" alt="screen shot 2017-07-18 at 10 31 51" src="https://user-images.githubusercontent.com/848085/28311260-fb0d54d4-6ba6-11e7-88a8-c62ebe5e6345.png">

I have tried signing in on both prod and stage, neither work.

**Comment by vladikoff** [comment]
These are not our reminders, but marketing. I think fixing this https://github.com/mozilla/fxa-bugzilla-mirror/issues/263 should fix it.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-bugzilla-mirror/issues/263 is now fixed and this should be good now 👍
