### ISSUE TITLE
(node:48) DeprecationWarning: DeprecationWarning for mem.emailRecord: Use mem.accountRecord

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#1999]
Noticed in a dockerflow test run:
`(node:48) DeprecationWarning: DeprecationWarning for mem.emailRecord: Use mem.accountRecord`

**Comment by philbooth** [comment]
This is from a `util.deprecate` call that we added to the `emailRecord` methods in our own code, see:

* https://github.com/mozilla/fxa-auth-db-mysql/pull/254#discussion_r126609827
* https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/mem.js#L540-L546
* https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/mysql.js#L470-L472

The memory db contains other code that leans on `emailRecord` hence it shows when you run the tests. My understanding is that we're ripping out `emailRecord` soon so it will go away. In the meantime, I think it's harmless.

@vbudhram, what's the rough plan for deleting `db.emailRecord`?

**Comment by vbudhram** [comment]
Unfortunately, after fixing some [edge cases](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L492) for change email, I don't see this being depreciated as soon as I would like.

The TL;DR is that we need to use the original account email to generate the password hash when a user resets their password. Which is fine and dandy, until the user deletes the original account email (delete occurs on emails table). Then `db.accountRecord` function would return unknown account. 

There are a couple things I could see to resolve this

* Do away with email hashing of password on reset and hash with something else
* Soft delete the original email in the emails table. Note that currently, even after deletion, no user can create an account with that email.

In the meantime I can remove the deprecation warnings to reduce noise in logs.
