### ISSUE TITLE
Sign Success Metric Tanked on July 19th

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#2013]
(note that I intentionally left out the Y axis in all my screenshots, please visit link for numbers)

According to this chart our sign-in success rate has tanked by 30% on July 17th:

https://sql.telemetry.mozilla.org/queries/2078?p_start_date=2017-02-01#3815

![Screen Shot 2017-07-24 at 10.37.38 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577ea18f9a14e11300564d30/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456f76b7191a379ef0c2856415c46bc30254d58eeb9cb74fce36f34985619e8d4640970c76c10ffba8217ba03b8298b4f80b6bbdb1dc7fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be14454a31b3163e470336e0a.png)

**Comment by davismtl** [comment]
This might be a result of the new firstrun page being deployed. Signin is now default over registration.

The volume seems to have gone up despite the rate dropping.
![Screen Shot 2017-07-24 at 10.40.58 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577ea18f9a14e11300564d30/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456f76b7191a379ef0c2f51415a46bc30254d58eeb9cb74fce36f34985619e8d4640970c76c10ffba8217ba03b8298b4f80b6bbdb1dc7fa2137a5dad11b61435c52dcbd4f3fb29b4dc259f34be14454ac133065e67f356e0a.png)

**Comment by davismtl** [comment]
We also see the number of user engaging with the form going through the roof:
![Screen Shot 2017-07-24 at 10.44.02 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577ea18f9a14e11300564d30/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456f76b7191a379ef0c2f55415f4cbc30254d58eeb9cb74fce36f34985619e8d4640970c76c10ffba8217ba03b8298b4f80b6bbdb1dc7fa2137a5dad11b61435c52dcbd4f3fb29a4ac259f34be14454ac11316ae270336e0a.png)

https://sql.telemetry.mozilla.org/queries/2078?p_start_date=2017-02-01#12065

Next step is to understand how this is impacting (1) registrations and (2) the overall number of users setting up Sync on firstrun, regardless of if they did so via signin or signup.

**Comment by vladikoff** [comment]
Closing for now!
