### ISSUE TITLE
Eliminate redundant calls to getGeoData

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2015]
Arising from https://github.com/mozilla/fxa-auth-server/pull/1993#discussion_r128997049, I notice that we can eliminate some duplicate calls to `getGeoData`. Just inside `/account/login` it is called on three separate occasions, for instance.

We should tidy these up so that we're not doing more work on the server than we need to. We can also lean on the data stored in redis, if it's available. Maybe these properties should be made available on the `SessionToken` object so that people are less likely to duplicate the effort in the future.

**Comment by rfk** [comment]
> Maybe these properties should be made available on the SessionToken object
> so that people are less likely to duplicate the effort in the future

+1; let's do the lookup once and store it somewhere for future reference.  On the request object?  On the session?
