### ISSUE TITLE
Drop in signup delivery rate around July 20

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2029]
I noticed this in our graphs just now:

<img width="749" alt="capture" src="https://user-images.githubusercontent.com/34695/28814406-c94c3d4e-76e0-11e7-8cc6-e296235efb86.PNG">

It looks like a significant drop in our signup email delivery rate around July 20th.  I'm not sure what might be behind it yet, filing a bug for further investigation.

**Comment by rfk** [comment]
This is roughly the same time period as the change to the first-run flow that caused changes in many of our other metrics, but it appears to be slightly relayed relative to those other changes, so may not be related.  It seems to correspond to the release date of train-91.

**Comment by vbudhram** [comment]
Latest graph shows that this is increasing?

<img width="707" alt="screen shot 2017-08-03 at 3 11 14 pm" src="https://user-images.githubusercontent.com/1295288/28939137-430c71a2-785e-11e7-8ff8-e047a598cd66.png">

**Comment by vladikoff** [comment]
from mtg: @rfk to check the graph again

**Comment by rfk** [comment]
It looks to have returned to it's previous level, but the timing of this can't be a coincidence - the drop lines up very closely with deploy date for train-91, and the return to normal with the deploy date of train-92.  Was there anything in train-91 that could explain this drop?

**Comment by rfk** [comment]
Looks like it's recovered.  I don't like unexplained mysteries but I don't think we're going to have the bandwidth to investigate this to completion, so closing out the issue.
