### ISSUE TITLE
fxa-auth-server cannot load mysql data to mariaDB.

### ISSUE THREAD

**Issue by korosuke114** [mozilla/fxa-auth-server#2030]
Here is error
I was using mariadb 10.1 version.
But I changed mysql5.6.x. it was working well.

Does this schema import support to mariaDB database?

fxa@mx ~/fxa-auth-server $ npm run start-mysql

> fxa-auth-server@1.92.0 start-mysql /home/fxa/fxa-auth-server
> NODE_ENV=dev scripts/start-local-mysql.sh 2>&1

keys file already exists
README.md  index.js  node_modules  package.json  test
mail_helper started...
{"Timestamp":1501747614170000000,"Logger":"fxa-auth-db-server","Type":"bin.db_patcher.patch-error","Severity":2,"Pid":10504,"EnvVersion":"2.0","Fields":{"err":"Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ALGORITHM = INPLACE LOCK = NONE;\n\n-- But it's *not* safe to do the following in ' at line 8"}}

npm ERR! Linux 4.9.34-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start-mysql"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! fxa-auth-server@1.92.0 start-mysql: `NODE_ENV=dev scripts/start-local-mysql.sh 2>&1`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the fxa-auth-server@1.92.0 start-mysql script 'NODE_ENV=dev scripts/start-local-mysql.sh 2>&1'.
npm ERR! This is most likely a problem with the fxa-auth-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=dev scripts/start-local-mysql.sh 2>&1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fxa-auth-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fxa-auth-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fxa/fxa-auth-server/npm-debug.log

**Comment by shane-tomlinson** [comment]
> ALGORITHM = INPLACE LOCK = NONE

@jrgm says there should be a lock between `INPLACE` and `LOCK`

**Comment by korosuke114** [comment]
Thanks update.

Here is I checked ALGORITHM in schema.
There are many missing comma.

fxa@mx ~/fxa-auth-server/node_modules/fxa-auth-db-mysql/lib/db/schema $ grep ALGORITHM *
patch-022-023.sql:ALGORITHM = INPLACE, LOCK = NONE;
patch-022-023.sql:ALGORITHM = INPLACE, LOCK = NONE;
patch-028-029.sql:ALGORITHM = INPLACE, LOCK = NONE;
patch-029-028.sql:-- ALGORITHM = INPLACE, LOCK = NONE;
patch-035-036.sql:ALGORITHM = INPLACE, LOCK = NONE;
patch-035-036.sql:ALGORITHM = INPLACE LOCK = NONE;
patch-035-036.sql:ALGORITHM = INPLACE LOCK = NONE;
patch-035-036.sql:ALGORITHM = INPLACE LOCK = NONE;
patch-036-035.sql:-- ALGORITHM = INPLACE, LOCK = NONE;
patch-036-035.sql:-- ALGORITHM = INPLACE, LOCK = NONE;
patch-036-035.sql:-- ALGORITHM = INPLACE, LOCK = NONE;
patch-036-035.sql:-- ALGORITHM = INPLACE, LOCK = NONE;
patch-038-039.sql:ALGORITHM = INPLACE LOCK = NONE;
patch-038-039.sql:ALGORITHM = INPLACE, LOCK = NONE;
patch-039-038.sql:-- ALGORITHM = INPLACE, LOCK = NONE;
patch-039-038.sql:-- ALGORITHM = INPLACE, LOCK = NONE;
patch-042-043.sql:ALGORITHM = INPLACE LOCK = NONE;
patch-054-055.sql:ALGORITHM = INPLACE, LOCK = NONE;
patch-055-054.sql:--ALGORITHM = INPLACE, LOCK = NONE;
patch-058-059.sql:ALGORITHM = INPLACE, LOCK = NONE;
patch-059-058.sql:--ALGORITHM = INPLACE, LOCK = NONE;
patch-059-060.sql:ALGORITHM = INPLACE, LOCK = NONE;
patch-060-059.sql:--ALGORITHM = INPLACE, LOCK = NONE;

Thanks,

**Comment by korosuke114** [comment]
I got another syntax error as follow.

fxa@mx ~/fxa-auth-server $ npm run start-mysql

> fxa-auth-server@1.92.0 start-mysql /home/fxa/fxa-auth-server
> NODE_ENV=dev scripts/start-local-mysql.sh 2>&1

keys file already exists
README.md  index.js  node_modules  package.json  test
mail_helper started...
{"Timestamp":1501819104109000000,"Logger":"fxa-auth-db-server","Type":"bin.db_patcher.patch-error","Severity":2,"Pid":27334,"EnvVersion":"2.0","Fields":{"err":"Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LOCK = NONE;\n\nCREATE INDEX securityEvents_uid_ipAddrHmac_createdAt\nON securityE' at line 3"}}

npm ERR! Linux 4.9.34-gentoo
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start-mysql"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! fxa-auth-server@1.92.0 start-mysql: `NODE_ENV=dev scripts/start-local-mysql.sh 2>&1`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the fxa-auth-server@1.92.0 start-mysql script 'NODE_ENV=dev scripts/start-local-mysql.sh 2>&1'.
npm ERR! This is most likely a problem with the fxa-auth-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=dev scripts/start-local-mysql.sh 2>&1
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fxa-auth-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls fxa-auth-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fxa/fxa-auth-server/npm-debug.log

**Comment by korosuke114** [comment]
Hi 

I found one statement from mysql document.

The ALTER TABLE clause LOCK=NONE is not allowed if there are ON...CASCADE or ON...SET NULL constraints on the table. 

in patch patch-035-036.sql has following statement.

CREATE INDEX securityEvents_uid_tokenVerificationId
ON securityEvents(uid, tokenVerificationId)
ALGORITHM = INPLACE,LOCK = NONE;

CREATE INDEX securityEvents_uid_ipAddrHmac_createdAt
ON securityEvents(uid, ipAddrHmac, createdAt)
ALGORITHM = INPLACE, LOCK = NONE;

Does "Create index" with "ON" statement support "LOCK = NONE" statement?

I tried to change "LOCK = NONE" to "LOCK = DEFAULT" and "LOCK = SHARE". all of statement reject and syntax error.

however, I removed Algorithm statement. sql command successfuly.

Here is operation ouptut.

MariaDB [ffauth]> CREATE INDEX securityEvents_uid_tokenVerificationId ON securityEvents(uid, tokenVerificationId) ALGORITHM = INPLACE, LOCK = DEFAULT;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LOCK = DEFAULT' at line 1

MariaDB [ffauth]> CREATE INDEX securityEvents_uid_tokenVerificationId ON securityEvents(uid, tokenVerificationId) ALGORITHM = INPLACE, LOCK = SHARE;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LOCK = SHARE' at line 1

MariaDB [ffauth]> CREATE INDEX securityEvents_uid_tokenVerificationId ON securityEvents(uid, tokenVerificationId) ALGORITHM = INPLACE, LOCK = NONE;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' LOCK = NONE' at line 1

MariaDB [ffauth]> CREATE INDEX securityEvents_uid_tokenVerificationId ON securityEvents(uid, tokenVerificationId);

**Comment by vladikoff** [comment]
from mtg: 

> The ALTER TABLE clause LOCK=NONE is not allowed if there are ON...CASCADE or ON...SET NULL constraints on the table.

**Comment by rfk** [comment]
The `securityEvents` table does indeed have an `ON DELETE CASCADE` foreign key constraint:

  https://github.com/mozilla/fxa-auth-db-mysql/blob/master/lib/db/schema/patch-032-033.sql#L10

So I feel like these should not have worked for us in production either :-/

The simplest fix here may be to drop the `ON DELETE CASCADE` given that we don't really make use of foreign key constraints on any other tables in this database.  Assuming such a thing is possible in mysql that is.

**Comment by vbudhram** [comment]
from mtg: closing for now
