### ISSUE TITLE
Map flow/activity events to amplitude events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2043]
Structure:
https://amplitude.zendesk.com/hc/en-us/articles/204771828-HTTP-API

Nomenclature:
https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4/edit#gid=1500952660

See also:
mozilla/fxa-content-server#5346

**Comment by rfk** [comment]
(Adding some notes based on our conversation yesterday)

For the initial work here, we're going to just massage our existing event stream into the format required by amplitude's HTTP API, and lot it out to disk as a separate event.  This will help us shake out any issues with the event taxonomy, e.g. fields that we don't easily have the ability to provide.  A separate card will be opened for sending this event stream to amplitude via their HTTP API.
