### ISSUE TITLE
Remove the "verification reminders" feature

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2060]
In the backend catchup meeting today, we discussed the "verification reminders" feature and the fact that it's still disabled in production because it causes our DB replication to lag.  We've tried a few things to fix this but haven't found a solution that sticks.  We could continue trying, but it's not at all clear that this would be a valuable use of our time.

So....what if we just pull the plug on this feature and move on?  We can revisit it afresh if it winds up back at the top of our priority list.  @davismtl thoughts?

**Comment by vladikoff** [comment]
> We can revisit it afresh if it winds up back at the top of our priority list

@rfk I think we should just send the templates that Ryan designed to Marketing / Basket team so they can use them and send the reminders that way. I think they already send one reminder, maybe they just need to add one more.

**Comment by rfk** [comment]
IIUC, the one thing the marketing team *cant* do is include a working "verify now" link, because they don't have the verification code for the user's account.

**Comment by vladikoff** [comment]
@rfk yea, I guess they can just link to the sync marketing or login page

**Comment by philbooth** [comment]
Nominating this for triage later.

**Comment by philbooth** [comment]
Shut up wafflebot, no-one likes you.
