### ISSUE TITLE
Try to implement caching layer for `getsessioniddevice`

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#2063]
Seems like the query we can optimize that route with caching 

Depends on https://github.com/mozilla/fxa-auth-server/pull/2019

Dashboard: https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/Auth%20DB%20By%20Route

**Comment by vladikoff** [comment]
To discuss with @rfk

**Comment by rfk** [comment]
I like the sound of it, but we'll have to be careful about potentially writing auth secrets into redis.  We may be able to structure things in such a way that this is not required.

**Comment by vladikoff** [comment]
> I like the sound of it, but we'll have to be careful about potentially writing auth secrets into redis. We may be able to structure things in such a way that this is not required.

👍

**Comment by vbudhram** [comment]
from mtg: closing
