### ISSUE TITLE
Generate device ids on the client

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2072]
I've been digging in to our device registration code to get a feel for how it would look if we were to generate device ids client-side. Turns out, it works surprisingly well (unless I'm missing something). Opening this issue as a proposal and to record my thoughts.

## The problem

It's important that we have a reliable device id for metrics events so that Amplitude can use it to retroactively assign uids to events that don't yet have one. Right now, most of the events we emit do not have a device id for a number reasons:

* Perhaps a user drops out of the sign-up funnel prematurely, before we create a device record.
* Perhaps they signed in to a vanilla web session, for which device records are not created.
* Perhaps the event is emitted from an auth server endpoint that is not authenticated by session token, on which the device id is a property.

The third of these is not a problem because we know the uid by that point. The first two need addressing.

## Proposal: Generate device id on the client

This directly addresses the first reason above. A side-effect of implementation is that we can easily address the second reason. A double-bonus side-effect of implementation is that we can also use it as a step towards persistent device ids, if we like.

### What's involved

* In the content server, look for device id in local storage early-ish during app start. If it doesn't exist, create one.
* Add the device id as a property to all content server flow events.
* Send device id to the back-end when signing in/up.
* In the auth server, add an optional `deviceId` property to the payloads for `/account/create` and `/account/login`.
  * If the property isn't set, do nothing. Existing device registration may still kick in.
  * If it is set, after the session token is created, call `db.upsertDevice`.

### Optional extras

* In the db, stop destroying device records with session tokens.
* In Firefox, do some magic to persist fxa device ids if a user signs out of Sync then later signs back in.

### Why is this good?

When I started thinking all this through, I had messy thoughts about device id conflicts because they're only 16 bytes long. But they're per user rather than globally unique and treating conflicts as updates makes the problem go away.

Truthfully, I forgot we even had the `upsertDevice` stored procedure (probably why I made the mistake of destroying device records in the first place). But of course it's perfect for this, we can trust the content server (and, eventually, Sync) to sanely re-use device ids and then the behaviour automatically transforms to what it was always supposed to be. This was probably explained with great clarity in a feature doc once upon a time, but finally now I can actually see it.

Legacy device registration, including placeholder devices, continues to work.

And it also works really well with session token expiry. If a session token gets zombified (which we know does happen), a re-used device id stops being associated with it and it becomes eligible for expiry (because we only expire session tokens that don't have a device).

### What are the risks?

Being a boundless optimist, none have occurred to me yet. What am I missing?

**Comment by philbooth** [comment]
> * In the auth server, add an optional `deviceId` property to the payloads for `/account/create` and `/account/login`.

Also `deviceName`, `deviceType`, `pushCallback`, `pushPublicKey` and `pushAuthKey`. We could infer `deviceType` from the user agent if it's not set, but probably best to still give clients the option to set it explicitly if they want.

**Comment by philbooth** [comment]
Tangential ref: #1077

**Comment by rfk** [comment]
> What are the risks?

One risk is that this will look a lot like a tracking cookie, and it might let us e.g. determine that the same browser instance has been used by two independent Firefox Account holders.  We'll need to coordinate with the data stewards on an appropriate policy for managing these IDs.

**Comment by philbooth** [comment]
Good point. Presumably this was also an issue with the original spec for device registration too, or does the fact that it was only tracking Sync sessions rather than vanilla web sessions give that a free pass?

**Comment by philbooth** [comment]
In the meantime, I'll just crack on with using flow id as the Amplitude device id then we can update this if and when.

**Comment by rfk** [comment]
No free passes, this was always going to be an issue with device ids :-)

We don't have to worry about it currently because device ids are transient, and we might be able to start with a similar approach here until we work through the details - create the device-id on the client, but don't persist it into localStorage in a way that would enable long-term tracking.

**Comment by philbooth** [comment]
Just realised, another thing we'd have to be careful of is how this affects the devices/apps view in the content server. Things that used to be web sessions would now have device records, so we'd need to make sure we don't mess up the icons etc.

**Comment by rfk** [comment]
>  Things that used to be web sessions would now have device records,

Hmm, good point.  I guess we can't do this only for the case of `service=sync` because its part of the metrics for all reliers.

**Comment by rfk** [comment]
>  I guess we can't do this only for the case of service=sync because its part of the metrics for all reliers.

Thinking out loud here...are we making problems for ourselves by conflating the device-id for amplitude metrics with the device-id used for our own device API?  If we had the content-server generate a unique id and include it in the metricsContext bundle as "device id", would that help us get to a good place without running into some of the above concerns?

**Comment by philbooth** [comment]
>  If we had the content-server generate a unique id and include it in the metricsContext bundle as "device id", would that help us get to a good place without running into some of the above concerns?

Landed the metrics context change for this in #2069, which will be in train 95. So we can target train 96 for the content server portion of this.
