### ISSUE TITLE
Onboarding Emails Sending All at Once

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#2077]
Michelle Warther was testing the email first flow and she got the 3 following emails at the same time:
- [Confirm your email and start to sync!](https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#)
- Still there?
- [ Hello again.](https://docs.google.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit#heading=h.x1itmtyugkhd)

<img width="512" alt="screen_shot_2017-08-17_at_3 55 00_pm_1024" src="https://user-images.githubusercontent.com/19537086/29784865-70e32b68-8bda-11e7-82bd-cde0a7764f32.png">

Is our scheduling working? When should each one be sent out?

These seem to be related to email confirmation reminders.

**Comment by davismtl** [comment]
@ryanfeeley Do you know what the **Still there?** email template is? I can't seem to find it in our email template document.

**Comment by seanmonstar** [comment]
If this is in dev.lcip, the reminder emails are set to a much shorter timeout, again for testing purposes.

**Comment by davismtl** [comment]
That would make a lot of sense. 
@shane-tomlinson is the email first flow that's behind a feature flag still using dev.lcip?

**Comment by ryanfeeley** [comment]
@davismtl Yeah, I don't think the last two will send unless it's from dev.lcip domain. Production users won't see it.

I think we should still send these, but would need to coordinate with marketing as they are sending things like this too IIRC.

**Comment by davismtl** [comment]
>  I don't think the last two will send unless it's from dev.lcip domain. Production users won't see it.

Aren't we planning to put verification reminders in productions? What are the delays for those before sending?

> I think we should still send these, but would need to coordinate with marketing as they are sending things like this too IIRC.

2/3 that I linked to above are reminders to confirm your email. Marketing won't send those. They get you to connect another device.

@ryanfeeley where can I see the content of the *Still there?* email? (even if it is not in prod)

**Comment by ryanfeeley** [comment]
@davismtl Sure! They are here: https://github.com/mozilla/fxa-auth-server/search?utf8=%E2%9C%93&q=still+there&type=

But more readable in our FxA Transactional Emails Google Doc (which I should probably be posting publicly).

**Comment by rfk** [comment]
> Aren't we planning to put verification reminders in productions? 

It's complicated: https://github.com/mozilla/fxa-auth-server/issues/2060
