### ISSUE TITLE
Doing (change email -> change pwd -> change email) bricks my password

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2080]
STR:

* Create an account and sign in to sync, call this "email1"
* Go through "manage account" and add a secondary email address, call this "email2"
* Make "email2" the primary account address
* Change your account password
* Disconnect from sync
* Reconnect to sync using "email2" and new password
* Go through "manage account" and switch "email1" back to being primary
* Disconnect from sync
* Attempt to reconnect to sync

Expected results:

* I should be able to log in to sync using the "email1" and the new password

Actual results:

* Login attempts with "email1" fail with "incorrect password", using both old and new passwords.
* Login attempts with "email2" tell me I have to login with the primary email
* I have to reset my password to get back into my account

**Comment by vbudhram** [comment]
This was fixed with https://github.com/mozilla/fxa-content-server/pull/5486 and https://github.com/mozilla/fxa-js-client/pull/258.
