### ISSUE TITLE
Implement a long-term solution for Amplitude device ids

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2081]
Currently they're stored in memcached as part of the metrics context, which expires after 2 hours. Ultimately we need them to be persistent, not just beyond the expiry period but across sessions too. This would need approval from data stewards, but it may look like the content server keeping them in local storage and included in more requests or it could just be an old-fashioned cookie that is associated with every request.

**Comment by philbooth** [comment]
Moving this to the `blocked` column until we have approval to persist the device id.

**Comment by vladikoff** [comment]
from mtg: this is okay for now
