### ISSUE TITLE
Allow device connected/disconnected push messages for iOS >= 9.0

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2083]
Newer versions of Firefox for iOS support these additional push messages, so we'll need to tweak out UA-sniffing to to allow them to be sent.

**Comment by shane-tomlinson** [comment]
@rfk - what's the priority on this?

**Comment by rfk** [comment]
Let's aim to have this ready for train-96, although I'm going to have a quick stab at it and if it's super simple it might make 95.
