### ISSUE TITLE
Dont notify the originating device about profile change.

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2084]
When changing an email address, we don't need to send a push notification to the device on which the change was performed.  It will get notified via webchannel from the content page.  Similar to https://github.com/mozilla/fxa-auth-server/pull/1931, requested in https://bugzilla.mozilla.org/show_bug.cgi?id=1368147#c13

**Comment by grigoryk** [comment]
Unrelated directly, but I noticed that changing a display name does not trigger a push notifications at all, regardless of the originating device. Is that intentional? It didn't seem quite right to me.

**Comment by rfk** [comment]
> Is that intentional?

Not intentional.  What's supposed to happen is:

* Profile server puts a message in SQS queue when profile data changes: https://github.com/mozilla/fxa-profile-server/blob/master/lib/routes/display_name/post.js#L41
* Auth server pulls messages off the queue: https://github.com/mozilla/fxa-auth-server/blob/master/bin/profile_server_messaging.js#L28
* Auth server converts them into push messages to connected devices: https://github.com/mozilla/fxa-auth-server/blob/master/lib/profile/updates.js#L14

It's possible some link in that chain is not working correctly in production.

Also, this made me realize that we won't be able to de-dupe profile change events that come in over this queue, since we won't know the originating device id.

**Comment by shane-tomlinson** [comment]
Ref #2085

**Comment by vladikoff** [comment]
cc @vbudhram to follow up

**Comment by grigoryk** [comment]
I'm observing that push messages do not always show up as a result of a profile change. Usually a first few profile modifications trigger a push, but if I perform the modification more than a few times, the subsequent ones do not.

It really feels like pushes are being throttled, either on GCM or Autopush sides. After waiting for a bit (a minute or two?), push messages start flowing again, and follow the pattern above.

**Comment by grigoryk** [comment]
Note that the above happens regardless of which device is originating a push.

**Comment by grigoryk** [comment]
More importantly: this behaviour is currently causing an intermittent "crash after changing primary email" on fennec beta. A push and a webchannel messages are racing to fetch a profile and to change the email locally if necessary; if results of the fetch overlap with local operations in a bad way, the looser of the race crashes the app.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1401318#c19 for an example.

A client fix is necessary for this regardless (this race can be triggered via other means, in theory), but fixing this bug would help clients quite a bit.

**Comment by rfk** [comment]
> I'm observing that push messages do not always show up as a result of a profile change.
> Usually a first few profile modifications trigger a push, but if I perform the modification more
> than a few times, the subsequent ones do not.
> It really feels like pushes are being throttled, either on GCM or Autopush sides.

I can't find anything definitive on the internets, but there's a lot of stuff suggesting some vague throttling behaviour in GCM, such as:

  https://stuff.mit.edu/afs/sipb/project/android/docs/google/gcm/adv.html#throttling

@bbangert does this sort of throttling behaviour sound familiar?

**Comment by bbangert** [comment]
@rfk I would assume its on the GCM side, as we don't have any throttling in autopush yet. ;)

I've asked @jrconlin if he's aware of anything on the GCM side. We might have some visibility into GCM error codes, in that we'd return a different status if GCM rejects it afaik. We have seen GCM have random delays or drop messages before.

**Comment by jrconlin** [comment]
If GCM rejects the message, we report it either as a 410 (GCM recipient is gone) or a 503 (GCM requests retry). Those are the only two errors that we know about.

Mind you, GCM, like Push, is a "best effort" delivery system, and it's certainly possible that some messages may get dropped for unknown reasons.

**Comment by vladikoff** [comment]
from mtg: closing for now, until we see issues with this. 🗡
