### ISSUE TITLE
Changing display name does not trigger a push notification in prod

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2085]
In https://github.com/mozilla/fxa-auth-server/issues/2084#issuecomment-326171405 @grigoryk noted that changing your display name doesn't seem to send a "profile updated" push message in production.  I wonder if the SQS pipeline from fxa-profile-server to fxa-auth-server is not quite working correctly?

**Comment by shane-tomlinson** [comment]
@jrgm going to check the SQS pipeline today.

**Comment by jrgm** [comment]
So, this wasn't configured on the auth-server side. That can be done now in https://github.com/mozilla-services/cloudops-deployment/compare/fxa-auth-profile-update-queue?expand=1

However, in stage, all attempts to `handleProfileUpdated` fail with error `TypeError: Request path contains unescaped characters` with no further details on the stack trace. So need to fix that first.

**Comment by rfk** [comment]
> TypeError: Request path contains unescaped characters

The `handleProfileUpdated` code is decoding the uid into a buffer, but the rest of the code expects it to be a hex string.  So we put the raw buffer into the URL when we make a request to fxa-auth-db-mysql and generate this error.  PR incoming.

**Comment by vladikoff** [comment]
should be fixed in train-95

**Comment by vladikoff** [comment]
will add note to deploy doc
