### ISSUE TITLE
Include email address in Manage Account links

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#2093]
We currently include a Manage Account button in some of our emails and include the following parameters:
* utm_source=email
* utm_medium=email
* utm_campaign=fx-account-email-verified
* utm_content=fx-manage-account

We should also include the current email address so that the user definitely logs into the right account:
* email=user%40example.com

**Comment by shane-tomlinson** [comment]
Firefox opens the /settings page with both `email` and `uid` for some extra protection against account deletion/recreation edge cases.

**Comment by ryanfeeley** [comment]
@shane-tomlinson Oops, forgot to attach screenshot. I don't see it in our new Secondary Email Added email.
<img width="923" alt="screenshot 2017-09-07 11 58 58" src="https://user-images.githubusercontent.com/68213/30172897-0f11c362-93c4-11e7-8834-bb9343a93c05.png">

**Comment by ryanfeeley** [comment]
@vbudhram @shane-tomlinson I still see a lot of **Manage account** buttons in our email that lack the email parameter.
