### ISSUE TITLE
Implement the email_version property on fxa_email amplitude events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2097]
Spinning this out from #2076 as a dedicated issue because it requires a bit of jiggery-pokery.

The [taxonomy](https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4) defines `email_version` in `event_properties` on the `fxa_email` amplitude events. Presumably the intention is to track the effect of any changes we make to the email templates.

Afaik this is something that we need to add, ideally as a value that increments itself automatically so that we don't forget to update it ourselves (which will definitely happen otherwise). Maybe with a little pre-commit hook that updates a js file containing nothing but template versions.

**Comment by vladikoff** [comment]
@philbooth train-97? cc @rfk
