### ISSUE TITLE
500 Server Error when resending code for an address I don't control

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2100]
STR:

* Login to FxA
* Make an authenticated POST to  `/recovery_email/resend_code` and specify an email's not on your account

Expected result:

* A 400-level error telling me I used an invalid email address

Actual result:

* A `500 Server Error`

Test script I was using:

```
>>> import fxa
>>> c = fxa.core.Client("https://nightly-auth.dev.lcip.org")
>>> s = c.create_account("ryans-new-account@rfk.id.au", "testpassword")
>>> s.apiclient.post("/recovery_email/resend_code", json={"email": "rfkelly@mozilla.com"}, auth=s._auth)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rfk/repos/mozilla/identity/PyFxA/fxa/_utils.py", line 300, in post
    return self.request("POST", url, json, **kwds)
  File "/home/rfk/repos/mozilla/identity/PyFxA/fxa/_utils.py", line 288, in request
    raise fxa.errors.ServerError(body)
fxa.errors.ServerError: An internal server error occurred
```

**Comment by vladikoff** [comment]
from mtg: seems like sending to `undefined`

**Comment by rfk** [comment]
Specifically, I think the problem is that if the `emailData.some()` call here fails to find any matches:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/emails.js#L220

Then we proceed using the default value of `emails = []`.  We should instead error out with some sort of 400-level error.
