### ISSUE TITLE
Implement the fxa_services_used user property on amplitude events

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2104]
Spinning this out from #2076 as a dedicated issue because it requires jiggery-pokery.

The [taxonomy](https://docs.google.com/spreadsheets/d/1G_8OJGOxeWXdGJ1Ugmykk33Zsl-qAQL05CONSeD4Uz4) defines `fxa_services_used` in `user_properties`. Although we know which service is associated with the current session, knowing all services that a user is signed in to is trickier. Maybe there is an easy lookup we can do in `fxa-oauth-server` or maybe we need to start storing them somewhere.

**Comment by rfk** [comment]
One option here is to send updates using the magic `$append` operator described in [1].  With each login event, send over a ` "$append": {"fxa_services_used": "service-name"}` as part of the user properties.  This means we don't have to materialize the full list of all services the user has used.  It also risks putting some duplicates in the list on the amplitude side, but they've told me that's OK and we can basically just treat the `fxa_services_used` as a set in the amplitude UI.

One other wrinkle: the auth-server only knows the hex client-id, not the human-readable name for each service.  We might need to map the common ones into human-readable names before shipping them off to amplitude.

[1] https://amplitude.zendesk.com/hc/en-us/articles/205406617-Identify-API-Modify-User-Properties

**Comment by vladikoff** [comment]
@philbooth train-97? cc @rfk
