### ISSUE TITLE
subscription notices not sent to fake-basket-server in local dev

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2112]
Ref https://github.com/mozilla/fxa-content-server/issues/5433.

While running the content-server functional tests locally, users are not being subscribed to basket if they click the "opt in" checkbox on signup. I instrumented the fake-basket-server to debug why and saw the subscribe endpoint is never called.

Now that the auth-server notifies the basket server about email opt-ins, we have a problem - the fake-basket server never receives the subscription notification. We don't run a local message queue.

**Comment by vladikoff** [comment]
I'm tracking this in https://github.com/mozilla/fxa-content-server/issues/5433 

This is almost working. Actually this server sends stuff now, we just need to pick it up
