### ISSUE TITLE
precommit hook is not working for everyone

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2128]
I've noticed that some people's commits are landing without running the precommit hook, mine included. I've also noticed that for some other people, the precommit hook is still working okay.

Initially I thought it was a problem with the `grunt-newer` stuff introduced in #2056. For instance, I noticed that the dependencies listed in `grunttasks/doc.js` are incomplete:

```
diff --git a/grunttasks/doc.js b/grunttasks/doc.js
index f92fb23c..e514eb4a 100644
--- a/grunttasks/doc.js
+++ b/grunttasks/doc.js
@@ -19,8 +19,11 @@ module.exports = function (grunt) {
     api: {
       // have a src and dest set allows grunt-newer to work
       src: [
+        'lib/devices.js',
         'lib/error.js',
+        'lib/features.js',
+        'lib/metrics/context.js',
         'lib/routes'
       ],
       dest: 'docs/api.md'
     }
```

However, fixing that made no difference. Then I tried ditching `grunt-newer` entirely and reverted to running `scripts/write-api-docs.js` directly. But still no luck.

So I think something might be wrong with `husky` on my machine. I nuked `node_modules` and reinstalled everything, on the off-chance that would fix it. It didn't.

People for whom the pre-commit hook definitely appears to be working:

* Shane
* Ryan

People for whom the pre-commit hook definitely appears not to be working:

* Me
* Edouard

People for whom the state of the pre-commit hook is undetermined:

* Vlad
* Vijay

**Comment by vbudhram** [comment]
After careful consider, Vijay switches to state pre-commit hook is definitely working.

Ref: https://github.com/mozilla/fxa-auth-server/pull/2129/commits/02e408a2c0e1a2f9c3cb1bfa8487630a398227cb

**Comment by vladikoff** [comment]
@eoger did you disable pre-commit hooks by default? I think we talked about it a bit

**Comment by eoger** [comment]
I use nvm without a default version, so I wonder if in some cases I may have opened a new terminal to commit.

**Comment by philbooth** [comment]
Related?

https://github.com/mozilla/fxa-auth-server/pull/2238#discussion_r153826932

**Comment by TDA** [comment]
@philbooth Might be completely useless info, but I have run into this outside of fxa when we had some git multiplexing (calling multiple scripts). If you guys have multiplexers set up locally, that might affect all your git hooks.
