### ISSUE TITLE
Amplitude email events are missing critical properties

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2133]
When testing [fxa-amplitude-send](https://github.com/mozilla/fxa-amplitude-send) using real data from FxA stage, I noticed that many (all?) email events are missing `uid` and `device_id`, causing them to be skipped as malformed events.

This is something I've seen locally too but mistakenly thought to be an artifact of the local dev environment. They need to be fixed.

**Comment by philbooth** [comment]
The events that are missing data are from delivery and bounce notifications, the infrastructure for which I'm deeply unfamiliar with. Testing locally I don't even seem to hit the relevant handlers, which is why I assumed this to be a local dev problem.

Eyeballing the code, all of the data we want is expected to be available on `message.headers`. If the data is not there for some reason, or is in a different format to what we expect, the behaviour would match what's described here.

@vbudhram, I think you were involved in writing these modules, do we have a reliable way to test that they're working? Especially with regards to the headers being passed to bounce/delivery notifications?

Also, I tried to find the relevant docs from AWS but failed. Are you able to point me in the right direction?

**Comment by philbooth** [comment]
> Also, I tried to find the relevant docs from AWS but failed.

Correction, I found [this](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html) but the notification objects seem to bear no relation to what our code expects vis à vis headers.

[Example bounce notification](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#bounce-object):

```json
{
   "bounceType":"Permanent",
   "bounceSubType": "General",
   "bouncedRecipients":[
      {
         "status":"5.0.0",
         "action":"failed",
         "diagnosticCode":"smtp; 550 user unknown",
         "emailAddress":"recipient1@example.com"
      },
      {
         "status":"4.0.0",
         "action":"delayed",
         "emailAddress":"recipient2@example.com"
      }
   ],
   "reportingMTA": "example.com",
   "timestamp":"2012-05-25T14:59:38.605Z",
   "feedbackId":"000001378603176d-5a4b5ad9-6f30-4198-a8c3-b1eb0c270a1d-000000",
   "remoteMtaIp":"127.0.2.0"
}
```

[Example delivery notificaation](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#delivery-object):

```json
{
   "timestamp":"2014-05-28T22:41:01.184Z",
   "processingTimeMillis":546,
   "recipients":["success@simulator.amazonses.com"],
   "smtpResponse":"250 ok:  Message 64111812 accepted",
   "reportingMTA":"a8-70.smtp-out.amazonses.com",
   "remoteMtaIp":"127.0.2.0"
}
```

Do we even know for sure that we are supposed to receive the headers when we get these notifications?

Without data from the headers, the flow and amplitude events that we emit here are useless. We'd need a different mechanism for accessing those properties (redis?).

**Comment by vbudhram** [comment]
@philbooth turns out that not all emails set `uid` and `device_id` properties, ref: [1](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/password.js#L277), [2](https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L271). Some definitely, do though. I can't recall the logic or reasoning on why those values would or wouldn't be included in the mail options.

If we do include them, AWS *should* propagate them with delivery bounce notifications. I'll put up a sample PR for consideration.

**Comment by philbooth** [comment]
> turns out that not all emails set `uid` and `device_id` properties

I don't think that is the issue. Only one of `uid` or `device_id` needs to be set for Amplitude to be happy. In both your links, `uid` is set. `device_id` need only be set where we have it, which is when there is a metrics context

The problem I see in the stage logs is broader than that though. For instance, none of these events have a `flow_id` either, which is also evident in redash. Here's a [graph of email events with no `flow_id`](https://sql.telemetry.mozilla.org/queries/41382/source#111444):

![screen shot 2017-09-23 at 09 17 00](https://user-images.githubusercontent.com/64367/30771461-38202aa4-a040-11e7-9c6c-f4dace383759.png)

The big jump for `sent` coincides with train 95 and was introduced by my Amplitude changes. I have a fix for that one incoming, but this issue is more concerned with the `bounced` and `delivered` events. Perhaps the extra logging added in #2135 will shed some light on it.

**Comment by philbooth** [comment]
The big jump for `sent` coincides with train 95 and was introduced by my Amplitude changes. I have a fix for that one incoming...

#2139

**Comment by rfk** [comment]
> Do we even know for sure that we are supposed to receive the headers when we get these notifications?

We're definitely supposed to, but it's a special thing you have to opt-in to by following instructions here:

  http://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-sns-notifications.html

So it's possible that stage has not been opted in to receiving the headers.  If the opt-in is set up properly then they're supposed to come back in the `headers` property of the `mail` object in the messge:

  http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#mail-object

**Comment by philbooth** [comment]
Pushing this back to `next` while we wait for the logging from #2135 to show up (or not).

**Comment by vbudhram** [comment]
> I'll put up a sample PR for consideration.

That was a terrible fail. But @rfk is correct, there is an AWS configuration to have SES propagate email headers, https://aws.amazon.com/blogs/ses/amazon-ses-now-includes-original-message-headers-in-notifications/.

I was under the impression that it was enabled in stage since @jbuck and I tested headers there before pushing to production, is that still correct?

**Comment by jbuck** [comment]
Yeah, I just checked and we have headers enabled in stage

**Comment by vbudhram** [comment]
> The problem I see in the stage logs is broader than that though. For instance, none of these events have a flow_id either, which is also evident in redash.

Here is an updated [query](https://sql.telemetry.mozilla.org/queries/44505/source) that shows the templates that don't have flow_ids. The `postVerifyEmail, verifySecondaryEmail` templates makes some sense because the `/verify_code` endpoint doesn't accept `metricsContext` (maybe it should?). I am curious why `verifyLoginEmail, verifySync` are so high. Could it be that some users are not going through content-server to get generated flow_id, and just using the apis?

![screen shot 2017-09-28 at 11 21 38 am](https://user-images.githubusercontent.com/1295288/30975112-6761c496-a43f-11e7-85aa-747e59dc93c6.png)

**Comment by philbooth** [comment]
Just recording that train 96 fixed my train 95 faux pas as hoped:

<img width="407" alt="Screen shot of a chart showing the number of email events without a flow id returning to historical levels" src="https://user-images.githubusercontent.com/64367/31224600-8498197a-a9c6-11e7-85e2-a2d1af6d6980.png" />

**Comment by philbooth** [comment]
Hmmm, and nothing from #2155 showing up in Kibana yet either.

**Comment by philbooth** [comment]
> Hmmm, and nothing from #2155 showing up in Kibana yet either.

* https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/PROD%20-%20Auth%20email%20headers%20missing%20uid%20and%20deviceId%20(bounced,%20delivered)
* https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/PROD%20-%20Auth%20email%20headers%20missing%20uid%20and%20deviceId

**Comment by philbooth** [comment]
I rather suspect I've fundamentally misunderstood the problem here.

After drawing blanks in Kibana, I went back to the stage logs that caused me to open this issue in the first place. All of the problematic events there are `fxa_email - sent`, which are mentioned earlier on in this thread and were fixed in mozilla/fxa-auth-server#2139. Foolishly I assumed something similar was wrong with the bounce events, but there's really no evidence for that.

Where I do have evidence for a problem with the bounce events is the absence of them in Amplitude. However, that doesn't necessarily mean they're not showing up because of missing properties. Maybe something else is wrong in that event pipeline. Digging into it now.

**Comment by philbooth** [comment]
I have a theory!

The bounce events are logged with a different logger to the other Amplitude events, initialised in `bin/email_notifications`. So the `fxa_email - bounced` events won't automatically show up alongside their peers from the rest of the auth server, unless we're explicitly looking for them in bouncer logs.

@jbuck, are we processing the bouncer logs for Amplitude events?

**Comment by jbuck** [comment]
Nice catch, we are not. I'll setup the Kinesis streams for the bouncer to point at the Amplitude function as well

**Comment by jbuck** [comment]
Nice catch, we are not. I'll setup the Kinesis streams for the bouncer to point at the Amplitude function as well

**Comment by rfk** [comment]
boom! nice catch @philbooth 👍

**Comment by vladikoff** [comment]
from mtg: @jbuck to press some AWS buttons to fix it...

**Comment by rfk** [comment]
>  I'll setup the Kinesis streams for the bouncer to point at the Amplitude function as well

This bug's been quiet for a while, @jbuck @philbooth can we confirm whether this was done and resolved the issue?

**Comment by philbooth** [comment]
I had a look in Amplitude for these on Friday as it happens, and couldn't see any bounce events showing up. I'm assuming it's not done yet?

**Comment by vladikoff** [comment]
from mtg: @jbuck to press the AWS buttons...

**Comment by vladikoff** [comment]
from mtg: @jbuck tried to get this working in `stage`, to press more AWS buttons in prod...

**Comment by vladikoff** [comment]
from mtg: @jbuck ping

**Comment by vladikoff** [comment]
from mtg: wasn't working in stage, but might work in prod... still looking at it

**Comment by rfk** [comment]
from mtg: let's include this in 104 deploy doc

**Comment by vladikoff** [comment]
from mtg: moving to train-107

**Comment by rfk** [comment]
from mtg: @jbuck what's the latest on this one, ahead of planning meeting on Monday?

**Comment by davismtl** [comment]
per triage meeting, I confirm that this is still very important. It prevents us from adding email to any funnel analysis.

**Comment by vladikoff** [comment]
from mtg: "we can always unship it", try it in prod?

**Comment by jbuck** [comment]
This is shipped to production ✨

**Comment by vladikoff** [comment]
@jbuck HERO!

**Comment by philbooth** [comment]
Look at all those lovely events!

https://analytics.amplitude.com/org/31251/chart/o88ulmz
