### ISSUE TITLE
isLastAccessTimeEnabledForUser() should disable reads as well as writes

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2142]
We have a feature-flag `isLastAccessTimeEnabledForUser()` that's used to pref on/off the tracking of "last acitve" timestamps in redis.  However, it only controls the writing of those timestamps, so if you pref it on and then off again you can end up reading stale data:

* We pref `isLastAccessTimeEnabledForUser()` for some subset of users
* Time passes, those users sync, and their last-access timestamps are updated in redis
* We pref off `isLastAccessTimeEnabledForUser()` for some operational reasons
* Those users no longer get their last-access timestamps updated in redis, but the old values stick around untouched
* When those users go to their "devices and apps" view on the web, we read the old stale last-access timestamps out of redis and display times that are wildly out of date

I suspect this is what's causing https://bugzilla.mozilla.org/show_bug.cgi?id=1403275 and similar.  @jrgm did we pref this on and back off again at some point?

One solution here is to have the `isLastAccessTimeEnabledForUser()` also pref off the reading of these timestamps from redis, so that we don't read stale data.

Another solution would be to just purge the current contents of redis, but I don't know what other effects that might have.

**Comment by jrgm** [comment]
Ugh. Yes. Not so much by whether `lastAccessTimeUpdates.enabled` and `lastAccessTimeUpdates.sampleRate` changed, than by `redis.enabled` being toggled.

**Comment by rfk** [comment]
Is it possible to just flush the stale data is redis, or is there other stuff in there we don't want to lose?

**Comment by jrgm** [comment]
It's probably cleanest to pref off, and then with no one using the cache, do FLUSHALL. 

But I was looking at the redis in stage (generated by tests running), and I'm not quite understanding the model. Sometimes it and Object (possibly empty `{}`) with subobjects keyed by tokenId, and sometimes it's an Array (possibly `[]`) with items in the list being objects with a tokenId key in them.

**Comment by rfk** [comment]
The lists may be left over from when https://bugzilla.mozilla.org/show_bug.cgi?id=1385192 was in stage, but I don't think it hit production..?

**Comment by jrgm** [comment]
Okay.
1) updated prod to run with LASTACCESSTIME_UPDATES_ENABLED=false, LASTACCESSTIME_UPDATES_SAMPLE_RATE=0, USE_REDIS=false
2) scaled down previous prod to zero
3) ran flushall to remove everything from redis
4) scaled previous prod back up and switched traffic back to it

So, now running with LASTACCESSTIME_UPDATES_ENABLED=true, LASTACCESSTIME_UPDATES_SAMPLE_RATE=0.3, USE_REDIS=true from a cleaned out cache.

**Comment by jrgm** [comment]
Also, stage, before the above, was FLUSHALL'd, and the JSON data structures are all object-based now.

**Comment by jrgm** [comment]
Micro-note: the comment at https://github.com/mozilla/fxa-auth-server/blob/master/lib/db.js#L540 referring to `array` is a leftover from the first impl.

**Comment by rfk** [comment]
Thanks @jrgm!

@mhammond reports that he's still seeing wildly out-of-date "last sync" timestamps, so perhaps this was not the whole story.  Perhaps we're also reading stale data from the db?
