### ISSUE TITLE
[Sentry] Are we handling AWS 454 Temporary service failure errors?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#2146]
See ref: https://sentry.prod.mozaws.net/operations/auth-prod/issues/652296/events/12289066/

cc @jrgm

**Comment by jrgm** [comment]
Formerly it used postfix to relay, and queue and retry, mail

**Comment by vladikoff** [comment]
Closing this for now to focus on other email related issues
