### ISSUE TITLE
User should receive an email when primary email changed

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2153]
From feature doc https://docs.google.com/document/d/1SaJEOGi2GEd69-Rype480Syl7DPdCSFSfRxmS7oKUrE/edit?ts=59d462e3

* User should receive a notification to the new primary email address that this is the new primary email address

**Comment by vbudhram** [comment]
@davismtl @rfk should this email be sent to all secondary emails as well?

**Comment by davismtl** [comment]
I would be in favor of sending this email to both addresses so long as the secondary was not previously bouncing (when it was the primary).

**Comment by rfk** [comment]
> I am in favor of sending to all since it is a notification type of email.

+1
