### ISSUE TITLE
Push verification message not sent to iOS?

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-auth-server#2156]
It looks like the FxA server will block verification messages sent to iOS

https://github.com/mozilla/fxa-auth-server/blob/9f6c153995f3569c495b47ced124634623b593ff/lib/push.js#L186-L198
`command` will be undefined since a verification message has no payload, which results in us dropping the message.

Ping @jhugman

**Comment by rfk** [comment]
What's the desired behaviour, that we send them to version 10.0 and above?

**Comment by philbooth** [comment]
@eoger ^

**Comment by philbooth** [comment]
Tangentially related, but I notice there is a curious mix of falsey values for `command` in this function. `null`, `undefined` and `false` are all knocking about, as can be seen in the following dashboard:

https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/FxA%20Auth%20unsupported%20push%20devices

Can all three be treated as equivalent for the purposes of this change, or is there some difference between them?

**Comment by jhugman** [comment]
I think the iOS client is in a position to receive them, but it's difficult
to test for them.

**Comment by rfk** [comment]
@jhugman what do we need to do to make it easier to test for them?  Would something like:

* Enable the messages for iOS 10.0
* Allow the `/account/devices/notify` endpoint to trigger empty-payload push messages in production so you can trigger them for testing

be helpful here?

**Comment by jhugman** [comment]
>
> Would something like:
>
>    - Enable the messages for iOS 10.0
>
>
>    - Allow the /account/devices/notify endpoint to trigger empty-payload
>    push messages in production so you can trigger them for testing
>
> be helpful here?

Yes please to both of these.

**Comment by rfk** [comment]
> Allow the /account/devices/notify endpoint to trigger empty-payload push messages in production

@vbudhram do we still have the PR that we used to enable this in a dev environment?  I had a bit of a look but couldn't find it.

**Comment by vbudhram** [comment]
@rfk This was the PR, https://github.com/mozilla/fxa-auth-server/pull/2050. However, it is fairly outdated. 

Updated PR inbound.

**Comment by rfk** [comment]
This is in production now
