### ISSUE TITLE
Add a timestamp to the "primaryEmailChanged" notification

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2160]
Since SQS doesn't guarantee ordering of messages by default, we need some way for our reliers to detect potential stale messages.  As discussed in [1], [2] the simplest thing we can do here is include a timestamp in the message body.  Using a timestamp is not ideal, e.g. it leaves the potential for races if we have events going out in quick succession.  But it's simple and it'll do the job on the timescales of events we care about for now.

In practice, this would mean we just add a "ts" field or similar into our outgoing SQS messages, giving the current time in seconds since epoch.  @vbudhram thoughts?

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1384385#c9
[2] https://github.com/mozilla/addons-server/issues/6451#issuecomment-335099369

**Comment by vbudhram** [comment]
I am in favor of adding the `ts` property to SQS messages. It seems the most straightforward and will probably cover the majority of cases. Is this property something we would want to add in general to all messages? I can see a similar issue with a user's display name or avatar. Granted those are not as critical as an email.

In the SQS docs they do claim to [support ordering](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html). Although, there seems to be a decent amount of configuration needed and several message processing limits.

**Comment by pmac** [comment]
Would be good to either use milliseconds since epoch or make the number a float and include the milliseconds that way. I fear we'd get some duplicate timestamps otherwise.

**Comment by rfk** [comment]
> Is this property something we would want to add in general to all messages?

I don't see any harm in adding it everywhere.

> Would be good to either use milliseconds since epoch or make the number a float
> and include the milliseconds

+1 to making it a float; "integer milliseconds" seems to be a javascript thing so having it be in seconds but at a higher precision seems like the path that's least likely to cause confusion in downstream reliers.
