### ISSUE TITLE
Use Firefox 57 logo in emails starting on 2017-11-14

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2185]
Ref mozilla/fxa-content-server#5603

Starting on 2017-11-14, we should start sending emails with the new Firefox logo.

cc @ryanfeeley

**Comment by shane-tomlinson** [comment]
@ryanfeeley, @jbuck - Do you know if the new logo is on [image.e.mozilla.org](https://github.com/mozilla/fxa-auth-server/blob/b55bfb0eaa73d61a1d3730b9c2f358774b105f5b/lib/senders/templates/verify.html#L15) already?

**Comment by ryanfeeley** [comment]
I don't.

**Comment by vbudhram** [comment]
New logo! https://image.e.mozilla.org/lib/fe9915707361037e75/m/3/firefox57-logo.png

**Comment by vbudhram** [comment]
This was closed in https://github.com/mozilla/fxa-auth-server/pull/2190
