### ISSUE TITLE
Add a manage devices button for new sign-in email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#2197]
I think it's useful to include the manage devices button (that should use the email parameter to ensure it only opens the intended user). See attached.

![manage-devices](https://user-images.githubusercontent.com/68213/32297352-4c50f0cc-bf25-11e7-82f7-fb6693b18c07.png)

Related: https://github.com/mozilla/fxa-auth-server/issues/2093

**Comment by ArkadiyVoronov** [comment]
Hi!
In "\fxa-auth-server\lib\senders\templates\new_device_login.html" I copy and past button from "post_verify.html"
![screenshot_1](https://user-images.githubusercontent.com/31352672/36934084-785f4ea8-1f05-11e8-9591-84f9d8b9b8ac.jpg)

**Comment by vladikoff** [comment]
@ArkadiyVoronov  good start, we might have a manage device button in other emails already. Send a pull request with your changes

**Comment by pluto5004** [comment]
Hi... Shall I take this as part of Outreachy contribution. Is it still open?

**Comment by ArkadiyVoronov** [comment]
Hi! I'm still working on it. Also as part of Outreachy contribution.
I'm a little stuck, but I will today\tomorrow for sure.

**Comment by DGRamya** [comment]
@vladikoff The Pull request for this issue is not accepted, is this issue still open for solving?

**Comment by vladikoff** [comment]
@DGRamya Feel free to send a pull request for this! we have some comments on that here https://github.com/mozilla/fxa-auth-server/pull/2327#pullrequestreview-101771715 that might help. Let me know if you have questions

**Comment by ryanfeeley** [comment]
Note that the way Sync prefs in desktop does it. 

* https://accounts.firefox.com/settings?service=sync&context=fx_desktop_v3&entrypoint=preferences&uid=b121360bd2354ea0a640081854f3d32a&email=user%40example.com

They include a UID and email so that the user is sure to manage to correct account. 

Can we copy this too?

**Comment by DGRamya** [comment]
@vladikoff ,
 For the fxa-content-server project, When I try to login  or create a new account I am facing the following error
Error: Loading chunk fxaClient failed.

![screenshot from 2018-03-28 14-17-24](https://user-images.githubusercontent.com/26709753/38048458-6acd930c-3293-11e8-85fa-b6d11607d1fa.png)

**Comment by vladikoff** [comment]
@DGRamya use `127.0.0.1:3030` instead of `localhost:3030`

**Comment by vidushi04** [comment]
@ryanfeeley can i work on this isuue ?

**Comment by ryanfeeley** [comment]
@vidushi04 Sure!

**Comment by vbudhram** [comment]
@shane-tomlinson Double check and it appears we added the `Manage Account` button to a bunch of our existing emails. Ref https://github.com/mozilla/fxa-auth-server/blob/9fe542ea03b88a45e84212eb7ba4060c4349af3b/lib/senders/email.js#L73, the ones with `manage-account`.

We however did not add a button for `Manage Devices` to the new sign-in email, therefore this is still a valid issue.

**Comment by arshadkazmi42** [comment]
I can take this up if it's still available.

**Comment by shane-tomlinson** [comment]
@arshadkazmi42 - We'd be happy for you to take a stab at this! Let us know if you need any guidance.

**Comment by arshadkazmi42** [comment]
Cool. I will start working on it. 👍

**Comment by arshadkazmi42** [comment]
@shane-tomlinson which link the button will point to?
Is this the url
https://github.com/mozilla/fxa-auth-server/blob/master/lib/senders/email.js#L152
?
