### ISSUE TITLE
Drop in Registration Rate

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#2198]
We have observed a drop in registration rate across all platforms with entrypoint firstrun.

(see email sent to team)

**Comment by rfk** [comment]
This is looking like an email deliverability issue, the drop is visible in charts on:

  https://sql.telemetry.mozilla.org/dashboard/fxa-email-deliverability

**Comment by rfk** [comment]
The date here also corresponds pretty directly to train-98 going to production:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1409599#c7

**Comment by davismtl** [comment]
@jbuck Anything go out on mail server?

**Comment by davismtl** [comment]
While it does seem to be email related, it *doesn't* seem to have impacted our login rates. :-/
Our login rate is stable and so is our login volume. This seems to be impacting registration only. (?!)

**Comment by rfk** [comment]
From IRC: no change to mail setup; we added the new logo but that was in a point release done well after the metrics changed.

Another thing I don't understand is, if this is an email deliverability issue, why is it only affecting firstrun?

**Comment by rfk** [comment]
This graph shows clearly that the effect is only appearing on firstrun:

 https://sql.telemetry.mozilla.org/queries/48507/source#130895

But trying to do a similar graph in amplitude shows it affecting *all* entrypoints, not just first-run.  So I don't know if this is some artifact of the way that amplitude differs redash, or what...

**Comment by davismtl** [comment]
CC @irrationalagent who's helping me out with analysis.

**Comment by davismtl** [comment]
> But trying to do a similar graph in amplitude shows it affecting all entrypoints, not just first-run. So I don't know if this is some artifact of the way that amplitude differs redash, or what...

That's not what I observed in Amplitude. It too shows that it is only impacting registration on firstrun.
https://analytics.amplitude.com/org/31251/chart/luluy01

**Comment by irrationalagent** [comment]
also shows firstrun specific if you group by utm_source in amplitude

**Comment by irrationalagent** [comment]
1. there is a noticable drop in registration form views across all entrypoints (did deploying the new train cause this?):
![screenshot-2017-11-2 fxa registration form views grouped by entrypoint - amplitude](https://user-images.githubusercontent.com/5625313/32346357-bc55528e-bfd2-11e7-809e-c7613b894457.png)

2. of those who did engage with the form, they submitted at normal rates.
3. after form submission, email sending rates drop from 78% to 15% on the 24th, mostly recover, then drop again: 
![screenshot-2017-11-2 fxa firstrun registration funnel - amplitude](https://user-images.githubusercontent.com/5625313/32346055-a6b94b02-bfd1-11e7-9b31-db0ae1ce6c60.png)

4. During the email problem, of emails that were sent, then they seem to have been confirmed at normal rates.

So yes, there seems to be an intermittent email-specific problem but the initial drop in volume might have been due to another issue related to the new train deployment

**Comment by irrationalagent** [comment]
also shows the strange selectivity of first-run emails being affected 
https://analytics.amplitude.com/org/31251/chart/kcuo2ub

**Comment by vladikoff** [comment]
@davismtl can this be closed now? I guess we figured out the reason for the drop ?

**Comment by davismtl** [comment]
I'll close this for now. Let's keep an eye on it.

**Comment by rfk** [comment]
> Let's keep an eye on it.

It doesn't seem to have gotten any better, yet...

**Comment by davismtl** [comment]
I re-opened this because there are still some anomalies.

We can see that the registration rate went back up but not yet to where it was previously:
https://analytics.amplitude.com/org/31251/chart/luluy01/edit/5n8cqh4

What doesn't help in understand what's going on is that they seem to have broken the utm parameter on firstrun during this time (although it seems to be fixed now when checking /firstrun):
https://analytics.amplitude.com/org/31251/chart/p9li5df

It seems to me like there may still be something going on with email deliverabity:
https://analytics.amplitude.com/org/31251/chart/qeogvcn/edit/yn8ln4q

We prod need to dig into this more.

I also see a drop in registrations/form submits:
https://analytics.amplitude.com/org/31251/chart/qeogvcn/edit/urdg6yb

Did we add second password? Did we change error messages?

I'm filing a bug to fix the utm parameters.

**Comment by davismtl** [comment]
I take that back. They still have the utm parameters in the /firstrun page. Did we brake something?

**Comment by davismtl** [comment]
See https://github.com/mozilla/fxa-amplitude-send/issues/27

**Comment by irrationalagent** [comment]
> It seems to me like there may still be something going on with email deliverabity:
https://analytics.amplitude.com/org/31251/chart/qeogvcn/edit/yn8ln4q

Here's a similar funnel, but for firstrun only. step 3 does seem to suggest an email problem.

**Comment by davismtl** [comment]
> Here's a similar funnel, but for firstrun only. step 3 does seem to suggest an email problem.
https://analytics.amplitude.com/org/31251/chart/krkbf5o/edit/zuug28q

The problem with that chart is that utm parameters are broken since Oct 24th (we don't know why yet) and that is resulting in breaking the email numbers too.

https://bugzilla.mozilla.org/show_bug.cgi?id=1415622

**Comment by rfk** [comment]
Our metrics have gone on a wild ride post-quantum, and it's not at all obvious that we'll be able to usefully compare the pre-quantum "normal" registration rate with the post-quantum "normal".  @davismtl do you want to keep this open for further investigation, or shall we close it an dig in again once (a) we understand the new normal post-quantum, and (b) we've resolve the various issues with getting data into amplitude?

**Comment by davismtl** [comment]
Let's close this. This will be impossible to analyze now.
