### ISSUE TITLE
Tag v1.99.2

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#2206]
@vbudhram is it okay to pick all these commits (your email stuff) into v99.2 or does something need to be in train-100?

![image](https://user-images.githubusercontent.com/128755/32360154-99984c0e-c029-11e7-9e5f-498d13e7e4d0.png)

**Comment by vbudhram** [comment]
@vladikoff Those are good to be in v99.2. 

As a side note, if #2194 gets uplifted too, then it should automatically fix https://github.com/mozilla/fxa-content-server/issues/5678, since it will send the extra email.

**Comment by vladikoff** [comment]
This is done
