### ISSUE TITLE
db.deleteAccount, db.deleteSessionToken and db.resetAccount have insane error paths

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2209]
They each work by updating MySQL concurrently with deleting from Redis. This means that one or other can fail independently, leaving the other in an inconsistent state. Instead, they should probably update MySQL first and then, on success, delete from Redis.

But even that has some problems. The fix for #2207 involves disabling the offline command queue for Redis. So if the MySQL call succeeds but the Redis call fails, there'd still be a problem (albeit less serious than the opposite issue, because of the way `db.sessions` merges the two result sets).

In that situation, the redis offline command queue would be really helpful, because it would automatically kick in and save the day. But we definitely don't want the offline command queue in `db.sessions` or `db.devices` because it introduces potentially indefinite delay when e.g. rendering the device manager on the front-end.

Something along the lines of a CQRS approach might work for us here: Initialise two copies of the redis client, one with offline queuing enabled and the other without. Reads can use the latter and fail fast, writes can use the former and get retry semantics that don't interfere with MySQL.

**Comment by rfk** [comment]
Thanks for raising this Phil!

IMHO we *must* be able to treat redis as a sort of optional extra here.  We don't intend for data to be purged from it like a true cache, but "session has data in MySQL but not in redis" is a thing that can happen and our code should be prepared to deal with it.  From that perspective, is it "safer" to delete from redis first, and if that succeeds then proceed to deleting from MySQL?

I also worry a little about race conditions in the way we access redis.  What if a user is sigining out on one device (hence deleting a sessionToken) while another of their devices is syncing in the background (hence updating a different sessionToken).  ISTM there's a race where the update might ressurect the deleted sessionToken.

**Comment by philbooth** [comment]
> "session has data in MySQL but not in redis" is a thing that can happen and our code should be prepared to deal with it.

Yep. Fwiw, `db.sessions` and `db.devices` both work like this at the moment but I'm now thinking we should try to encapsulate that relationship in one place so that the different `db...` methods don't have to honour it explicitly (and differently) in separate implementations.

> is it "safer" to delete from redis first, and if that succeeds then proceed to deleting from MySQL?

It definitely is. I wasn't sure whether failing to e.g. reset an account was acceptable from a user perspective if redis is down. If it is, we should definitely do it that way round.

> What if a user is sigining out on one device (hence deleting a sessionToken) while another of their devices is syncing in the background (hence updating a different sessionToken). ISTM there's a race where the update might ressurect the deleted sessionToken.

Good point, this is also true. We need a mutex or some other form of synchronisation between these operations.

**Comment by philbooth** [comment]
> ...a mutex or some other form of synchronisation...

Which we could set in redis, it just occurred to me. If redis is down, these methods are going to fail anyway (or will do, once we've change them to work redis-first). And if redis is up, there's an entire page in the docs dedicated to distributed locking:

* https://redis.io/topics/distlock

Including a reference to this npm module (which I've not dug into yet):

* https://www.npmjs.com/package/redlock

**Comment by rfk** [comment]
There's also some sort of optimistic-concurrency pattern involving `WATCH` that we could look into:

  https://redis.io/topics/transactions

I don't have any experience with either pattern though so I don't know which one would be more appropriate here.

**Comment by philbooth** [comment]
Because it's difficult to reliably exercise from our remote tests, I hacked a little test script together just to make sure that `WATCH` does what we want it to:

https://gist.github.com/philbooth/040e1f6b9f64264247844e59e6da1e1f

@rfk, hopefully this addresses your concern about it operating locally to the connection. If you comment out line 32, you can see different output demonstrating the different return value from `redis.exec` in each case.

**Comment by rfk** [comment]
Thanks @philbooth!  Based on your tests, I now have the opposite question - will the watch/exec combo be too broad when handling a bunch of users concurrently?

IIUC, your tests show that `WATCH` is specific to the client created through `redis.createClient`.  Digging into the source a little, this makes sense, because this function returns a RedisClient instance [1] which opens a single connection to the redis server:

  https://github.com/NodeRedis/node_redis/blob/master/index.js#L46

However, our DB code appears to call `redis.createClient` exactly once, here in the constructor:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/db.js#L67

Meaning that every call to redis, for all users doing served by this node process, will be going through a single connection to redis.  Does this open the possibility for a `WATCH` issued for one user to abort the processing of updates for an unrelated user?  Or worse, does it mean we have a bunch of potential weird concurrency issues by trying to open multiple `MULTI` streams concurrently on the same connection?

**Comment by philbooth** [comment]
Ah, good point, you're dead right of course. Just had a play locally and it's total chaos with one connection, but appears to work correctly as long everything's limited to one watch/multi per connection.

I'll dig in to more tomorrow, perhaps one of the following can help us:

```
~/c/fxa-auth-server (phil/2209) $ npm search 'redis pool'
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
redis-connection-pool     | a redis client…      | =silverbucket   | 2017-05-07 | 1.6.1    | redis client database connection pool manager
node-redis-connection-poo | Simplistic node…     | =pasupulaphani  | 2017-01-12 | 2.9.0    | node redis cache store connection pool node-pool generic-pool connection pooling
l                         |                      |                 |            |          |
express-redis-pooled-clie | Build a…             | =octoblu-user   | 2016-10-18 | 2.0.0    | pool express redis
nt                        |                      |                 |            |          |
redis-connection          | Re-use a single or…  | =nelsonic       | 2017-08-25 | 5.4.0    | redis connection single multiple re-useable global
meshblu-core-redis-pooled | Build a…             | =octoblu-user   | 2016-07-05 | 2.5.0    | meshblu job-logger redis
-job-manager              |                      |                 |            |          |
simple-redis-pool         | Simplistic node…     | =pasupulaphani  | 2017-01-12 | 2.7.0    | node redis cache store connection pool node-pool generic-pool connection pooling
redis-client-pool         | Config driven, on…   | =bajix          | 2017-10-05 | 2.2.5    | redis config
redis-pool-connection     | Re-use a single or…  | =hengkiardo…    | 2017-05-12 | 1.4.0    | redis connection pool
pool-redis-promise        | wrapper for…         | =kristofmic     | 2015-07-26 | 1.0.1    | node redis pool promise
redis-pool-fns            | redis-pool-fns       | =hewenhan       | 2017-10-20 | 1.1.2    | redis pool functions
redispool                 | Redis pool.          | =carlhopf       | 2017-03-15 | 1.1.12   | redis pool
node-cache-redis          | Simplistic node…     | =pasupulaphani  | 2017-03-10 | 2.2.0    | redis cache store connection pool node-pool generic-pool connection pooling scal
simple-redis-cache        | Simplistic node…     | =pasupulaphani  | 2017-01-14 | 1.6.1    | redis cache store connection pool node-pool generic-pool connection pooling scal
sol-redis-pool            | Generic resource…    | =solhive        | 2017-04-28 | 0.3.3    | pool redis
newredis                  | A redis connection…  | =wallacegibbon  | 2017-11-16 | 1.0.3    | redis pool async es6
redis-generic-pool        | Connection pool…     | =hfwang         | 2013-07-30 | 1.0.0    | redis pool pooling
dbexecutors               | Tool to simplify db… | =wallacegibbon  | 2017-11-16 | 1.0.4    | mysql redis pool
sails-hook-subscriber     | Kue based job…       | =lykmapipo      | 2016-03-01 | 1.0.1    | sails kue queue subscriber pubsub consumer workers job redis
@npmcorp/redis-pool       | a pooled redis…      | =aearly…        | 2016-11-30 | 2.0.1    | redis redis-pool
lvge-redis                | Redis Connection…    | =justinchou     | 2016-03-03 | 2.0.2    | Redis Pool
```
