### ISSUE TITLE
Don't send a "New sign-in to Firefox" email when the user signs in to Lockbox

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2213]
Currently, when a user signs in to Lockbox or Notes or some other relier that wants keys, we will send them an email saying "New sign-in to Firefox".  This is the same email we send after the user signs in to sync, and it has the potential to cause confusion and alarm.

Our options here include:

* Don't send any email when the user is signing in to Lockbox.  This may not be safe because, from the auth-server's perspective, logging in to Lockbox produces credentials that can also be used to log in to Sync.
* Send a Lockbox-themed email rather than one about Firefox.  We'd have to figure out the wording etc here, and hopefully figure out a way to easily re-use it for Notes and other OAuth reliers in future.

@ryanfeeley thoughts on the right approach from the user's perspective here?

**Comment by ryanfeeley** [comment]
@rfk I think we should still be sending an email, but make it more generic (or more specific).

Apple has a clever approach. Would something like this work for us?
![image](https://user-images.githubusercontent.com/68213/32665139-54460b18-c601-11e7-89ca-009274565533.png)

**Comment by rfk** [comment]
>  Would something like this work for us?

I think it's got potential.

We also have to consider that lockbox intends to go through our auth loop a *lot*.  We probably want to send an email when the user does a signin on a totally new device, but not if they "reauth" on an existing device, along the lines of https://github.com/mozilla/fxa-content-server/issues/5703

**Comment by vladikoff** [comment]
from mtg: train-101 we are gonna try to address the messaging

**Comment by ryanfeeley** [comment]
@rfk I realize this bug is about the frequency of the emails. Your approach sounds correct (only new devices).

In the meantime I have some suggestions for our two emails (confirm sign-in and new sign-in). https://docs.google.com/a/mozilla.com/document/d/1I7TSNa7mvUFipX48OhGSRbuVybIqSb5QdnCmivSjl-c/edit?usp=sharing

**Comment by rfk** [comment]
> I realize this bug is about the frequency of the emails

It is about both the frequency and the content; I'd be happy to morph it into just a "improve email content" bug and track the "send them less frequently" somewhere else, because I think getting the content right is more urgent.

**Comment by ryanfeeley** [comment]
@rfk I think all the necessary changes are included in the suggestions in the doc hopefully

**Comment by ryanfeeley** [comment]
@rfk Ah… with the exception of the illustrations. We may have to revert to the Firefox logo as the Sync logo is not relevant to everyone.

**Comment by rfk** [comment]
> In the meantime I have some suggestions for our two emails (confirm sign-in and new sign-in).

Relatedly, we may also get users signing *up* for an account through Lockbox.  Our default onboardng email is probably OK for this, but it'd be worth a look to see if we want to make any tweaks.

**Comment by rfk** [comment]
FWIW the proposed changes in the google doc look good to me!  We'll have to be careful not to accidentally replace "%(serviceName)" with "Sync" when they're signing in to sync, but instead keep the existing "Firefox" wording.

**Comment by ryanfeeley** [comment]
@rfk I’m suggesting that we say "Sync" for Sync sign-ins. I'm still thinking about the registration email.

**Comment by vladikoff** [comment]
@rfk hm I guess the auth server has no idea what the `serviceName` is for some client id. Should be do a /v1/client/[id] lookup?

**Comment by rfk** [comment]
@philbooth had to solve a similar problem for amplitude events IIRC, so there might be some mapping available locally.  If not, a lookup seems OK short-term, we know the URL of the oauth-server already.

Longer-term, I'm adding this to my long list of reasons why the oauth-server functionality should just be merged into the auth-server...

**Comment by philbooth** [comment]
@vladikoff, all the service names should be mapped from their client ids in config now, both here and in the content server fwiw. See `config.oauth.clientIds` in this repo and, in case you ever need it for something else, `config.oauth_client_id_map` in the content server. (different setting names in each place are to try and be consistent with the rest of the surrounding config)

**Comment by vladikoff** [comment]
from mtg: add memory cache for fetching oauth ids / names
