### ISSUE TITLE
Use signed cookies to avoid email confirmation loops

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2214]
To avoid having to put the user through frequent email-confirmation loops, we could have the auth-server set a signed cookie when the user has a verified login, and use the presence of this cookie to skip verification on logins from the same device.

I imagine this looking something like:

* Use hapi's builtin support for signed cookies: https://hapijs.com/tutorials/cookies
* On endpoints where the user might have a verified session, check whether they do, and set or refresh a signed cookie containing their uid
* On new login attempts, check for this cookie and skip verification if present

@shane-tomlinson points out that since the auth-server runs on a different domain to the content-server where login requests originate, this would technically be a third-party cookie and hence might get blocked under various cookie policies.  It should have some non-zero hit-rate though, and we can use initial metrics from trying out it to know whether there's value in trying to make it a first-party cookie somehow.

This one is also probably worth a small feature-doc, since we'll want to be able to analyze its effect on sign-in success.  But I think it's only a one-issue project in github.

**Comment by davismtl** [comment]
@vbudhram i think tha tthis is what we referring to for 2FA. 

I think we should review the rules for this. 
- Should it be a hard 30 days since last confirmation loop? 
- Or should it be a rolling 30 days that refreshes with every login, independently of the date of last confirmation loop?

**Comment by rfk** [comment]
See also https://github.com/mozilla/fxa-auth-server/issues/2212 which is also designed to help with the "do a confirmation loop every time" problem.

**Comment by rfk** [comment]
If we decide to move ahead with this one, we'll also need to check on the policy/legal aspects of it, given various cookie laws.  I expect it'll be OK because users have agreed to the ToS by the time we want to set this cookie, but always worth double-checking.

**Comment by vladikoff** [comment]
from mtg: waiting for decisions

**Comment by juliemccracken** [comment]
@vladikoff and @rfk: Marshall Erwin and Peter Seeger appear to approve in Bug 1444263 https://bugzilla.mozilla.org/show_bug.cgi?id=1444263.
I've asked legal for formal sign-off in the bug to formalize their approvals.

**Comment by juliemccracken** [comment]
Peter told me that he's going to formally approve and close the bug. Ok to proceed.

**Comment by rfk** [comment]
I don't think we're going to get back to this with any urgency, closing it out
