### ISSUE TITLE
Come up with a plan for reducing redis memory usage

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2222]
Current projection says we'll need to scale again in 6-9 weeks. Some things to consider:

* Can we store a more efficiently encoded blob? JSON involves repetition of keys etc.
* Are we deleting with maximum aggression/efficiency?
* Can we set a TTL to expire data?
* Should we investigate the long tail of accounts that have large amounts of data?

/cc @jrgm, @jbuck, @rfk, @vladikoff: as discussed in meeting just now.

**Comment by philbooth** [comment]
I also notice there is a `return_buffers` option on the node redis client. So we could even store a gzipped blob there (regardless of whether it's vanilla JSON or some more efficient encoding).

**Comment by jbuck** [comment]
The easiest option here would be to set a TTL on every bit of data we insert & change the eviction policy from `noeviction` to `allkeys-lru` [docs](https://redis.io/topics/lru-cache).

It'd be more work, but I think we should explore changing how we store data as well. Right now we store sessions keyed on the uid (`fxa-auth-session05480d17b7441a3fa5be23fc0a4b4d1c`) which then contains a stringified JSON object:

```
{
  "45ad7b24aa3ee9dd2c123bd5b599abed2e84db5da6210ef0746b8481ae95eb1e": {
    "tokenId": "45ad7b24aa3ee9dd2c123bd5b599abed2e84db5da6210ef0746b8481ae95eb1e",
    "uid": "05480d17b7441a3fa5be23fc0a4b4d1c",
    "uaBrowser": "Firefox Beta",
    "uaBrowserVersion": "10.0",
    "uaOS": "iOS",
    "uaOSVersion": "11.1.1",
    "uaDeviceType": "mobile",
    "uaFormFactor": "iPhone",
    "lastAccessTime": 1510853069405,
    "createdAt": 1490625317825,
    "location": {
      "city": "Toronto",
      "country": "Canada",
      "countryCode": "CA",
      "state": "Ontario",
      "stateCode": "ON"
    }
  },
  "1624727da48c4882a0aa76a709d5a03f4362b2b9c50e2a8318537f7d0ba85868": {
    "tokenId": "1624727da48c4882a0aa76a709d5a03f4362b2b9c50e2a8318537f7d0ba85868",
    "uid": "05480d17b7441a3fa5be23fc0a4b4d1c",
    "uaBrowser": "Firefox",
    "uaBrowserVersion": "59",
    "uaOS": "Mac OS X",
    "uaOSVersion": "10.12",
    "uaDeviceType": null,
    "uaFormFactor": null,
    "lastAccessTime": 1510853047468,
    "createdAt": 1461865847139,
    "location": {
      "city": "Toronto",
      "country": "Canada",
      "countryCode": "CA",
      "state": "Ontario",
      "stateCode": "ON"
    }
  }
}
```

I'm totally spit balling, but I wonder if we had two separate keys for storing, `uid:blah` which is a list/set/sorted set (not sure which data structure is best for our needs) containing all of the sessions for a user and `sessionid:blah` which is a flattened hash containing the various properties of a session. I'd want to benchmark both the memory and speed difference somehow before coding this up in a patch but maybe something along the lines of this?

**Comment by philbooth** [comment]
I also notice that there are some quick, low-impact wins to be had from dropping `tokenId`, `createdAt` and anything where the value is `null`. And the `ua...` properties probably don't need to be stored most of the time, only the ones that are different to what we have in MySQL.

I'm going to benchmark/compare my gzip idea, as that also has the neat side effect of making it easy to handle two different storage formats. With `detect_buffers` set to `true`, the client will return either a buffer or a string depending on the data, so we can lean on that in the code to decide whether to unzip after reads. Although definitely shout if you think gzip is a dumb idea and I'm wasting my time.

**Comment by jbuck** [comment]
Yeah good point, dropping the fields we don't need would also save memory.

I googled around for people gzipping data before sending it to Redis and it looks like some people have done it with some success. I'd definitely want to benchmark though, I feel like our data set is relatively small and we'd need to weigh that against the compression/decompression time.

**Comment by philbooth** [comment]
> I also notice that there are some quick, low-impact wins to be had from dropping `tokenId`, `uid`, `createdAt`...

Fwiw, I've included this bit in #2235.

**Comment by philbooth** [comment]
Another, albeit minor, cause of our Redis usage never shrinking is that `db.deleteSessionToken` is writing empty objects rather than removing entries, when the last session token for a given uid is deleted. I only noticed this while doing #2235, not sure how much of a difference it makes in practice but it is fixed incidentally there.

**Comment by philbooth** [comment]
Even the key prefix is a bit unfortunate, in hindsight. We should have opted for something shorter, or even no prefix at all. Is it worth the extra logic for coping with multiple prefixes if we fix it it?

**Comment by jrgm** [comment]
re: key prefix, probably not worth it. 16 bytes key vs. ballpark 1000 bytes value (key prefix size apparently does matter from some quick read of some articles, but only when key size is about value size. Given our ratio, not so important. Another recommendation was to not mix heterogenous types in redis stores; just use another redis store.(That might be true, but depends on the fixed cost vs. variable cost if/when we had a reason for another use of redis in fxa-auth).

**Comment by vladikoff** [comment]
from mtg: plan will be revealed this week!

**Comment by philbooth** [comment]
> from mtg: plan will be revealed this week!

Fwiw I'm working on comparing a couple of concrete plans against each other with some concrete tests cases.

Plan "a": Rather than stringifying each session token as an object, stringify it as a fixed length array with fixed indices for each property. The idea being that we stop paying to store all of the property names like `uaBrowserVersion` etc. You can see this at https://github.com/mozilla/fxa-auth-server/commit/33168a62547bd56a833715234b924b85071b4859.

Plan "b": gzip

Plus I can compare whatever other concrete plans we want to using the same test cases.

**Comment by rfk** [comment]
> Rather than stringifying each session token as an object, stringify it as a fixed length array 
> with fixed indices for each property. The idea being that we stop paying to store all of the
> property names like uaBrowserVersion etc

Nice.  For historical context, we mooted something similar for resume tokens once upon a time:

  https://github.com/mozilla/fxa-content-server/issues/3026#issuecomment-194129259

But I think we just never prioritized doing that work.  I'll be interested to see how it works out in this case!

**Comment by philbooth** [comment]
I compared three approaches using [this script](https://github.com/mozilla/fxa-auth-server/blob/893dea954f79a009c48e62c26f3a60d3e4b789aa/scripts/redis-benchmark.js):

* Fixed-length arrays with fixed indices, so we don't store keys.
* Gzipped (raw binary).
* Gzipped (base-64 encoded).

I gave it 10,000 iterations in each case then compared the final stats. The clear winner was fixed-length arrays. Congratulations fixed-length arrays, I know you worked very hard for this victory.

Output from the script follows. The timings are in nanoseconds, memory numbers are bytes (except for the `_human` ones, obviously).

* Fixed-length arrays:

  ```
  # Timings
  Aggregate update time: 1829227393
  Mean update time: 182922.7393
  Median update time: 24312
  Aggregate get time: 47198059455
  Mean get time: 4719805.9455
  Median get time: 4536636

  # Memory
  used_memory:2024976
  used_memory_human:1.93M
  used_memory_rss:2183168
  used_memory_rss_human:2.08M
  used_memory_peak:2024976
  used_memory_peak_human:1.93M
  total_system_memory:17179869184
  total_system_memory_human:16.00G
  used_memory_lua:37888
  used_memory_lua_human:37.00K
  maxmemory:0
  maxmemory_human:0B
  maxmemory_policy:noeviction
  mem_fragmentation_ratio:1.08
  mem_allocator:libc
  ```

* Gzipped (binary):

  ```
  Mean update time: 280254.3862
  Median update time: 27280
  Aggregate get time: 153036561236
  Mean get time: 15303656.1236
  Median get time: 14710575

  # Memory
  used_memory:3297408
  used_memory_human:3.14M
  used_memory_rss:3502080
  used_memory_rss_human:3.34M
  used_memory_peak:3297408
  used_memory_peak_human:3.14M
  total_system_memory:17179869184
  total_system_memory_human:16.00G
  used_memory_lua:37888
  used_memory_lua_human:37.00K
  maxmemory:0
  maxmemory_human:0B
  maxmemory_policy:noeviction
  mem_fragmentation_ratio:1.06
  mem_allocator:libc
  ```

* Gzipped (base-64):

  ```
  # Timings
  Aggregate update time: 2747165713
  Mean update time: 274716.5713
  Median update time: 27148
  Aggregate get time: 261841894827
  Mean get time: 26184189.4827
  Median get time: 25745753

  # Memory
  used_memory:2406480
  used_memory_human:2.29M
  used_memory_rss:3526656
  used_memory_rss_human:3.36M
  used_memory_peak:3298288
  used_memory_peak_human:3.15M
  total_system_memory:17179869184
  total_system_memory_human:16.00G
  used_memory_lua:37888
  used_memory_lua_human:37.00K
  maxmemory:0
  maxmemory_human:0B
  maxmemory_policy:noeviction
  mem_fragmentation_ratio:1.47
  mem_allocator:libc
  ```

If anyone wants to check my working, which is probably wise, you can find it in the `phil/2222-wip` branch. In the meantime, I'll start polishing up the fixed-length array approach and write some tests for it etc.

**Comment by philbooth** [comment]
Looking at those numbers, it's clear my code for the gzipped (binary) approach was wrong. The base-64 memory numbers are smaller than binary memory numbers.

I thought the node redis client knew what to do with buffers, but maybe I was wrong. Fixing and re-running those tests.

**Comment by philbooth** [comment]
> Fixing and re-running those tests.

Although, duh, I could also just use the power of maths to extrapolate from one to the other instead. Raw binary will be 25% smaller than the equivalent base-64 encoded data, which would make the gzipped binary a little bit smaller than fixed-length arrays: 1,804,860 bytes vs 2,024,976 bytes for 10,000 session tokens.

So gzipped binary is smaller than fixed-length arrays. Fixed-length arrays are faster than gzipped binary. Tradeoffs.

I guess the other question about gzipped binary concerns @jrgm's comment about heterogeneous types in https://github.com/mozilla/fxa-auth-server/issues/2222#issuecomment-345915281. Although I assumed redis treats everything the same ultimately, it's all just bytes. But anyway, possibly that's another point in favour of fixed-length arrays.

**Comment by philbooth** [comment]
Forgot to include baseline numbers for current `master`. These are they:

```
# Timings
Aggregate update time: 2071476903
Mean update time: 207147.6903
Median update time: 26372
Aggregate get time: 402205119609
Mean get time: 40220511.9609
Median get time: 41115652

# Memory
used_memory:2397392
used_memory_human:2.29M
used_memory_rss:3543040
used_memory_rss_human:3.38M
used_memory_peak:3298288
used_memory_peak_human:3.15M
total_system_memory:17179869184
total_system_memory_human:16.00G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.48
mem_allocator:libc
```

**Comment by philbooth** [comment]
> Tradeoffs.

Although not really, because the times we're talking about here are all vanishingly small. Fractions of milliseconds.

**Comment by philbooth** [comment]
Let me summarise all of that in one easy-to-read table using sensible units:

 Test|Median time (db.updateSessionToken)|Median time (db.sessions)|Memory usage (10k tokens)|Memory reduction
----|--------------------|-----------------|------------|----------------
`master`|0.03 ms|41.1 ms|2.29 mb|0%
fixed-length array|0.02 ms|4.5 ms|1.93 mb|-16%
gzip binary|0.03 ms|14.7 ms|1.72 mb|-25%
gzip base-64|0.03 ms|25.7 ms|2.29 mb|0%

This suggests that, if I can get gzip binary data working correctly, it's the best format for me to use (from those tested).

**Comment by philbooth** [comment]
It doesn't make sense  that`db.sessions` is slower in master than it is for any of the unpacking approaches I tried. But anyway, ignore the time stuff.

**Comment by philbooth** [comment]
> It doesn't make sense  that`db.sessions` is slower in master...

Oh god, I'm such a fool! I wasn't restarting the db server between test runs and the memory db has a very naive implementation that iterates through all session tokens. So the timings for `db.sessions` above are utter bunkum. Sorry.

**Comment by philbooth** [comment]
The downside to gzip, other than making sure we can get the node redis client to correctly send binary data, is that it makes it harder to debug stuff by looking in redis. You can't  just eyeball the data, you need to unzip it first.

I think we should see what effect the train-101 improvements have on the situation from @jrgm+@jbuck's perspective and then they can advise whether a further 16% is sufficient or if we need a binary solution.

**Comment by philbooth** [comment]
@jrgm just had a look at the charts in AWS for this and there is good news! The steady climb in memory usage turned into a drop initially and now seems to be level. So the immediate problem seems sorted.

Going forward, if we want to reduce further, it seems like the 16% reduction from switching to an array will be good enough, without needing to gzip anything.

**Comment by vladikoff** [comment]
from mtg: "switching to an array will be good enough" the plan is to add this improvement and we should be okay from there , for now.
