### ISSUE TITLE
Implement redis pruning

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2223]
I should have mentioned this when we were discussing #2222 last night but it was late and I wasn't thinking clearly. Currently there is no logic for pruning expired session tokens from Redis. This is a problem on two levels: memory usage (also see #2222) and data integrity (also see #2209).

**Comment by philbooth** [comment]
One complication with this, which I only just realised, is that we don't store `createdAt` in Redis any more. Granted there will be some old, non-updated tokens in there that still have it, but they'll dwindle quickly as we prune them. That has implications for how we approach this issue.

Firstly, it rules out simply porting the MySQL pruning logic to Redis. We'd need to `SCAN` through keys in Redis and then try to fetch each token from MySQL before deciding whether or not to prune. That would be a huge increase in db reads and seems wildly inefficient.

We also can't just flip the order of those operations round to use SQL for efficiently pre-selecting the tokens, because we already expired a whole bunch of them from MySQL that weren't deleted from Redis (although, going forward, this approach could be made to work for future tokens).

Something we could do is make a pruning decision inside `updateSessionToken` because that has to read from both stores anyway, so has the information we need. Of course, this only works out of the box for tokens that are passed to `updateSessionToken`, although it's also straightforward to broaden it to all tokens for the user.

A different approach that achieves the same result would be to change `updateSessionToken` to start writing `createdAt` to Redis again, and then implementing basic pruning logic using `SCAN` and `createdAt`.

Currently I'm leaning towards conditionally pruning inside `updateSessionToken` because it doesn't require storing the extra field in Redis and still achieves the same result as setting `createdAt` again. It's also way less complicated than trying to link the Redis and MySQL pruning loops together, and has more reach than that because of the potential for so many older tokens to be pruned when other tokens for the same user get updated.

I'm interested to know what anyone else thinks though

**Comment by rfk** [comment]
> Currently I'm leaning towards conditionally pruning inside updateSessionToken

This seems reasonable to me as the first step, given it's both simple and localized.

Another addition could be to lazily purge expired tokens inside `db.sessions` and `db.devices`.  IOW, if we're building the merged list of tokens, and we find that there are tokens in redis that don't exist in MySQL, then we write back to redis with a purged set of tokens.
