### ISSUE TITLE
Add an API for cloning a session token

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2236]
In [Bug 1419505](https://bugzilla.mozilla.org/show_bug.cgi?id=1419505) we are discussing a new ability to cleanly "clone" an existing Firefox profile.  If the original profile happens to be connected to sync, the intended end-state is that resulting new profile is connected to sync, but has its own FxA session token and device record that is separate from the original profile.  It should be able to get itself into such a state without prompting the user to re-enter their password.

To support this, we could add the ability to clone an FxA session token, perhaps something like:

----

**POST /session/duplicate**

🔒 HAWK-authenticated with session token

Create a new sessionToken as a duplicate of an an existing `sessionToken`, inheriting the verification status of the existing token.

*Request body*:
* `reason`: Alphanumeric string indicating the reason for establishing a new session; values t.b.d. for metrics purposes.

*Response body*:
* `uid`: string, regex(HEX_STRING), required
* `sessionToken`: string, regex(HEX_STRING), required
* `verificationMethod`: string, optional
   The medium for how the user can verify.
* `verificationReason`: string, optional
   The authentication method that required additional verification.
* `verified`: boolean, required
* `authAt`: number, integer
  Authentication time for the session (seconds since epoch).

----

The response body here is the same as you'd get from calling /account/login, minus the optional keyFetchToken because the cloned profile should already have keys.

@mozilla/fxa-devs thoughts?

**Comment by shane-tomlinson** [comment]
You know where this could potentially be useful? A pairing flow where device A passes a sessionToken to device B. For device B to sign in, it'd need the endpoint to return a keyFetchToken too, unless device A passed a cloned sessionToken and the keys it already holds to device B.

**Comment by shane-tomlinson** [comment]
Following on from the last comment, even if keyFetchToken were returned by the endpoint, device B would still need the user's password so that it could generate kB, so perhaps just passing the cloned sessionToken and device A's kB is the way forward.

**Comment by rfk** [comment]
@shane-tomlinson you're right, the other way we could go here would be to turn it into a kind of two-step pairing API, where device A creates one of those special "one time login" tokens we've talked about in the past, and then device B consumes it to get a new sessionToken and keyFetchToken.  That A and B happen to be the same device during a profile clone doesn't seem like it'd make too much difference (apart from maybe generating some spurious emails about new devices being connected).

The downside of going that route is, potentially bigger piece of work and more crypto bits that could require review.

**Comment by shane-tomlinson** [comment]
>  and then device B consumes it to get a new sessionToken and keyFetchToken.

Even if device B were to get a keyFetchToken, it still needs the user's password to get kB, doesn't it? For the pairing flow, I'm trying to sidestep that requirement.

**Comment by rfk** [comment]
> Even if device B were to get a keyFetchToken, it still needs the user's password to get kB, doesn't it?

You are correct, it would also need unwrapKb from the user's password, or we'd need to do some clever crypto blah-blah like in https://mail.mozilla.org/pipermail/dev-fxacct/2016-June/001929.html.  Doing a direct transfer of kB is probably simpler at this point.

**Comment by mhammond** [comment]
> Doing a direct transfer of kB is probably simpler at this point.

Aren't we looking at the client dropping kB ASAP for lockbox?

**Comment by rfk** [comment]
Sure.  We should word that as "doing a direct transfer of whatever key material the browser needs to have in order to sync", we don't need to assume that it's directly handling kB.

**Comment by mhammond** [comment]
But I thought that brings us back to the session token? Either way, I'll leave this discussion to the people who know what they are talking about ;)

**Comment by vladikoff** [comment]
Moved to 104
