### ISSUE TITLE
SMS are not sent

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#2243]
### STR

* Visit https://accounts.firefox.com/sms
* Type a number, submit
* Get green `App link sent to [number]`

### Actual

No SMS :(

### Expected

SMS

**Comment by vladikoff** [comment]
From #2244 

> While updating https://github.com/mozilla/fxa-bugzilla-mirror/issues/406, came across some inconsistencies with what our SMS metrics were [reporting](https://dash.adjust.com/#/statistics/overview/default/gqrwnbypw28p/hc80kp?from=2017-11-20&to=2017-11-26&range=custom&sort=installs&reverse=true&timezone_id=172&attribution_type=click&grouping=os_names&conversion_type=all&attribution_source=dynamic&scale=sqrt&gkpi=installs).

> Tested sending to USA and Canada numbers but didn't receive the message. The auth-server reports a 200 and that it was sent successfully. There doesn't appear to be an changes with how we send SMS messages so I am not sure what could be causing this.

**Comment by jbuck** [comment]
It's an AWS quota issue:

`"providerResponse": "No quota left for account",`

I'll file a support ticket

**Comment by shane-tomlinson** [comment]
> "providerResponse": "No quota left for account",

Can we make use of those responses to flag us and report an error to the user?

**Comment by vladikoff** [comment]
Ref https://github.com/mozilla-services/cloudops-deployment/pull/1414

**Comment by shane-tomlinson** [comment]
SMS works again, closing.
