### ISSUE TITLE
SMS does not appear to be sending

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2244]
While updating https://github.com/mozilla/fxa-bugzilla-mirror/issues/406, came across some inconsistencies with what our SMS metrics were [reporting](https://dash.adjust.com/#/statistics/overview/default/gqrwnbypw28p/hc80kp?from=2017-11-20&to=2017-11-26&range=custom&sort=installs&reverse=true&timezone_id=172&attribution_type=click&grouping=os_names&conversion_type=all&attribution_source=dynamic&scale=sqrt&gkpi=installs).

Tested sending to USA and Canada numbers but didn't receive the message. The auth-server reports a 200 and that it was sent successfully. There doesn't appear to be an changes with how we send SMS messages so I am not sure what could be causing this.

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/fxa-auth-server/issues/2243
