### ISSUE TITLE
Add service name to sign-in confirmation emails

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#2249]
From our Transactional Emails doc, let's add the service name to our sign-in confirmation emails.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/68213/34013960-17a484de-e0df-11e7-8008-595aded776cb.png">

**Comment by vladikoff** [comment]
from mtg: use a cached list of names for this. (ids do not change that often so we should be able to cache it)
