### ISSUE TITLE
Change 'confirm email' design to let users know that they should FxA to the address book

### ISSUE THREAD

**Issue by jbuck** [mozilla/fxa-auth-server#2255]
Inspired by https://bugzilla.mozilla.org/show_bug.cgi?id=1428337 I wonder if we should add a CTA in our verification emails and perhaps other emails as well so help ensure emails are getting delivered to our users. I know for FastMail that’ll whitelist emails coming through; I bet it’s help with other providers.

**Comment by ryanfeeley** [comment]
@rfk @jbuck Yes! Putting it in the email won't work if they're not arriving in the first place.

I imagine that after users resend the email, the "Email resent" success message could be appended.

So this:
* https://github.com/mozilla/fxa-content-server/blob/master/app/tests/spec/views/mixins/resend-mixin.js#L68

Becomes:
* Email resent. Add accounts@firefox.com to your contacts to ensure a smooth delivery.

Thoughts?

**Comment by rfk** [comment]
I like this FWIW; I also wonder if we can somehow show it on the "check your email" screen even before the user has clicked "resend email".

**Comment by vladikoff** [comment]
This didn't make crouton, but we need a decision anyway because this is in `next`

**Comment by rfk** [comment]
Need to sync up with Alex before we can work on this

**Comment by ryanfeeley** [comment]
Current screen for reference:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/68213/36436315-e4e8cc3e-1631-11e8-98ae-72548ac55f09.png">

**Comment by vladikoff** [comment]
final decision: `Email resent. Add accounts@firefox.com to your contacts to ensure a smooth delivery.`
