### ISSUE TITLE
Totp MFA API Design

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2262]
## fxa-auth-server

Connects with https://github.com/mozilla/fxa-auth-db-mysql/issues/297

#### POST /session/verify/topt

:lock: HAWK-authenticated with session token

Verify a session using a TOTP code.

##### Request body

* `uid`: *string, max(32), regex(HEX_STRING), required*
  * The uid associated with the token code
* `code`: *string, min(6), max(6), required*
  * The 6 digit TOTP code

##### Response body

* {}

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: XXX`:
  Invalid authentication token
___
#### POST /session/topt/recoveryCodes

:lock: HAWK-authenticated with verified session token

Generate new TOTP recovery codes

##### Request body

* `uid`: *string, max(32), regex(HEX_STRING), required*
  * The uid to regenerate recovery codes

##### Response body

* array of recovery codes `['123-123-123', '123-123-123']`

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: XXX`:
  uid not found

___
#### POST /session/topt/recoveryCode

:lock: HAWK-authenticated with session token

Consume TOTP recovery code

##### Request body

* `code`: *string required*
  * The recovery code used to verify session

##### Response body

* `{}`

##### Error responses

Failing requests may be caused
by the following errors
(this is not an exhaustive list):

* `code: 400, errno: XXX`:

**Comment by vbudhram** [comment]
@rfk This is a rough outline of the APIs I was thinking of adding. Haven't finalized all the error codes as of yet, mind a sanity check?

**Comment by TDA** [comment]
@vbudhram Super minor, but the rest endpoints should say `totp` instead of `topt`.

Also, shouldnt the `POST /session/topt/recoveryCodes` actually be a `GET` if all it does is generate the codes? More like:
```
GET /session/topt/recoveryCodes?uid=xxxx-....
```

**Comment by rfk** [comment]
@TDA oh hi! 👋 thanks for weighing in here, we've been digging through the notes from you previous work on this topic :-)

Initial impressions:

* I'm not sure whether we need a separate endpoint for consuming a recovery code, or whether we should just accept recovery codes in the `/session/verify/topt` endpoint and just do the right thing behind the scenes.
* We'll need endpoints for adding and removing a TOTP device; I'm not entire sure where they should live in the API namespace though, thoughts?
* We'll need to consider what additional information gets added to the response from APIs like `/session/status` and friends.
* Some existing APIs may start returning an error if called with a non-verified token, and the user has TOTP enabled.  I'm thinking about `/account/delete` as an example, but maybe it's just anything that's authed with a sessionToken.
* We need to consider how TOTP integrates with the password-change and password-reset flows - basically anywhere the user might be entering a password.

**Comment by vbudhram** [comment]
@TDA @rfk Thanks for input, updated! I have taken this issue and broken it up into 3 smaller independent ones.

* Management API, create/delete and verify code (performs validation only) https://github.com/mozilla/fxa-auth-server/issues/2293
* Session Verification, if code validated, verifies corresponding session https://github.com/mozilla/fxa-auth-server/issues/2295
* Recovery Code API https://github.com/mozilla/fxa-auth-server/issues/2294
