### ISSUE TITLE
Change CAD link in the verified email

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#2264]
Much like how desktop Firefox Sync tells users to connect another device, and directs them to CAD on the web, we should also be doing in this in our emails.

Related bugs (for URL and UTM parameter inspiration)
* https://bugzilla.mozilla.org/show_bug.cgi?id=1418466
* https://bugzilla.mozilla.org/show_bug.cgi?id=1420193

Current:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/68213/35415124-810519d2-01f2-11e8-922d-b244c40be6d5.png">

**Comment by vladikoff** [comment]
This was done in https://github.com/mozilla/fxa-auth-server/pull/2297
