### ISSUE TITLE
"Tap to begin" notification on iOS app when signout on other device

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#2265]
I know we are working to improve send tab with push, ios and sync teams but I thought I'd share an event that I detected sends a "Tap to begin notification".

I see this generic notification on iOS when I signout on another device. Not sure how much we control around this or that iOS team does.

**Comment by davismtl** [comment]
I also got the same notification when I signed back in on that device.

**Comment by rfk** [comment]
We send connect/disconnect messages to Fx-iOS 10.0 and above:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/push.js#L198

I wonder if some of these don't actually support the messages.

**Comment by davismtl** [comment]
stefan thinks that it's just related to the overall change we are doing to push on ios and send tab.

I'll just close this for now.
