### ISSUE TITLE
Update login notifications to include name of relier (edited)

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#2268]
edit: Below is my partially panicked bug about getting a login notification to Firefox when I hadn't logged in. Turns out a Lockbox triggered it. 

**Proposal:** Let's make this login notification emails more clear by adding the relier in the email body.

--- original problem ---
This morning, as the ux fxa meeting was starting, I got an notification about a login to my FxA.

The curious thing is that the IP is the mountain view office. The curious thing is that it looks like my laptop but I guess it could be anyone else's Mac in the office.

Any ideas about what could have caused this? 

**New sign-in to Firefox**
Firefox on Mac OS X 10.13
Mountain View, CA, United States (estimated)
IP address: XX.XX.XX.XXX
8:28:40 AM (PST) Monday, Jan 29, 2018

**Comment by davismtl** [comment]
Now that I've had time to dig into this, this was triggered for a sign-in to Lockbox.

We should create a new email template for them or put the relier in the email body...

**Comment by rfk** [comment]
I think this is covered by the in-progress https://github.com/mozilla/fxa-auth-server/issues/2213, so closing as a dupe, but please re-open if it seems like there's more to it than that.
