### ISSUE TITLE
Basket errors for "verified" queue messages

### ISSUE THREAD

**Issue by pmac** [mozilla/fxa-auth-server#2274]
Basket is throwing `KeyError`s due to a missing key in `verified` messages on the queue. Basket has always expected these messages to contain a `locale` key but on our staging instance these messages are missing this key. If this is intentional I just need to know so that I can make this an optional bit of data in our processing.

/cc @rfk

**Comment by rfk** [comment]
From IRC discussion, we've concluded that this can happen if the account creation request does not send an Accept-Language header,  Please update to treat this field as optional, although if that doesn't make sense for some reason, we could also try to set a default value on the FxA side.

**Comment by pmac** [comment]
I've updated basket to treat these messages as tests and simply drop them. We don't need to record users that don't have a good locale anyway since we couldn't email them. 

Addressed in https://github.com/mozmeao/basket/commit/3ff6f238335d7ce8179c3d8e529a849361c86200

Thanks!
