### ISSUE TITLE
Lockbox doesn't recognize that I am signed into browser

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#2277]
Steps to reproduce:

- Make sure you are logged into Firefox Sync
- Install lockbox alpha add-on
- Open Lockbox and go to login

Expected Result:

- FxA in Lockbox recognizes me and has my email pre-populated (and maybe shows me my avatar).

Actual result:

- I was totally unrecognized. 
- I had to add my email and password
- I had to confirm my login

Other details from that experience for full context:

- When I went to sign in the second time, FxA in Lockbox recognized me and only required my password.
- It did send me a scary inaccurate login confirmation email too. We however already have a few bugs filed for that. a) to update the copy and b) to not send login confirmation if the device is recognized

**Comment by rfk** [comment]
I wasn't able to reproduce on a fresh Nightly profile.  The lockbox login page prompted me to enter my password again, but it pre-filled my email address and displayed my profile picture.

Under the hood, the works by:

* When you sign in to sync, we store some state in localStorage on accounts.firefox.com containing your sessionToken, email address, etc
* When you later go to sign in to lockbox, we check in localStorage and use the state found there if possible

What I suspect has happened in your case @davismtl, is that this localStorage state got cleared somehow, possibly from signing in and out of different OAuth provides with different email addresses.  We haven't yet grappled with the technical (and security-related) details of trying to restore the localStorage state by querying the browser to see whether you're signed in.

**Comment by davismtl** [comment]
I am currently unable to reproduce it. Steps I followed:

- Deleted add-ons
- Reinstalled via this link: https://mozilla-lockbox.github.io/lockbox-extension/
- Login

It detected that I am logged into FxA and even displayed my Avatar. 

I don't know if that was the most efficient way to replicate (dunno if something cached) so I'm open to suggestions.

**Comment by rfk** [comment]
unable to repro, closing
