### ISSUE TITLE
Please add log in with Google

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/fxa-auth-server#2291]
A lot of Chrome users don't try Firefox since it cannot sync bookmarks without a new signup.

Basically users go to the account page, see the signup page and drop it.

It would be really nice to have a Log in with Google button on the signup page so Chrome defecters would feel welcome.

**Comment by andreicristianpetcu** [comment]
![screenshot_20180208-201535](https://user-images.githubusercontent.com/922368/35990669-6ea85b5c-0d0d-11e8-92ac-7b119b1b323b.png)

**Comment by rfk** [comment]
> Chrome sync does not have e2e encryption, right?

It can, and my memory may be out of date, but I think they use your account password for encrypting some stuff and they allow you the option of specifying a second "encryption passphrase" that makes all your data encrypted.

> I think Google uses the history for ads and profiling.

I don't think they do this, not because they can't but because they don't need to - google's analytics and other its of code are on enough of the web that they can get a good sense of your history without needing the browser to send it to them explicitly.

A related option that we've discussed is some sort of "guest account" functionality, similar to what e.g. Pocket does.  This would let you get started with some of the features without having to explicitly create an account.  Both options would likely be a significant amount of work though.

Anyways, this repo probably isn't the right place to have this product-level discussion; @davismtl assigning to you for triage and/or migration to the right tool.

**Comment by davismtl** [comment]
> A lot of Chrome users don't try Firefox since it cannot sync bookmarks without a new signup.
> Basically users go to the account page, see the signup page and drop it.

Before closing this card in this repo, I'm interested in knowing where this feedback was captured. I'd love to understand the context more.

During user testing and user research, we haven't heard any desire for this. I haven't seen this through SUMO or social media either. Additionally, we asked users via a survey (granted 2 years old so not recent) if they would prefer to use a 3rd party login and it was a majority who didn't want to. More recently, the IAM team asked us to integrate FxA on Mozilla's various sites because users don't want to use 3rd party logins.

All in all, it's something we've considered before but most of the data was pointing us to believe that nobody wanted it. If you have data or feedback that is telling us otherwise, we'd certainly like to consider it! Given it's a very big chunk of work, I just want to be sure that we collect all the facts first.

Thanks in advance

**Comment by davismtl** [comment]
> A lot of people just want to test out Firefox before switching. Some people believe that being logged into Google is a "Chrome integration" that Firefox lacks https://www.makeuseof.com/tag/chrome-vs-firefox-android-browser/

Just saw this post. I think there is a difference between signing into Google to use Sync vs having the browser signed into Google for easy access to Google services. 

Another element covered in the article around accounts was profile switching which doesn't require a Google Account for us to do. (although still very complicated)

Lastly, it seemed like the concern was more about no proper integration to Android OS (Google Now) which I am unsure requires to be signed into a Google Account in the browser.

All in all, the concerns brought up in that article seem to be unrelated to Sync and FxA. IIUC, it seems more like a lack of proper OS integration.

**Comment by andreicristianpetcu** [comment]
I actually do a lot of support on Twitter and Reddit and I bump into this issue several times before. I am not only interested in support but also if pople switch browsers from and to Firefox. Usually people say stuff like "yeah, Firefox, I would switch to you if you had X feature". I ask more info about this X feature. Some people say that they want bookmarks sync then I say that you can do this and point them to some relevant page. This is usually where they say "yeah but I need a new account, Chrome works with my existing account". If we have a log in with Google + the import data from Cbrome, it would be very easy to convert people.

Social support completly ignrores non-Firefox users. People who use Chrome but see all the news about Firefox. This is due of how Buffer works, tweets need to be @ firefox to show up in Buffer.

I also had this complaint from a work coleague: "I will not switch to FF since Chrome is so well integrated into my workflow. I just log in once and I sync my stuff". I tried to tell him that he can create an account in 30s but he would not listen, People on the web hate creating new accounts.

I will post here any future conversation I will have on Twitter on this subject if this is ok with you. I cannot find my previous conversations since I tweet A LOT!

**Comment by andreicristianpetcu** [comment]
Found an unrelated conversation. He first says he likes Chrome for sync, then he is told FF has sync then he says Google Account is more convenient.

https://twitter.com/AL_HD90/status/959741881100972033 and https://twitter.com/AL_HD90/status/959807245625249792

I was not part of this conversation, I was searching for my tweets and found this.

**Comment by davismtl** [comment]
Thanks for sharing and please share with us as you uncover more of this feedback. It's much appreciated.

**Comment by vladikoff** [comment]
> Anyways, this repo probably isn't the right place to have this product-level discussion; @davismtl assigning to you for triage and/or migration to the right tool.

👍 

@davismtl to link to follow up bugs if there are any

**Comment by andreicristianpetcu** [comment]
If you have any bugzilla item for this issue please share it here also.

**Comment by andreicristianpetcu** [comment]
@davismtl here is more of the feedback you wanted: Digital Trends mentiones sign in with Google & sync as one of Chrome's advantages that make it superiour "Sign into your Google account on one device and all your Chrome bookmarks, saved data, and preferences come right along. It’s a standard feature you can find on other platforms, but Chrome’s integration is second to none." https://www.digitaltrends.com/computing/best-browser-internet-explorer-vs-chrome-vs-firefox-vs-safari-vs-edge/

**Comment by davismtl** [comment]
The argument they are presenting is around awesome data syncing and not that you can use Google Accounts to login.

On the topic of syncing, I disagree about their view of how Chrome is second to none given Firefox Sync encrypts your data better, syncs all the same data types, allows you to find Synced Tabs easily and to send tabs between devices. But at that point, it means we don't do a good enough job communicating about it about those additional benefits. Improved communication is certainly something we can and will work on.

**Comment by andreicristianpetcu** [comment]
My interpretation was that it syncs with a google account implying that people already have a g account. Agree with you on the other topics.

**Comment by andreicristianpetcu** [comment]
> The one problem is that it does have a slow start-up when loading and installing it can be a struggle as users have to create an account for use on other devices.

https://www.techworld.com/picture-gallery/developers/firefox-vs-chrome-which-browser-is-best-for-your-business-3675411/

**Comment by andreicristianpetcu** [comment]
> I mostly just use Chrome because it connects to my Google account, which makes syncing my history and bookmarks super easy.

https://www.reddit.com/r/chrome/comments/8oos89/comment/e062iub

I will add here info about people who use Chrome mainly because they have a Google account and not a Firefox Sync account.

**Comment by davismtl** [comment]
I've asked for clarification from that person because I suspect they don't know they can also sync in Firefox.
https://www.reddit.com/r/chrome/comments/8oos89/firefox_dropped_below_the_10_share_value_on/e08j947

**Comment by andreicristianpetcu** [comment]
> Firefox quantum is beautiful, super fast and I love everything about it but basically I'm heaviliy inside the google ecosystem and not being able to have a google-sync account where I have all my favorites page, my password stored, my history that influence my google news and all of that is synced directly with my phone... Well it's really a thing for me.

Same issue here.

https://www.reddit.com/r/firefox/comments/8p56yj/why_im_not_using_firefox_even_tho_i_love_it/

Thank you for asking that and for still being interested in this issue @davismtl 

Also here is an ideea.... maybe if the users see a google logo on the log in page they will be more interested in signing in with google. But instead of a normal sign in, you would get the user's gmail account and send a signup email there also by explaining why they need to also set a password.

**Comment by davismtl** [comment]
Unfortunately, his reason for wanting Google Accounts isn't really possible because we can't import data via OAuth and we can't write back either due to limited APIs.

At this time, the best way to get your Chrome data into Firefox is via import.
