### ISSUE TITLE
Installation fails on Debian Stretch i386

### ISSUE THREAD

**Issue by shapirus** [mozilla/fxa-auth-server#2301]
Compilation error in a dependency package (scrypt-hash):

> ../crypto_scrypt-sse.c: In function ‘blkxor’:
> ../crypto_scrypt-sse.c:102:8: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
>    D[i] = _mm_xor_si128(D[i], S[i]);
>    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
> In file included from ../crypto_scrypt-sse.c:33:0:
> /usr/lib/gcc/i686-linux-gnu/6/include/emmintrin.h:1286:1: error: inlining failed in call to always_inline ‘_mm_xor_si128’: target specific option mismatch
>  _mm_xor_si128 (__m128i __A, __m128i __B)
>  ^~~~~~~~~~~~~
> ../crypto_scrypt-sse.c:102:10: note: called from here
>    D[i] = _mm_xor_si128(D[i], S[i]);
>           ^~~~~~~~~~~~~~~~~~~~~~~~~
> scrypt.target.mk:103: recipe for target 'Release/obj.target/scrypt/crypto_scrypt-sse.o' failed
> make: *** [Release/obj.target/scrypt/crypto_scrypt-sse.o] Error 1
> make: Leaving directory '/home/mozsync/mozsync/fxa-auth-server/node_modules/scrypt-hash/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> 

Builds successfully, however, with `export CFLAGS="-msse4.1"`

The package in question is probably unmaintained, last updates happened over 3 years ago. There is a similar issue for it that's been opened since 2014 (https://github.com/dannycoates/scrypt-hash/issues/4) that I've updated as well.

**Comment by jrgm** [comment]
What hardware platform are you building on?

**Comment by shapirus** [comment]
That's a Linode-1024 instance, kernel version 4.14.14-x86_64-linode94.

**Comment by rfk** [comment]
@shapirus thanks for the report; could you please test whether https://www.npmjs.com/package/scrypt installs OK for you?  It looks to be a fairly similar package (wrapper around native code, async via `Nan::AsyncQueueWorker`) that we might be able to use as a replacement without too much hassle.

**Comment by vladikoff** [comment]
Please see https://github.com/dannycoates/scrypt-hash/issues/4#issuecomment-199941565

**Comment by vladikoff** [comment]
We can discuss further there if u still have issues

**Comment by shapirus** [comment]
@rfk https://www.npmjs.com/package/scrypt builds just fine, even without any warnings.

@vladikoff that solution is not relevant, since it applies to a several years' older system. Debian Stretch is newer and has gcc well above 4.8 (namely 6.3.0), and the compilation error is different.

For me personally, a "-msse4.1" workaround solves the issue, but in the long term it might be better to avoid using a package that, even though its compilation (only?) fails in a rare, these days, i386 environment, looks like an abandoned one. Especially if there is an easy alternative.

**Comment by vladikoff** [comment]
> in the long term it might be better to avoid using a package that, even though its compilation (only?) fails

The package author still works at Mozilla and if it breaks in future versions of Node we will kindly ask him to update it :)

> Especially if there is an easy alternative.

We initially wanted to use https://www.npmjs.com/package/scrypt but it didn't work out so well. I forgot what the issue was. It has some complications with the API or installation as well.

**Comment by vladikoff** [comment]
> We initially wanted to use https://www.npmjs.com/package/scrypt but it didn't work out so well. I forgot what the issue was. It has some complications with the API or installation as well.

That was 3-4 years ago, this might have changed now.
