### ISSUE TITLE
Use default args rather than "options" param in ./test/client/

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2308]
Default args are cool, options arguments are annoying, and the test client API uses a lot of them.

**Comment by vladikoff** [comment]
👍

**Comment by vladikoff** [comment]
This issue basically deals with removing `options = options || {}` code with something like:

```js
function Module(options = {}){
```

**Comment by hritvi** [comment]
Hey! Can i take this issue @vladikoff @rfk ?

**Comment by vladikoff** [comment]
@hritvi Hey! Yeap, basically find where we use `options = options || {}` or `opts = opts || {}` and replace that with Default params https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters and send a pull request

**Comment by hritvi** [comment]
Hey @vladikoff ! I can't figure it out what went wrong in the pull request . Can you please help me out in this. Thanks :)
