### ISSUE TITLE
TOTP Notification emails

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2310]
from mtg:
- [x] Send an email when TOTP enabled
- [x] Send an email when TOTP disabled
- [x] New device sign-in with TOTP (reusing new device sign-in)
- [ ] New recovery codes generated
- [ ] Recovery code used for login

**Comment by ryanfeeley** [comment]
Here is copy for 1.

> `From: accounts@firefox.com`
> `Subject: Two-step authentication enabled`
>
> **Two-step authentication enabled**
> You have successfully enabled two-step authentication on your Firefox Account. Security codes from your authentication app will now be required at each sign-in.
> [ Manage account ]

Any suggestions on fine print? If an intruder has turned this on, it's going to be very hard to turn off. Impossible?

For 2 and 3, I imagine our **New sign-in to Firefox** emails will suffice without change.

**Comment by rfk** [comment]
from mtg: looks like we have everything we need to work on this for 108.

**Comment by ryanfeeley** [comment]
@vbudhram added location info above.

**Comment by vladikoff** [comment]
from mtg: 109 will have recovery code emails
