### ISSUE TITLE
Check TOTP during password reset

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2311]
Users with TOTP enabled should not be able to reset their account without entering a valid TOTP code.  @vbudhram @ryanfeeley do we have UX designed for doing a TOTP prompt in the password-reset flow?

API-wise, this will look a little different to what we're doing for session tokens, because there's no sessionToken involved in the password reset flow.  I think we have two options.  We could either accept the verification code in the request body for `/account/reset`, like this:

```
> POST /account/reset
> Authorization: Hawk account-reset-token
> {
>    "authPW": "NEW_AUTHPW",
>    "sessionToken": true
>}
.
< 401 Unauthorized
< {
<    "code": 401,
<    "errno": 154,
<    "message": "Verification code required"
< }

------

> POST /account/reset
> Authorization: Hawk account-reset-token
> {
>    "authPW": "NEW_AUTHPW",
>    "sessionToken": true,
>    "verificationCode": "TOTP_CODE_HERE"
>}
.
< 200 OK
```

Or, we could add verification state to the `accountResetToken`, and require the caller to call `/SOMETHING/totp/verify` with the `accountResetToken` before using it for `/account/reset`.

I kinda lean towards the first option for simplicity.

**Comment by rfk** [comment]
From discussion with @vbudhram: we should definitely do this before declaring the feature "done", but maybe we can ship a preview release behind a feature-flag without having implemented this check?  To discuss.

**Comment by vbudhram** [comment]
While we still want to complete this, it has been backlogged in favor other tasks. Not that currently, users that complete a password reset will still have to enter their password when the attempt to re-login. Because of this, the security risk is much lower.

**Comment by rfk** [comment]
We haven't had any complaints about the current behaviour, and we were comfortable enough with it from a security perspective to ship.  We're going to WONTFIX this for now, unless we get feedback from users that we need it.
