### ISSUE TITLE
 Check TOTP during password change

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2313]
The `/password/change/start` route accepts an email and password, and returns a verified keyFetchToken.  For users with TOTP enabled, it feels like we should require a TOTP code here as well - otherwise a compromise of account credentials will allow an attacker to access key material through this endpoint without doing a TOTP verification.

**Comment by rfk** [comment]
This might be too ambitious for Q1, but hear me out...I think we should deal with this by completely revamping the way we do password change.

Right now, you have to do a password change in three steps:

1. Call to `/password/change/start` to prove you know the current password, and to get a `keyFetchToken` so that you can calculate an updated value for `wrapKb`.  This returns a `passwordChangeToken` that you need to use for step 3.
2. Use the `keyFetchToken` to fetch `wrapKb`, and re-wrap it using the new password.
2. Use the `passwordChangeToken` to call `/password/change/finish` to provide the new password and updated `wrapKb`.

The content-server wraps these in some additional calls to `/account/login` because it really wants a sessionToken that persists across the password change, but the `/password/change/` API makes that awkward.

What if we got rid of the `passwordChangeToken` and just offered a single `/password/change` endpoint that was authenticated directly with a `sessionToken`?  The password-change flow might then look something like this:

1. Prompt the user for their current password.  Either use `/account/login` to generate a new `sessionToken` and `keyFetchToken`, or use `/session/reauth` to reauth an existing one and get a fresh `keyFetchToken`.
2. Use the `keyFetchToken` to fetch `wrapKb`, and re-wrap it using the new password.
3. Use the `sessionToken` to call `/password/change` to provide the new password and updated `wrapKb`.  This endpoint can check the `authAt` timestamp on the session and error out of the password was not provided recently.

This would give us TOTP handling for free in step (1), and would simplify some of the current awkwardness around this flow in the content-server.

**Comment by rfk** [comment]
From discussion with @vbudhram: we should definitely do this before declaring the feature "done", but can likely ship a preview release behind a feature-flag without having implemented this check.

**Comment by vbudhram** [comment]
> What if we got rid of the passwordChangeToken and just offered a single /password/change

I'm 👍🏽 for this proposal. Some additional thoughts

* If a user entered TOTP code to login, they should not have to enter a TOTP code to change password, since the session was verified with TOTP.
* If there are existing unverified sessions, and TOTP was enabled on another session, then attempts to `/password/change` should returned unverified.
* Optionally, it would be nice to move away from hashing email and password during this step.

**Comment by vladikoff** [comment]
from mtg: need to confirm how others do this

@ryanfeeley how do you want this to look like?

Please also see https://github.com/mozilla/fxa-auth-server/issues/2312 and https://github.com/mozilla/fxa-auth-server/issues/2311

**Comment by vbudhram** [comment]
With https://github.com/mozilla/fxa-auth-server/pull/2437 merged, we can move this to the backlog.

**Comment by rfk** [comment]
I think we should just close it, we're doing what it says in the bug title and the broader refactor can come at a later time.
