### ISSUE TITLE
Add pushbox as an "attached service"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2319]
The new ["pushbox" service](https://docs.google.com/document/d/1YT6gh125Tu03eM42Vb_LKjvgxc4qrGGZsty1_ajf2YM/edit#heading=h.mt5o69jf1o39) will be acting as an FxA service provider and hosting a small amount of (encrypted) data for the user's account.  We should connect them up to the SQS feed of account events for attached services, so that pushbox can:

* Learn about account deletions, and destroy the user's data
* Learn about device deletions, and destroy data stored for for that device

**Comment by rfk** [comment]
On the pushbox side, they'll need some sort of script to receive and process the account events, similar to this one used by the sync tokenserver:

  https://github.com/mozilla-services/tokenserver/blob/master/tokenserver/scripts/process_account_events.py

**Comment by vladikoff** [comment]
from mtg: waiting for production pushbox

**Comment by rfk** [comment]
@eoger I wonder if we can close this, and its partner over in https://github.com/mozilla-services/pushbox/issues/10#issuecomment-369767886, and just do the delete directly from FxA as part of the call to `/account/destroy`?

**Comment by eoger** [comment]
I think you have to make a request for each service "inbox" you want to delete which is not ideal. However if we end up with the "single inbox" solution I described in the email I sent earlier this week, it makes total sense 👍

**Comment by rfk** [comment]
> However if we end up with the "single inbox" solution I described
> in the email I sent earlier this week, it makes total sense

@eoger IIUC we did in fact end up with the "single inbox" situation, so should we revisit this?

**Comment by eoger** [comment]
Agree, we should do this

**Comment by rfk** [comment]
Hmm...on reflection, I think it will be simpler *from the auth-server's perspective* if we keep this using the SQS notifications rather than doing it inline.  Doing it inline means teaching other parts of the auth-server codebase about pushbox, and it seems valuable to keep that knowledge as contained as possible.

Let's give this a shot and see how it shakes out on the pushbox side, then we can revisit.

What do we need in order to unblock this bug @eoger @jrconlin - is it just a matter of e.g. getting the event flowing in a dev environment for testing?

**Comment by rfk** [comment]
Hrm, actually this comment from the linked [pushbox issue](https://github.com/mozilla-services/pushbox/issues/10#issuecomment-385591280) seems to suggest we can't use the existing SQS messages for this:

>Due to using the device-id in the index, we have no way to do query ranges
> for all the device id's per fxa uid, so the delete's will need to be for each device.

So we may indeed have to do this manually on device disconnect, account reset, account deletion...basically any event that might cause a device id to be deleted.  Bleh.

**Comment by rfk** [comment]
Either way, I think this can be unblocked and some action taken on the FxA side.

**Comment by jrconlin** [comment]
I noted in the [pushbox issue](https://github.com/mozilla-services/pushbox/issues/10#issuecomment-386638306) that we'd need the uid:deviceid combo for pushbox. Rustbox makes it a bit easier to delete all devices for a given uid, (although I'd have to add code to do that, with enough safeguards).

If there's a good schema change we should consider, now is a good time to implement it. ;)

**Comment by rfk** [comment]
I think "delete all data for a given uid" is a valuable operation to be able to perform, if it's possible to make the schema support this then we should definitely do so.

**Comment by shane-tomlinson** [comment]
@rfk - is this still tracking for train-114?

**Comment by vladikoff** [comment]
from mtg: need new queues...

what is pushbox.dev using? --> stable.dev!

**Comment by vladikoff** [comment]
blocked by production pushbox

**Comment by jrconlin** [comment]
Related [operational bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1459667)

**Comment by vladikoff** [comment]
from mtg: need to check prod status

**Comment by rfk** [comment]
Pushbox is live in prod; if the SQS queues are hooked up then we should be OK to close this out.

**Comment by vladikoff** [comment]
@jrconlin could you confirm that the queues issue got fixed?

Moving to "blocked", waiting for deploys now...

**Comment by jrconlin** [comment]
Pushbox 0.1.2 consumes all messages it reads off of the SQS queue.

**Comment by vladikoff** [comment]
> Pushbox 0.1.2 consumes all messages it reads off of the SQS queue.

Awesome Thank you!!
