### ISSUE TITLE
Add ability for devices to learn what capabilities their peers support

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2320]
For the [new send-tab system](https://docs.google.com/document/d/1YT6gh125Tu03eM42Vb_LKjvgxc4qrGGZsty1_ajf2YM/), we want to add a new message type (#2318) that up-to-date devices can use to send tabs between themselves.  In order for this to work in a backwards-compatible fashion, the sending device needs to be able to determine whether or not the receiving device supports the new push message type (and if it doesn't, to fall back to the old method of sending).

@mhammond has sketched out some initial thoughts on how this might work here:

  https://docs.google.com/document/d/1YT6gh125Tu03eM42Vb_LKjvgxc4qrGGZsty1_ajf2YM/edit#heading=h.872x2btqp7nb

But that's just suggestions, and we should feel free to design something that works well for FxA and fits into our existing API.  I think we have a bit of design work to do here before we can implement anything, but I wanted to get the bug on file for further discussion.

**Comment by rfk** [comment]
Notes from IRC discussion with @eoger:

* We introduce an open-ended notion of "device  capabilities".
* "device capabilities" is a set of strings, taken from a known list that we expect to grow over time
* when you read info about a device from the fxa-auth-server, you'll get a new "capabilities" attribute that is a list of capability strings
* devices include their capabilities in their device registration record, there's no API for adding/removing capabilities apart from updating the device registration record
* on the backend, we map the capability strings into enums for efficient storage, and store them in a one-to-many join table named e.g. "deviceCapabilities"

**Comment by eoger** [comment]
This is done! 🎉
