### ISSUE TITLE
Updates to `Verify primary email` template

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2322]
from mtg:

* Include ip, device info, location, timezone by passing to mailer function
* Update footer text to `If you did not authorize this action, please change your password. For more information, please visit Mozilla Support.`

cc @ryanfeeley

**Comment by vladikoff** [comment]
@vbudhram we already have location here: https://github.com/mozilla/fxa-auth-server/blob/master/lib/senders/partials/verify_primary.html#L9 Am I looking at the wrong template?

**Comment by vbudhram** [comment]
The template is correct, however it is not being passed the location data to render. This is how the email actually looks

![screen shot 2018-03-13 at 10 39 42 am](https://user-images.githubusercontent.com/1295288/37348649-0179e516-26ab-11e8-89dc-4760aae35aa2.png)

**Comment by vladikoff** [comment]
oh wild!
