### ISSUE TITLE
Migrate to `Buffer.from`

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#2333]
Some instances of old syntax: 

![image](https://user-images.githubusercontent.com/128755/37221075-a3cfcba4-2396-11e8-903c-1013140b984f.png)

Related: https://github.com/mozilla/fxa-auth-db-mysql/issues/311
Related: https://github.com/mozilla/fxa-auth-db-mysql/issues/316

cc @deeptibaghel

**Comment by deeptibaghel** [comment]
Thanks @vladikoff , i will complete it :)

**Comment by vladikoff** [comment]
👍  🏅
