### ISSUE TITLE
Pass an encoded hex email to DEL /emails

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2334]
From https://github.com/mozilla/fxa-auth-db-mysql/pull/315/files, we also need to update the auth-server [delete email endpoint](https://github.com/mozilla/fxa-auth-server/blob/45ae7b2048e9115590611a55454627d3840119a8/lib/db.js#L1102), to pass an encode email, similar to https://github.com/mozilla/fxa-auth-server/blob/45ae7b2048e9115590611a55454627d3840119a8/lib/db.js#L1069

**Comment by deeptibaghel** [comment]
@vbudhram , i will do it.

**Comment by vladikoff** [comment]
👍
