### ISSUE TITLE
Audit metricsContext payloads

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2376]
Continuing from the discussion in https://github.com/mozilla/fxa-content-server/pull/5992#discussion_r177963118, there might be some cases where we're sending `metricsContext` to the auth server when it already exists in memcached.

This isn't a big deal, but I think the model we were aiming for was that it only needs to be sent to the "entrypoint" routes, and after that we should lean on the cache. It was never really documented or communicated anywhere though, so in addition to sorting it out we should also look at documenting it properly. Maybe in `docs/metrics-events.md` or perhaps a new doc linked to from that one.

Even better than that, can we encapsulate the definition in code so that the "entrypoint" endpoints are an actual thing? Off the top of my head, it seems like any route that is authenticated with a token should not need `metricsContext`. If that's true (ish), we might be able to consider something in `lib/server.js` that automatically sets `metricsContext` on the endpoints where it's needed. Or not, if that seems too weird and magical.

**Comment by rfk** [comment]
> Even better than that, can we encapsulate the definition in code so that the "entrypoint" endpoints 
> are an actual thing?

👍 I think this sounds pretty worthwhile FWIW

**Comment by arunikayadav42** [comment]
Hello I am new to open source and have basic knowledge of JS!Can I please get started with contributing to this project?

**Comment by philbooth** [comment]
There's more and better discussion about this in #2496, closing this.
