### ISSUE TITLE
ECONNREFUSED during npm t

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2383]
Is there something I'm supposed to have running on port 4100 that I don't know about? If not, can we shut this error up? It vexes me.

```
test.ERROR: Notifier.publish {"op":"Notifier.publish","err":"NetworkingError: connect ECONNREFUSED 127.0.0.1:4100"}
```

**Comment by vladikoff** [comment]
We should disable SQS Notify in tests or at least the fake the Notifier

**Comment by philbooth** [comment]
(or mock the log object)

**Comment by vladikoff** [comment]
> (or mock the log object)

sorry that is what i meant when i said  "fake the Notifier" , oops
