### ISSUE TITLE
Set correct `authenticatorAssuranceLevel` when verifying with recovery code

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2385]
From https://github.com/mozilla/fxa-content-server/pull/5992#issuecomment-378895940, a user that verifies a session using a recovery code does not have the same privledges as a user that verifies using a TOTP code. The side affect of this is that they will not be able to remove the TOTP token after logging in with recovery code.

Since recovery codes are considered another form of authentication and one time use, I think should give them the same assurance level as TOTP.

**Comment by rfk** [comment]
👍   IIRC the plan was to add another verificationMethod specifically for recovery codes, in which case we just need to map that string to `otp` here:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/authMethods.js#L16

And all the other authenticatorAssuranceLevel stuff should Just Work as intended.
