### ISSUE TITLE
update amo-account-change-stage sqs to get messages from accounts.firefox.com

### ISSUE THREAD

**Issue by eviljeff** [mozilla/fxa-auth-server#2387]
https://sqs.us-east-1.amazonaws.com/142069644989/amo-account-change-stage is getting it's messages from accounts.stage.mozaws.net apparently, but amo stage (addons.allizom.org) uses fxa prod (accounts.firefox.com) instead.  Can you switch the queue to get messages from fxa prod instead?

**Comment by eviljeff** [comment]
AMO stage (addons.allizom.org) is generally available to anyone to use, though is typically only used by the addons teams at Mozilla, and QA (softvision).

As mozilla/addons-server#6451 is about updating emails addresses _without_ users logging in it's really only about keeping email addresses up to date for when we email users (login updates the email address without SQS being involved).  We don't email users on stage and dev so outside of production AMO it's actually pretty much useless anyway, we just want to be able to test it before it goes live.

So if you want to limit the messages to certain email addresses that's fine for mozilla/addons-server#6451 as long it covers MOCO & QA.

However, mozilla/addons-server#7922 is about listening to account deletion messages too.  We're still trying to get clarification from legal, but if we _do_ have to delete AMO accounts when the FxA account is deleted, then there **may** be a legal requirement under GDPR to also delete a user's account on AMO stage too, and we can't know in advance if they'd be MOCO/QA.

**Comment by eviljeff** [comment]
@rfk do you have a rough idea of when you would be able to implement the filtering necessary to allow you to enable the change requested in comment#0?

**Comment by vladikoff** [comment]
from mtg: need to chat about this in the devops meeting

**Comment by rfk** [comment]
from mtg: this should be fine if we filter the stream down to only "delete" events, which contain only the account uid rather than email address

**Comment by rfk** [comment]
> this should be fine if we filter the stream down to only "delete" events,
> which contain only the account uid rather than email address

Actually no, I'm confused here, from the above discussion we can *ignore* the deletion events but AMO needs to know about the email-change events, which do indeed contain email addresses.

**Comment by rfk** [comment]
@jbuck, from your investigation of the SQS/SNS filtering feature does it seem possible to look for messages with `event: "primaryEmailChanged"` and `email: /@(mozilla\.com|softvision\.(com|ro)$/`?

**Comment by jbuck** [comment]
So it looks like we'll need to do some code changes to get [message filtering](https://docs.aws.amazon.com/sns/latest/dg/message-filtering.html) to work - it filters based on message attributes which is JSON metadata you can attach to the message. But then we can add any message attributes and files we want.

**Comment by eviljeff** [comment]
@jbuck / @rfk can we get a rough timescale on making the code changes on fxa-server?

**Comment by rfk** [comment]
Let's try to do this for fxa train-111, which will be in stage next week and in prod the week after.  I made a start on the necessary code changes for message filtering here:

  https://github.com/mozilla/fxa-auth-server/pull/2410

@jbuck if we can verify this works in a dev environment some time this week, we should be able to land it for train-111.

**Comment by jbuck** [comment]
So, cross-account cross-region SNS/SQS integration is a useless pile of junk.

This [Terraform documentation](https://github.com/hashicorp/terraform/pull/9838/files) describes the problems you'll run in to when attempting to do this.

I decided to create both queues in prod because that actually works.

@eviljeff You'll need to get someone to update the configuration/permissions, but they simply need to change what queue they're pulling from:

* https://sqs.us-west-2.amazonaws.com/361527076523/amo-account-change-stage
* https://sqs.us-west-2.amazonaws.com/361527076523/amo-account-change-prod

I haven't setup message filtering yet because cloudformation doesn't support that, but I'd be happy to see that fetching from the queue is working first anyways

**Comment by eviljeff** [comment]
@jbuck I changed the url in addons-server settings, and we've deployed it to amo stage.  Are there other permissions/configurations to be changed on your side/aws?  (It's not working, from a qiuck test)

**Comment by jbuck** [comment]
@eviljeff yeah, I had to update the IAM role in https://github.com/mozilla-services/cloudops-deployment/pull/2035

**Comment by jbuck** [comment]
Alright, seems to be working on stage now. Ready for QA!

**Comment by eviljeff** [comment]
looking good from our end!
