### ISSUE TITLE
Check SMS budget status in /sms/status

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2399]
As @rfk pointed out in https://github.com/mozilla/fxa-content-server/issues/6077#issuecomment-382190093, we don't want to pollute the content server backend with stuff related to SMS.

The content server already makes a request to `/sms/status` before rendering the SMS view. It seems straightforward enough to include a budget check in that endpoint and `&&` the result into the `ok` property of the response payload.

Of course, the check would not be made inline by every auth server instance every time it handles a status request. Instead we'd keep the flag in Redis and update it periodically.

**Comment by shane-tomlinson** [comment]
@philbooth - this would act similar to when we had Nexmo and checked the account balance?
