### ISSUE TITLE
Notify user of low recovery codes

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2409]
From https://docs.google.com/document/u/1/d/1m4D_7DZAfXt4e-bEbfI-5s_x2XFO7TEQo1a_SQcj1O8/edit, one of the requirements for Q2 was to notify users when they are low on recovery codes and prompt them to generate new ones. This value should be configurable amount.

**Comment by vbudhram** [comment]
This is fixed!

**Comment by SorinaFlorean** [comment]
Tested on stage server - Train 112 ( platforms Android, Win 10).  the emails started when there was only two codes to use, and continued until I generate new ones (after I used all codes). 
![2018_05_18_15_36_50_low_recovery_codes_remaining_sflorean_mozilla com_mozilla_mail](https://user-images.githubusercontent.com/24588037/40237873-50ee58fa-5aba-11e8-942c-f6549e2a2aed.png)

**Comment by vbudhram** [comment]
@SorinaFlorean Cool, that works as intended 👍🏽
