### ISSUE TITLE
Bulk-Mailer references module that no longer exists, `../mailer/index.js`

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2416]
> ➜  scripts git:(master) node bulk-mailer.js                                                                                 git:(master|)
{"Timestamp":1525267633595000000,"Logger":"bulk-mailer","Type":"uncaughtException","Severity":0,"Pid":94047,"EnvVersion":"2.0","Fields":{"error":"Error: Cannot find module '../mailer/index'","stack":"\n    at Function.Module._resolveFilename (module.js:547:15)\n    at Function.Module._load (module.js:474:25)\n    at Module.require (module.js:596:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/Users/shanetomlinson/development/fxa-auth-server/scripts/bulk-mailer.js:14:14)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)"}}

We used the bulk-mailer to send [Password reset required emails](https://github.com/mozilla/fxa-auth-server/blob/7a5e80a4d59d0f394c31d740a5a6145b0a9a024d/lib/senders/templates/password_reset_required.html#L1) a couple of years ago. We have refactored how emails are sent since then and `../mailer/index` no longer exists, the Mailer is now located at [lib/senders/email.js](https://github.com/mozilla/fxa-auth-server/blob/master/lib/senders/email.js).

**Comment by shane-tomlinson** [comment]
Assigning to myself, I don't like having this broken.

**Comment by philbooth** [comment]
@shane-tomlinson, we've bitten by this before in this repo, scripts suffering from bit-rot as the production code changes. It's made me think we should start writing basic tests for the scripts directory.

If you have time to add a basic automated test while you fix it, it might help reduce the likelihood of breaking again in the future.

**Comment by shane-tomlinson** [comment]
>  It's made me think we should start writing basic tests for the scripts directory.

Wholeheartedly agree!

**Comment by vbudhram** [comment]
Bumping this to 124, since there are a couple things that need to be fixed.
