### ISSUE TITLE
Asked to sign into Sync on other devices whenever I connect a new device

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2419]
Last night I signed into Sync on my tablet. When I came back to my laptop this morning, Firefox told me I had to re-connect to Sync by signing into FxA. The strange thing is when I opened the device list, the laptop had just synced 1 minute ago, and I have two entries for the tablet.

<img width="551" alt="screen shot 2018-05-03 at 09 25 33" src="https://user-images.githubusercontent.com/848085/39568574-90e49714-4eba-11e8-9e8f-555a60dc7af6.png">

My location was removed.

**Comment by mhammond** [comment]
Ouch. Does about:sync-log on the tablet show any logs from that time?

**Comment by philbooth** [comment]
And the location data is gone for *all* devices, which seems weird and troubling.

And yet it still picked the location-enabled branch in the template, leaving us with that hanging `near...`, which is doubly weird and troubling. The content server contains [logic in app/scripts/views/settings/clients.js](https://github.com/mozilla/fxa-content-server/blob/2a55dd5bc2526a14722ebe367b5524f9b8b9c3d7/app/scripts/views/settings/clients.js#L147-L158) that is supposed to at least omit the `near...` part when we don't have a location.

**Comment by shane-tomlinson** [comment]
> And the location data is gone for all devices, which seems weird and troubling.

Sorry, I should have been more clear. I manually removed the location data. The public knows I'm around London, they don't need to know which part.

**Comment by philbooth** [comment]
> Sorry, I should have been more clear. I manually removed the location data.

Oh! I should have realised that's what you meant, lol.

**Comment by philbooth** [comment]
@shane-tomlinson maybe what you're seeing here is the same behaviour that all these people are getting:

https://sql.telemetry.mozilla.org/queries/4837/source#9867

**Comment by shane-tomlinson** [comment]
I no longer have the logs from way back, and I haven't seen this since. Closing until it happens again.
