### ISSUE TITLE
We shouldn't log metrics events for unknown routes

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2423]
From a recent discussion on dev-fxacct, a server misconfiguration lead to some requests for unknown URLs to the auth-server, and the following log output:

```
fxa-auth-server.DEBUG: server.onRequest
fxa-auth-server.INFO: request.summary {"op":"request.summary","code":404,"errno":999,"rid":"1525718907949:linux-box:7129:jgtxgn8h:10055","path":"/bundle-ba35c2d66b86a6485c3243f4ca7d121be2c892c9/app.bundle.de.js","agent":"Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0","t":1,"uid":"00"}
fxa-auth-server.ERROR: metricsEvents.emitFlowEvent {"op":"metricsEvents.emitFlowEvent","event":"route./bundle-ba35c2d66b86a6485c3243f4ca7d121be2c892c9/app.bundle.de.js.404.999","missingFlowId":true}
```

It seems weird that we're trying to log a flow event on a completely non-existent route.  I wonder if the filtering list here:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/metrics/events.js#L52

Should be an include-list, rather than an ignore-list.

**Comment by philbooth** [comment]
The other thing we could do is just not emit the event whenever response status is 404.
