### ISSUE TITLE
/recovery_email/resend_code throwing a 500

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2433]
Found this from failures on team-city and travis, then updating fxa-auth-server and re-installing all deps.

> request.summary {"op":"request.summary","code":500,"errno":999,"rid":"1525981272320:stomlinson-30887:80760:jh0xrfiu:10018","path":"/v1/recovery_email/resend_code","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0 FxATester/1.0","remoteAddressChain":["127.0.0.1"],"t":34,"uid":"3bc3ccd491d64a84a941f01ad2cafdf5","stack":"Error: Not Found\n    at handleResponse (/Users/shanetomlinson/development/fxa-local-dev/fxa-auth-server/lib/pool.js:67:19)\n    at RequestSet.callback (/Users/shanetomlinson/development/fxa-local-dev/fxa-auth-server/node_modules/poolee/lib/pool.js:151:4)\n    at RequestSet.handleResponse (/Users/shanetomlinson/development/fxa-local-dev/fxa-auth-server/node_modules/poolee/lib/request_set.js:66:8)\n    at Endpoint.complete (/Users/shanetomlinson/development/fxa-local-dev/fxa-auth-server/node_modules/poolee/lib/endpoint.js:162:11)\n    at Endpoint.succeeded (/Users/shanetomlinson/development/fxa-local-dev/fxa-auth-server/node_modules/poolee/lib/endpoint.js:168:8)\n    at IncomingMessage.gotEnd (/Users/shanetomlinson/development/fxa-local-dev/fxa-auth-server/node_modules/poolee/lib/endpoint.js:326:8)\n    at emitNone (events.js:111:20)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"}

cc @vbudhram

**Comment by shane-tomlinson** [comment]
Then on the auth-db server logs, I see:

> 1|auth-ser | {"Timestamp":1525981477868000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":4,"Pid":80756,"EnvVersion":"2.0","Fields":{"code":404,"route":"unknown","method":"GET","path":"/emailBounces/746573745f7369676e696e302e3931323537343434383936393230353640726573746d61696c2e6465762e6c6369702e6f7267","err":"Error: Not Found","t":4}}

**Comment by vbudhram** [comment]
This was fixed in https://github.com/mozilla/fxa-auth-db-mysql/pull/352
