### ISSUE TITLE
Update emails to use Photon styles

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2448]
blocks mozilla/fxa-content-server#6083

<img width="375" alt="screen shot 2018-05-21 at 14 33 36" src="https://user-images.githubusercontent.com/848085/40310243-0885d45c-5d04-11e8-96ea-bbdf7589a7c9.png">

**Comment by vladikoff** [comment]
@shane-tomlinson please reopen if we still plan to do that. We spent some time on existing templates with Ryan F.
