### ISSUE TITLE
Should we move the mapping of SES BounceType and BounceSubType strings into this repo from fxa-auth-db-mysql

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2454]
fxa-auth-db-mysql currently accepts raw strings from SES in `createEmailBounce` and maps them to integer values. It doesn't perform the inverse transformation when returning them from `fetchEmailBounces`, so we're left with a leaky abstraction in both directions: The auth db is coupled to strings that come from SES and the auth server is coupled to the auth db's mapping to integers.

Fortunately the auth db also accepts integers, so it doesn't need to be this way. We could define the mappings in this repo and eliminate both abstraction leaks; the db would only ever know about integers and they'd be defined in one place in this repo rather than separately in both of them.

Fwiw I also feel the same way about the mappings for `DEVICE_CAPABILITIES`. It violates the principle of least astonishment to accept one data type in create and return a different one from read.

**Comment by vbudhram** [comment]
> It doesn't perform the inverse transformation when returning them from fetchEmailBounces

I think this is a worthwhile update. It should return the data type that was used when it was created. 

However, I do like the idea of the database layer being able to validate the values that are being added to it. If we ever decided to refactor auth-server or write a new service for it, it might be possible to miss some of the mappings and store some invalid values. Not sure if that is a real issue though.

**Comment by philbooth** [comment]
> However, I do like the idea of the database layer being able to validate the values that are being added to it. If we ever decided to refactor auth-server or write a new service for it, it might be possible to miss some of the mappings and store some invalid values. Not sure if that is a real issue though.

If that's a key aim, then we should at least marshall the strings to something that matches our usage in the bounce module, i.e. "hard", "soft" and "complaint". But we're not doing that, we're sending raw values directly from AWS instead. To my mind the stuff that's coupled to SES should at the very least be localised to one repo, rather than spread over two.

But actually I'd go further than that. Maybe my thinking is wrong here but I feel like the db server should be kept thin, with as much logic as possible pushed into the auth server. If the schema says something's an int, then the db server should be happy with any int. It makes more sense for the auth server to define whether specific integer values are valid, because it's the thing which uses those values.

I guess I'd characterise it as keeping logical validation close to the logic and only performing physical validation in the storage layer.

**Comment by rfk** [comment]
> It violates the principle of least astonishment to accept one data type in create and return a different one from read.

+💯

**Comment by philbooth** [comment]
We're going to have migrated away from the auth db in the email service before getting to this, let's kill it.
