### ISSUE TITLE
Map verificationMethod to an enum

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2455]
From https://github.com/mozilla/fxa-auth-server/pull/2300#discussion_r190684377 we should try to use an enum for `verificationMethod`. We currently have this mapping that could be [reused](https://github.com/mozilla/fxa-auth-server/blob/b830707e32c301753acac913d036e02a316e4ef7/lib/tokens/session_token.js#L14).

**Comment by hybrid1999** [comment]
Is this still an open issue?

**Comment by shane-tomlinson** [comment]
> Is this still an open issue?

@vbudhram can you provide some guidance?

**Comment by vbudhram** [comment]
@hybrid1999 @shane-tomlinson, took a look at this again and it really isn't an issue. Marking closed.

@hybrid1999 Feel free to check out some other issues!
