### ISSUE TITLE
[circle] 3 tests related to device capabilities alway fail

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2458]
There is no v1.113.0 auth-server tag since 3 tests always fail, e.g., https://circleci.com/gh/mozilla/fxa-auth-server/2629

(I've tried running locally but that's even worse (npm@6 first fails with `cb() not called`. Then it claims to succeed, but it didn't install `mocha`. Then, after installing `mocha`, the binary node modules weren't installed. And finally, after repairing all that, I have about 100 tests that fail. )

**Comment by rfk** [comment]
Need to revert db-server change: https://github.com/mozilla/fxa-auth-db-mysql/pull/360

**Comment by rfk** [comment]
Should be fixed by the above, closing
