### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by prundukevich** [mozilla/fxa-auth-server#2462]
Hi,
unfortunately I am unable to compile the service with existing npm-shrinkwrap.json file. Below is what I changed. 

diff npm-shrinkwrap.json npm-shrinkwrap.json_back 
3692c3692
<           "from": "git+https://github.com/mozilla/eslint-plugin-fxa.git#e082927b4c6dc17d21414e35f4c94312adbaba92"
---
>           "from": "eslint-plugin-fxa@git+https://github.com/mozilla/eslint-plugin-fxa.git#e082927b4c6dc17d21414e35f4c94312adbaba92"

**Comment by rfk** [comment]
Thanks for the report, what version of node and npm are you using?
