### ISSUE TITLE
Should `unverifiedSession` or `unverifiedAccount` return a 401?

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2465]
From https://github.com/mozilla/fxa-auth-server-private/pull/73#discussion_r193724510, both [unverifiedSession](https://github.com/mozilla/fxa-auth-server/blob/81700dae04777187b7ba5a687b9a036a14d06888/lib/error.js#L606) and [unverifedAccount](https://github.com/mozilla/fxa-auth-server/blob/81700dae04777187b7ba5a687b9a036a14d06888/lib/error.js#L257) return a 400 bad request error. Should these be 401 unauthorized?

This change will require some down stream changes to the js-client and content-server.

**Comment by rfk** [comment]
> This change will require some down stream changes to the js-client and content-server.

It's also possible that various Firefox clients would need updating, since they can sometimes trigger these errors directly.

**Comment by rfk** [comment]
Also, I'd argue for a `403 Forbidden` in this case - your auth credentials were received and processed just fine and we know exactly who you are, we're just refusing to perform the requested action because of the state of your account.

**Comment by vladikoff** [comment]
from mtg: @vbudhram triage this out of backlog?

**Comment by vbudhram** [comment]
I don't think so. I wouldn't be opposed to closing this if there isn't any intention to fix it because of the legacy client requirements.

**Comment by rfk** [comment]
I agree they probably *should* return such a status code, but I also can't see us ever getting around to doing the migration work necessary to change it.  Let's close this out unless anyone is feeling particularly inspired to take it on.
