### ISSUE TITLE
Expose ability to make the verificationMethod optional

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2466]
Currently, when using passing a `vertificationMethod` on a login a request, the auth-server will attempt to force the user to login with that method. 

In some scenarios, we would like this to be optional and only perform verification if the request needs to be verified. For example, if a successful login was just performed on this ip address or it is a new account.

We can add a new optional query param to specify whether or not the `verificationMethod` is optional (if it needs to be verified) or should be forced.

**Comment by vladikoff** [comment]
@vbudhram triage this out of backlog?

**Comment by vbudhram** [comment]
I don't have set plans to finish this, it is ok to keep in backlog.

**Comment by davismtl** [comment]
Since this is being considered for papercuts OKR, important to note that Lockbox has mentioned this in our weekly meetings. The current links provide a bad experience according to them, and I totally agree.

**Comment by rfk** [comment]
> Lockbox has mentioned this in our weekly meetings.

Is their ask to use code rather than links, or to skip this screen more frequently where possible, or both?

**Comment by davismtl** [comment]
From meeting notes to be more specific:
"Email confirmation link dropped them into Firefox for iOS, then deadended them"
