### ISSUE TITLE
Redis error "DEL can't be processed. Stream not writeable."

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2495]
This showed up in sentry:

  https://sentry.prod.mozaws.net/operations/auth-prod/issues/4427379/

It's an error thrown in lib/redis/connection.js when calling `client.delAsync(key)`.  Maybe just some operational error e.g. redis closing the socket?

**Comment by philbooth** [comment]
Interesting.

Although I've got no insight about possible root causes, I wonder if it's worth attempting some kind of retry logic in this case? The two places we call it, `deleteAccount` and `resetAccount`, are both kind of important.

**Comment by vladikoff** [comment]
Seems like no history of this error anymore in Sentry and no reoccurring
