### ISSUE TITLE
Let's think through the metricsContext params properly

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2496]
From a discussion in the meeting just now, it probably only makes sense for the first endpoint in each flow to support a `metricsContext` param. Otherwise it opens the possibility of us creating weirdness like mozilla/fxa-content-server#6258, where events from a single flow have different UTM params.

I think originally we put `metricsContext` on to more endpoints because we weren't entirely confident about relying on memcached in all cases, because it's set to expire data after 2 hours. Although this was a consideration for the flow events, now that Amplitude has our back it's less of a concern.

**Comment by rfk** [comment]
+1

> I think originally we put metricsContext on to more endpoints because we weren't entirely
> confident about relying on memcached in all cases

That's my recollection as well, and memcache was originally a bit of a hack to work around legacy clients that did not send the metricsContext bundle.  I agree times have changed and we should just include it at the start of the flow, simplifying downstream logic.

**Comment by philbooth** [comment]
I've taken a look at routes that accept `metricsContext` and have some concrete proposals.

Firstly, we definitely want to keep it on the following routes because they start a flow:

* `/account/create`
* `/account/login`
* `/password/forgot/send_code`

I *think* we also want to keep it on these routes, because they occur outside a proper flow but we still want their flow events:

* `/session/reauth`
* `/signinCodes/consume`
* `/sms`
* `/totp/create`

I think we can deprecate it on these routes because they occur inside an existing flow:

* `/account/reset`
* `/recovery_email/resend_code`
* `/password/forgot/resend_code`
* `/password/forgot/verify_code`
* `/session/verify/recoveryCode`
* `/session/verify/totp`
* `/account/login/send_unblock_code`

I might be wrong though, as I have a very sketchy understanding of where some of these routes fit in to our flows. If you disagree with any of the above, please make your disagreement known here!

In terms of the actual deprecation work itself, it needs to happen in two stages:

1. Stop sending `metricsContext` in the deprecated cases. Parallel to this we can also add logic to the auth server that refuses to set `metricsContext` for a flow id if it already exists in memcached (belt-and-braces protection so we don't get this wrong again in the future, as suggested by @shane-tomlinson).

2. Physically remove `metricsContext` from the js client and auth server for the deprecated endpoints.

**Comment by philbooth** [comment]
We could also consider two flavours of the `metricsContext` schema:

* For routes that start a flow, it stays the same and includes optional UTM params.

* For routes that are outside a flow, a variant without UTM params is used instead. This is further prevention against unexpected UTM params showing up in metrics where we don't expect them.

**Comment by rfk** [comment]
> because they occur outside a proper flow but we still want their flow events

Is this because we co-opted the flow events pipeline to report metrics on these features?

> `/account/login/send_unblock_code`

This one I'm not clear on...IIUC it gets called after a failed attempt to `/account/login`, but before the attempt that succeeds and generates a `sessionToken`.  We may need to keep it on that route for metrics purposes, even though it can't stash the metricsContext bundle for latest use.

**Comment by philbooth** [comment]
> Is this because we co-opted the flow events pipeline to report metrics on these features?

Yep, exactly. It's naughty I guess, but also pretty useful.

> We may need to keep it on that route for metrics purposes, even though it can't stash the metricsContext bundle for latest use.

:+1: Thanks!

**Comment by philbooth** [comment]
Fwiw, having just tested it locally, it turns out that the auth server is not responsible for mozilla/fxa-content-server#6258 after all (assuming I'm following the right steps to reproduce it, of course). I don't think that means we shouldn't do the things I suggested in the comments here, but it does mean they're lower priority than I thought they were.

My bad for getting busy theorising without actually doing anything empirical to back it up, but here is what I actually see in the logs after verifying my email in a different browser:

* Auth server logs.

  ```
  {"op":"amplitudeEvent","event_type":"fxa_reg - email_confirmed","time":1530794422604,"user_id":"6ac1da1b22114629b31cba8cae13c948","device_id":"44647c271e84490d90b5a04e08bbc8c2","session_id":1530794317349,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.11","event_properties":{"service":"sync"},"user_properties":{"flow_id":"276a3dac780e5621c49846c5c82d8deec2f2fc2cfa625f4e27f2d291b41c97c8","ua_browser":"Firefox","ua_version":"63.0","$append":{"fxa_services_used":"sync"},"sync_device_count":1,"sync_active_devices_day":1,"sync_active_devices_week":1,"sync_active_devices_month":1,"newsletter_state":"unsubscribed"}}
  {"op":"amplitudeEvent","event_type":"fxa_email - sent","time":1530794422666,"user_id":"6ac1da1b22114629b31cba8cae13c948","app_version":"115","event_properties":{"service":"sync","email_type":"registration","email_provider":"other","email_template":"postVerifyEmail","email_version":1},"user_properties":{"$append":{"fxa_services_used":"sync"},"sync_device_count":0,"sync_active_devices_day":0,"sync_active_devices_week":0,"sync_active_devices_month":0}}
  {"op":"amplitudeEvent","event_type":"fxa_activity - cert_signed","time":1530794423484,"user_id":"6ac1da1b22114629b31cba8cae13c948","device_id":"44647c271e84490d90b5a04e08bbc8c2","session_id":1530794317349,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.11","event_properties":{"service":"sync"},"user_properties":{"flow_id":"276a3dac780e5621c49846c5c82d8deec2f2fc2cfa625f4e27f2d291b41c97c8","ua_browser":"Firefox","ua_version":"58.0","$append":{"fxa_services_used":"sync"},"sync_device_count":1,"sync_active_devices_day":1,"sync_active_devices_week":1,"sync_active_devices_month":1}}
  {"op":"amplitudeEvent","event_type":"fxa_reg - complete","time":1530794423484,"user_id":"6ac1da1b22114629b31cba8cae13c948","device_id":"44647c271e84490d90b5a04e08bbc8c2","session_id":1530794317349,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.11","event_properties":{"service":"sync"},"user_properties":{"flow_id":"276a3dac780e5621c49846c5c82d8deec2f2fc2cfa625f4e27f2d291b41c97c8","ua_browser":"Firefox","ua_version":"58.0","$append":{"fxa_services_used":"sync"},"sync_device_count":1,"sync_active_devices_day":1,"sync_active_devices_week":1,"sync_active_devices_month":1}}
  ```

* Content server logs.

  ```
  {"op":"amplitudeEvent","event_type":"fxa_email - click","time":1530794422621,"user_id":"6ac1da1b22114629b31cba8cae13c948","device_id":"14a8905e017a432d827fa98257bd3e11","session_id":1530794317349,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.11","event_properties":{"service":"sync","email_type":"registration"},"user_properties":{"entrypoint":"menupanel","flow_id":"276a3dac780e5621c49846c5c82d8deec2f2fc2cfa625f4e27f2d291b41c97c8","ua_browser":"Firefox","ua_version":"63.0","utm_campaign":"fx-welcome","utm_content":"fx-activate","utm_medium":"email","utm_source":"email","$append":{"fxa_services_used":"sync"}}}
  {"op":"amplitudeEvent","event_type":"fxa_connect_device - view","time":1530794422859,"user_id":"6ac1da1b22114629b31cba8cae13c948","device_id":"14a8905e017a432d827fa98257bd3e11","session_id":1530794317349,"app_version":"115","language":"en","os_name":"Mac OS X","os_version":"10.11","event_properties":{"service":"sync","connect_device_flow":"signin"},"user_properties":{"entrypoint":"menupanel","flow_id":"276a3dac780e5621c49846c5c82d8deec2f2fc2cfa625f4e27f2d291b41c97c8","ua_browser":"Firefox","ua_version":"63.0","utm_campaign":"fx-welcome","utm_content":"fx-activate","utm_medium":"email","utm_source":"email","$append":{"fxa_services_used":"sync"}}}

  ```

So none of the auth server events have a `utm_source` at all, but the two content server ones both have `"utm_source":"email"`. As that's a user property, Amplitude will do the propagation to subsequent events for us, until it's set again.

I'm moving this one back to the backlog.

**Comment by philbooth** [comment]
Coming back to this afresh, I recall why we can't deprecate metrics context on some of the suggested routes in https://github.com/mozilla/fxa-auth-server/issues/2496#issuecomment-402479779.

It's stashed in memcached keyed by the token id and of course, the password reset flow uses 3 separate tokens so each endpoint must either accept its own metrics context or the preceding step must call `stash` instead.

That leaves the list of deprecated endpoints like so:

* `/recovery_email/resend_code`
* `/session/verify/recoveryCode`
* `/session/verify/totp`

Additionally, if we call `metricsContext.stash` inside `/password/forgot/send_code`:

* `/password/forgot/resend_code`
* `/password/forgot/verify_code`

And if we call `metricsContext.stash` inside `/password/forgot/verify_code`:

* `/account/reset`
