### ISSUE TITLE
Selectively divert some fxa-email-service traffic via a different provider

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2497]
Firstly we'd need legal and ops approval for sending email via Sendgrid. Then we'd need to set up an official Mozilla Sendgrid account. Then we'd need to consider how to turn it on for specific cases such as users who are having deliverability problems, or domains that are having deliverability problems, or some percentage of requests, or whatever. We also need to make sure that our metrics story is tracking the sender that's used so we can attribute failure/success rates correctly.

**Comment by vladikoff** [comment]
Seems like SocketLabs is the one we can try to selectively divert
