### ISSUE TITLE
Write tests for lib/senders/email_service.js

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2509]
For instance, I noticed that it doesn't fail gracefully when `fxa-email-service` isn't running, because the response handler tries to dereference `body` (which is `undefined` if `err` is set).

This is my fault for getting over-excited and not spotting there were missing tests when I reviewed the PR.

**Comment by brizental** [comment]
Alright, I'm going to start working on this, but just to make sure which tests we are talking about here, these are the ones I came up with:

Check that everything goes well when...

- ... request is successful and email service sends email successfully.
- ... request is successful but email service errors.
- ... request is unsuccessful.

**Comment by philbooth** [comment]
@brizental, I think there's 2 main things to focus on:

* Assert that params are serialized on the request as expected.
* Assert that there is no combination of `err` and `body` that can cause the callback logic to be wrong.
