### ISSUE TITLE
Implement fine-grained control over outgoing email provider

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2512]
Here's 2 use cases:

1. A user reports that they are not receiving emails from FxA. We have no bounce records for them. We want to try routing their email via Sendgrid (or whatever) to see if it makes any difference.

2. Our delivery rate for a particular domain is worse than all the others. We want to route all email to that domain via Sendgrid (or whatever).

Here's a strawman proposal, presented as the simplest thing I could think of that would work:

1. We maintain a JSON file containing mappings of regex patterns to provider names. It lives in this repo.

2. Periodically (hourly?) in the background, auth server processes fetch and parse the latest JSON file from GitHub.

3. When this repo wants to send an email, it matches the address against its parsed mappings. If a match is found, the `provider` param is set on the request to `fxa-email-service`. Otherwise the request is not changed.

Obviously, we'd need to be careful about maintaining the JSON file for performance reasons: keep the number of regexes down to a strict minimum and make sure we don't do anything stupid like redos ourselves. But at least, now that we have branch protection enabled, we can be confident those mappings are being eyeballed before pushing to `master`. Plus we get everything else git offers as a side-effect: full history, commit messages, easy revert of changes, versioning and so on.

Discuss.

**Comment by philbooth** [comment]
> Plus we get everything else git offers as a side-effect: full history, commit messages, easy revert of changes, versioning and so on.

Double plus, we get everything else GitHub+Travis offers as a side effect, i.e. automated testing on push. So we can assert things like how many regexes there are in the mappings file and how long they take to execute.

**Comment by rfk** [comment]
> A user reports that they are not receiving emails from FxA. We have no bounce records for them. We want to try routing their email via Sendgrid (or whatever)
> ...
> We maintain a JSON file containing mappings of regex patterns to provider names. It lives in this repo.

I like the fine-grained control in general, but we'll need to be careful about PII handling if it's fine-grained down to the individual user level.

An alternative might to be have live config like we do for the customs-server, that can be changed with a script.  Probably not living in memcached though...

**Comment by philbooth** [comment]
> I like the fine-grained control in general, but we'll need to be careful about PII handling if it's fine-grained down to the individual user level.

Oh yeah, very good point indeed.

**Comment by philbooth** [comment]
I just had a quick chat to @jrgm about this as I'm working on a branch that uses Redis to store live config that controls routing for email traffic. He had two concerns:

* Although Redis is reliable, it's possible for it or the data in it to disappear. We should fallback to solid behaviour (i.e. not using the new service) in that case.

* Using Redis makes it harder to see the current config, because you need to query Redis to see the config. It's conceivable that we could expose some kind of password-protected endpoint to make it more readily available as a blob of JSON. I'm happy to pursue this in my branch if it seems like a big enough deal to spend a bit of time on.

(there was also some discussion about using zookeeper or etcd instead but Redis is probably good enough given that we already have it running in the stack)

**Comment by philbooth** [comment]
Just noting an edge case I ran up against while implementing this.

It's possible for a primary email address to match some routing regex but not one of the secondary email addresses (or vice versa). In that event, I'm assuming the correct thing to do is to independently send two separate emails, one via the auth server and one via fxa-email-service.
