### ISSUE TITLE
Test fails due to failed redis connection

### ISSUE THREAD

**Issue by SarenT** [mozilla/fxa-auth-server#2520]
Hi,

I am trying to install fxa-auth-server on my Raspberry Pi. After the installation, I am trying to run the tests with:
```
firefoxuser@myrpi:~/git/fxa-auth-server $ npm test

> fxa-auth-server@1.115.1 test /home/firefoxuser/git/fxa-auth-server
> VERIFIER_VERSION=0 MEMCACHE_METRICS_CONTEXT_ADDRESS=none NO_COVERAGE=1 scripts/test-local.sh

keys file already exists

test.CRITICAL: uncaughtException Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
npm ERR! Test failed.  See above for more details.
```
I don't have redis server installed. But it is also not mentioned in the prerequisites. Am I missing something here?
Thanks!

**Comment by philbooth** [comment]
@SarenT, you say Redis is installed but is it actually running? And if so, is it running on port 6379? If Redis is available on 6379 this error should go away.

Also worth noting that it should be possible for you to run without Redis if you set `redis.enabled` to `false` in config.

**Comment by SarenT** [comment]
@philbooth Sorry, redis is not installed, since it wasn't in prerequisites. What difference does it make to run without? Should I disable it in index.js:
```
redis: {
    enabled: {
      default: **true**,
      doc: 'Enable redis cache',
      format: Boolean,
      env: 'USE_REDIS'
    },
```
to
```
redis: {
    enabled: {
      default: **false**,
      doc: 'Enable redis cache',
      format: Boolean,
      env: 'USE_REDIS'
    },
```

**Comment by philbooth** [comment]
@SarenT oh sorry, I misread your comment!

Although disabling it that way will work, it's better if you set it in `config/${NODE_ENV}.json`. The config is loaded via [convict](https://github.com/mozilla/node-convict) if you're not familiar with it, so environment-specific settings can override defaults without modifying source from the git repo.

Alternatively, you can also just set the `USE_REDIS` environment variable to `false`.

**Comment by SarenT** [comment]
@philbooth Thanks! I will read more about convict. Why is redis needed? What happens if I don't use it?
My goal is to synchronize personal firefox installations (tabs, bookmarks etc.) on phone, PC etc. via a private server.

**Comment by philbooth** [comment]
@SarenT we use it to store updates about connected devices - browser and operating system version, device name and so on. Those are displayed in the list of connected devices on the logged-in settings view, so the effect of disabling Redis will be that that view contains out of date information.

In production, our `devices` and `sessionTokens` tables are really big, so updates to them are something of a resource hog. Using Redis means we can keep that information up to date without thrashing the db, is all.
