### ISSUE TITLE
Unexpected error when updating device record

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2533]
From [sentry](https://sentry.prod.mozaws.net/operations/auth-prod/issues/4476632/):

```
Error: An internal server error occurred
  File "/app/lib/routes/devices-and-sessions.js", line 255, in Object.keys.some.key
    return payload.availableCommands[key] !== token.deviceAvailableCommands[key]
  File "/app/lib/routes/devices-and-sessions.js", line 254, in isSpuriousUpdate
    spurious = spurious && Object.keys(payload.availableCommands).some(key => {
  File "/app/lib/routes/devices-and-sessions.js", line 181, in handler
    if (isSpuriousUpdate(payload, sessionToken)) {
  File "/app/lib/server.js", line 320, in server.ext
    reply.continue()
...
(68 additional frame(s) were not displayed)
```

Maybe one of the fields in there is unexpectedly undefined?

**Comment by philbooth** [comment]
The error text implies that it is `token.deviceAvailableCommands` itself which is `undefined`:

> TypeError: Uncaught error: Cannot read property 'https://identity.mozilla.com/cmd/open-uri' of undefined

**Comment by philbooth** [comment]
Would changing the test on line 253 to the following be a valid fix:

```js
if (payload.availableCommands && token.deviceAvailableCommands) {
```

Or is there some deeper root cause we need to get to the bottom of? Do we reasonably expect `deviceAvailableCommands` to always exist?

**Comment by rfk** [comment]
> Do we reasonably expect deviceAvailableCommands to always exist?

I expect it should always exist, defaulting to `{}`, so I would worry a little that we're papering over some deeper problem.

**Comment by shane-tomlinson** [comment]
@philbooth - I pulled this into active because you are already digging into this to determine the cause.

**Comment by philbooth** [comment]
> I would worry a little that we're papering over some deeper problem.

I think the only way to get in to this situation is for `POST /account/device` to be invoked with a non-existent device id. The session token still needs to exist but either the device record got deleted somehow or the value of the id got corrupted client-side somehow. The only way I managed to make that situation occur locally was by physically deleting the device record from the db.

So it seems like my simple proposed fix would indeed be papering over a deeper issue. How and why the db or the client got into that state though, remains a mystery.

**Comment by philbooth** [comment]
(returned this to the backlog because I'm not sure what to do with it now)

**Comment by jrgm** [comment]
Have been quite a number of these in the period after the db fix. They may be fading out now.
