### ISSUE TITLE
Error: accountDestroy method did not return a value, a promise, or throw an error

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2563]
Sentry (prod):

https://sentry.prod.mozaws.net/operations/auth-prod/issues/4522381/

**Comment by davehunt** [comment]
Now that (as I understand it) this is deployed, we're seeing error 102 (Unknown account) whenever we try to destroy an account, even when the account exists. This may mean that test accounts are no longer being cleaned up... /cc @philbooth @shane-tomlinson @vladikoff

**Comment by philbooth** [comment]
@davehunt I don't think this has gone out yet. Based on `git log` it looks like it will be in train 119, which should be live some time this week.

**Comment by davehunt** [comment]
Thanks @philbooth I thought it was going out yesterday. It's still interesting that we were getting an unexpected error when attempting to discard an unknown account, and now get an unknown account error when expecting a successful destroy.

**Comment by davehunt** [comment]
I should note that we're testing against staging. Is there a way I can test what's going to be released this week?

**Comment by philbooth** [comment]
Ah, my bad! It is indeed on staging already.

**Comment by philbooth** [comment]
Although actually, I can see stage is running 119.0 and there have been point releases containing bug fixes since that one. And one of those bug fixes is to `/account/destroy` so maybe that's the problem.

I'll check with @jbuck or @jrgm when they get online about updating stage to the latest auth server point release, maybe that will sort it.

**Comment by philbooth** [comment]
Auth server 119.3 is now on stage.

**Comment by jbuck** [comment]
@philbooth I've built 119.3 on stage now

**Comment by davehunt** [comment]
Thanks, it looks good!
