### ISSUE TITLE
Failures to send via fxa-email-service nonetheless tell the user it was sent.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2565]
This may apply to other failures too (there may be an ancient issue about this). 

But anyways, when the fxa-email-service fails to send to SES, the user is told "Check your email for the verification link sent to...". Which we should know they cannot successfully do.

**Comment by philbooth** [comment]
Part of the problem here is fixed in #2566. That's not the whole story, however.

I'm not sure why, but the auth server swallows email-sending errors in some (but not all) routes. For example:

https://github.com/mozilla/fxa-auth-server/blob/bc55e8b3f5d416c1ca35f993b2d7e3d77b5b1a39/lib/routes/account.js#L298-L310

Obviously it would be a trivial change to stop it swallowing these errors, but I need to find out whether there's some reason for it to be like that first.

**Comment by philbooth** [comment]
> I'm not sure why...

If I'd stopped to think about this for a few seconds it might have become obvious. Semantically it would be weird for `/account/create` to fail due to an email-sending error, because the account has already been created in the db by that point. So maybe instead of failing, we could return a property in the response to indicate what's happened?

**Comment by shane-tomlinson** [comment]
I'm weighing in with incomplete information. 

It seems a bit strange to me that we'd swallow errors in some routes but not others, at least when transactional emails are involved and some user action is required. For a signup, if an email bounces it seems reasonable to me to view the db account creation and email sending as one atomic unit. If the email sending fails the user will never be able to verify the account - is there any point in keeping the account in the DB? Seems reasonable to roll back the account creation in the DB. Granted we'll still allow a re-sign up when an email is unverified so there might not be any real harm in keeping the account in the DB, though it seems like bad housekeeping if we know the account will never be verified.

**Comment by philbooth** [comment]
Related discussion from IRC:

> `11:40:45 <pb>` stomlinson: should we return something from the /account/create endpoint that indicates no email was sent, or should we even fail the response in that case?
> `11:41:43 <pb>` stomlinson: failing the response seems technically wrong because the account has been created in the db. but if they can't verify their email, is it any use as an account?
> `11:42:49 <•stomlinson>` pb: reading now.
> `11:44:30 <•stomlinson>` pb: viewing the db/email sending as one atomic unit, can we roll back the db creation if the email sending fails?
> `11:44:49 <pb>` stomlinson: we could do that, yep
> `11:45:03 <•stomlinson>` pb: Any ideas why some routes swallow email sending errors while others don't? 
> `11:45:07 <pb>` stomlinson: was there ever a reason for letting unverified accounts hang around as a thing?
> `11:45:27 <pb>` stomlinson: i presume ultimately that comes down to developer choice. whoever implements the endpoint, decides
> `11:45:45 <pb>` (and maybe contextually, the semantics for some make more sense than the sematics for others)
> `11:47:23 <•stomlinson>` pb: I think the idea is that if a user signs in with an unverified account w/ the correct u/p, we send them an email again but let them sign in instead of creating a new account. I think this was necessary for old Firefox desktops (and perhaps new too) where we'd have to send the browser a "signout" WebChannel message, wait for that to complete, then send a "login" with the new uid.
> `11:47:41 <•stomlinson>` pb: but I think we figured that out for some subset of desktop browsers. I have to look.
> `11:48:10 <pb>` stomlinson: ah, okay, that flow does make sense now you mention it
> `11:48:21 <•stomlinson>` pb: https://github.com/mozilla/fxa-content-server/blob/68dd42e60c99055a8b1c42974f8fb0e0ef0f5772/app/scripts/models/auth_brokers/base.js#L449
> `11:49:18 <•stomlinson>` pb: it looks like it's used for force_auth

**Comment by shane-tomlinson** [comment]
From meeting: Check all email sending routes to ensure sending errors are surfaced to the user. There is an existing 400/errno that indicates the email was not sent.

**Comment by vladikoff** [comment]
from mtg: if mail service failed then delete the account and tell the user email failed
