### ISSUE TITLE
inconsistent restrictions on email length?

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2568]
Try this email: emailservice.3570790ce85ed78cb20049e31d90e7ec65f20a1c57c8b9ab495e@restmail.net

Front end in browser disallows it. Auth api /create accepts it. Email service throws some kind of error on it.

**Comment by jrgm** [comment]
Yes, that is an invalid length for the userpart. Just not sure why auth-server allowed it.

**Comment by philbooth** [comment]
**TODO:** Use the same validation regex as the email service in the auth and content servers.

https://github.com/mozilla/fxa-email-service/blob/e0a283915af8f956ee2895e5025a393f98902068/src/validate/mod.rs#L29

**Comment by vladikoff** [comment]
😱
