### ISSUE TITLE
Change the email service errno values to numbers

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2569]
Because of:

https://github.com/mozilla/fxa-email-service/pull/161/files#diff-dd02a9e1af125dcee823974d07d358b4R58

These must change:

https://github.com/mozilla/fxa-auth-server/blob/58f608306e94a006de902e85ebe828a5adedc073/lib/senders/email_service.js#L12-L14

**Comment by vladikoff** [comment]
from mtg: if mail service failed then delete the account and tell the user email failed
