### ISSUE TITLE
error accessing token.deviceAvailableCommands

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2582]
See https://sentry.prod.mozaws.net/operations/auth-prod/issues/4558491/

token.availableCommands can be undefined, trying to dereference a key within that causes an exception to be thrown.

**Comment by philbooth** [comment]
I think this is a dup of #2533, okay if we close this in favour of that one?

**Comment by shane-tomlinson** [comment]
Closing as dup
