### ISSUE TITLE
Don't prepopulate password after a login is blocked

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-server#2605]
If a user is blocked because they had a bad password, they need to submit their password again after they use an unblock code.

We, however, prepopulate the bad password in the login field making it too easy for users to submit the bad password again.

This problem was initially documented here:
mozilla-lockbox/lockbox-ios#662

and then #1998

**Comment by rfk** [comment]
Moving to content-server, which controls that password form field: https://github.com/mozilla/fxa-content-server/issues/6512
