### ISSUE TITLE
Tests are flaky in circle

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2620]
@vbudhram, @vladikoff and I ran into 3 flaky tests on Circle while trying to put together https://github.com/mozilla/fxa-auth-server/pull/2616.

* token_code_tests - should consume valid code
* totp_tests - should check if totp token exists for user
* totp_tests - should not fail to delete unknown totp token

The tests all hit the 10 second time limit and croaked. 

@vbudhram & @vladikoff, any theories?

**Comment by shane-tomlinson** [comment]
More failures here: https://circleci.com/gh/mozilla/fxa-auth-server/3342

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/fxa-auth-server/issues/2402
