### ISSUE TITLE
Loading chunk vendors~fxaCLient failed.

### ISSUE THREAD

**Issue by trooper91** [mozilla/fxa-auth-server#2625]
after creating everything step by step i get this error when i try to create an account
`Loading chunk vendors~fxaClient failed. (error: http://127.0.0.1:3030/bundle/vendors~fxaClient.bundle.js)`

**Comment by vladikoff** [comment]
@trooper91 did you open `localhost` or `127.0.0.1` , you must open `http://127.0.0.1:3030`

**Comment by trooper91** [comment]
now i am getting FxaClient.default is not a contructor
