### ISSUE TITLE
Force all users through fxa-email-service

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2631]

**Comment by philbooth** [comment]
Pushed this back to train 123.

My current thinking is now 10% for train 121, 50% for train 122, 100% for train 123.

**Comment by philbooth** [comment]
Pushing this back a few trains, as per discussion in the back-end meeting.

**Comment by philbooth** [comment]
Pulled across to `active` to be done as part of the train 125 deployment cycle. Note this is an ops task, so there's no need to freak out about the fact I'm on PTO and my face is on this.

**Comment by jrgm** [comment]
Running at 50% in prod now. Previous panics not seen in Sentry. Emails on bounce list are showing up in sentry.

Overall send/deliver statistics look the same by either sending path.

**Comment by vladikoff** [comment]
> Overall send/deliver statistics look the same by either sending path.

🏅

**Comment by jrgm** [comment]
Disabled in production. @see https://github.com/mozilla/fxa-email-service/issues/239#issuecomment-438913101

**Comment by vladikoff** [comment]
from mtg: 

bounce cases get reported into sentry as errors

**Comment by vladikoff** [comment]
from mtg: switching to 100% of users this week

**Comment by vladikoff** [comment]
It's live for 100%! 

@brizental @philbooth party time! 🎉 

Leftover issue filed in https://github.com/mozilla/fxa-email-event-proxy/issues/12 for socketlabs
