### ISSUE TITLE
Import fxa-oauth-server into this repo

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#2679]
Per discussion in https://github.com/mozilla/fxa-auth-server/pull/2673 we want to try to reduce development complexity by importingthe fxa-oauth-server into this repo, making this more of a "monorepo".  If that goes well we might consider doing the same thing to some of our other repos, such as fxa-auth-db-mysql.

This is a tracking issue for things for us to do/check during that merge:

* [x] Bring the code across as a subdirectory (with intact git history?)
* [x] Update README in the fxa-oauth-server repo to note the new location
* [x] Add stub `./docs/` files in fxa-oauth-server to redirect to new docs location
* [x] Migrate oauth-server issues to auth-server repo, or close any that don't seem useful
* [x] Port any train-123 point-releases over to this repo
* [x] Disable CI integrations on the oauth-server repo
* [x] Migrate or delete wiki pages from fxa-oauth-server repo
* [x] Mark oauth-server repo as archived.
* [x] Update fxa-local-dev
* [x] Check fxa-dev to see if anything needs updating

@mozilla/fxa-devs anything else for the checklist?

**Comment by rfk** [comment]
>  Bring the code across as a subdirectory (with intact git history?)

We're doing this either here or here, depending on what we want from the history:
* https://github.com/mozilla/fxa-auth-server/pull/2673 (without commit history)
* https://github.com/mozilla/fxa-auth-server/pull/2680 (with commit history)

**Comment by vbudhram** [comment]
We will probably need to migrate any existing oauth issues to auth-server

- [ ] Migrate oauth issues to auth-server

**Comment by rfk** [comment]
Thanks @vbudhram, I'm going to edit it into the master checklist in the issue description for completeness.

**Comment by rfk** [comment]
> * Update README in the fxa-oauth-server repo to note the new location
> * Add stub ./docs/ files in fxa-oauth-server to redirect to new docs location

These are both in https://github.com/mozilla/fxa-oauth-server/pull/619

**Comment by rfk** [comment]
>  Disable CI integrations on the oauth-server repo

We'll have to wait until train-123 migration issues are resolved before we can do this, we might need a train-123 point-release of oauth-server which should come from the old fxa-oauth-server repo.

**Comment by rfk** [comment]
>  Update fxa-local-dev

This was done in https://github.com/mozilla/fxa-local-dev/pull/132

>  Check fxa-dev to see if anything needs updating

AFAICT fxa-dev is working correctly without any changes, because the docker image is still being published to the same place.

**Comment by shane-tomlinson** [comment]
@rfk the remaining checkbox items have all been completed, haven't they? If so, can you close this?

**Comment by rfk** [comment]
I ticked off a couple more, the only one left is:

>  Migrate or delete wiki pages from fxa-oauth-server repo

Which I'll aim to get done before Monday so we can close this out.

**Comment by rfk** [comment]
> Migrate or delete wiki pages from fxa-oauth-server repo

Turns out you can check out a repo's wiki as a git repo, which made this migration a lot easier than I'd feared.  This issue is now complete.
