### ISSUE TITLE
Allowlisting test accounts for sign-in confirmation

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-server#2685]
From discussions with Lockbox, they were asking if it was possible to add a whitelist for certain email accounts to always bypass any sign-in confirmation.

Currently, these are the steps during the App Store review of Lockbox
1. Lockbox team submits for review
    * They provide a test account to use, which they have access to its inbox
2. App reviewer starts review, install Lockbox
3. App review uses test account to login
    * They are prompted to confirm sign-in, FxA emails confirmation link
4. Lockbox team clicks link and confirms sign-in
5. App reviewer logs in and reviews application

With the introduction of sign-in codes (emailed a code instead of a link), the Lockbox team has no way of giving this code to the reviewer so they can verify the login attempt and proceed reviewing the app.

I can't seem to find the original reasons why we did not add this in besides having a possible configuration footgun. Or maybe waiting until we expose the configuration for the user to select from our settings page? Or maybe we didn't have a use case for needing it before?

In the long run, I think this question will continue to pop up if FxA is incorporated into new mobile applications that require a consistent login experience and have to be reviewed.

@mozilla/fxa-devs Thoughts?

**Comment by devinreams** [comment]
And not that it's an unsolveable problem, but a similar concern arises with integration tests where we have to build/maintain code to sign in to email inboxes and click a link _or_ retrieve a code.

Hard-coded or single-purpose test accounts could be less potential breakage or maintenance burden on some test infrastructure.

**Comment by rfk** [comment]
> Or maybe waiting until we expose the configuration for the user to select from our settings page? 

It might have been this, but I don't think we have any concrete plans to do that.

We have config to force confirmation *on* for certain email addresses, I'm not opposed to carefully-reviewed config to force it off.  We might want to make it a list of individual email addresses rather than a regex to guard against config errors.

**Comment by vbudhram** [comment]
> We might want to make it a list of individual email addresses rather than a regex to guard against config errors.

I'm 👍🏽 for that. We could always start with specific emails and then extend to regex if the use case comes up.

**Comment by philbooth** [comment]
@vbudhram can you triage this out of the backlog if it's the wrong place?

**Comment by rfk** [comment]
Just saw this going by in the #lockbox channel on slack:

```
Joe Gasiorek [7:54 AM]
@dreams looks like the iOS app was rejected because they couldn’t sign in with those creds :(

dreams [8:02 AM]
@Joe Gasiorek was distracted and I just “clicked” the confirmation link so they can go back in now :crossed_fingers:
I will respond in the App Review portal right now
```

So I think we should try to move this forward if possible, and I can volunteer some of my time to work on it.  @shane-tomlinson what do you think about the proposed approach?

One possible concern I have is about people unexpectedly uploading real data into the sync account for a test user, but I guess we have that problem already.  Maybe we should also think about downstream things we can do in sync to make "test accounts" easier/safer.

**Comment by devinreams** [comment]
For our specific use case, we promise we are not going to be uploading real data to our Apple / Google / internal test account: `firefoxlockbox@gmail.com`

It’s intended for QA and confirmation is not necessary as nothing is actually “at risk” in that account.

**Comment by rfk** [comment]
> One possible concern I have is about people unexpectedly uploading real data into the sync
> account for a test user

The reverse is also true in some circumstances.  If we had a test account for sync with known credentials, and someone synced a malicious addon up to that account, it might propagate down and install that addon for users doing testing.  Not likely to be a problem for lockbox, but something else for us to keep in mind with the whole "test accounts" notion more broadly.

**Comment by rfk** [comment]
I'm nominating this for "next" so we can discuss in upcoming planning meeting.

**Comment by devinreams** [comment]
Thank you all for your help landing this quickly!
