### ISSUE TITLE
Add a SessionToken authenticated /key-data endpoint

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-auth-server#2693]
OAuth server's `/key-data` doesn't work very well with Desktop assertions.
We can avoid Desktop having to craft an assertion by letting it authenticate itself with a session token.

**Comment by rfk** [comment]
The oauth-route, for reference:

  https://github.com/mozilla/fxa-auth-server/blob/326ca02ee8be2b753800f189f29247911afefa5f/fxa-oauth-server/lib/routes/key_data.js#L71-L73

I propose calling the new route something like `/certificate/claims`, on the logic that it returns to you the claims that you could parse out of the signed certificate if you wanted to, but it's saving you all that parsing trouble.

**Comment by rfk** [comment]
@eoger are you blocked on this for your desktop patch?

**Comment by eoger** [comment]
I'm fine with keeping `JSON.parse` logic in the desktop pairing patch at the moment.

**Comment by vladikoff** [comment]
@rfk for 127?
