### ISSUE TITLE
[oauth] issues with delete query 2018-10-26

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#2695]
At 21:06Z Friday, monitoring alerts fired for the fxa-oauth service. 

Investigation showed that queries to the fxa-oauth were being blocked behind this query: `DELETE FROM tokens WHERE userId=X'...' AND clientId IN (...list of client ids...);`. Killing that query would clear the blocking queries, but eventually another such delete would occur and service would start failing again.

An explain of the equivalent select showed:
```
| id | select_type | table  | type  | possible_keys                   | key              | key_len | ref  | rows | Extra 
|  1 | SIMPLE      | tokens | range | tokens_client_id,tokens_user_id | tokens_client_id | 8       | NULL | 7876 | Using index condition; Using where
```

We decided to put back the foreign key on the tokens table, as it appeared related. That FK had been removed on Wednesday morning.

```
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE tokens ADD FOREIGN KEY (clientId) REFERENCES clients(id) ON DELETE CASCADE, ALGORITHM = INPLACE, LOCK = NONE;
```

After killing off a couple of in-progress DELETEs to unblock the ADD FOREIGN KEY query, operation instantly returned to normal.

(We also put back the FK on `codes` a while later because sure why not, do it now).

Running a similar explain now, I get:
```
| id | select_type | table  | type | possible_keys                   | key            | key_len | ref   | rows | Extra
|  1 | SIMPLE      | tokens | ref  | tokens_client_id,tokens_user_id | tokens_user_id | 16      | const |    1 | Using index condition; Using where
```

The query in question is https://github.com/mozilla/fxa-oauth-server/blob/train-122/lib/db/mysql/index.js#L185 - QUERY_DELETE_ACCESS_TOKEN_FOR_PUBLIC_CLIENTS

**Comment by rfk** [comment]
@jrgm to ensure consistency with what's in production, should we do another "rollback" migration that adds the foreign key back in, before trying to implement  fix here?

**Comment by jrgm** [comment]
> @jrgm to ensure consistency with what's in production, should we do another "rollback" migration that adds the foreign key back in, before trying to implement fix here?

Yes, we probably should do that, and I should add back the foreign key for fxa_oauth.refreshTokens so it's a complete rollback.

**Comment by jrgm** [comment]
And yeah, I was pondering if a FORCE INDEX might be a fix while this was happening, but adding back the FK was the better call. Thanks @jbuck.

**Comment by rfk** [comment]
> one option is to add a FORCE INDEX on the above query to make sure it always uses
> the tokens_user_id index

Ugh; according to [1] index hints are only supported on `SELECT` statements, not `DELETE` statements, so we can't use `FORCE INDEX` here :-(

[1] https://dev.mysql.com/doc/refman/8.0/en/index-hints.html
