### ISSUE TITLE
Arabic emails not working

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2714]
When I sign up in Russian, I receive the verification email in Russian. When I sign up in Arabic, I receive it in English. What gives?

**Comment by philbooth** [comment]
Coincidentally, we recently had another Arabic-specific translation issue that was caused by its array index being falsey/zero: https://github.com/mozilla/fxa-shared/pull/35

**Comment by philbooth** [comment]
@philbooth to investigate if this is happening in prod too or just locally.

**Comment by philbooth** [comment]
Just tried this out in prod and it happens for me there too.

I think this is something we should really get to the bottom of, but I'm on PTO this week. So, taking my face off and returning to the triage column. Can you guys prioritise it during today's meeting?

**Comment by vladikoff** [comment]
Confirmed this, getting English emails for [ar] locale in Firefox.

**Comment by vladikoff** [comment]
it seems the issue is the 

```
"Plural-Forms: nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5);\n"
``` part in the ar `server.po`, if i swap it with a russian one then emails are translated properly

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/ar/LC_MESSAGES/server.po#L14
