### ISSUE TITLE
npm install not install grunt-cli on oaut-hserver

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa-auth-server#2723]
After an npm install in the oauth-server grunt-cli is not installed, but is needed. What is wrong or do I do something wrong?

thank you...

**Comment by vladikoff** [comment]
@misterhsp CLI is either global: https://gruntjs.com/getting-started#installing-the-cli or you can access it via `node_modules/.bin/grunt`

**Comment by misterhsp** [comment]
I have add a line in my dockerfile npm install grunt-cli.
