### ISSUE TITLE
QUERY_ACCESS_TOKEN_INSERT called with extra parameter

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-auth-server#2725]
See in the call bellow: https://github.com/mozilla/fxa-auth-server/blob/f055f23bd9e7876dddddb67067b34a180f2d19b8/fxa-oauth-server/lib/db/mysql/index.js#L442-L449
We should remove the last `t.profileChangedAt,` parameter (column was dropped in a recent patch)

**Comment by rfk** [comment]
I think we hoped to be able to bring that column back after resolving recent db migration issues, but you're right we should clean it up in the meantime.

**Comment by rfk** [comment]
@jrgm to clarify, did we keep the `profileChangedAt` column on the `codes` and `refreshTokens` tables in production?
