### ISSUE TITLE
Session policy

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#286]
Session tokens are a limited resource (#130, #281), therefore we need a policy for their allocation. Web sessions add a new wrinkle to the topic.

How do we manage both device and web based sessionToken usage?
Do device and web share the same pool of sessionTokens?

**Comment by rfk** [comment]
I found this gem in the google oauth developer docs [1], and was reminded of how much hand-wringing we did over whether and how to cap the number of sessions on an account:

"""
There is currently a 25-token limit per Google user account. If a user account has 25 valid tokens, the next authentication request succeeds, but quietly invalidates the oldest outstanding token without any user-visible warning.
"""

[1] https://developers.google.com/identity/protocols/OAuth2#expiration

**Comment by shane-tomlinson** [comment]
At first glance, I like this approach. We'll have to move the content server off of using /auth/login to check a user's password and on to the new check password endpoint. We'll also have to consider how signing in to multiple OAuth reliers could, in theory, affect a super-long-standing Sync session. It would be unfortunate if a user was signed out of Sync when they signed in to some other relier.

**Comment by vladikoff** [comment]
@rfk should we rebrand this into the new 'session token manager' work?

**Comment by rfk** [comment]
Oh man, so much history in this issue.

> should we rebrand this into the new 'session token manager' work?

I think this is related slightly different.  The session-token-management work is about the user explicitly managing their own sessions.  This bug is about how to *automatically* manage those sessions in order to keep them to a reasonable number.  But it's probably worth thinking about both at the same time.

>  ckarlof commented on 7 Dec 2013 
> > we should be prepared to treat sessions as first class models, with rich properties, including 
> > type, ip address, location, creation time, last activity, etc. We should also be prepared for
>  > (i.e., not be shocked when we need to build) a "Sessions API" to support something 
> > like the Github Security History tab.

That @ckarlof guy was really on to something way back then...

**Comment by vladikoff** [comment]
from mtg: @rfk to update this issue

**Comment by rfk** [comment]
Per https://github.com/mozilla/fxa-auth-server/issues/1863 we are introducing the following rules:

* Sessions that register a device record will live indefinitely
* Sessions that do not register a device record will expire after 4 weeks

The remaining question is whether we want to set an upper bound on the number of session tokens that can be live at any one time, but we don't have any such caps on other tokens types AFAIK so let's re-open that discussion afresh if and when we decide to act on it.
