### ISSUE TITLE
FR - Arrow blue CTA button in signup verification email is on a different line to text

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2860]
In languages other than English where the text is longer, the arrow is on a different line. That's ugly. Does the arrow actually provide value? If not, I vote we kill it.

<img width="397" alt="screenshot 2019-01-11 at 12 54 54" src="https://user-images.githubusercontent.com/848085/51036735-efe41480-15a5-11e9-8876-23be0b49ccb1.png">

ref #2859 because it'll update the same email template.

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
@shane-tomlinson Here's a bunch https://github.com/mozilla/fxa-auth-server/search?q=%26rarr%3B&unscoped_q=%26rarr%3B

**Comment by hritvi** [comment]
@shane-tomlinson I have made the changes on my local. Making a PR for the same :slightly_smiling_face:
