### ISSUE TITLE
Strange error message: "A TOTP token not found"

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2888]
ref https://github.com/mozilla/fxa-content-server/issues/6904

https://github.com/mozilla/fxa-auth-server/blob/acd40c3916cdeeff1484c4eadfd51fc1164c41dc/lib/error.js#L797

Seems like "A " should be removed from this string.

**Comment by vbudhram** [comment]
> Seems like "A " should be removed from this string.

I struggle with words sometimes lol, but yea we should remove the `A`.
