### ISSUE TITLE
Test using Node 10 on travis

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2906]
We use scrypt-hash here which does not work on node 10, luckily @philbooth has done the work to [provide a node 8 & 10 compatible interface](https://github.com/mozilla/fxa-auth-db-mysql/pull/473/files) that uses scrypt-hash on node 8 and crypto.scrypt for node 10.

We should drag that wrapper over here and start testing on node 10.

**Comment by philbooth** [comment]
Hmm? https://github.com/mozilla/fxa-auth-server/pull/2902

**Comment by shane-tomlinson** [comment]
> Hmm? #2902

[Where is my mind?](https://www.youtube.com/watch?v=N3oCS85HvpY)
