### ISSUE TITLE
Include `service` as data when sending `verified` events to Basket

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2915]
Initial conversation in https://github.com/mozmeao/basket/issues/131

The Mozmeao team would like to create custom onboarding journeys for different services, but we don't provide sufficient information for them to do so.

When we send `verified` events, we do not send along which service the user was signing up for.

I propose we send the `service` info along with the `verified` event that's broadcast to reliers.

@pmac, for OAuth reliers `service` is the relier's client_id. We could convert that to something more human readable like we do for metrics, not sure what's best for your uses.

blocks https://github.com/mozmeao/basket/issues/132

Longer term we could probably also send `login` events for all services rather than just Sync to enable Mozmeao to send helpful info when a user with an existing account signs in to a new service.

cc @pmac, @LaurenNiolet

**Comment by pmac** [comment]
> I propose we send the `service` info along with the `verified` event that's broadcast to reliers.
> 
> @pmac, for OAuth reliers `service` is the relier's client_id. We could convert that to something more human readable like we do for metrics, not sure what's best for your uses.

That all sounds perfect to me.

> Longer term we could probably also send `login` events for all services rather than just Sync to enable Mozmeao to send helpful info when a user with an existing account signs in to a new service.

That would also be good. All we'll need is information on what to expect in the queue message JSON schema and we'll figure out where to put the new info on our side.

**Comment by davismtl** [comment]
In support of this fix, this will also be needed since IoT Things is experimenting with FxA. They don't want Things users to get any Firefox onboarding emails. They'll likely want to personalize their onboarding experience.

**Comment by LaurenNiolet** [comment]
It's alive!! Services are coming through and at a reasonable mix (most sync, the rest are scattered among the other services.
