### ISSUE TITLE
Incorrect parameters passed to DB in bin/profile_server_messaging.js

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2916]
This file: https://github.com/mozilla/fxa-auth-server/blob/master/bin/profile_server_messaging.js

It passes [incorrect parameters when opening the DB](https://github.com/mozilla/fxa-auth-server/blob/a0c0e77e317d9fdc3c49488df60ae29d1e996eb8/bin/profile_server_messaging.js#L20-L21) which makes me believe it's no longer used. I don't see any tests for it either.

If it's unused, let's remove it.

cc @jrgm, @eoger

**Comment by shane-tomlinson** [comment]
As @jrgm and @philbooth point out, we should have some tests for this.

**Comment by jrgm** [comment]
Just to note what was said in triage meeting: It is used and is running in production and does appear to be working and not showing errors, but maybe just because it never calls the db object's methods in a way that would fail.
