### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/fxa-auth-server#2919]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/fxa-auth-server/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by philbooth** [comment]
@mozilla/fxa-devs there's 10 pages in the wiki for this repo, should we use this issue to migrate them elsewhere?

**Comment by shane-tomlinson** [comment]
@philbooth - it looks like a lot of them are out of date too! I've changed write access to only include users in teams with push access until we can migrate the content elsewhere.
