### ISSUE TITLE
Add an /oauth/authorization route, authenticated with a sessionToken

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#2933]
As part of our quest simplify our OAuth infastructure and remove BrowserID, let's move the [OAuth /authorization endpoint](https://github.com/mozilla/fxa-auth-server/blob/master/fxa-oauth-server/docs/api.md#post-v1authorization) over to the auth-server and authenticate it directly with a sessionToken, rather than having to indirect through a separate services with a BrowserID assertion.

This supports the Fennec -> Fenix migration flow (since Fenix can use Fennec's sessionToken to authorize itself as a new client) as well as furthering broader architectural efforts to make OAuth the primary mechanism of authorizing things via FxA.  Other consumers include the Desktop half of the pairing flow, which currently uses the BrowserID-authenticated `/authorization` route.

Ref: https://github.com/mozilla/fxa-auth-server/pull/2932 for a WIP PR.

(@vladikoff I edited your issue comment to add more details as part of breaking down https://github.com/mozilla/fxa-auth-server/issues/2547#issuecomment-468482625)

**Comment by rfk** [comment]
Vlad has deployed a WIP branch of this here: https://github.com/mozilla/fxa-auth-server/commits/feature.fenixmigrator
