### ISSUE TITLE
Re-enable verification reminder emails

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2939]
In #2060 we removed verification reminder emails because we were using DB calls that were unsafe for replication. Let's bring the feature back using replication safe DB calls. @jbuck suggests we might be able to do this by sending events to SQS and having individual instances consume the events so that only one entry is insert per reminder.

**Comment by davismtl** [comment]
@shane-tomlinson do you think this could be moved up by one train? 133 instead of 134? I guess it mostly depends on the size of this work which is unclear to me.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson do you think this could be moved up by one train? 133 instead of 134? I guess it mostly depends on the size of this work which is unclear to me.

I'm trying to get a sense of the size of this myself, one of the reasons we removed the reminders is because we were using SQL that was not safe for database replication. I'm trying to find out which calls those are and whether we have an easy path forward without leaning on another datastore. 

@philbooth has expressed an interest in helping here and may have some more ideas on how to move forward.

**Comment by jbuck** [comment]
If you want to keep the verification reminders in MySQL, write the code assuming that there's a single reader/writer and we could run it on the fxa-admin box

**Comment by vladikoff** [comment]
I forgot why we didn't redis this, but I suggest y'all redis this.

**Comment by philbooth** [comment]
Having spent a bit of time this morning familiarising myself with all the context here, I realise the linked issue in the opening comment doesn't contain all the context. So for reference purposes...

* Original db PR: https://github.com/mozilla/fxa-auth-db-mysql/pull/127
* Auth server PR: https://github.com/mozilla/fxa-auth-server/pull/1203
* Issue discussing the problem: https://github.com/mozilla/fxa-auth-db-mysql/issues/196
* An attempted fix: https://github.com/mozilla/fxa-auth-db-mysql/pull/200
* Related to previous: https://github.com/mozilla/fxa-auth-mailer/pull/255
* Removal of the auth server logic: https://github.com/mozilla/fxa-auth-server/pull/2283

Adding my face and moving it into `active` / `train-133`, although I'm not guaranteeing that anything is going to ship this train, just yet.

**Comment by philbooth** [comment]
> I suggest y'all redis this.

Fwiw, this is what I intend to do.

**Comment by shane-tomlinson** [comment]
> Fwiw, this is what I int

👍 I hoped this.

**Comment by philbooth** [comment]
Vague implementation plan:

* Store reminders in a Redis [sorted set](https://redis.io/topics/data-types-intro#redis-sorted-sets), ordered by creation timestamp.

* Run a simple script on `fxa-admin` that fetches the next batch from the aforementioned sorted set, dispatching any reminder emails and deleting records as necessary. We can schedule this with cron so no need to including looping logic in the script itself.

* Make sure the script has sane logic around not sending two reminders if e.g. there is an interuption to normal processing, so the first and second reminder intervals both activate in a single iteration.

**Comment by shane-tomlinson** [comment]
@philbooth to make explicit for the vague implementation plan: reminders are only sent if the account is still unverified.

**Comment by davismtl** [comment]
>     * Run a simple script on `fxa-admin` that fetches the next batch from the aforementioned sorted set, dispatching any reminder emails and deleting records as necessary. We can schedule this with cron so no need to including looping logic in the script itself.

Two questions that come to mind:
- how often would the cron run?
- how long do we want to wait before reminding someone?
- do we want to run them twice?

I will provide product recommendations for these. I will investigate first.

**Comment by philbooth** [comment]
> * how long do we want to wait before reminding someone?

Fwiw, defaults from config for the old implementation were 2 days before the first reminder and 7 days before the second reminder.

**Comment by davismtl** [comment]
Per conversations this morning:
- We will send first reminder after 24h, the second reminder will be after 5 days
- this should educate the frequency of running the cron job. (hourly?)

**Comment by philbooth** [comment]
> > * how long do we want to wait before reminding someone?
>
> Fwiw, defaults from config for the old implementation were 2 days before the first reminder and 7 days before the second reminder.

From meeting: let's try 1 day and 5 days

**Comment by philbooth** [comment]
While working on this, I noticed that `POST /recovery_email/verify_code` accepts some of its parameters both in the query string and in the body. That's silly and annoys me, because the only client is the content server, which we're in control of and can force to always use either one or the other.

Looking at the code, the key point is the `verifyCode` method in `fxa-js-client`. You can see that it always sends the data in the body, never as query params.

Thus I am hereby advertising that, included in this change, I'm also going to remove the query params from `POST /recovery_email/verify_code`. If there's anyone has a reason it's wrong for me to do that, please let me know!

**Comment by shane-tomlinson** [comment]
> Thus I am hereby advertising that, included in this change, I'm also going to remove the query params from POST /recovery_email/verify_code. If anyone has a reason it's wrong for me to do that, please let me know!

I'm not sure *why* they were added as query parameters, perhaps @vladikoff or @dannycoates remember. This seems like a reasonable change to make as a standalone PR.

**Comment by vladikoff** [comment]
> I'm not sure why they were added as query parameters

I think we wanted to POLL that endpoint, so a GET query param was a way to go

**Comment by philbooth** [comment]
Polling is for `/recovery_email/status` though right? I'm specifically talking just about `POST /recovery_email/verify_code` here, which would only need to be sent once, when the user clicks the link in the email.

**Comment by philbooth** [comment]
(the link itself is a `GET` request of course, but that's handled by `CompleteSignUpView` in the content server, which just redirects it to this `POST` in the auth server)

**Comment by jbuck** [comment]
We can use big query to ensure nobody is somehow accidentally using the
queue parameters

**Comment by vladikoff** [comment]
@philbooth ah `POST /recovery_email/verify_code`, I cannot remember why at this time, hmm..

**Comment by shane-tomlinson** [comment]
```
SELECT
  *
FROM
  `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_20190320`
WHERE
  jsonPayload.fields.path LIKE "/v1/recovery_email/verify_code?%"
LIMIT
  1000
```
...
> This query returned no results.

**Comment by philbooth** [comment]
WIP PR is at #2990.
