### ISSUE TITLE
Log using a mozlog-compatible interface

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2940]
Similar to https://github.com/mozilla/fxa-customs-server/issues/322

This repo writes directly to stderr w/o using mozlog 2.0, which is different than other fxa servers. This can cause confusion with questions like "why does this server write an object with an op whereas other repos call the log method with the op as the first argument and then an object?" Or at least, that's what I asked. What's doubly confusing is the code under the fxa-oauth-server uses mozlog, the auth-server code does not.

Maybe shared server side logging should be part of fxa-shared so we can reduce confusion.

**Comment by farhan787** [comment]
@shane-tomlinson may I fix this ?

**Comment by philbooth** [comment]
Correction to this bug, `lib/log.js` does use `mozlog` internally, just the interface it exposes is different. If we decide that is a problem for us, we can change the signature of its methods and all the method calls so that they take `op` as the first argument instead of a property.

**Comment by shane-tomlinson** [comment]
Using VSCode regexp replacement, I was able to do the replacements using regular expressions:

`log.([^)]+)\({\n?\s*op: '([^']+)',`
=> `log.$1('$2', {`

I suspect the tests are going to take some grunt work.
