### ISSUE TITLE
dockerbuild error on node10

### ISSUE THREAD

**Issue by misterhsp** [mozilla/fxa-auth-server#2948]
> scrypt-hash@1.1.14 install /home/fxa/fxa-auth-server/node_modules/scrypt-hash
> node-gyp rebuild

make: Entering directory '/home/fxa/fxa-auth-server/node_modules/scrypt-hash/build'
  CC(target) Release/obj.target/scrypt/crypto_scrypt-sse.o
  CXX(target) Release/obj.target/scrypt/node_scrypt.o
In file included from ../node_modules/nan/nan.h:190:0,
                 from ../node_scrypt.cc:3:
../node_modules/nan/nan_maybe_43_inl.h: In function 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)':
../node_modules/nan/nan_maybe_43_inl.h:88:15: error: 'class v8::Object' has no member named 'ForceSet'
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
In file included from ../node_scrypt.cc:3:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)':
../node_modules/nan/nan.h:817:60: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../node_scrypt.cc:2:0:
/home/fxa/.node-gyp/10.15.2/include/node/node.h:177:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/fxa/.node-gyp/10.15.2/include/node/node.h:91:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../node_scrypt.cc:3:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)':
../node_modules/nan/nan.h:831:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../node_scrypt.cc:2:0:
/home/fxa/.node-gyp/10.15.2/include/node/node.h:170:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/fxa/.node-gyp/10.15.2/include/node/node.h:91:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../node_scrypt.cc:3:0:
../node_modules/nan/nan.h: In function 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)':
../node_modules/nan/nan.h:845:62: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../node_scrypt.cc:2:0:
/home/fxa/.node-gyp/10.15.2/include/node/node.h:163:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/fxa/.node-gyp/10.15.2/include/node/node.h:91:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
In file included from ../node_scrypt.cc:3:0:
../node_modules/nan/nan.h: In member function 'v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const':
../node_modules/nan/nan.h:1453:5: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../node_scrypt.cc:2:0:
/home/fxa/.node-gyp/10.15.2/include/node/node.h:177:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/fxa/.node-gyp/10.15.2/include/node/node.h:91:42: note: in definition of macro 'NODE_DEPRECATED'
     __attribute__((deprecated(message))) declarator
                                          ^~~~~~~~~~
../node_scrypt.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE Scrypt(Nan::NAN_METHOD_ARGS_TYPE)':
../node_scrypt.cc:137:27: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
  N = info[2]->Uint32Value();
                           ^
In file included from /home/fxa/.node-gyp/10.15.2/include/node/v8.h:26:0,
                 from /home/fxa/.node-gyp/10.15.2/include/node/node.h:63,
                 from ../node_scrypt.cc:2:
/home/fxa/.node-gyp/10.15.2/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/fxa/.node-gyp/10.15.2/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../node_scrypt.cc:138:27: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
  r = info[3]->Uint32Value();
                           ^
In file included from /home/fxa/.node-gyp/10.15.2/include/node/v8.h:26:0,
                 from /home/fxa/.node-gyp/10.15.2/include/node/node.h:63,
                 from ../node_scrypt.cc:2:
/home/fxa/.node-gyp/10.15.2/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/fxa/.node-gyp/10.15.2/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../node_scrypt.cc:139:27: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
  p = info[4]->Uint32Value();
                           ^
In file included from /home/fxa/.node-gyp/10.15.2/include/node/v8.h:26:0,
                 from /home/fxa/.node-gyp/10.15.2/include/node/node.h:63,
                 from ../node_scrypt.cc:2:
/home/fxa/.node-gyp/10.15.2/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/fxa/.node-gyp/10.15.2/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../node_scrypt.cc:140:33: warning: 'uint32_t v8::Value::Uint32Value() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
  buf_len = info[5]->Uint32Value();
                                 ^
In file included from /home/fxa/.node-gyp/10.15.2/include/node/v8.h:26:0,
                 from /home/fxa/.node-gyp/10.15.2/include/node/node.h:63,
                 from ../node_scrypt.cc:2:
/home/fxa/.node-gyp/10.15.2/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/fxa/.node-gyp/10.15.2/include/node/v8config.h:324:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [scrypt.target.mk:106: Release/obj.target/scrypt/node_scrypt.o] Error 1
make: Leaving directory '/home/fxa/fxa-auth-server/node_modules/scrypt-hash/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.0-3-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fxa/fxa-auth-server/node_modules/scrypt-hash
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> fxa-geodb@1.0.4 postinstall /home/fxa/fxa-auth-server/node_modules/fxa-geodb
> node scripts/start-db-download.js

**Comment by philbooth** [comment]
Same as mozilla/fxa-auth-db-mysql#487, I think you can ignore this. Is it causing anything to fail?
