### ISSUE TITLE
Add semicolons

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2953]
The OAuth server uses them. The content server uses them. The profile server uses them. Let's use them here too.

**Comment by hritvi** [comment]
May I May I work on this @shane-tomlinson. And also can you give a brief insight into this. Thanks!!

**Comment by shane-tomlinson** [comment]
I think it would be to update the [semi](https://eslint.org/docs/rules/semi) rule in .eslintrc to ["error", "always"], and then running [eslint with the `--fix` option](https://eslint.org/docs/user-guide/command-line-interface).

**Comment by shane-tomlinson** [comment]
@hritvi - and yeah, you sure may work on this!

**Comment by shane-tomlinson** [comment]
Assigning myself to indicate that it's taken.
