### ISSUE TITLE
Remove support for node 8, support 10+

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#2958]
We still support node 8 but our Docker images are now built using node 10. Let's drop support for node 8 and remove node-scrypt from the devDependencies list.

**Comment by farhan787** [comment]
> remove node-scrypt from the devDependencies list.

@shane-tomlinson if I'm not wrong node-scrypt is not there is devDependencies.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson if I'm not wrong node-scrypt is not there is devDependencies.

You are right, I meant optionalDependencies.

**Comment by farhan787** [comment]
@shane-tomlinson ok, but now node-scrypt is used nowhere in the project.

**Comment by shane-tomlinson** [comment]
It is used [here](https://github.com/mozilla/fxa-auth-server/blob/9a8cb1744abb89c2035f2ff7bc0cfc8eb24ee05f/lib/crypto/scrypt.js#L19) and should be removed. It looks like we should also be able to remove [this `if` statement](https://github.com/mozilla/fxa-auth-server/blob/9a8cb1744abb89c2035f2ff7bc0cfc8eb24ee05f/lib/crypto/scrypt.js#L59:L64), deleting from `if`, up to and including the [first `else`](https://github.com/mozilla/fxa-auth-server/blob/9a8cb1744abb89c2035f2ff7bc0cfc8eb24ee05f/lib/crypto/scrypt.js#L64).

**Comment by farhan787** [comment]
@shane-tomlinson I thought it's literally node-scrypt, btw thanks for correcting me.
