### ISSUE TITLE
Replace the `redis.watch.conflict` 500 errors with 409 Conflict

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-server#2966]
It's annoying when these show up in Sentry because they're not actionable and already well-understood. When I wrote the code I thought `500` was the semantically appropriate status to return, but maybe `409 Conflict` would be fine too. Then we'd stop getting badgered in Sentry.

**Comment by shane-tomlinson** [comment]
> but maybe 409 Conflict would be fine too

👍 this seems reasonable.

**Comment by farhan787** [comment]
@philbooth may I fix this ?

**Comment by philbooth** [comment]
Sorry @farhan787, I already opened a PR.

**Comment by farhan787** [comment]
@philbooth no problem, just saw you amazing work there!
