### ISSUE TITLE
Force users to re-auth if they log in from an "unfamiliar" country

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#393]
Per https://github.com/mozilla/fxa-auth-server/issues/222#issuecomment-29769332

> 6) if a user attempts to login from an "irregular" country (ie: they always log in from US/Canada but start getting strange login attempts from Egypt or Brazil) then we force them to confirm the login by email challenge or something. This could be possibly inconvenient for a certain number of users who travel frequently.
Also infers we somehow track/log a user's login history/location.

**Comment by vladikoff** [comment]
@shane-tomlinson to check Aha.io for this

**Comment by shane-tomlinson** [comment]
@rfk, the closest I could find in Aha is FXA-47, "Security event notifcations and dashboards". A similar "Improve User-Facing Security Affordances and Mechanisms" also exists. Would this fall under one of those?

**Comment by rfk** [comment]
Per IRl discussion, @shane-tomlinson is going to surface this as a card in Aha and close it out here

**Comment by vladikoff** [comment]
@shane-tomlinson tried but could not get permissions

**Comment by rfk** [comment]
@billmaggs is working on escalating permissions for @shane-tomlinson; in the meantime I created [1] so we can go ahead and get this closed out.

[1] https://mozilla.aha.io/features/FXA-61
