### ISSUE TITLE
Bad MAC error when talking to server

### ISSUE THREAD

**Issue by st3fan** [mozilla/fxa-auth-server#429]
When talking to today's fxa-auth-server, I get a Bad MAC (Hawk) error when using the picl-spec-crypto client. The API endpoint that fails is `POST /v1/session/create`

I think this is either a regression in the server, or the picl-spec-crypto client was not updated to reflect a server change.

The problem does not happen to the version deployed to `https://api-accounts.dev.lcip.org/`. But I think that deployment is behind at least a week or so.

I'm going through commits but the cause is hard to find.

**Comment by ekessel** [comment]
I'm having the same problem with v1.39.0 on a debian vm I use node v0.10.25. Strange is that the same installation works an a debian vm. Please let me know what you need (e.g. logs).

**Comment by rfk** [comment]
So, I did re-open this but just noticed how old the original bug is, so I'm going to close it back out.  @ekessel it would be great if you could file a new bug with more information about the problem you're seeing.

**Comment by ekessel** [comment]
Will do
