### ISSUE TITLE
onepw protocol should specify sync key management method for user

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#451]
After the user logs in to FxA with `service=sync`, the client needs to determine how to fetch/derive the user's keys. To allow for future key management methods (pairing, 2nd password), I propose @warner's idea of returning a `keyFetchMethod` value that specifies how this should be done for the user. Legacy clients that don't support future methods can "bug out" to a web content flow (https://bugzilla.mozilla.org/show_bug.cgi?id=951306) or display an error.

**Comment by rfk** [comment]
If this is old enough to be saying "onepw protocol" then it's old enough to be RESOLVED/WONTFIX.  We may revisit this topic in the future but we can do it under a fresh bug.
