### ISSUE TITLE
Restrict allowed origins in CORS

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#550]
Is there any reason why shouldn't restrict the allowed origins to the content server domain? The rest of our clients are native.

**Comment by rfk** [comment]
Wow, this is an oldie.  @ckarlof are you still interested in us pursuing this?  My instinct is to agree with @ncalexan sentiment above but happy to push ahead if you still see value in it.

**Comment by ckarlof** [comment]
> IMO, accessing the Auth API from 3rd party untrusted web contexts is an anti-pattern I explicitly want to block, and limiting CORS would help with that. No one should be soliciting the user's credentials on their pages and interacting with our Auth API except for the FxA content server. 

Let me add on to that: "Mozilla reliers accessing the Auth API directly is also an anti-pattern I want to block". 

However, there are ways around CORS if you really want to access the API directly, e.g., proxying those requests through the server.

Since we don't use cookies to authenticate anything, then this is less of a concern (otherwise, we could have CSRF vulns). If ever had evidence that "people" (Mozilla reliers or randos) are accessing the auth api at any significant rate or scale, then this is something we may want to put in place. Like I said before, in theory, it shouldn't break anything because all legitimate accesses to the API in unprivileged Web contexts should be from our content server page.

**Comment by ckarlof** [comment]
As the new FxA lead, it's your call @rfk on when and if we do it.

**Comment by rfk** [comment]
OK, I'm going to z-later this as we close out Q1 and reconsider it when reviewing the backlog for Q2.

**Comment by rfk** [comment]
taking this for triage, will either close our schedule

**Comment by rfk** [comment]
After thinking it over, let's try to move forward with this by defaulting the allowed origins to `*` for our local dev and testing environments, but setting it explicitly in stage and production.  Since we're guarding against unwanted behaviour rather than plugging a security issue, I think this should be a suitable tradeoff w.r.t testing pain.

Concretely, this will look like a `CORS_ORIGIN` config option that defaults to `*` but can be set in production.  We have some prior art for it in the content-server config.

**Comment by rfk** [comment]
I'm going to re-open this and try to tackle it in some background cycles.  Not because I think there are any security problems with our current setup, but because I'm tired of fielding spurious bug-bounty reports about it...

**Comment by rfk** [comment]
FWIW this is still the plan:

> After thinking it over, let's try to move forward with this by defaulting the allowed origins to * for our
> local dev and testing environments, but setting it explicitly in stage and production. Since we're
> guarding against unwanted behaviour rather than plugging a security issue, I think this should be a
> suitable tradeoff w.r.t testing pain.
>
> Concretely, this will look like a CORS_ORIGIN config option that defaults to * but can be set in
> production. We have some prior art for it in the content-server config.

**Comment by rfk** [comment]
As if by magic time machine, this functionality was already implemented and we just never got around to switching it on in production:

  https://github.com/mozilla-services/puppet-config/issues/1606

I've opened a PR against the new deployment repo to help push this over the line:

  https://github.com/mozilla-services/cloudops-deployment/pull/1547

**Comment by vladikoff** [comment]
from mtg: PR from @rfk is there, need input from @jrgm

**Comment by jrgm** [comment]
mozilla-services/cloudops-deployment#1547 has been merged and train-105 will go out with this configured (first in stage where there's automated and softvision device testing; then in prod, solo canary first).

**Comment by rfk** [comment]
This appears to be successfully live in production!
