### ISSUE TITLE
How do we put the app into maintenance mode?

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/fxa-auth-server#639]
Occasionally we need to do database maintenance or migrations. Most of the time these will not affect normal operation however for some scaling events it might result in the service being unavailable. 

Ideally the user should get a friendly and informative message to try again later. 

From the ops side, since we're running clusters of servers a central switch that updates all the servers at once is essential.

**Comment by rfk** [comment]
This is a year old, closing it out
