### ISSUE TITLE
Missing createSchema support and/or docs on using the http db backend

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#718]
Reporting on behalf of a user in IRC, who tried to do a run-your-own-fxa setup but failed because the schema-creation scripts are missing from this repo.  We should do one or more of:

  * add some docs on how to do this with the new http-db-server
  * remove the createSchema config option to avoid confusion
  * temporarily re-instate the schema-creation scripts during migration to the new backend

This may or may not also break a fresh awsbox deploy, I haven't tried.

**Comment by vladikoff** [comment]
from mtg: 

it now links to docs
and we also added more docs to run both DBs
