### ISSUE TITLE
Optimize account/reset -> account/login flow

### ISSUE THREAD

**Issue by zaach** [mozilla/fxa-auth-server#736]
It would save the client an extra request if we could fold `account/login` into `account/reset` and respond with a new `sessionToken` and `keyFetchToken`, etc., like we did for `account/create`.

**Comment by rfk** [comment]
@zaach still interested in this after all this time?

**Comment by zaach** [comment]
I suppose we could check out the metrics for this flow to see just how (non) urgent an optimization it is.

**Comment by rfk** [comment]
I have the very strong impression we're never going to move on this; we can always re-open if it becomes a big deal in practice
