### ISSUE TITLE
Services discovery API

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#738]
Keep it simple:

https://github.com/mozilla/fxa-auth-server/wiki/Service-discovery-API

I have reverse domain name notation in the proposal, but whatever.

**Comment by rfk** [comment]
(passing ownership of this over to @shane-tomlinson)

**Comment by ncalexan** [comment]
Folks, as Fennec migrates to the Web, we *really* want to avoid having 10 preferences for configuration.  Can we take a stab at some simple JSON configuration interface?

**Comment by rfk** [comment]
yes; what's the canonical list of preferences you're going to need for Fennec?

**Comment by shane-tomlinson** [comment]
More proposals in https://github.com/mozilla/fxa-oauth-server/issues/187

**Comment by vladikoff** [comment]
@rfk should we move this to Aha?

**Comment by rfk** [comment]
Migrating further discussion and prioritiazation to https://mozilla.aha.io/features/FXA-65
