### ISSUE TITLE
revisit domain logging

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#740]
Hapi reworked their internal domain code and the request tracing logging no longer works. We should either delete it or fix it.

**Comment by rfk** [comment]
> We should either delete it or fix it.

@dannycoates says we should delete it

**Comment by vladikoff** [comment]
@rfk need a bit of context here, what do we need to remove?

**Comment by rfk** [comment]
IIRC it's to do with anything where we access `process.domain` like this: https://github.com/mozilla/fxa-auth-server/blob/master/lib/tokens/token.js#L66

I have vague recollections of there being more to it than this, but perhaps we've already refactored parts of it away.
