### ISSUE TITLE
Have /v1/recovery_email/verify_code return a sessionToken

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#763]
This is to allow the verification link landing page to create browser ID assertions even if the user opens the link in a different browser. This is to enable two things:

1) Subscribing to various Firefox newsletters on the landing page (which requires talking to an API which need a BiD assertion).
2) Resuming an Oauth flow to a web relier from the email link landing page, even if it's in another browser.

To avoid the creation of two sessionTokens on each account creation, we could add an additional parameter to `/verify_code` which allows the client to signal whether it wants a sessionToken. The default could be "no".

This change would also require us to invalidate verify codes after they are used, since they now have power. 

I've already discussed this with @warner, but I'd appreciate an additional sanity check from @warner, @dannycoates, and others. If we're all set with the design, it would be nice to get the implementation done in train-18 or 19.

**Comment by rfk** [comment]
We haven't had a compelling need for this since 2014, so I'm going to close it out
