### ISSUE TITLE
Fetch and cache all trusted jkus on app startup

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#792]
This would help reduce some of the attack surface of using jkus.

**Comment by vladikoff** [comment]
what should we do about this one @rfk?

**Comment by rfk** [comment]
I think we've done what we can here - fxa-jwtool has a caching layer, but we need to keep open the option of re-fetching the JKU when we see a new key id, because the service might rotate its keys and we don't want to have to coordinate an fxa server bounce every time that happens.
