### ISSUE TITLE
Check for the typ property in preVerifiedTokens

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#796]
Such a thing was suggested by @rfk, and I added to the docs:

https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#preverifytoken

**Comment by rishibaldawa** [comment]
How will typ property be verified? 

I'm thinking it'll happened somewhere around or near this file. https://github.com/mozilla/fxa-auth-server/blob/bbe0688b45a5d1d1ed6cb82bbeb17542c8d8193f/lib/preverifier.js#L29

**Comment by ckarlof** [comment]
@rishibaldawa, I think that's right, but you'll probably need to pass in the expected `typ` and figure out how that works with the rest of the code.

**Comment by rfk** [comment]
@shane-tomlinson, remind me, did we decide we could remove support for `preVerifyToken` because nobody was using it?  I vaguely recall having such a conversation with you.

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson, remind me, did we decide we could remove support for preVerifyToken because nobody was using it?

Yass! The only user was Fx OS Marketplace, and they removed the functionality in Jan 2015. Kill with fire.

Ref https://github.com/mozilla/fxa-content-server/issues/4152

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-js-client/issues/227

**Comment by rfk** [comment]
Great, I'm going to close this issue and replace it with one that removes `preVerifyToken` support in auth-server.

**Comment by rfk** [comment]
Closing in favour of https://github.com/mozilla/fxa-auth-server/issues/1599
