### ISSUE TITLE
always check email case on login

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#800]
authPW combines both the case sensitive email address and password in its stretching. On the server we look up the account via *normalized email*, then do the scrypt hubaju with authPW, if that matches we accept the login. Its *possible* for the case of the email field sent in the request to not match the account record and still have a valid authPW and hence be logged in. If they don't match its likely something *funny* is going on.

**Comment by rishibaldawa** [comment]
I can help with this if someone can point me to the files to look at.

**Comment by rfk** [comment]
Hi @rishibaldawa!  Thanks for offering to help out.  The code for the login route is at:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/routes/account.js#L218

The idea here would be to check that the submitted email matches the one that was looked up on the `emailRecord` from the db.  If they don't match then throw an instance of `AppError.incorrectPassword` which will set the right error codes for the client:

  https://github.com/mozilla/fxa-auth-server/blob/master/lib/error.js#L141
