### ISSUE TITLE
Require re-verification of email when an account has too many bad logins (i.e. account lockout)

### ISSUE THREAD

**Issue by fmarier** [mozilla/fxa-auth-server#801]
This was originally filed as https://github.com/mozilla/fxa-customs-server/issues/39 and the support in the customs-server was merged in https://github.com/mozilla/fxa-customs-server/pull/60.

Like @ckarlof said, we probably need an email flow that isn't password reset and not the same as the initial email verification. So a new error message/screen in the content server as well as a new email template.

https://wiki.mozilla.org/Identity/Firefox_Accounts/Account_lockout

**Comment by ckarlof** [comment]
@shane-tomlinson, @rfk, @chilts. I'm happy to see this almost ready. 

One question: it seems that the time period used for rate limiting and locking is tied to the same time interval: https://github.com/mozilla/fxa-customs-server/blob/master/config/config.js#L47

The intention of account locking was to put up a bigger speed bump for attackers who weren't deterred by our gentler rate limiting that automatically resets after `rateLimitIntervalSeconds`. Meaning, the lockout was meant to address attacks where there are `badLoginLockout` bad logins over a longer period, e.g. `n*rateLimitIntervalSeconds`. I don't know what `n` should be. Maybe 10, or 100? We can tweak that empirically, I suppose. Thoughts?

**Comment by rfk** [comment]
@ckarlof interesting point; this would put `n*rateLimitInvervalSeconds` on the order of hours or even days, which is longer than I was naively thinking, but makes sense as a guard against distributed slow-trickle brute-force attempts like https://github.com/blog/1698-weak-passwords-brute-forced.

**Comment by rfk** [comment]
I filed https://github.com/mozilla/fxa-customs-server/issues/75 to track this on the relevant repo.

**Comment by shane-tomlinson** [comment]
The auth-server portion of this was merged in #867, closing
