### ISSUE TITLE
Notify Basket API of accounts created prior to Basket API integration

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#802]
#786 will automatically notify Basket of new FxA users, but we need a way to import legacy FxA users to Basket as well.

Options:
1) Dump the DB and manually import. (not unless we have to)
2) Do it via the Basket API. (via an endpoint that likely doesn't exist yet)

Thoughts @dannycoates? Perhaps we could run a cron job each night and trickle them over? With this approach, we need some way to indicate whether an account has been sent over. We'll need to decide what to do for accounts that haven't been backfilled with a locale.

/cc @pmclanahan

**Comment by rfk** [comment]
IIUC we plan to put locale data into the profile server, which makes the oauth-token approach more attractive.  @ckarlof do you have a more details oauth-based approach in mind here?

**Comment by ckarlof** [comment]
Summary of RL discussion with @rfk:

* we don't have a timetable for moving the locale into the profile server because there is no customer use case which is motivating it ATM
* enabling this for Basket might require a way for privileged servers to be able to conjure up an OAuth token for *any* user, which is probably not something we want to rush into

**Comment by rfk** [comment]
TBH, I don't think we need to worry about this anymore.  The way we're using basket has changed so that it's no longer a big deal if there's accounts missing on their side.  Closing it out.
