### ISSUE TITLE
Move password verification to the DB

### ISSUE THREAD

**Issue by fmarier** [mozilla/fxa-auth-server#807]
In order to avoid pulling the password verifier out of the DB, through the auth-db-server and into the auth-server, we should send the fully scretched password into the DB for verification by a stored procedure.

This means that we need to go to the DB first and grab the user row for the salt value, then stretch the password and send it to the DB where it will be compared with the verifier.

(part of https://bugzilla.mozilla.org/show_bug.cgi?id=1045264)

**Comment by rfk** [comment]
@chilts is there anything in this issue that hasnt been covered by the  suite of PRs that you reviewed?

**Comment by rfk** [comment]
IIUC we're now doing this, closing
