### ISSUE TITLE
Test customs.* functions are being called at the appropriate times

### ISSUE THREAD

**Issue by chilts** [mozilla/fxa-auth-server#822]
From: https://github.com/mozilla/fxa-auth-server/pull/821#issuecomment-57433777

The other thing we need to check is that the various routes are correctly calling customs.check, customs.flag etc at the appropriate times. For example, send the API a bad password and verify that it calls through to the right customs server method.

(A follow-on from #799 and #821.)

**Comment by vladikoff** [comment]
updated the tests several times since then, reopen if still needed
