### ISSUE TITLE
Log account events

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#826]
Events currently only get broadcast to SNS. It would be useful to log these events for batch processing. Maybe another SQS queue with a logger process would be enough...

**Comment by rfk** [comment]
We could go Full Distributed and make the event-log the canonical source of truth:  http://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying

(I'm only partly joking - this would be super handy for e.g. multi-region replication as well as for downstream notifications)

**Comment by rfk** [comment]
We're following up on this idea with the new notifications work, see e.g. https://github.com/mozilla/fxa-auth-db-mysql/pull/20
