### ISSUE TITLE
Expire email verification tokens

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#829]
They currently live forever and can be "resubmitted".

**Comment by rishibaldawa** [comment]
if this is something simple, I can pick this up.

**Comment by rfk** [comment]
Thanks  for the offer @rishibaldawa.  We have some broader changes in the works that might affect this, e.g. the possibility of changing your email address, adding multiple email addresses, or maybe even not having an email address at all.  I think it makes sense to get or technical story straight on those aspects, and do this bug as part of that broader refactor.

I'm tagging this for triage to discuss in tomorrow's meeting.

**Comment by rfk** [comment]
We'll pick this up in Q3 as part of broader refactor of email management

**Comment by rfk** [comment]
The conclusion from ur discussion today was that this will require surgey to the accounts data model anyway, so we might as well roll it up into a broader refactor rather than try to do it as a one-off.

**Comment by rishibaldawa** [comment]
lemme know if I can pick up something else, preferably lightweight / lowkey.

**Comment by rfk** [comment]
@rishibaldawa we're trying to do a better job of taggings things as "good-first-bug" if they're lightweight enough to dive straight in to; you can use these waffleboard searches to get an overview of current bugs with that label right across the project:

  https://waffle.io/mozilla/fxa-auth-server?search=good-first-bug
  https://waffle.io/mozilla/fxa-content-server?search=good-first-bug

Or if you're after something a little deeper, let me know what interests you and I'll carve something out to fit :-)

**Comment by rfk** [comment]
I'm going to close this out, and we'll do it as part of the data model refactor which is covered in another bug
