### ISSUE TITLE
disable preverfied when marketplace has had a chance to move users over.

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#833]
From a discussion with @ckarlof, we should disable this after marketplace has migrated. (Possibly even put in code to disable automatically after a certain date).

**Comment by rfk** [comment]
@andymckay do you know if the marketplace migration via `preVerifyToken` is still active, or whether we can safely disable it by now?

**Comment by jrgm** [comment]
I'll let @andymckay do final confirmation, but this is done:

https://github.com/mozilla-services/puppet-config/pull/1044
https://bugzilla.mozilla.org/show_bug.cgi?id=1125211

**Comment by rfk** [comment]
Oh great, sounds like it's all good so I'm going to close it out

**Comment by andymckay** [comment]
Yep, good to remove, thanks.
