### ISSUE TITLE
Pass unique request ID through to the db server

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#835]
We tag each request with a unique ID and use it for loging purposes.  It would be helpful to pass this through to the db server (e.g. as some sort of `X-Request-ID` parameter) so that we can correlate logs between the two servers.

**Comment by chilts** [comment]
Sending the `request.rid` from the auth server to the auth db server means passing it from the `routes/*.js` to the `db.*()` calls. The simplest/most obvious way is just to add an extra `rid` parameter to each `db.*()` call.

While this will work it'll be a little bit of churn in all the routes and the `db/http.js`. I'm not overly worried about a number of changes ... but wondering if any of you have a better way of doing it, else I'll just crack on with it! :)

**Comment by rfk** [comment]
@dannycoates did same magic to include the `rid` in logging output even if it's not passed in directly, maybe we can use a similar approach here?

  https://github.com/mozilla/fxa-auth-server/blob/master/log.js#L40

Having to pass it around explicitly sounds awful :-(

**Comment by dannycoates** [comment]
Domains have fallen out of favor in node and I'm not sure that logging trick is 100% working anymore. We might be able use something like https://www.npmjs.com/package/continuation-local-storage buuut IDK. Context is the harderest problem in Computer Science.

I think its worth a (limited) bit of effort to research a magical solution though. We can always do explicit if that fails.

**Comment by chilts** [comment]
Some interesting things there. I'll have a play with some stuff on Friday afternoon - that sounds like the perfect time for some mad-science! :)

**Comment by rfk** [comment]
realistically, I don't think we're going to get around to this; closing it out
