### ISSUE TITLE
Use email authentication to mitigate spam filterings

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#838]
I noticed that in Gmail, emails coming from senders like Google or eBay have a key icon and are alleged to be authenticated.

https://support.google.com/mail/answer/3070163

Is this something we can do, and would it mitigate SPAM filtering?
https://support.google.com/mail/answer/180707

**Comment by rfk** [comment]
Closing in favour of the more recent https://github.com/mozilla/fxa-auth-mailer/issues/64
