### ISSUE TITLE
Shorter email address for account notifications

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-server#841]
I spotted this screenshot on twitter and realized that perhaps verification@accounts.firefox.com might be too long an address in some contexts.

![2014-11-26 22 58 31](https://cloud.githubusercontent.com/assets/68213/5230524/9a831674-76f5-11e4-89a3-1da8ac291731.png)

How feasible would it be to use the email address accounts@firefox.com for activity notifications?

**Comment by ckolos** [comment]
filed https://bugzilla.mozilla.org/show_bug.cgi?id=1129189 with infra to get DKIM in place for this account.

**Comment by rfk** [comment]
@ckarlof do we have any special requirements for e.g. receiving email at this address?  I don't recall the details of what we set up for foo@accounts.firefox.com

**Comment by ckarlof** [comment]
It shouldn't bounce, but no human is going to read that email.

**Comment by ckolos** [comment]
Quick update - There is some reservation about tying up the firefox.com domain to a DKIM record associated with the Amazon SES pipeline which would curtail the ability to do so for other non-fxa products in AWS. Also, I'm waiting on a r+ from secops.

**Comment by ckolos** [comment]
secops r+'d (a bit ago) this and accounts@firefox.com is live. Which train would you like to start testing this in?

**Comment by jrgm** [comment]
Yeah we can probably do this with this train. So test mails have been sent out from this sender?

**Comment by pdehaan** [comment]
This what the response I got when I emailed the new address to say hello:

> Delivery to the following recipient failed permanently:

>     acccounts@firefox.com

> Technical details of permanent failure:
> Google tried to deliver your message, but it was rejected by the server for the recipient domain firefox.com by mx2.corp.phx1.mozilla.com. [63.245.216.70].

> The error that the other server returned was:
550 5.1.1 <acccounts@firefox.com>: Recipient address rejected: User unknown in virtual alias table

But than again, I'm not sure if I tried emailing the previous address and seeing if it responded or bounced.

**Comment by ckolos** [comment]
gah! That's new. I will follow up with infra first thing Monday morning.

**Comment by ryanfeeley** [comment]
@pdehaan @ckolos  I read three Cs there.

**Comment by ckolos** [comment]
I do too on second look. Thanks @ryanfeeley

**Comment by rfk** [comment]
This is live as of train-31
