### ISSUE TITLE
consider increasing passwordForgotToken (and others?) to more than 15 minutes

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#845]
Follow-up to https://github.com/mozilla/fxa-auth-server/issues/842 and https://bugzilla.mozilla.org/show_bug.cgi?id=1110000

The problem *may* have been simply that 15 minutes is to short of an expiry time for the token in some scenarios.

Values set here: https://github.com/mozilla/fxa-auth-server/blob/master/tokens/index.js#L15-L19

**Comment by jrgm** [comment]
This was reported again in https://github.com/mozilla/fxa-content-server/issues/2063. What would be a reasonable value for passwordForgotToken? 30 minutes?

**Comment by cedk** [comment]
For the greylisting, it will depend on how fast the mail server will retry to send and how long the greylisting is set. Usually greylisting is around 5 mins.

**Comment by cedk** [comment]
I find 30 minutes still quite short if you think some fetch there emails few times per day.
Why not 1 day?

**Comment by ckarlof** [comment]
We're changing it to an hour. We can measure the effect of this by monitoring the rate of invalid tokens on the password reset endpoint.
