### ISSUE TITLE
Verification polling is causing performance problems

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-server#849]
It came up in a recent standup meeting that the current Desktop rate of email verification polling (3s) is causing performance issues.

We could decrease the polling rate. Should we just hard code some change in Desktop, or is it worth making it dynamically configurable by the auth server? The client code could throw it over to the Desktop code during login.

**Comment by shane-tomlinson** [comment]
We could also do an exponential backoff on the client after a reasonably-short time period. Change the poll to 5-10 seconds for 2 minutes, then backoff.

**Comment by ckarlof** [comment]
> We could also do an exponential backoff on the client after a reasonably-short time period. Change the poll to 5-10 seconds for 2 minutes, then backoff.

Good idea. I think the bulk of these requests are coming from Firefox, FWIW.

**Comment by shane-tomlinson** [comment]
Link to https://github.com/mozilla/fxa-content-server/issues/68

**Comment by shane-tomlinson** [comment]
Link to:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1122443
* https://github.com/mozilla/fxa-content-server/issues/2038
* https://github.com/mozilla/fxa-content-server/pull/2039

**Comment by shane-tomlinson** [comment]
Closing here - we should be able to handle this on the content server and browser. If that strategy does not work, we can re-open this.

**Comment by ckarlof** [comment]
Desktop patch is in progress to do exponential backoff capping at 1 ping/minute: https://bugzilla.mozilla.org/show_bug.cgi?id=1018022
