### ISSUE TITLE
Misleading error type and errno for /certificate/sign failure

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#858]
In the course of looking at a bug report on IRC, @ckarlof noted this line
https://github.com/mozilla/fxa-auth-server/blob/master/routes/sign.js#L105

However, use of AppError.invalidRequestParameter to report this error returned from the signing cluster seems misleading. Should it be some other error/errno?

**Comment by dannycoates** [comment]
That's the best error for this case because the only time that line gets hit is when the submitted `publicKey` is invalid. Its effectively the same as a validation error, but Joi isn't capable of that level of validation.

**Comment by ckarlof** [comment]
Action on this is for @jrgm to file a PR with a clarifying comment in the code and for @dannycoates to review.

**Comment by vladikoff** [comment]
@jrgm please reopen if still needed.
