### ISSUE TITLE
mysterious 400/107 error when using marketplace.allizom.org

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#859]
@krupa put this image in IRC 

![screen shot 2015-01-21 at 2 25 23 pm](https://cloud.githubusercontent.com/assets/758162/5847681/c6af2044-a184-11e4-9f72-85caa6b0383e.png)

I traced back in Kibana logs, and it was from an account/create. This pop-up was using marketplace stage (https://marketplace.allizom.org/). I don't know if there is any more that can be investigated here.

**Comment by ckarlof** [comment]
Unclear why this happened, but if don't already, we need a dashboard that tracks the frequency of oddball errors like this in production. I feel like we used to have a Kibana dashboard which buckets the frequency of different error nos for the auth API, but I can't find it anymore.

**Comment by dannycoates** [comment]
I didn't notice the reverse mozilla in the domain. The problem is most likely the `redirectTo` request parameter. Prod auth-server only accepts `mozilla.com` addresses.

**Comment by jrgm** [comment]
So, we don't really have anything actionable to pursue on this issue. CLosing.
