### ISSUE TITLE
mail_helper blocks port 25?

### ISSUE THREAD

**Issue by FinMike** [mozilla/fxa-auth-server#864]
After updating to today's git version, i can not have verification emails send. 
There was a postfix already runnig on port 25 of this machine for other reasons than fxa, and after restart, this postfix is blocked by mail_helper.js listening to port 25 so it doesn't even start.  

Is there a way to work arount this?

**Comment by vladikoff** [comment]
Change the mailer port if needed https://github.com/mozilla/fxa-auth-server/blob/12e526cf05615400ef24410f3892dc163ec61a3c/config/config.js#L83

**Comment by FinMike** [comment]
sorry, that might be a misunderstanding: problem is port 25, not 9001?
