### ISSUE TITLE
self-hosted server / trouble staying logged in / strange errors

### ISSUE THREAD

**Issue by codeling** [mozilla/fxa-auth-server#869]
Running on my own server, I'm having trouble getting the combination auth-server and sync server to run. When I try to log in via the sync dialog, the sync page appears properly, I can login, it seems to be successful. Then I get to a page with one big button saying "Administrate" (or rather its german equivalent). When I click on that, I get back to the settings dialog, telling me that I need to login.

In my sync log i have this:
```
1423175931872	FirefoxAccounts	DEBUG	got keyPair
1423175931872	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1423175932522	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format","log":[]}
1423175932522	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format","log":[]}
1423175932523	Sync.BrowserIDManager	ERROR	Authentication error in _fetchTokenForUser: AuthenticationError([object Object])
1423175932523	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.account
1423175932523	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1423175932523	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
```

and
```

1423175932525	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: AuthenticationError([object Object])
1423175932525	Sync.BrowserIDManager	ERROR	Could not authenticate: AuthenticationError([object Object])
1423175932525	Sync.BrowserIDManager	INFO	currentAuthState returning error.login.reason.account due to previous failure
1423175932525	Sync.Status	DEBUG	Status.login: error.login.reason.account => error.login.reason.account
1423175932525	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
```

and
```

1423175940943	Sync.BrowserIDManager	ERROR	Authentication error in _fetchTokenForUser: AuthenticationError(TokenServerClientServerError({"now":"2015-02-05T22:39:00.943Z","message":"Authentication failed.","cause":"invalid-credentials","response_body":"{\"status\": \"invalid-credentials\", \"errors\": [{\"location\": \"body\", \"name\": \"\", \"description\": \"Unauthorized\"}]}","response_headers":{"server":"nginx/1.4.6 (Ubuntu)","date":"Thu, 05 Feb 2015 22:38:59 GMT","content-type":"application/json; charset=UTF-8","content-length":"110","connection":"keep-alive","x-weave-timestamp":"1423175939.36","x-timestamp":"1423175939"},"response_status":401}))
1423175940943	Sync.Status	DEBUG	Status.login: error.login.reason.account => error.login.reason.account
1423175940943	Sync.Status	DEBUG	Status.service: error.login.failed => error.login.failed
```

The sync server (fxa-auth-server) has no output during all of this, there's no more output after the initial configuration display.

The credentials are definitely right (and the seen behavior - that the login doesn't really fail but just doesn't take hold - also doesn't seem to indicate that)....

I have set it up according to this german guide: https://thomas-leister.de/internet/ubuntu-firefox-sync-1-5-server-installieren/
some more information on previous trouble I had can be found here: https://github.com/mozilla-services/syncserver/issues/52

I'm at a loss at what I can do to further debug this...

Edit: Tried now to use Paste#http instead of gunicorn (not sure if this should work as well behind nginx?) There I keep getting this:
```
ERROR:syncserver:The public_url setting does not match the application url.
This will almost certainly cause authentication failures!
    public_url setting is: https://publictokendomain
    application url is:    http://publictokendomain
```
not sure if this is a paste#http or a general problem? Where is this application_url coming from?

**Comment by rfk** [comment]
Sorry to leave this unattended for so long, it slipped off my radar.  Are you still having trouble with this?

This error:
```
1423175932522   FirefoxAccounts ERROR   error POSTing /certificate/sign: {"code":401,"errno":110,"error":"Unauthorized","message":"Invalid authentication token in request signature","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format","log":[]}
```

Indicates that the problem is almost certainly on the fxa-auth-server side.  Your login session seems to be somehow going missing from the db.  Can you confirm in the auth-server and auth-db-server settings that it is correctly using mysql for storage?

**Comment by codeling** [comment]
I'm sorry but I'm not able to invest any more time in this. I have switched to using the provided auth
&sync servers instead. Thanks a lot for your help anyway!
