### ISSUE TITLE
Always "unknown error"

### ISSUE THREAD

**Issue by mathstuf** [mozilla/fxa-auth-server#872]
I'm always getting errno=999 for any request. It doesn't seem that setting `LOG_LEVEL` to `debug` in the environment gets me any more information either. Is there a way to actually get more logging or find out where the error is coming from?

**Comment by rfk** [comment]
You could try `LOG_LEVEL=trace` to get output about what operations are being performed, which may help you track down the problem.

**Comment by mathstuf** [comment]
I don't see any difference with `LOG_LEVEL=trace`. Either in the config files or the environment (only `INFO` lines are being printed).

**Comment by rfk** [comment]
If you're getting a 999, the error is probably being routed through the `translate` function here: https://github.com/mozilla/fxa-auth-server/blob/master/error.js#L55

You could try adding your own logging in that function to track down the source of the error.

**Comment by mathstuf** [comment]
So this was actually caused by problems with the setup. See https://github.com/mozilla/fxa-content-server/issues/2096

**Comment by mathstuf** [comment]
Ah, nevermind, still getting 999.

**Comment by mathstuf** [comment]
So with some poking around, all I can figure is that the 999 error comes in to 'onPreResponse' as `request.response` in `server/server.js`. The backtrace just disappears into the bowels of hlib, so I can only assume the error comes from it as some default or something. The response is already in the non-descript 999 state before it even hits the error translator. FWIW, the requested URL path is `/v1/account/create`. And nginx is silent, so it isn't going through there.

**Comment by rfk** [comment]
Hi @mathstuf, are you still working on getting this up and running?  I'd love to move forward with this bug but I honestly can't think of something else to try, short of "do a clean re-install and see if it works then".  I wonder if it's e.g. a problem with a dependency that silently failed to install correctly.

**Comment by jrgm** [comment]
Haven't heard back. Gonna close this for now, but if you have more info feel free to reopen. Thanks.
