### ISSUE TITLE
Send initial account notification emails

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#875]
* reset password
* change password
* add new sync device

More context: https://id.etherpad.mozilla.org/fxa-activity-notifications

Link to https://github.com/mozilla/fxa-auth-mailer/issues/24

**Comment by rfk** [comment]
IIRC @ckarlof suggested we could use basket for sending these kinds of more "chatty" emails, as a way to get familiar with that system.  Chris, do I in fact recall correctly?

**Comment by rfk** [comment]
> add new sync device

I'm not confident we can reliably detect this from the auth-server.  How do we distinguish between a new device connecting to sync, and some transient web login session?

**Comment by rfk** [comment]
In fact we have a Q1 goal along the lines of "figure out how to distinguish long-lived device sessions from transient web sessions", so I guess this plays into that nicely :-)

**Comment by ckarlof** [comment]
> IIRC @ckarlof suggested we could use basket for sending these kinds of more "chatty" emails, as a way to get familiar with that system. Chris, do I in fact recall correctly?

Yes. Given how easy it seems to add these, I'd rather not block on the integration to send these initial ones.

**Comment by ckarlof** [comment]
> I'm not confident we can reliably detect this from the auth-server. How do we distinguish between a new device connecting to sync, and some transient web login session?

I know that signups get a `service=sync` parameter. We could make logins for sync do the same thing.

**Comment by rfk** [comment]
These are live as of #/876
