### ISSUE TITLE
Put some text on "Reset Password"/"Verify Account" emails indicating that the user should 'Click the big blue button'

### ISSUE THREAD

**Issue by ckolos** [mozilla/fxa-auth-server#881]
With the release of train-31, the email alias accounts@firefox.com has been pointed at my inbox. It's been fun. 

I've noticed that quite a few valid emails are seemingly sent back to the accounts@f.c address by the actual recipient of the two types of email. In some cases, the email is sent with text like "Verify me" or "Plz reset my pass", etc. 

I'm only left with the conclusion that some people might not realize that we intend for them to click the big blue button in the middle of the mail message to continue. Because of that, I don't think it's overkill to add some text to the boilerplate indicating "Hey. You person, click the big blue button to continue this process"

**Comment by rfk** [comment]
>  the email alias accounts@firefox.com has been pointed at my inbox

Thanks Chris, you're a brave man.  What was the previous behaviour - hard bounce, silent blackhole, something else?  Me could consider some sort of automated bounce response as part of the strategy for dealing with this.

**Comment by rfk** [comment]
(Also assigning to @ryanfeeley for UX feedback/triage)

**Comment by ryanfeeley** [comment]
I wonder if there is a rendering issue with the button. Are we using that platform that tests emails? Was it Litmus?

**Comment by pdehaan** [comment]
I vaguely recall Mailinator having some rendering issues with the big blue buttons on some emailz: https://github.com/mozilla/fxa-content-server/issues/1053

But I'm fine with redirecting all the emails to accounts@firefox.com to @ryanfeeley's inbox and letting him triage.

Or even if it goes into some shared mailbox and we build some dashboard so we can all read the emails if we get bored and/or lonely.

**Comment by ckolos** [comment]
@rfk I can't honestly say. When the original account verification@accounts.firefox.com was setup, I didn't have any insight on the behavior of the email. What I've asked the infra team to do is forward emails to the same destination as the old one. If we'd prefer a shared mailbox, I can ask about that too.

**Comment by ckarlof** [comment]
@ryanfeeley, can you comment on whether we need to add copy about needing to click the button? I can see @ckolos's point that it's not obvious that the next step is to click the button.

**Comment by ryanfeeley** [comment]
Append "now"

**Comment by ckarlof** [comment]
> I didn't have any insight on the behavior of the email. What I've asked the infra team to do is forward emails to the same destination as the old one. If we'd prefer a shared mailbox, I can ask about that too.

I received messages on the previous address for a while. Lots of crazy stuff on there, e.g., automated spam filter responses, manual replies, bounces, etc.

**Comment by rfk** [comment]
@ryanfeeley sorry not to follow - is `'Append "now"'` your concrete suggsstion for a fix here?  Append to the text in the button?

**Comment by ryanfeeley** [comment]
Correct

**Comment by rfk** [comment]
Great, thanks - I might take this one as a simple exercise in getting more familiar with our strings process.

**Comment by TrashbinPornoDolske** [comment]
Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by philbooth** [comment]
PR @ https://github.com/mozilla/fxa-auth-mailer/pull/55.
