### ISSUE TITLE
Production exception - RecipientError: Can't send mail - all recipients were rejected

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#883]
There were two occurences of this exception in production at 2015-03-02T23:43:16.325Z 	and 2015-03-02T23:43:06.220Z, both fx36 on win8. Probably could bear some investigation, e.g., are we somehow trying to use an invalid email address?

```
RecipientError: Can't send mail - all recipients were rejected
    at SMTPClient._actionRCPT (/data/fxa-auth-server/node_modules/simplesmtp/lib/client.js:1052:27)
    at SMTPClient._onData (/data/fxa-auth-server/node_modules/simplesmtp/lib/client.js:354:29)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

**Comment by rfk** [comment]
At the least, we should catch this and log the email address to further checking

**Comment by jrgm** [comment]
> At the least, we should catch this and log the email address to further checking

Actually, I think the email address is already logged, now that I looked into this a bit. However, it is stripped out of Kibana reporting for PII reasons. But perhaps @ckolos can look and tell us if there is something unusual about the email address.Those logs are at 2015-03-02T23:43:16.325Z on ip-172-31-15-54, and 2015-03-02T23:43:06.220Z on ip-172-31-22-96.

**Comment by ckolos** [comment]
Same email address in both messages, -<something>-@<someplace>.net. The dashes were present in the address on both servers.

**Comment by rfk** [comment]
I guess the leading dash is causing the error.  This does validate as a proper email address according to the server's validation routine, and I'm pretty sure it's *technically* valid according to the RFC.  We may need to dig into the validation rules used by postfix for comparison.

**Comment by jrgm** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=165244, but interesting note at the end, saying that leading dash is intentionally disabled in Postfix.

**Comment by dannycoates** [comment]
nice sleuthing y'all! So should we add that config to allow them?

**Comment by rfk** [comment]
> So should we add that config to allow them?

This seems like the simplest option to me, and I don't see any harm in it

**Comment by ckolos** [comment]
added allow_min_user here: https://github.com/mozilla-services/puppet-config/tree/auth_issue883

**Comment by rfk** [comment]
Nice work all, calling this one closed

**Comment by jrgm** [comment]
Yeah, I confirmed that this was fixed on stage.
