### ISSUE TITLE
"missing region in config" errors when running content server tests on travis

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-server#888]
Ref https://github.com/mozilla/fxa-content-server/issues/2187

An example from https://travis-ci.org/mozilla/fxa-content-server/builds/53189367

> 13:41:31.317Z ERROR fxa-auth-server: (op=Notifier.publish)
> err: {
>   "message": "Missing region in config",
>   "code": "ConfigError",
>   "time": "2015-03-05T13:41:31.317Z"
> }

I realize this is most likely an error in our configuration, but I'm posting it here to get the folks who know the most about the auth server involved.

**Comment by dannycoates** [comment]
I think this has come up before. In dev this error is benign but in prod its a problem. I suppose we could add a config option that disables the notifier. By default it would remain enabled but could be disabled in dev.

**Comment by pdehaan** [comment]
See #701 for historical context.
