### ISSUE TITLE
replace bigint with bignum?

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#889]
Community interest for big integers has moved to [bignum](https://www.npmjs.com/package/bignum). To run on current and future versions of node (#880) I think it will be worthwhile to switch.

https://github.com/mozilla/browserid-crypto also uses bigint, YAY!

**Comment by vladikoff** [comment]
This is a great idea :+1:

**Comment by rfk** [comment]
yes, doeet :thumbsup:

**Comment by pdehaan** [comment]
IIRC, @dannycoates was saying that this would not be needed after https://github.com/mozilla/fxa-auth-server/pull/902 lands.
