### ISSUE TITLE
Zap the unused and unloved "devices" API

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#890]
@chilts' recent work on availability remined me that we still have this "devices" API endpoint kicking around, being used by no-one and offer zero useful functionality.  It is literally just noise in our API.  @dcoates @chilts @jrgm how would you feel about unilaterally zapping it from the published API and pretending it never happened?

Yes, it would technically be in violation of API compatibility rules.  But I'm pretty sure nobody would notice and it would break precisely nothing.

**Comment by ckarlof** [comment]
destroy

**Comment by jrgm** [comment]
So, I did a kibana query back to Jan 1 (but I think we only keep 6 weeks or so data), and I see small blip of ~30 queries at the beginning of February, but there is no UA associated with the queries, so maybe someone just probing based on the docs. 

I only ask this for completeness but Is it worth leaving a stub 404 on the /v1/account/devices route with a payload that says this was intentionally removed (and not just accidentally missing).

**Comment by ckarlof** [comment]
> I only ask this for completeness but Is it worth leaving a stub 404 on the /v1/account/devices route with a payload that says this was intentionally removed (and not just accidentally missing). 

I believe we anticipated using `status code 410, errno 116: endpoint is no longer supported` for this purpose.

**Comment by jrgm** [comment]
Just to confirm (again), but a kibana query of production data in the past 30 days shows zero calls to /v1/device (or anything with a path matching device).
