### ISSUE TITLE
improve code coverage for error paths of lockout code

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#896]
There are some missing areas of code coverage with some of the new lockout code, for example, in the error handling for DB.prototype.unlockCode(), and in some 'if (emailRecord.lockedAt) then throw' code paths in handlers for:

    /account/login handler
    /account/unlock/verify_code
    /account/destroy
    /password/change/start

**Comment by rfk** [comment]
@chilts I'm going to put a couple of "in progress" your bugs back into "ready" for now, since per IRL discussion you've got other things on the go at the moment
