### ISSUE TITLE
fxa-lastAuthAt (last FXA authentication time) is out of sync or not getting set

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxa-auth-server#899]
The ``fxa-lastAuthAt`` time from [these claims](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-15) is incorrect for me on ``https://verifier.accounts.firefox.com/v2``.

Curiously, the time is correct when I access ``auth_at`` from the [oauth response](https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#response-6) on ``https://oauth-stable.dev.lcip.org``

The ``fxa-lastAuthAt`` time is too far in the past and after testing with a fresh account, my theory is that the time is not getting updated each time I **re-enter** the password.

Here are some details:

When doing a PIN reset flow via web browser on ``https://oauth-stable.dev.lcip.org``, my logs say:

    FxA auth_at: "2015-03-20 16:34:05"; PIN reset start: "2015-03-20 16:33:46"

When doing a PIN reset on Firefox OS 2.1 via claims from ``https://verifier.accounts.firefox.com/v2``, my logs say:

    FxA auth_at: "2015-03-19 20:50:23"; PIN reset start: "2015-03-20 16:35:47"

While watching network traffic, I can see that the device is posting to ``https://api.accounts.firefox.com`` when I re-enter my password.

To try it yourself, here are some steps to reproduce:

Oauth:
* On a Firefox desktop search ``:paid`` on https://marketplace.firefox.com/
* Click a price to pay for the app
* Log in and create a PIN
* Close the payment window
* Click the price again
* Click 'forgot PIN'
* Re-enter Firefox Account password when prompted
* Enter a new PIN and confirm the PIN
* If you see the payment page then the reset was successful

Native:
* On a 2.1 (or higher) Firefox OS device, open Marketplace
* Search ``:paid``
* Tap a price to purchase the app
* Log in and create a PIN
* Close the payment window
* Tap the price again
* Tap 'forgot PIN'
* This will bounce you to the settings app to re-enter your Firefox Account password
* Enter and confirm a new PIN
* You should see an error message

**Comment by ckarlof** [comment]
> When doing a password reset flow via web browser on https://oauth-stable.dev.lcip.org, my logs say:

> When doing a password reset on Firefox OS 2.1 via claims from https://verifier.accounts.firefox.com/v2, my logs say:

Do you mean "pin reset" here, or did you actually do a FxA password reset? Your STR don't mention any FxA password resets.

/cc @SamPenrose

**Comment by SamPenrose** [comment]
Hhmm. It looks like I created this issue when trying to fix another:

  https://github.com/mozilla/gecko-dev/blob/master/services/fxaccounts/FxAccountsManager.jsm#L146

This bug will not be patched for 2.x.

**Comment by dannycoates** [comment]
I don't know all the intricacies of this flow, but from the auth-server's perspective `fxa-lastAuthAt` is tied to the [sessionToken](https://github.com/mozilla/fxa-auth-server/wiki/onepw-protocol#creating-a-session) which are only created by requests to [/v1/account/create](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-v1accountcreate) and [/v1/account/login](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#post-v1accountlogin).

The `fxa-lastAuthAt` of a sessionToken is immutable. To get a newer value requires a new token.

**Comment by kumar303** [comment]
To back up: our end goal is to only allow a user to reset their PIN *after* they've re-entered their Firefox Account password. To do that we check the timestamp for the last time they re-entered their password and make sure it happened after they began resetting their PIN.

**Comment by kumar303** [comment]
@ckarlof oops, yeah, I corrected the summary

**Comment by ckarlof** [comment]
@dannycoates, yeah I don't think this is a server issue.

**Comment by ckarlof** [comment]
> Hhmm. It looks like I created this issue when trying to fix another:

@SamPenrose, can you unpack that please?

**Comment by SamPenrose** [comment]
@ckarlof we don't store the new cert after a refreshAuth, because it was revealing a passel of bugs calling for a significant rewrite. Comment #0 on the bug in question explains why, not that you should care. Kumar has revealed that my workaround created a new bug.

@kumar303 I think you're going to have to add an extra set of timestamps. Something like:

  // in your forgot PIN handler
  this.authRefreshed = 0;
  navigator.mozId.request({refreshAuthentication: 0}); // force password challenge
  // in the onlogin callback you passed to navigator.mozId.watch()
  this.authRefreshed = Date.now()
  // in the PIN reset routines.
  if (Date.now() > this.authRefreshed + GRACE_PERIOD) {
    // error out
  }

**Comment by kumar303** [comment]
Hmm. The reason we're using server timestamps (the "last FxA auth") is so that this protection cannot be bypassed by an attacker who is in control of the device, e.g. one who could modify JavaScript. The scenario here is that an attacker steals a phone and wants to make purchases on the pre-authed phone so they try to reset the PIN.

**Comment by SamPenrose** [comment]
I don't have a good answer. Patching 2.x correctly is essentially impossible at this point, and when it was "easier", we were afraid to do so because of the other issues it revealed.

**Comment by rfk** [comment]
This and a variety of other small bugs make me wish for a `/session/refresh` endpoint that will check the password and bump the lastAuthAt without creating a new session.

> Patching 2.x correctly is essentially impossible at this point

Is this because the patch required would be too complex/risky, or because we basically cannot ship any sort of patch to 2.x?

**Comment by SamPenrose** [comment]
> Is this because the patch required would be too complex/risky, or because we basically cannot ship any sort of patch to 2.x?

Each of those problems is daunting. I believe 2.1 has reached consumers; 2.2 has certainly reached partners. For complex/risky, see https://bugzilla.mozilla.org/show_bug.cgi?id=1031580#c0 and following. And of course they interact; if we discover a problem in the patch after a hypothetical upload or OTA ...

**Comment by ckarlof** [comment]
> This and a variety of other small bugs make me wish for a /session/refresh endpoint that will check the password and bump the lastAuthAt without creating a new session.

For historical context: https://github.com/mozilla/fxa-auth-server/issues/538

My recollection is, at the time, @dannycoates rejected having an extra endpoint in favor of just creating a new session token. At the time, we also didn't have anyone using it. :)

Worth revisiting.

**Comment by rfk** [comment]
@kumar303 where do you want to go from here?  It sounds like there's not much we can do to help with this on the server-side, and a client-side fix is unlikely.  Is this something that can be worked around without impacting security for non-affected devices?

**Comment by kumar303** [comment]
@rfk we're tracking it here https://bugzilla.mozilla.org/show_bug.cgi?id=1145878

We'd like to get a client/server fix for this (anything we can use to verify password entry). It sounds like maybe B2G 3.0 and up would be a realistic target? There are some ideas for workarounds in that bug above.

**Comment by SamPenrose** [comment]
I'd strongly recommend moving MP to OAuth-only, and if necessary (which it may not be), updating the client relier library to integrate with mozId, which would fix the problem and is what we want to do anyway:

https://github.com/mozilla/fxa-relier-client/issues/33

The approach mooted about in:

https://bugzilla.mozilla.org/show_bug.cgi?id=1031580#c0

is a significant Gecko rewrite which will be made redundant by the move to the relier library.
