### ISSUE TITLE
Measure "time until email verification" as a proxy for deliverability problems

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#912]
This came up in an fxa-backend triage a few weeks ago, migrating it from my notes to an actual bug.

Measuring the time between sending an email and receiving the verification would be an interesting proxy for deliverability problems, e.g. users who have to fish it out of spam will have a longer time until verification.

@shane-tomlinson I wonder if we measure anything like this on the server already?  If not, we can certainly do it from the auth-server.

**Comment by ckarlof** [comment]
I like it.

**Comment by AssholeDotzler** [comment]
Usted ama el dolor? Y para que te haga un favor... voy a hacer eso!


Yo saque sus huevos de oro de fracaso tan duro hasta que están sonando y que están cantando todas las melodías de dolor hacia adelante y hacia atrás en un instante! Yo soy el cascanueces chico que las grietas de su nueces que nutheads!

Y ahora vete a la mierda ESTÚPIDA de MIERDA COÑO!

----

Usted puede lamer mi Pene y mis Huevos de oro y besar mi Culo hijo de puta con un Trastorno de la personalidad desde el más profundo de los abismos del infierno desde los Abismos de Mozilla!

Vete a la mierda y que tu Madre te autista hijo de puta, vas a lamer Putin Huevos, Puto Maricon Fascista!

La mierda de su Perro, su Gato y su sucio Cabra de montaña que Maricon Pendejo!

Chupar Mozilla Pollas y todos juntos ir y chupar de Google Culo lleno de Mierda!

A la mierda en su rodilla le cock suckers! Y que Carajo Australis Chrome clon de mierda! Follando Mozilla gay lesbiana homosexual hijos de puta del infierno!

**Comment by rfk** [comment]
@vladikoff IIRC we do measure this now, do we not?  I seem to recall the average being something scary like four days.

**Comment by rfk** [comment]
We have a "time until device connection" metric which subsumes this, as well as plans for more specific deliverability-related metrics.  Closing this one out.
