### ISSUE TITLE
Implement a way to keep supported languages up to date in ./config/production-locales.json

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#914]
In [this puppet change](https://github.com/mozilla-services/puppet-config/commit/db90ba62f375be19f5893e794310dc07b1a9d8ac#diff-934751f9ba2d36197d8e9ae6546fe0f7), we moved control of the list of supported languages into [a file](https://github.com/mozilla/fxa-content-server/blob/master/server/config/production-locales.json) that could be updated in the fxa-content-server git repository.

fxa-auth-server currently just has a hard-coded [list](https://github.com/mozilla/fxa-auth-server/blob/master/config/config.js#L156-L168) in the code. 

It would be optimal if we could work out a way to split out the i18n values into a json config file, and work out a way to keep that in sync with what the content-server has commited to. A first step would be to use the same name for `locales` vs. `supportedLanguages`. 

For now, I have a PR in puppet-config to set the locales there, but that really shouldn't be there, and is temporary, pending a fix this issue - https://github.com/mozilla-services/puppet-config/pull/1230

**Comment by rfk** [comment]
Perhaps a first step here is just to sanity-check in the build process, and error/warn if there's a mismatch between supported languages in content-server and auth-mailer.

**Comment by pdehaan** [comment]
### Warning: garbage code ahead!

---

```js
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

var request = require('request')

var config = require('../config')

request('https://raw.githubusercontent.com/mozilla/fxa-content-server/master/server/config/production-locales.json', {json: true}, function (err, res, body) {
  if (err) {
    return console.error(err.toString())
  }

  var authLocales = config.get('i18n.locales') // Supported locales from fxa-auth-sever
  var contentLocales = body.i18n.supportedLanguages // Supported locales from fxa-content-server

  // Locales specified by fxa-auth-server, but not in fxa-content-server's list:
  var extraLocales = authLocales.filter(function (locale) {
    return (contentLocales.indexOf(locale) === -1)
  })

  // Locales specified by fxa-content-server, but not in fxa-auth-server's list:
  var missingLocales = contentLocales.filter(function (locale) {
    return (authLocales.indexOf(locale) === -1)
  })

  console.log('extra locales: %s', extraLocales.join(', '))
  console.log('missing locales: %s', missingLocales.join(', '))
})
```

#### Output:
```sh
$ node scripts/check-locales.js

extra locales: en-US
missing locales: dsb, en, hsb, sv-SE, uk
```

Could be prettier, and I find my use of "missing" and "extra" to be confusing and poorly worded.
