### ISSUE TITLE
POST /v1/account/unlock/verify_code throws 'contains invalid parameters' instead of ' invalid verification code'

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#937]
### STR
Use the provided curl example in the docs against the local server (127.0.0.1:9000):
https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#request-8

### Expected

Either `200 OK {}` OR `status code 400, errno 105: invalid verification code`

### Actual
```
{"code":400,"errno":107,"error":"Bad Request","message":"Invalid parameter in request body","info":"https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#response-format","validation":{"source":"payload","keys":["code"]},"log":[]}%
```

### Details
Tested on fxa-auth-server `ec669ceb37f754335e296d13ec985deefc2d122d`
ref https://github.com/mozilla/fxa-js-client/issues/151

**Comment by dannycoates** [comment]
The example `code` should be 32 chars not 64.
