### ISSUE TITLE
Switch from ass to nyc?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-server#945]
Per @dannycoates' https://github.com/mozilla/fxa-auth-server/pull/939#issuecomment-104058947

> _"It might be worth looking at https://www.npmjs.com/package/nyc"_

---

**nyc** &mdash; a code coverage tool built on istanbul that works well for applications that spawn subprocesses.

**Comment by rfk** [comment]
I doubt we're going to get around to prioritizing this, closing it out
