### ISSUE TITLE
Support for changing primary email address

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-server#957]
To support https://github.com/mozilla/fxa-content-server/issues/2527 we need to make some fairly significant changes to our auth model.

Accounts currently use the primary email for more than just an alias to the `uid` (User Identifier). Its used to:

- salt the login password sent to the auth-server, `authPW`
- salt for unwrapping `kB`
- the recovery email address
- the "username" (how one identifies themself)

To allow one to change their email address the first thing we need to do is separate the salting concerns. We don't want to require the salt to change when the email changes otherwise it becomes like a password change scenario which has complications for Sync and kB. We can do this by adding a new db field specifically for the salt, `passwordSalt`, which will initially be a copy of the `email` field, except that it will *not* change. Now the `email` field can safely change without affecting the crypto bits.

**How this changes the login flow.**

The client will optimistically try to salt the password with the user given email address as usual. If they haven't changed their address, they're logged. If they have changed it, the password will not validate, the server will compare the submitted email with the passwordSalt. If they are different, it will return a new error (nearly identical to the existing "Incorrect email case") "Incorrect salt" with the correct salt in the payload. The client can recompute the authPW and retry.

*An actual password change flow is an opportunity to make passwordSalt and email the same again*

Do we need to worry about "offline" unwrapping of kB? If so the client will need to store passwordSalt.

cc @rfk @eoger

**Comment by pdehaan** [comment]
If I change my primary email address, does that mean that we need to ping the Basket API, remove their original email address and resubmit to basket with their new email address (assuming they signed up for the newsletters through FxA)?

**Comment by dannycoates** [comment]
@pdehaan that seems like a reasonable expectation to me

**Comment by rfk** [comment]
We'll need to do *something* with basket but the dance @pdehaan  just outlined horrifies me; let's make sure the notification system can solve this problem in a nice way.

**Comment by dannycoates** [comment]
> the dance @pdehaan just outlined horrifies me

heh, right. The expectation that changing my email will stop messages to the old address and start them on the new one is the important part. The auth-server itself should probably only need to announce the "changedEmail" event and allow downstream to handle their own details.

**Comment by pdehaan** [comment]
> ... but the dance @pdehaan just outlined horrifies me

@pdehaan; proudly horrifying Mozillians since 2013!

**Comment by rfk** [comment]
I think we already have a generic "shit's changed yo" event type in the auth-db-server notification stuff, originally intended to signal change in locale.  Piggybacking on that makes sense, i.e. basket sees a "changed" event and just refreshes all the relevant profile data about that user.

**Comment by shane-tomlinson** [comment]
>  heh, right. The expectation that changing my email will stop messages to the old address and start them on the new one is the important part. The auth-server itself should probably only need to announce the "changedEmail" event and allow downstream to handle their own details.

Perhaps I'm lazy, but I sort of feel this should be left to the user, or at a minimum, require user action. The user opted in to the emails on address A. Even though they change their primary address, they may not fully understand the repercussions and automatically changing the basket email to address B with no interaction/explicit callout of the effect could be unexpected.

**Comment by rfk** [comment]
> Do we need to worry about "offline" unwrapping of kB? If so the client will need to store passwordSalt.

No, I don't think clients should be trying to store anything that could lead to kB.  They should derive that keys they need and then store those.  So it seems fine to make an online-only operation.

**Comment by rfk** [comment]
> We don't want to require the salt to change when the email changes otherwise it becomes
> like a password change scenario which has complications for Sync and kB.

Possibly terrible UX, but if we prompted for the password during the email change (like a "re-enter your password to confirm this important action" type thing) then IIUC we could update the salt as part of the change without breaking things for connected clients.

**Comment by dannycoates** [comment]
> IIUC we could update the salt as part of the change without breaking things for connected clients

Even if it is the case that Sync would technically be able to recover by "starting over" with the new kB it seems like the nuclear option for kB encrypted data in general. Especially when its almost just as easy for us to not change the salt. Am I off base on any of that? My knowledge on the details of how we use kB are not very fresh in my mind.

I view this change as separating these two concerns that in hindsight should have been separate from the start.

**Comment by seanmonstar** [comment]
Also, the email is saved in the oauth-server, to facilitate the profile server's /email route. The email is saved per token, so when a token expires (maximum 2 weeks), the new email will then be in place. But that lag is poopy.

**Comment by rfk** [comment]
> by "starting over" with the new kB

IIUC we can effect a password change without changing kB, by doing some magic with the value of wrap(wrap(kB)) that's stored in the server.  It's only the password *reset* that should cause a change in kB and make sync go nuclear.

> the email is saved in the oauth-server, to facilitate the profile server's /email route

Ah yes, thanks, I had forgotten about that.  Let's be sure to use this opportunity to clean up the duplication there as well.  Also, IIUC this could get complicated with long-lived refresh tokens that would keep the old email around forever.

**Comment by rfk** [comment]
> I view this change as separating these two concerns that in hindsight should
> have been separate from the start.

Details of how we get there aside, I like this view of things.

**Comment by rfk** [comment]
IIRC the main point of using the email to salt the password stretching, was to avoid requiring two round trips for login in the common case.  I guess the broader question is, do we want to try to preserve that property somehow while allowing for a "you got a stale salt, try this one" error message for edge cases?  Or will changing your email address relegate you to two-round-trips-for-login until such time as you forget your password and have to reset it?

**Comment by seanmonstar** [comment]
> Also, IIUC this could get complicated with long-lived refresh tokens that would keep the old email around forever.

Yea, that would extend the lag forever. Even 2 weeks would un acceptable, so unless there's a way to remove the email out of the database entirely for oauth, the way forward would be that the oauth server would need to listen for notifications, and update all codes/access_tokens/refresh_tokens for a give uid.

**Comment by rfk** [comment]
I'm thinking this might be a job for service tokens; when the profile server needs to know the email address, it just asks the auth server for the current value using either the existing "profile" scoped token, or a synthesized backend service token.  We could do a bit of caching to speed it up, with notifications to ensure freshness, but the underlying mechanism would be to pull this data out of the auth server directly.

@seanmonstar thoughts?

**Comment by seanmonstar** [comment]
That could work. Though, does that mean the profile server racks up tokens for every user? Might it make more sense to have simply have a way for the profile server to authenticate to the auth server, such as a shared secret (wah), and ask for any email it needs?

**Comment by dannycoates** [comment]
> doing some magic with the value of wrap(wrap(kB)) that's stored in the server.

that's right! I should have looked at the change password code. I forgot about the extra level of wrap in there. Anyway, if we answer the UX question around passwords we can get this part rolling.

@ryanfeeley UX question: Is it reasonable to ask the user for their password when they want to change their email address?

**Comment by zaach** [comment]
From the flow diagram[1] it looks like the password is required to initiate the flow. Which seems like a good idea, since you'd be able to reset the password if you have control of the email account.

[1]: https://www.lucidchart.com/documents/view/9c9a4647-615f-4b7c-a4db-71ae10afcd04

**Comment by dannycoates** [comment]
Nice! Thanks @zaach

**Comment by ryanfeeley** [comment]
Well said @zaach! It's been a while. I probably put it there for a reason, or saw it so many places before I put it there in faith. Honestly, I can't remember.

**Comment by rfk** [comment]
> Might it make more sense to have simply have a way for the profile server to authenticate
> to the auth server

This is what backend service tokens are all about, doing this in a granular way that's in line with the existing permission system around our services.

**Comment by rfk** [comment]
Heads-up that we may be opening a can of worms for native android account objects, ref https://bugzilla.mozilla.org/show_bug.cgi?id=1173566

**Comment by eoger** [comment]
Here's what I understood from this discussion, we reuse a lot of what we do in the [change password flow](https://github.com/mozilla/fxa-auth-server/wiki/onepw-protocol#changing-the-password). I'd love some feedback so I can start to work on it!

![change-email flow](https://cloud.githubusercontent.com/assets/6424575/8318423/0f616264-19b9-11e5-8081-40d2c58e27fc.png)

**Comment by dannycoates** [comment]
@eoger nailed it! :+1:

**Comment by eoger** [comment]
This image was useful but it does not outline how we interact with the email. Here's what I had in mind:

1. POST /v1/email/change/send_code (params: oldEmail, email, authPW)
   => Server responds with a keyFetchToken and a emailChangeToken (containing the new email and a verification code). It also sends an email with the url including the verification code.

2. User clicks on the link in the email

3. POST /v1/email/change/finish (params: verification code, authPW, wrapKb)
    => Server retrieves the emailChangeToken and updates all necessary db fields

What do you think?

**Comment by dannycoates** [comment]
> What do you think?

I think that will work, but not performing the change until after the verification link is clicked might be confusing. We'll either need messaging to tell the user that the change isn't complete until they click the link in the email, or we could do the change but mark the account as unverified while sending the verification link.

The difference is subtle, but to *me* it seems like the UX edge cases are easier if we make the change up front. What if the email doesn't arrive quickly? How do I request a new one? If I forget about verifying what does the login message say when I try to use the new address? An optimistic change can handle those cases like a fresh unverified account.

@ryanfeeley Thoughts on the email change verification flow?

**Comment by ckarlof** [comment]
I had a chat with @ryanfeeley about this in Whistler. My conclusion was that regardless of how we want to expose "change" to the user, at the API level, it may be better to expose more of an add/delete/verify/set primary API than a change/verify API. This will give us more flexibility in the future to allow the user to have multiple emails associated with her account, and it will also help make it more clear how we handle the purgatory state of an added, but unverified email address. Then we can implement "change" as:

1) add
2) verify
3) set primary
4) delete

**Comment by ryanfeeley** [comment]
@dannycoates Change upon email verification is e-actly as I’d specced it (my Nightly is not inputting ecks and wons currently). https://www.lucidchart.com/documents/view/9c9a4647-615f-4b7c-a4db-71ae10afcd04

**Comment by rfk** [comment]
Hmm...I agree about generalizing the backend, but if we go all the way to multiple addresses on the backend, should we just go all the way on the frontend as well?

**Comment by ckarlof** [comment]
> if we go all the way to multiple addresses on the backend, should we just go all the way on the frontend as well?

If we "go all the way on the frontend", we need to figure out WTF to do with all these extra email addresses (from a user perspective) from day one. Changing email as a MVP is more straightforward user expectation-wise, but I'm open to being convinced otherwise.

**Comment by rfk** [comment]
Fair point.  Conversely, we have to be care about not getting users stuck in weird half-way states where they have an old email associated with their account that they don't want anymore, but no way to see or fix this situation in the UI.

**Comment by rfk** [comment]
Following on from @ckarlof's point above, I think it makes sense to implement the email parts of #973 and then build the change-email flow on top of them.  @eoger are you still interested in diving into this?  (totally fine if not, I just want to make sure we coordinate properly if you do)

**Comment by rfk** [comment]
@billmaggs @ryanfeeley it seems to me that this is large enough that we should create a corresponding user-story in aha for work scheduling purposes.

**Comment by billmaggs** [comment]
Yeah, I will do that now. We're agreed that the feature is just changing your one email address, right? No multiple address user requirements for now; make it any way you want on the back end, of course.

**Comment by rfk** [comment]
Yep, agreed, only changing the one from a UX perspective.

**Comment by vladikoff** [comment]
@billmaggs will check if the card exists for this

**Comment by vladikoff** [comment]
Created an ideas: https://mozilla.aha.io/ideas/FXA-I-2 

Closing until we prioritize this

**Comment by rfk** [comment]
Since there's a lot of good context in this bug, I added a link back to it from the feature card.
