### ISSUE TITLE
Re-enable checkPassword API

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#960]
We had to revert the use of the checkPassword API due to some dependency mis-match issues:

  https://github.com/mozilla/fxa-auth-server/pull/954

Things seem stable now, so let's un-revert it and get it out on this train.

**Comment by chilts** [comment]
This will be fixed with https://github.com/mozilla/fxa-auth-server/pull/964

**Comment by chilts** [comment]
All of this has been implement from the PRs mentioned here : https://github.com/mozilla/fxa-auth-db-mysql/issues/51#issuecomment-110996075
