### ISSUE TITLE
Do we allow passing service=sync in query parameters?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#961]
I noticed in our kibana logs that Android is making account-create requests like this:

```
  request		POST /v1/account/create?service=sync&keys=true HTTP/1.1
```

But from a quick glance at the code, some of our service-handling logic only looks for it in the request body.  We should sanity-check the flow here to make sure users on android are getting the expected experience.

**Comment by rfk** [comment]
We don't currently, but should accept it in the qs as well as the request body.

**Comment by rfk** [comment]
As a clearer restatement of the purpose of this bug:  We currently accept a "service" parameter in request bodies and do things with it; we should find all the places where that happens and ensure that it looks in the query parameters as well.

**Comment by philbooth** [comment]
Hey @rfk, I have [a branch](https://github.com/mozilla/fxa-auth-server/compare/phil/issue-961) for this but I'm having some trouble with a couple of tests. Can you help?

The tests that I've added for `/account/login` and `/password/forgot/send_code` are both timing out. The message `No verify code match` is logged to the console, which I can see comes from `test/mail_helper.js` if certain headers are missing. I'm not sure what I need to do to make them work though.

Links to the tests:

* [log in with service query parameter](https://github.com/mozilla/fxa-auth-server/blob/9114fb4b31e84a06afba730d47884652672ec8e9/test/remote/account_login_tests.js#L125-L144)
* [forgot password with service query parameter](https://github.com/mozilla/fxa-auth-server/blob/9114fb4b31e84a06afba730d47884652672ec8e9/test/remote/password_forgot_tests.js#L331-L359)

Do you know what I'm doing wrong?

**Comment by philbooth** [comment]
Ugh, sorry @rfk. Please ignore me, I'm an idiot. :)
