### ISSUE TITLE
Allow users to opt out of event notification emails

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#972]
As of #876 we're sending notifications to the user when important things happen on their account, like adding devices and changing passwords.  We should give them the ability to opt out if they don't find these useful. 

(As a side benefit, this will give us something we can measure to judge whether the emails are useful - if everyone's opting out, we should reconsider sending them at all).

/cc @shane-tomlinson

**Comment by rfk** [comment]
@ryanfeeley this could be something that drives us to flesh out that "communication preferences" page a little more.

**Comment by ryanfeeley** [comment]
I'd also like to take a pass at improving the email copy. I don't think it's transparent enough at the moment.

**Comment by rfk** [comment]
That would be great :-)

**Comment by pdehaan** [comment]
Should a user be able to opt out of "security" emails?
I recently had to generate an "app password" for my Apple iCloud something, and there was no unsubscribe button &mdash; only links to Support and privacy policy, etc.

/cc @ryanfeeley

**Comment by ryanfeeley** [comment]
Doing a quick check in my inbox, I don't see other providers giving a way to opt-out of security related notices — probably for security reasons :)

I don't think we should offer this feature, but we can measure nasty replies and add it if the number is say higher than 3%?

**Comment by rfk** [comment]
So...I guess I'll close this WONTFIX, and @ryanfeeley can open a new bug for improving the copy of those emails.  Thanks folks!

**Comment by pdehaan** [comment]
> @rfk: "... can open a new bug for improving the copy of those emails."

Filed as https://github.com/mozilla/fxa-auth-server/issues/977
