### ISSUE TITLE
Bad Mac during registration

### ISSUE THREAD

**Issue by ekric** [mozilla/fxa-auth-server#974]
As requested here https://github.com/mozilla/fxa-auth-server/issues/429 I'm opening a new issue.

I'm using v1.39.1 but the problem also occurs with v1.39.0 and v1.38.0 it doesn't occur with 1.37.0

Here ist the relevant part of the log:

{"Timestamp":1435941708950000000,"Logger":"fxa-auth-server","Type":"activityEvent","Severity":6,"Pid":3842,"EnvVersion":"2.0","Fields":{"event":"account.created","uid":"378d7c401c02421dbf42403e85fc4bb6","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0"}}
{"Timestamp":1435941708954000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":3841,"EnvVersion":"2.0","Fields":{"code":200,"route":"putsessiontokenid","method":"PUT","path":"/sessionToken/c1bd6a750692a6fdb3a98cc55294bd67690bc43f4073ff6737368bb278142f1c","t":1}}
{"Timestamp":1435941708975000000,"Logger":"fxa-auth-server","Type":"mailer.send","Severity":6,"Pid":3842,"EnvVersion":"2.0","Fields":{"op":"mailer.send","email":"..."}}
{"Timestamp":1435941708989000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":3842,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"errno":0,"rid":"1435941708672:debian:3842:ibnulmlm:10001","path":"/v1/account/create","lang":"de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0","remoteAddressChain":"[\"192.168.56.1\",\"127.0.0.1\"]","t":317,"uid":"00","email":"..."}}
{"Timestamp":1435941709021000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":3841,"EnvVersion":"2.0","Fields":{"code":200,"route":"getsessiontokenid","method":"GET","path":"/sessionToken/c1bd6a750692a6fdb3a98cc55294bd67690bc43f4073ff6737368bb278142f1c","t":0}}
{"Timestamp":1435941709039000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":3842,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":401,"errno":109,"rid":"1435941709017:debian:3842:ibnulmlm:10002","path":"/v1/recovery_email/status","lang":"de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0","remoteAddressChain":"[\"192.168.56.1\",\"127.0.0.1\"]","t":21,"uid":"00"}}
{"Timestamp":1435941709114000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":3841,"EnvVersion":"2.0","Fields":{"code":200,"route":"getsessiontokenid","method":"GET","path":"/sessionToken/c1bd6a750692a6fdb3a98cc55294bd67690bc43f4073ff6737368bb278142f1c","t":1}}
{"Timestamp":1435941709117000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":6,"Pid":3842,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":401,"errno":109,"rid":"1435941709111:debian:3842:ibnulmlm:10003","path":"/v1/recovery_email/status","lang":"de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0","remoteAddressChain":"[\"192.168.56.1\",\"127.0.0.1\"]","t":6,"uid":"00"}}

Content server says: "NetworkError: 401 Unauthorized - http://.../v1/recovery_email/status"

Please let me know if you need any more information. I use debian wheezy, node v0.10.25, npm 1.3.24 and nginx 1.2.1-2.2+wheezy3

**Comment by vladikoff** [comment]
99% of bad mac errors happens when PUBLIC_URL of the auth server does not match the content servers:
https://github.com/mozilla/fxa-auth-server/blob/master/config/index.js#L30
https://github.com/mozilla/fxa-content-server/blob/master/server/lib/configuration.js#L64

**Comment by ekric** [comment]
Maybe it's my config, has something been changed in the config syntax till v1.37.0? I can't find anything in the documentation.

This my prod.json:
{
  "publicUrl": "http://fxaccount-api.example.com",
  "contentServer": {
    "url": "http://fxaccount.example.com"
  },
  "db": {
    "backend": "mysql"
  },
  "mysql": {
    "user": "fxa"
  },
  "smtp": {
    "host": "mail.example.com",
    "port": 25,                                
    "secure": false,                            
    "password": "...",                
    "sender": "Firefox Accounts Server <fxacc@example.com>",
    "resendBlackoutPeriod": 0                  
  },                                           
  "toobusy": {                                 
    "maxLag": 0
  },
  "log": {
    "level": "info"
  },
  "verifierVersion": 0,
  "bounces": {
    "region": "us-east-1"
  },
  "customsUrl": "none",
  "trustedJKUs": [
    "http://127.0.0.1:8080/.well-known/public-keys",
    "http://127.0.0.1:10139/.well-known/public-keys"
  ],
  "lockoutEnabled": true,
  "snsTopicArn": "disabled"
}

This is my local.json:
{
  "public_url": "http://fxaccount.example.com",
  "fxaccount_url": "http://fxaccount-api.example.com",
  "oauth_client_id": "...",
  "oauth_url": "http://127.0.0.1:9010",
  "profile_url": "http://127.0.0.1:1111",
  "profile_images_url": "http://127.0.0.1:1112",
  "client_sessions": {
    "cookie_name": "session",
    "secret": "...",
    "duration": 86400000
  },
  "env": "development",
  "use_https": false,
  "static_max_age" : 0,
  "i18n": {
    "supportedLanguages": ["af", "an", "ar", "as", "ast", "az", "be", "bg", "bn-BD", "bn-IN", "br", "bs", "ca", "cs", "cy", "da", "de", "dsb", "el", "en", "en-GB", "en-ZA", "eo", "e
  },
  "route_log_format": "dev_fxa",
  "logging": {
    "fmt": "pretty",
    "level": "debug"
  },
  "static_directory": "app",
  "metrics": {
    "sample_rate": 1
  },
  "allowed_parent_origins": ["http://127.0.0.1:8080"],
  "csp": {
    "enabled": true,
    "reportUri": "/_/csp-violation"
  }
}

The domains are fully working locally.

Thank you

**Comment by rfk** [comment]
And the exact same config file works fine in v1.37?  Interesting.

There hasn't been a lot of change since that version, but we did make some tweaks to config file loading:

  https://github.com/mozilla/fxa-auth-server/blob/master/CHANGELOG

I wonder if it's e.g. picking up config from the environment that it wasn't seeing in previous versions.  We may need @dannycoates to take a look at this one.

**Comment by ekric** [comment]
Yes, the same config works on v1.37

I just check out the tag and do a "npm install"/"npm start"

**Comment by dannycoates** [comment]
`CONFIG_FILES` is now an explicitly required environment variable to load json configs. Previously it looked for a json file matching `NODE_ENV`. See also https://github.com/mozilla/fxa-dev/commit/5df49370dfe56c1d30fde8376646577b5b08fd04

**Comment by ekric** [comment]
How does that effect my behavior? You mean that my config isn't loaded?

My config file is in: fxa-auth-server/config/prod.json

I changed "start": "NODE_ENV=prod scripts/start-local.sh 2>&1" in package.json

and I see:
> fxa-auth-server@1.39.1 start /home/fxcloud/fxa-auth-server
> NODE_ENV=prod scripts/start-local.sh 2>&1

**Comment by vladikoff** [comment]
@ekric , you might need to set something like `CONFIG_FILES=./config/prod.json npm start`

**Comment by ekric** [comment]
It works, thank you. It would be great if you could include a example (prod) config with the current version like with the content server.
