### ISSUE TITLE
improve the copy on security notification emails

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-server#977]
Per https://github.com/mozilla/fxa-auth-server/issues/972#issuecomment-119328033

> @ryanfeeley: "I'd also like to take a pass at improving the email copy. I don't think it's transparent enough at the moment."

**Comment by pdehaan** [comment]
On the topic of security notification emails... I just authorized a site to sync some ebooks to my Dropbox account, and received this email shortly after. Not sure if this is something we want to consider when a person authorizes a service like Pocket, or if that's just an excessive use of email:

![](https://cloud.githubusercontent.com/assets/557895/8599106/6a535662-2613-11e5-95e7-571ce8fa197a.png)

**Comment by rfk** [comment]
Interesting.  Pocket sends a lot of email of their own when you connect, I wonder if ours would be one too many.

**Comment by ryanfeeley** [comment]
Pocket emails are more about onboarding, and getting you to use the product.

The Dropbox email above is more of a security notice that is pretty standard for any account system that has reliers. It's just a good idea, especially as we're an account that is syncing passwords.

I think we should be doing both. The security notices should fit the style I've set here along with a few other reminder and post-verification emails: http://people.mozilla.org/~rfeeley/fxa-emails/

**Comment by shane-tomlinson** [comment]
@ryanfeeley, has this been taken care of with the work @dannycoates did?

**Comment by rfk** [comment]
IIUC, the copy on the existing notice has been improved, and there's also a suggestion of doing more to surface security-related events.  I've captured to later in a Aha for further discussion and prioritization:

  https://mozilla.aha.io/features/FXA-47

Closing this out, @ryanfeeley feel free to re-open if there's more concrete work to be done here.
