### ISSUE TITLE
Add sudo:false to .travis.yml

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-server#981]
Spotted in the Travis logs while I was writing crappy PRs and breaking builds:

> This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
> If you require sudo, add `sudo: required` to your .travis.yml
> See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

We probably want to throw an explicit `sudo: false` in our .travis.yml to be obvious and silence that warning/info in the logs.

**Comment by TDA** [comment]
I already see a sudo: false in the .travis.yml :O @pdehaan

**Comment by pdehaan** [comment]
Closing. I'm... not a smart man.
