### ISSUE TITLE
Record device id on sessionTokens

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-server#988]
In order to provide useful contextual information in our future "things connected to your account" dashboard, we will need to associate sessionTokens with the device that owns them.  In #983 I proposed adding some generic activity metadata to every token, but for tokens that belong to a device we should be able to do even more.

Strawman:  

* Add `device` and `description` fields to the sessionToken metadata.  Web login sessions can leave `device` blank, while sync login sessions can specify their sync client GUID and maybe their human-readable device name.
* Add a `POST /v1/session/update` endpoint through which devices can update the metadata on their session, e.g. change the description field.
* Revisit #950 to allow listing all your sessions along with the associated metadata.
* Treat the `device` ID as a stable device identifier, which means e.g. if you login with `device=FOO` then we clobber any existing sessionToken for `device=FOO`, we don't send a notification that "a new device is connected", etc.

In future work, the `device` identifier might become a foreign key into a separate "device catalog" service, or a more full-featured devices API on this server itself.  But this seems like a sensible first step for tracking them, and is something we might be able to complete in the Fx42 timeframe.

@kitcambridge @ckarlof @bbangert thoughts?

**Comment by kitcambridge** [comment]
:+1: This seems sensible to me! In particular, I think having the auth server issue the device ID simplifies token revocation and remote logout quite a bit.

I wonder, though, if we could just use the session ID as the device ID. This means it won't be stable if the user signs out of Firefox, then signs back in...but maybe that's not so bad. Otherwise, I think we'd want to persist `(lastAccountId, lastDeviceId)` locally, and make sure we clobber the `lastDeviceId` if the user signs in with a different account.

**Comment by rfk** [comment]
> having the auth server issue the device ID 

On re-reading, this is not clear from my initial post:  I think the client should provision its own "device ID", and to begin we should just use the sync client GUID that we already have in the "services.sync.client.GUID" pref in desktop.  This means even less work for integrating with existing client code.

> I wonder, though, if we could just use the session ID as the device ID.
> This means it won't be stable if the user signs out of Firefox

I'd really like it to be stable across signouts eventually, but it's probably OK for a while if it's not.  I wonder, is the current sync client GUID is stable across signouts?  I wouldn't be surprised either way.

**Comment by rfk** [comment]
>  if we could just use the session ID as the device ID.

Also, some FxA sessions are not owned by a device, e.g. if you login to pocket on the web using FxA in Chrome.  So having a separate flag that indicates the session is owned by a device will be useful.

**Comment by kitcambridge** [comment]
>  I think the client should provision its own "device ID", and to begin we should just use the sync client GUID that we already have in the "services.sync.client.GUID" pref in desktop.

Ah, I see now. Thanks for the clarification; I missed that.

> I'd really like it to be stable across signouts eventually, but it's probably OK for a while if it's not. I wonder, is the current sync client GUID is stable across signouts?

Got it. IIRC, @rnewman mentioned that it's not, and Sync just tries really hard to delete the old client when you sign out...but it's equally likely I recall incorrectly.

**Comment by rfk** [comment]
> I wonder, is the current sync client GUID is stable across signouts?

Testing in nightly shows it is indeed cleared when I disconnect from sync.  But it seems to persist across e.g. password reset events that force me to re-authenticate, so that's an improvement over just using the sessionToken directly.

**Comment by rnewman** [comment]
Careful. The client GUID lives in prefs, so it’s restored from backups and duplicated (!) when a user copies their profile/restores their device/etc.

If you need guaranteed uniqueness (which is kind of the point of a device tracking system, right?) then the Sync client GUID isn’t it.

See e.g., Bug 1151336 for discussion.

**Comment by rfk** [comment]
Eeeewwwww, thanks for the heads-up @rnewman.  It's not clear to me how we'd solve this any better though, short of actually asking for an actual device-id from the actual device.  ISTM anything we store in the profile as the potential to be copied to a second one.

**Comment by rnewman** [comment]
I think one longer-term solution is for an identifier to be allocated at first sign in time, by the server. If the client keeps it for long (e.g., across multiple signins), it also needs a mechanism to detect reuse, which is likely to be OS specific, and perhaps backed up by some server-assisted heuristics.

**Comment by rfk** [comment]
Hmm, actually the default device description generated by sync can reveal personal information:

  https://groups.google.com/forum/#!topic/mozilla.governance/emZ5cAb7hk8

So we'd need to be careful about slurping this in and storing it in encrypted account metadata.

**Comment by rfk** [comment]
After looking at timelines, I think we should scope this down to just "store a client-provided device id" and leave the description aspect for future work.

**Comment by rfk** [comment]
> I think one longer-term solution is for an identifier to be allocated at first sign in time, by the server.

After thinking this through, I don't see any advantage of allocating on the server versus allocating on the client.  What do you see as the advantage?

@rnewman @ncalexan what do you think about putting the various sync clients in charge of generating a device ID for themselves, storing it locally using whatever mechanism makes sense, and submitting it to the server to identify themselves when they request a sessionToken?

What I like about using the sync client GUID is that we can tie that to additional existing device metadata via e.g. about:sync-tabs in the client.  I'll take your advice if that's going to create more weirdness than it solves.  But ISTM that if we put the client in charge of maintaining a long-lived device ID for itself, then it could just start using that for the sync client GUID as well.

**Comment by ckarlof** [comment]
I'm not really a fan of client created identifiers that are expected to be unique. @rfk, what's the downside of having the server allocated the id?

**Comment by rfk** [comment]
No particular downside except that it will likely require a second request; client-generated ids mean the client could identify itself up-front in the initial request.

**Comment by rfk** [comment]
I was hoping this was small and simple enough to get in a quick win last cycle, but it sounds like there's enough weirdness that we need to step back a little.  I'm closing it in favour of a more general "design device id registration" bug over in #1009.
