### ISSUE TITLE
Is it possible for POST /v1/recovery_email/verify_code to return more info

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#989]
## Problem

Hard to tell how many "actual" verification events occurred via the content server. If the user has 2 tabs open or uses a secondary device to verify the account the api returns the same result

Current code: https://github.com/mozilla/fxa-content-server/blob/01dabb7f08ec33c33206e4cabad879c92864a6a9/app/scripts/views/complete_sign_up.js#L67
Current metrics report: 
![image](https://cloud.githubusercontent.com/assets/128755/8779123/a5528ac0-2ecf-11e5-8663-e37027867ee4.png)

## Expected
(something like this with better naming:)
Successful requests will produce a "200 OK" response with a JSON body:
```
{ already_verified_just_now_in_another_browser: true }
```
## Actual

```
Successful requests will produce a "200 OK" response with an empty JSON body
```

Does it make sense to add this feature to the api?

**Comment by rfk** [comment]
Essentially, if you correctly verify an account that is already verified, return something in the body of the response to indicate this slightly-strange-but-perfectly-ok state of affairs?

**Comment by vladikoff** [comment]
> Essentially, if you correctly verify an account that is already verified, return something in the body of the response to indicate this slightly-strange-but-perfectly-ok state of affairs?

Yeap!

**Comment by dannycoates** [comment]
We have an event in the auth-server for this, we should just measure it from the source.

**Comment by rfk** [comment]
We decided to close this in favour of #992

**Comment by vladikoff** [comment]
@dannycoates https://github.com/mozilla/fxa-auth-server/blob/eec574ca8a3b72d32d3b2d3e21837ef06240f4a7/lib/routes/account.js#L493

**Comment by rfk** [comment]
> We decided to close this

So yeah, I'm going to actually close it :-)
