### ISSUE TITLE
"A new device is now syncing to your Firefox Account" mail sent when re-entering a changed password

### ISSUE THREAD

**Issue by mhammond** [mozilla/fxa-auth-server#990]
If you change your password on a device, you correctly get a "your password has changed" email. If you then go to another device, get prompted to reauthenticate due to the password change, then enter your new password, you then get an email telling you "A new device is now syncing to your Firefox Account" - which isn't correct - it's not a new device.

Ryan says these are supposed to be filtered out, but apparently they are not.

**Comment by rfk** [comment]
Did you notice this on a desktop machine, android device, or both?

**Comment by mhammond** [comment]
This was done on desktop using 2 different profiles on the same physical device.

**Comment by mhammond** [comment]
(actually, even the same profile - ie, change password, restart, re-enter new password and you get the mail)

**Comment by shane-tomlinson** [comment]
That's because the user must re-enter their password, which is considered a signin. We don't know *why* the user must sign in, it could be their session expired, it could be a password change. We just know it's a signin. So, a new email is sent.

The fix? Probably to know why the session has expired. Or, have the future device manager send emails when a new device connects.

**Comment by mhammond** [comment]
Maybe change/clarify the text of the email for now?

**Comment by rfk** [comment]
Overlaps with https://github.com/mozilla/fxa-auth-mailer/issues/60 where @ryanfeeley suggests a more generic wording for the new-device emails.

We could also consider having FxA tell the content-server that this is a reconnect, and having content-server pass that on to auth-server in the "reason" parameter.  But given we're working on exposing a more explicit notion of devices this quarter, it doesn't seem worth it on balance.  Closing this in favour of the linked issue.
