### ISSUE TITLE
Add datadog to the fxa-auth-server

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-server#992]
We need to log verification events properly and we can do so using datadog.

@rfk what can we do about the 10% metrics on the content server vs 100% or a different 10% on the auth server?

**Comment by rfk** [comment]
Start collecting 100% everywhere? :-P

Seriously though, this is a good question that I'm not sure I have a good answer too.  Perhaps we should reconsider whether the server-side logging can give you precisely what you need?

**Comment by rfk** [comment]
Based on conversations with @vladikoff, we may need to send some a/b testing state to the server and persistently associated it with the user for at least a little while.  For example, we could send along the "unique user id" and able experiment decisions when creating an account, and store them in memcache on the server for a month so we can refer to them when a/b testing multi-step flows.
