### ISSUE TITLE
review error handling of requests to fxa-auth-db-server daemon

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-server#996]
In https://github.com/mozilla/fxa-auth-server/issues/993, a bug in fxa-auth-db-mem was causing it to throw 500 Internal Server Error http response back for emailRecord requests for an unknown user.

The auth server apparently was eating this error response and continuing on the promise chain, ultimately dying in a way that was massively unclear about the root cause of the failure. We should revisit  that code and figure out why the problem wasn't failing fast on the 500 response.

**Comment by vladikoff** [comment]
from mtg: let's revisit once we have a 500 again
